### ISSUE TITLE
Searchbar in the editor

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#1012]
**Describe the content or mechanics you are proposing.**
In the map editor, add a searchbar to filter for a specific block. Allow filters such as "Drill", "Power", "Terrain", "Walls", etc. Or just lookup a block by name, or both.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would make it easier to find the block you want. There are lots of blocks and it takes time to look for the one you want, especially because they're all placed in one large uncategorized all-inclusive selection with no indication if they're power blocks, terrain, drills, etc.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by YellOw139** [comment]
You can add terrain blocks in the editor, then edit in-game to build structures such as factories, power, turrets, etc, as in the in-game editor they are organized.

Maybe it's still not ideal for terrain blocks (there's so many of them and further categorization could help), but otherwise we might already have enough to make maps comfortably. Oh, and yeah, a search bar would be nice, but categories are already more or less there, even if they could be better.

**Comment by DeltaNedas** [comment]
search bar always welcome

**Comment by summetdev** [comment]
I will do it soon. 🚀

**Comment by summetdev** [comment]
Merged.
