### ISSUE TITLE
clean links button in processor

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#1043]
**Describe the content or mechanics you are proposing.**

A button in the configuration table of a processor that will:
1. remove unused links
2. flatten link names from e.g. router3, router6 to router1, router2

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

When messing about in a processor your links often get garbled and having a button to clean them would be great

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by joshuaptfan** [comment]
I mocked up how the button would look in the UI. I was imagining a "clear" instead of "clean" button, that simply deletes all current links, as it would be instantly understood what that does, compared to "clean".
![Logic Clear Links](https://user-images.githubusercontent.com/15149002/102809399-c7aae600-4376-11eb-8a0b-8b442aeef9ec.png)
