### ISSUE TITLE
Campain play on multi sector at one time (multiplayer)

### ISSUE THREAD

**Issue by GamyGamer** [Anuken/Mindustry-Suggestions#1046]
**Describe the content or mechanics you are proposing.**
As title say. I and my friend are playing campain on multiplayer and I want to fight on sector (1) and my friend on sector (2) at the same time. Also special option to allow certain users to allow research and lauching cores

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would make possible to split our job with capturing, or when we are at the same sector and enemy is suddently attacking sector, then we would split up to keep sector alive.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
this would annihilate a phone (lowest common denominator) which can just about run one map, let alone two at once

**Comment by GamyGamer** [comment]
So, what about adding "allow multiple sectors at once (multiplayer)" switch with information that it can be resource demanding. Personally I play only on PC because my mobile is way too old to handle normal even gameplay

**Comment by 50275** [comment]
Okay, so imagine running 1 sector with a lot of factories and large waves. Okay, not too much lag, right?

Then multiply that by a few hundred to simulate the entire planet to more accurately simulate the multiplayer coop campaign experience. Your phone is dying? Why not use your PC? What do you mean it's not responding?

**Comment by GamyGamer** [comment]
You don't need to simulate all sectors, just only those where are players and rest keep as it was. Also I don't think there are hundreds of sectors

**Comment by MineMS49** [comment]
I just had the same situation as described. Two players, two sectors but only one have the control.

I don't know how the multiplayer works really, but there's a host and guests. Is it possible to add another role, like _invited_, to be able to move from sector to another ?
The host control where the game is launched on one sector, _invited_ have access to the planet map and can move as well. Guest will be restricted to follow either the host or the _invited_.

About performance, you just need graphics rendering on client side. A system similar to the auto-fight/auto-defense while away can be used. Even in solo you may get two sectors attacked at the same time, or trying to get three or more easy sectors at once. It will be sent as a per minute calculation and a few raw data between host <-> _invited_. When they all gather to the same sector, it comes back to normal multiplayer, host having the lead/decision power.

**Comment by MineMS49** [comment]
Ok, so I read again this post, nothing happened since my last comment. The `README.md` explains no comments will be added and issue will certainly not be closed by mainteners. From this point, what's left to do ?

Problems with features requests are commonly :
- Doesn't fit the template, this one does ;
- The feature request is on the list of "_A few things you shouldn't suggest_", reviewing the list, I don't think so ;
- Does not fill a niche, nor fulfill a need, nor bring more diversity to the game, nor bring more strategy to the game. The point of this feature is to enable a multi sector activity. This makes possible to work or rework the strategy for each sectors.

Problem with this feature : 
- Game will be easier
- It will take less time to finish the campaign
- When the sending accross sectors is available, the game is pretty much over (one producing resources, another using them)

Ways to balance the game :
- Add more content (V7 is in preparation)
- Add more difficulty, I'll explain it later but to sum up : Increase attack frequency
- Make the launchpad less efficient
    - Need more power
    - Resources sent can crash and be lost in the process (part of the random environmental events, planned in Trello for V7 ?)
- Add a recon/scout event, let's say a Quad comming arround to destroy energy production.*


\* : As the planet has some enemy bases, it's not impossible that some air commanders units are patrolling


I'll try to explain this whole feature from a different perspective.


**Describe the content or mechanics you are proposing.**

Create another role during Campaign multiplayer to allow a group to split into different sectors. As phone is lowest common denominator, and the goall is not to kill the fun of the game, limit can be set to 3 sectors at the same time. A warning message for performance can be raised to inform any user. To balance the game and prevent a fast completion, the vulnerability system can be raised using the number of players in the group. Something like :
| Players | Ratio |
|---------|-------|
| 1       | 100%  |
| 2       | 120%  |
| 3       | 160%  |
| 4       | 240%  |
| 5       | 500%  |
| 6       | 820%  |

Some random environmental events (planned in Trello for V7) can also ruin a sector which has to be rebuilt, forcing the split to this sector and the current one.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This will allow players to discover the game together without forcing them to do the same thing. For examples :
• A resource is fully used because everyone is building on their side, they will try to increase the throughput to end their building.
• When you need power, players will all try to fix the problem without doing anything else.
• Defense wasn't good enough and gets breached, it's panic time but game over. At this point, near by sectors might not be able to re-engage because resources have been used and aren't back yet.

Being one, two, three or more player we often end up doing the same fix which means overdoing it. Being able to split on differents sectors helps to plan a strategy.
It's like, on one hand you are using tactics whereas on the other hand you tune your strategy.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
_This is the only feature request about coop/multiplayer campaign._

2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
_I've just checked and read planned suggestions on the Trello taskboard._

3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
_I started with V5 and played V6 completely. I then restarted V6 in multiplayer and submitted my comment._

4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
_I read again the `README.md` which was update the day before my comment and has not changed since._

**Comment by itcannotbe** [comment]
> this would annihilate a phone (lowest common denominator) which can just about run one map, let alone two at once

And people ignored this comment.

**Comment by MineMS49** [comment]
Ok, then. It's impossible because phone is too weak. I'm ok with that. I was just trying to propose a workarround to have the rendering on one side (client) and a few data exchange (much ligther than a fullsimulated planet). But again, I'm not good in coding, so if you say it's not possible I've got my response. Thank you

**Comment by GamyGamer** [comment]
Original poster here, Thank you so much for expanding this suggestion, this help a lot.
I don't think hosting multiple sectors on one phone is impossible, game is preety optimised.
Unfortunally we won't know if this feature will be added to this game due to how this github page is monitored, no response from main developer and competing with 1.4k issues.

My solution would be adding this function as experimental (disabled by default), Main server would be user that started hosting game where everyone would be joining (right now how is this handled). But instead hosting another instance of sector on same device, what about hosting it on client that switched server, still dependent on main server and exchanging data across them (capture status, saves, resource launches ect.).

**Comment by godotgamedeveloper** [comment]
As discovered and noted by the OP of the thread where I mentioned this issue (as indicated above), this one is a duplicate of https://github.com/Anuken/Mindustry-Suggestions/issues/459 and https://github.com/Anuken/Mindustry-Suggestions/issues/916.
