### ISSUE TITLE
Shouldn't processors use power?

### ISSUE THREAD

**Issue by Catchears** [Anuken/Mindustry-Suggestions#1065]
**Describe what you would like changed, and why.**
I'm sorry if Anuke has said that this is coming or why it is not coming but shouldn't processors use power? Wouldn't that make sense? At least make the hyper processor use power. Why would it need cooling if there's nothing heating it up?

**Describe the changes you want to propose. Include possible alternatives.**
Processors should use power. Alternative: They should at least use something.

**Comment by scarf-generic** [comment]
Whats the reasoning behind them using power? They are already limited by processing speed, you think they need more nerfs?

**Comment by Catchears** [comment]
>At the very least make the hyper processor use power. Why would it need cooling if there's nothing heating it up?

Also, I know that mindustry isn't meant to be realistic but seeing as processors use power irl it would make sense for them to use power here as well? An object sensing things, performing mathematical operations and controlling other things should use something imo.

**Comment by scarf-generic** [comment]
> Also, I know that mindustry isn't meant to be realistic but seeing as processors use power irl it would make sense for them to use power here as well? An object sensing things, performing mathematical operations and controlling other things should use something imo.

Somewhere out there is a screenshot of anuke saying that reality has no hold over mindustry. Saying "because thats how it works in real life" makes no sense because mindustry is not real life, and its not trying to be real life. Shouldnt conveyors use power too? Why dont ore patches get used up? Why dont units need fuel to fly/move? **I am asking why you think logic needs a nerf, not why you think the nerf makes sense. This is about balance, not imitating the real world.**

**Comment by scarf-generic** [comment]
Found it.
![20201104_143358](https://user-images.githubusercontent.com/69741577/98165050-d44cab00-1eaa-11eb-8218-adb1c92bc8ff.jpg)

**Comment by 50275** [comment]
The power nodes would be such a mess if this was added

**Comment by itcannotbe** [comment]
Nah. You can always just turn the opacity of power node's lasers down if that is your concern.

**Comment by Catchears** [comment]
Login needs a nerf because you can use it to control multiple turrets at the same time, make units transport or mine resources, show the items in your core, analyse your power network and tell you how long you have until your batteries are empty, make flares coal bomb the enemy core, automatically turn explosion-proof thorium reactors on and off based on power demand, automatically phase overdrive the power generators based on demand, make units automatically build something based on a certain combination of switches, make a calculator with a graphics interface, play pong or geometry dash and a whole lot more. What does it cost you? You have to build the processor once and from that point on you're limited only by its connection range and speed, Assuming a processor doesn't get destroyed by the player or an enemy, it will continue working forever on a single, one-time investment. Imo this is a bit too low of a price for such a powerful tool.

**Comment by scarf-generic** [comment]
> Login needs a nerf because you can use it to control multiple turrets at the same time, make units transport or mine resources, show the items in your core, analyse your power network and tell you how long you have until your batteries are empty, make flares coal bomb the enemy core, automatically turn explosion-proof thorium reactors on and off based on power demand, automatically phase overdrive the power generators based on demand, make units automatically build something based on a certain combination of switches, make a calculator with a graphics interface, play pong or geometry dash and a whole lot more. What does it cost you? You have to build the processor once and from that point on you're limited only by its connection range and speed, Assuming a processor doesn't get destroyed by the player or an enemy, it will continue working forever on a single, one-time investment. Imo this is a bit too low of a price for such a powerful tool.

Most of the things here can be done by a player. You can manually mine copper, but with a single one-time investment of 12 copper you can make a drill mine copper for you. Mindustry is about automation, and you are complaining about something able to automate players actions for a set cost. Mechanical drills do the same thing, should they cost power too?

**Comment by scarf-generic** [comment]
Also, saying logic needs a nerf because of the things it can do is pretty pointless.
"Oh yeah conveyors need a nerf because they can transport all 16 resources and they dont use power and its a single time investment. Imo conveyors are too powerful and need to cost power or something"
See how much of a non-answer that is? You arent comparing it to anything, you just list what it can do and say it needs a nerf.

**Comment by Catchears** [comment]
>Mindustry is about automation

Yes, I agree.

>You arent comparing it to anything, you just list what it can do and say it needs a nerf.

You seem to have missed this part:
>"You have to build the processor once and from that point on you're limited only by its connection range and speed, Assuming a processor doesn't get destroyed by the player or an enemy, it will continue working forever on a single, one-time investment.

>but with a single one-time investment of 12 copper you can make a drill mine copper for you

Ok, I didn't make my point that clear.

Here: I think the processor needs a nerf because imo it's too powerful for what it costs. 

Happy?

**Comment by 50275** [comment]
It's not actually very powerful. All it can do is tell objects to do specific actions, such as making ripples not fire at duos and instead the arcs that are shooting at them. It doesn't increase damage output like cyrofluid. It doesn't boost buildings like an overdrive dome. It doesn't prevent blast bombing. It just helps you control your stuff.

**Comment by 50275** [comment]
Realism is not important here, even Anuke said so.
![image](https://user-images.githubusercontent.com/68676339/98281871-5c928500-1f6b-11eb-85ad-c6023a74e1db.png)

If you want realism then there's a ton of things that don't make sense such as how units e.g. flare can literally be made out of sand and coal and how oil and titanium can make a special metal literally stronger than normal titanium. Or how surge alloy has electric shock effects, while not having any power stored or anything like that. 
Actually, solar power is completely replaceable. Although free power squares are effectively removed, RTGs (they use thorium, but anuke buffed them so much that you can run a few hundred with a single airblast), and you can use impacts. (the only expensive material here is titanium)

**Comment by scarf-generic** [comment]
> > You arent comparing it to anything, you just list what it can do and say it needs a nerf.
> 
> You seem to have missed this part:
> 
> > You have to build the processor once and from that point on you're limited only by its connection range and speed, Assuming a processor doesn't get destroyed by the player or an enemy, it will continue working forever on a single, one-time investment.
> 
> I think the processor needs a nerf because imo it's too powerful for what it does.

So processor is too cheap because it can do all the things you listed? All those things can be done by a player, you just pay for the processor to automate it but be slightly slower/worse. The only thing to compare it to is a player, and there is a very large amount of player ships you can make for free. Wanna make items go from one vault to another? Have an alt account with a custom client join and transfer items. Costs nothing, works better, there is no real downside besides player slots. Comparing alt accounts and logic, logic is much worse and costs more. You think it needs to be even worse than it already is?

**Comment by Catchears** [comment]
Right, and what about the mobile players who can't run two clients at the same time?

**Comment by scarf-generic** [comment]
> Right, and what about the mobile players who can't run two clients at the same time?

1. Some mobile players can
2. Everybody knows mobile mindustry is a direct downgrade of pc mindustry

Thats not the point. The point is, a player could be doing all the things that the processor is doing. You are building a processor to automate what you are doing, so that it you dont spend the entire game transporting itemsor whatever. This is similar to how you build drills on copper so that you dont spend the entire game manually mining copper.

**Comment by scarf-generic** [comment]
woohoo
