### ISSUE TITLE
Unit Transparency

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry-Suggestions#108]
**Describe the content or mechanics you are proposing.**
Similarly to bridges and power lines, what about transparency for units? Editing your defenses can be difficult when you have tons of units (probably revenants) blocking your visibility.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Definitely a quality of life thing that'll make seeing under units easier.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by DeltaNedas** [comment]
will look ugly as overlapping transparent guns + unit body will have dark spots like hurricane shadow (vbucks mod)

**Comment by HaphLife** [comment]
> will look ugly as overlapping transparent guns + unit body will have dark spots like hurricane shadow (vbucks mod)

Sure it might be ugly, but it would have functional purpose. Bridge opacity can be kindof ugly, but it serves a purpose, so I use it.

**Comment by markozajc** [comment]
Would come in handy when my draugs are obstructing the whole view.

**Comment by HaphLife** [comment]
> Would come in handy when my draugs are obstructing the whole view.

Especially phantom builder drones. Make 30 of those guys and they are ALWAYS in your way.

**Comment by Anuken** [comment]
This looks terrible and is too much work to support. Make your units move somewhere else instead.

**Comment by HaphLife** [comment]
> This looks terrible and is too much work to support. Make your units move somewhere else instead.

You are aware that (at least before 6.0, I don’t know about afterwards) there are multiple types of units you cannot control (draugs and phantoms) are you not? You did make them. 

Additionally, retreating all of your flying units while modifying one’s defenses might be a dangerous move (and the need to do that is a big negative to using them) Should we really have to sacrifice gameplay options because the rendering engine is too limited?

 Even just a togglable “make friendly units invisible” would work here (If there is an optional keybind, it might actually be a more elegant solution), and would be significantly less “work to support” and avoid “being ugly”. 

All we want is to actually be able to see what we’re building without spam clicking and reading the description text.

**Comment by Anuken** [comment]
> there are multiple types of units you cannot control

That's not relevant anymore; in v6 you *will* be able to more precisely control all types of units. There is no need to make them *retreat* altogether, either.

Also, note that massive swarms of weak units (e.g. wraiths) will not be possible to construct in v6 due to the unit cap, and as such, you will be less likely to run into situations where moving swarms of units blot out important parts of your base.

**Comment by markozajc** [comment]
You can control all units in 6.0, dontcha worry.

**Comment by HaphLife** [comment]
> in v6 you _will_ be able to more precisely control all types of units.

 Awesome, that could fix the problem.



> unit cap

I hope that players have access to the “higher teir/more damaging” troops you mentioned would spawn in later waves, otherwise PVP might look a lot different (more offensive turrets)
