### ISSUE TITLE
Allow logic to detect power output of a linked building

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#1090]
**Describe the content or mechanics you are proposing.**
Before you say this can be done already, reread the title. You can detect power output and use over the entire grid, but you cant detect power output use of a single linked building. I suggest an addition to sensor in logic that lets you detect how much power a linked building is producing. For example, even if power on the grid is -350, you could sense that the linked combustion generator is producing 60 power/sec, or that the linked water extractor is using however much power its using.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would let logic have more information on linked objects. Pretty simple idea, not sure how complex it would be to implement but it would give more options for logic-controlled power managment.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sample-text-here** [comment]
Adding on to this, i think that reading an impact's efficiency is equal to it's power output/max power production
![image](https://user-images.githubusercontent.com/56274831/98423145-984c4e00-2042-11eb-92e3-380e41504f63.png)
for example, this would have about 0.3 efficiency

**Comment by scarf-generic** [comment]
Yeah, that would be good too

**Comment by quetzalcoatl** [comment]
Actually, you can do that now, indirectly, with a few extra blocks, namely: the battery diode.
This one allows you to flow power between two grids, but keep the grids separate.
If you don't want it to be directional and if you want to have the powerflow two-way, just use 2 diodes set to opposite directions.

Here's an example
![image](https://user-images.githubusercontent.com/1564880/105979297-cd8d9880-6093-11eb-842c-568508a7de27.png)

I marked power grids boundaries with dashed red line. All connected by 2-way diodes. All empty.

1 has one large battery = 50k
2 has three large batteries = 150k
3 has six batteries = 300k

As you can see their capacities were not totalled up, so they are in fact separate power grids.

Also thanks to bi-di diodes, if I connect external power from 4 to one-way input 5 (it's one-way just for example, it can be 2-way, no problems), ALL 10 batteries will charge up, and I can also discharge all of them, and of course their powergrid identities stay separate from the external power grid.

I don't say that it's better than the improvement you suggested. What you suggested sounds nice and handy! But, you can get this "detection" already now: just separate the power grid identities, even down to a single building, like I've just shown. Yeah, it's tedious. But possible :)

**Comment by kdvolder** [comment]
@quetzalcoatl I do not understand how this allows to read the power output of a power source such as for example an impact reactor. Impact reactor isn't a battery and its capacity reads out as 0. 

I think what we want is a way to detect the power being output by a reactor. In my case I want to manage booting up a impact reactor via processor. To that it would be nice to have a (preferably easy) way to detect whether the impact generator is putting out power or not. That doesn't seem possible as soon as I connect the reactor to the network, even via a diode, the reactor power output sensor just returns the power output in the overall network. 

Maybe I am missing something, and maybe I didn't quite understand the workaround you suggested, but have not found a way so far to detect whether impact reactor is putting out power near its maximum. If I am misunderstanding/missing something,  I'll be more than happy for someone to explain it to me.

**Comment by quetzalcoatl** [comment]
@kdvolder  I made those screenshots and I presented differences in "capacity" only because it was quicker and I could use less components to show the idea.

Look at that screenshot once again: capacities are separate, and are related to three separate battery packs. Those are three power grids. You can see they are separate, because their storage capacities did not merge. Try it.  If they are connected directly (touching each other) or connected by power nodes (yellow lasers), then their capacities merge. If they are connected by diodes only, their capacities don't merge. Power flows, but nothing gets merged. Neither the power output!

Now, their capacities didn't merge, so they are separate power grids, then you can connect combustion generator to first battery pack, impact generator to second battery pack, and a set of power-consumers to third battery pack. I didn't do it on the screenshot, to remove noise. Maybe that was a wrong idea. However, I deliberately places both BATTERIES and POWERNODES. Note how each powernode is connected just to its own battery pack. If you do that, you will see that powernode on first batterypack will have "power: +60; stored xxx/54k", the p-node at 2nd will show "power: +6k; stored: zzz/158k" and the p-node at 3rd will show "output: -asdasd; stored: sdfsfd/304k".

This means, that you can inspect the currect output of an impact-generator by watching the "power" of its related powernode on its dedicated batterypack. And since you need to have diodes for separation, it's easy to control them by logic (you can't disconnect power nodes by logic, but you can flip diodes!)

If I have some time in the evening, I'll re-make this screenshot with sources and consumers added, so the "power" is not zero everywhere.

**Comment by quetzalcoatl** [comment]
@kdvolder 
![image](https://user-images.githubusercontent.com/1564880/107255102-41d31f00-6a38-11eb-8d4d-c61cb60c9cd3.png)

**Comment by kdvolder** [comment]
Okay but try and attach a power void to outgoing (and enabled) diode of the power source. When I do that then it immediately draws down the power in the connected net. There seems to be no way then to determine when impact reactor is outputting positive power (i.e producing more than it consumes).  Well, it is easy enough to see when in the UI looking at the reactor 'power output'. But there seems to be no way to do that via processor/sensors.

**Comment by quetzalcoatl** [comment]
@kdvolder hope this helps: https://www.reddit.com/r/Mindustry/comments/lh42bf/diodeslogic_impactgenerator_that_starts_up_and/
