### ISSUE TITLE
Ambient breeze sound

### ISSUE THREAD

**Issue by Bedsurfer** [Anuken/Mindustry-Suggestions#1101]
**Describe the content or mechanics you are proposing.**
A quiet and subtle wind track playing in the background, to add atmosphere to levels.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more game play options or how it will fill a new niche.**

The planet Mindustry takes place on seems devoid of life, and desolate as well. adding this subtle wind/breeze will add to the atmosphere of the game, regardless of weather.It would also end up blending well into sandstorms in the campaign.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Bohaska** [comment]
Just ask someone to make a mod for this, and send that guy a wind track.

**Comment by Catchears** [comment]
Why do you think that this should be a mod and not added to the game?

**Comment by sample-text-here** [comment]
> Just ask someone to make a mod for this, and send that guy a wind track.

99% of the suggestions here can be made into mods. Then why aren't they? It's because people want them in the base game, so they can join vanilla servers and still have the same experience. They want their schematics to work everywhere and for their friends or new players to have the same experience. 

But you have a point so lets delete all the music, items, liquids, units, and blocks and make it so they're mods instead.
