### ISSUE TITLE
Remove the 20 wave addition punishment

### ISSUE THREAD

**Issue by SirFancypants** [Anuken/Mindustry-Suggestions#1104]
**Describe what you would like changed, and why.**
I would like to remove the 20-wave penalty for failed/unfinished campaign levels. This penalty mechanic disrupts some key game mechanics such as:
a. Hard levels become even harder, making for near impossible levels
b. Halts game progress (sometimes indefinitely), making a lot of players (including myself) tend to have to search for workarounds and quite possibly, cheats.

**Describe the changes you want to propose. Include possible alternatives.**

a. Remove the 20-wave penalty entirely
b. Possibly: instead of keeping your base infrastructure intact, reset the sector entirely as an alternative penalty.

**Comment by itcannotbe** [comment]
1. It's not even always wave 20.
2. Stay away from harder difficulty sectors until you are confident enough that you can beat the sector with the tech you have.
3. Just honestly get good at the game.

**Comment by Bohaska** [comment]
@itcannotbe good points, but if you don't know that you gotta stay away from hard sectors, it makes no sense to 'punish' you for not beating them.

**Comment by DayTimer** [comment]
> *ping* good points, but if you didn't know that you gotta stay away from hard sectors, it makes no sense to 'punish' you for not beating them.

Again, there is **NO SUCH MECHANIC**. Your sector could only be attacked if there is an enemy base nearby (crux core in a neighbour sector).

**Comment by Bohaska** [comment]
@DayTimer He meant before you captured the sector.

**Comment by DeltaNedas** [comment]
that doesnt exist

**Comment by Humanoid-X** [comment]
Before you can capture a planet campaign sector, a super hard wave appear.

Last time I played I remember beating the wave before quite well. Then... at Wave 20... AAAAAAaAaAA! Tons  of atrax appeared... 

And the worst time I played... I had capture the  sector, but somehow the sector is under attack again.
The last wave before capturing it again, five Zeniths and something like twenty atrax spawned. and... you know. My defense is totally reduced to scrap.

Please note that all these sectors I mentioned are all Difficulty 2 Sector.

Also, my apology because I'm bad in English.

**Comment by mwoehlke** [comment]
Ahem: #1091. Certain sectors are ***broken***. 174 is "allegedly" difficulty-2, has very limited resources, and — contrary to its *reported* difficulty rating — is *unbeatable* if you take it on as the second sector. Losing it before securing it, which invokes the penalty as in this issue, makes it virtually unwinabble, *period*.

**Comment by Humanoid-X** [comment]
(Sorry for the late reply)

Really? I beat Secror 174 quite easily :-/
Is our procedural generation somehow different?

**Comment by Humanoid-X** [comment]
It's just the wave 20 punishment that is hard.

**Comment by SirFancypants** [comment]
> Ahem: #1091. Certain sectors are _**broken**_. 174 is "allegedly" difficulty-2, has very limited resources, and — contrary to its _reported_ difficulty rating — is _unbeatable_ if you take it on as the second sector. Losing it before securing it, which invokes the penalty as in this issue, makes it virtually unwinabble, _period_.

Hmmmm, sector 174 is actually the first sector I cleared after GZ. I'm not going to lie, it was pretty easy to be completely honest

**Comment by mwoehlke** [comment]
My 174 is full of Arc enemies (don't have all the mech names memorized). I found it *much* more difficult than the other sectors I've played since. The 20-wave penalty bumps those to *Lancer* enemies. I'm not sure the 40-wave version is beatable, as there is no titanium in that sector. I got to the point (keeping in mind this was the first sector I attempted after Ground Zero, so I had only *just* researched silicon and my strongest defensive turret was Hail) where I literally could not rebuild, or even eliminate a wave before the next one would spawn.

Sorry, but it is *literally* unwinnable at a tech level attainable without playing other sectors first if you fail it on the first attempt. Even *with* a better tech tree, I consider Lancer enemies in a titanium-free sector to be unfairly overpowered. If those get into attack range *at all*, they *will* wipe out most of your defenses in just a few shots.
