### ISSUE TITLE
Add a way for players to join each other without having to portfoward or go to the other persons house. (non steam players)

### ISSUE THREAD

**Issue by TheCorruptedKing** [Anuken/Mindustry-Suggestions#1153]
It has come to my attention that a lot of players have been getting annoyed with "how to make servers" and "how to portfoward" to play with eachother without having to join a server by someone else, so here's what I have to say, add a feature like among us where players could have public/private lobbys where people could join and play with other players without having to do all that hard work. Basically a substitute for co-op.

**Comment by itcannotbe** [comment]
1. RIP Template
2. IF YOU DON'T WANT TO DO PORT FORWARDING OR OTHER FREE WAYS TO HOST A GAME AT LET OTHER PEOPLE CONNECT. ***THEN FUCKING PAY SOME COMPANY TO HOST IT FOR YOU***. NOTHING IS FUCKING FREE NOR CHEAP FOR AN AD-LESS, NO IN-APP PURCHASES, MOSTLY FREE TO DOWNLOAD AND PLAY GAME LIKE, I DON'T KNOW, LIKE FUCKING MINDUSTRY, THIS GAME?

**Comment by HaphLife** [comment]
@itcannotbe a) Chill out, b) valid points, c) there might be *some options* to simplify the existing system, which we should consider.

Obviously it’s not going to change from the current system, where one person plays host, since servers aren’t free, but there (might?) have been some innovations in internet technology in the last 20 years. Perhaps something as simple as a guide/wizard for setting up port forwarding would be a valid option.

**Comment by HaphLife** [comment]
And by that I mean a guide that ships with the game (as opposed to searching the internet for guides)

**Comment by TheCorruptedKing** [comment]
Sleep deprivation is a thing give me a break

**Comment by itcannotbe** [comment]
> And by that I mean a guide that ships with the game (as opposed to searching the internet for guides)

That would be hard, as each router manufacturer has a different interface for their devices.

**Comment by DeltaNedas** [comment]
ok then use a vpn if you dont have your router password
the concept of public servers that anyone can join.... did you try public servers?

**Comment by marky0470** [comment]
zerotir
