### ISSUE TITLE
allow selection of launch loadouts even if your too poor to launch with them, so you can know what resources you need

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1190]
title says words that are cool, this would decrease the difficulty of picking a schematic to launch with as the launch menu would provide all the info you'd need.

[X] i put a x in a box

**Comment by Bohaska** [comment]
@Legomonster33 Try making a pull request for this, or ask someone else to do it for you. Anuke should not waste his time on this

**Comment by Catchears** [comment]
You know, most people can't code in Java (or at all) and you don't necessarily need to ask someone directly to implement something. I'm pretty sure I've seen PRs which implement suggestions and I've considered doing it myself as well. Just because something is here as a suggestion doesn't mean Anuke himself has to add it.
