### ISSUE TITLE
Dont Restrict the way people enjoy the game, 

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1227]
![image](https://user-images.githubusercontent.com/54417042/99344581-6a46e500-285e-11eb-8514-937ebb06de52.png)
**Describe what you would like changed, and why.**
Don't force people to play the game in a specific way, this typically leads to people not being able to enjoy the game the way they want to.

**Describe the changes you want to propose. Include possible alternatives.**

having it so that specific sectors unlock certain blocks for free, but you can also pay to unlock them, this encourages capping sectors but doesn't restrict people from playing how they want to.

**Comment by RedstonerKBC** [comment]
Adding on to that, I like the way Minecraft does things. They don't implement chat filters, slow-mode, anti-griefing plugins, hacked-client detectors, hate speech detectors, safe-space generators, inappropriate skin detectors, moderation bots, etc. They let individual servers moderate their own server however they want.

I think that's how Mindustry should be too. Let servers configure their server how they want. Some servers will be very "safe" for people to play while others will be without very many rules. This lets servers be diverse and people can still choose which communities they like, while still being apart of the larger Mindustry community.

**Comment by SarisWinterwisp** [comment]
I think that the sector hardlocks for items were an entirely beneficial change. While it may slow down players such as yourself who deem it unnecessary and unlikable, it is extremely beneficial to those who have not been introduced to the game and its mechanics. As well, by forcing players into moving to harder areas it allows the difficulty to curve instead of either flatlining as they research everything from one sector, or hardwall as they slowly collect the necessary items to research, not know how to use the items, and then be crushed because of a failure to use the items they were introduced to. By forcing the player to move forward it encourages a better way to play the game than letting it run in the background and coming back every 15 minutes, which can damage a player's experience with the game and its campaign.

**Comment by Nhimanss** [comment]
I agree with @SarisWinterwisp but I feel that playing the campaign again after you already know what to do is a hard sell. This is because you don't even have routers in the beginning. arguably newbies will understand the router fairly quickly.
Mindustry without routers isn't fun!
