### ISSUE TITLE
Campaign Balance

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1248]
**Describe what you would like changed, and why.**
As it stands, there is one main problem with the current campaign, there are many incentives to afk/farm. most notable of these is that research costs items, and time = items, so if you spend time farming you can research things, note that farming isn't very enjoyable and is typically very boring. another issue is how launching resources either with your core or with launch pads, removes nearly all the challenge from the game.

**Describe the changes you want to propose. Include possible alternatives.**
I suggest changing the research system so that instead of spending items to unlock things, you unlock things by capturing sectors. this would encourage playing the game, exploring the map, and remove the main reason people
> sit around

which ultimately leads to a more boring experience and creates situations where the optimal strategy isn't to have fun, rather its to sit around farming resources waiting to unlock everything. in having research tied to sector capping in order to unlock stuff you have to actually play the game. be in uncomfortable situations, and have a better gameplay experience.

i also suggest removing the ability to launch with resources, and import resources, as they remove some of the main fun things in the game. taking what limited stuff the map has an making do, as with the ability to have outside resources you can just build a wall of defenses and call it a day. without having to anything else.

**Comment by the-kido** [comment]
i like the idea of needing to capture a certain amount of sectors for some items to be researched but Anuke is closing in on finishing v6 so things like this will probably be ignored.

**Comment by sample-text-here** [comment]
Instead of needing lots of materials, you should need lots of unique items, each with their own recipe relying on other factories. Having less items but more uniqueness would make players design more and different factories instead of copy-pasting the same schematic 100 times

right now there are only 16 unique materials and some of them are raw, mineable resources. also, most factories are only 2 layers deep, like silicon -> surge or pyratite -> blast. more layers of factories would be nice, and some feedback loops would be good too. before you start saying "use mods", imo if a game needs mods to be fun there's something wrong.
