### ISSUE TITLE
More types for ulocate

### ISSUE THREAD

**Issue by TheSlaylord** [Anuken/Mindustry-Suggestions#1260]
**Describe what you would like changed, and why.**
Unit Locate command lets you choose a type of the building you want to locate, but only these types.
![Screenshot_20201119_081755](https://user-images.githubusercontent.com/62336673/99625010-5529ac00-2a40-11eb-8271-e1465ecb9733.jpg)
What if I needed to locate conveyors? Or walls? Or maybe drills?

**Describe the changes you want to propose. Include possible alternatives.**
Add a few more types for the ulocate command, or let player write the block to the type field, like @mechanical-drill.

**Comment by scarf-generic** [comment]
"If we make enough of these, maybe anuke will add it"

**Comment by scarf-generic** [comment]
#1242 #974

**Comment by UltraBlackLinux** [comment]
I don't like the toxicity that comes with your comment @scarf-generic

**Comment by scarf-generic** [comment]
> I don't like the toxicity that comes with your comment @scarf-generic

Its only toxic if you want it to be. Im quoting something that i said on a different issue because it applies here as well. Its not sarcastic, i want this added too. I just commented on the fact that many people have suggested this, and that suggesting it more will likely get anuke to add it. Would appear that this happened with naval support units, i dont see why it wouldnt work here.

Im sorry you find my comment toxic i guess, not really sure how to reply to that @UltraBlackLinux

**Comment by Legomonster33** [comment]
> Would appear that this happened with naval support units, i dont see why it wouldnt work here.

Ver epic yoes
