### ISSUE TITLE
core in c++

### ISSUE THREAD

**Issue by wirke** [Anuken/Mindustry-Suggestions#128]
Have you tried to rewrite the core in c++? This would give more performance, because io servers (pvp) often have lags on some maps.

**Comment by potatoisagender** [comment]
woah. You want to rewrite the whole game, in a whole new language??

**Comment by itcannotbe** [comment]
> woah. You want to rewrite the whole game, in a whole new language??

Actually.....

Woah. You want to rewrite the whole game, in a whole new language because you experienced lag in a specific server, running a specific gamemode that actually push the game to it's limits because of the shear size of the map, the humongous amounts of units and players involved, and you're counting a rewrite to c++ to solve the issue when it really isn't if the people playing there is actually trying to destroy another instead of amassing hordes of units per gameplay?

You must not be serious?

**Comment by wirke** [comment]
No, I just want to turn the kernel into a C++ library and attach it to the java code.

**Comment by itcannotbe** [comment]
You've clearly contradicted your initial request.

**Comment by wirke** [comment]
I was trying to convey that initially.

**Comment by Anuken** [comment]
Optimization is nowhere near as simple as saying "C++ is fast, Java is slow, rewrite it". I have no interest in rewriting Mindustry in C++, and it's far too late for that anyway.
