### ISSUE TITLE
Less-persistent logic links

### ISSUE THREAD

**Issue by valtsu41** [Anuken/Mindustry-Suggestions#1398]
Every time I do something with logic, I get annoyed in that if I delete a block that is linked to a processor, the link still persists after that. This makes it really annoying, because I need to spam the block that was linked to the range of the processor to get the linked block back to the place it was (since I usually forget it) and disable the link.

I request that this would be changed by either automatically deleting dead links, adding a delete dead links -feature or by simply keeping displaying dead links, so they can be unlinked.

**Comment by Vlexa** [comment]
I was looking for this issue because i find this rather annoying myself. Its probably like this to work fine with automated reconstruction. 

it might just be like this because logic is still incomplete. 

**The main issue here is that even if i manually unlink, the constant persists. Thats is probably a bug.** Meaning if i unlink cell2 and then link another its suddenly cell3 instead of cell2. Manual unlinking should clear the constant from memory for reuse on another block. 

The only way i have currently of clearing a processor link memory is to unlink all elements, copy ( F key ) it and place again. Then all is reset.

**Comment by rdragonrydr** [comment]
Seconded. I'm having the same problem.

A place where this is really awkward is if the block being removed is one I physically can't leave in that location, but now my link numbers are all messed up, and it breaks my code.

I'm not actually sure if this persists over a schematic/paste operation, but I'm worried about it breaking a _second_ time if I use the new links and then paste a copy of that in (probably not, since it seems to remember links even if the item is *physically not present in the schematic* (which is also very frustrating)).

As another note, pasting in a schematic with a disconnected link results in whatever item took that spot now having a link.
