### ISSUE TITLE
Water extractor is being overused

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#1402]
**Describe what you would like changed, and why.**
60 energy / sec is too little for the thing. Water extractor is being used in 95% schematics with liquids involved. Nobody even cares about other liquid sources.
***Typical player:*** *oh it's a nice lake over there but I am too lazy to build an actual pipe to my building so I will just use water extractor it's only 60 energy per second*   

**Describe the changes you want to propose. Include possible alternatives.**
Make water extractor use 150 energy / sec. So the players would prefer actual water sources. This will also force players to not use steam generators too much. Also cultivators should use less water then or no energy at all.

**Comment by Quick-korkc** [comment]
not all sectors have water tile
steam gens is early-middle game only power
most of schematic who using water extractor use a large space
water extractor also get nerfed in v6

more nerf = useless

**Comment by itcannotbe** [comment]
The nerf is a joke.
From 7.8 water per second to 6.6 water per second isn't that large of a nerf tbh.

**Comment by Quick-korkc** [comment]
> The nerf is a joke.
> From 7.8 water per second to 6.6 water per second isn't that large of a nerf tbh.

no
did you see the efficiency blocks?
i agree if in servers, but in campaign ABSOLUTELY NO

**Comment by Bedsurfer** [comment]
> not all sectors have water tile
> steam gens is early-middle game only power
> most of schematic who using water extractor use a large space
> water extractor also get nerfed in v6
> 
> more nerf = useless
Most sectors do after an update a few builds ago. Size doesn't matter, people use them because its convenient and it gets repetitive, its to easy to use them, its much more interesting to use pipes/pumps then use ext but often they are easier to use. Also, the nerf was nearly useless. A nerf is justified not only for balance reasons but for gameplay reasons.

**Comment by itcannotbe** [comment]
> > The nerf is a joke.
> > From 7.8 water per second to 6.6 water per second isn't that large of a nerf tbh.
> 
> no
> did you see the efficiency blocks?
> i agree if in servers, but in campaign ABSOLUTELY NO

Ah yes, I think you forgot that you can place the water extractor on tiles without negative affinities and go on with your day.

**Comment by BlueWolf3682** [comment]
water extractor truly should be made a literal last resort in my opinion, with a high power cost and low output (maybe 120pu/s and 4.4lu/s output)

**Comment by Quick-korkc** [comment]
> > > The nerf is a joke.
> > > From 7.8 water per second to 6.6 water per second isn't that large of a nerf tbh.
> > 
> > 
> > no
> > did you see the efficiency blocks?
> > i agree if in servers, but in campaign ABSOLUTELY NO
> 
> Ah yes, I think you forgot that you can place the water extractor on tiles without negative affinities and go on with your day.

dont thinking about yourself
most of designer helped with water extractor

**Comment by itcannotbe** [comment]
> water extractor truly should be made a literal last resort in my opinion, with a high power cost and low output (maybe 120pu/s and 4.4lu/s output)

You can't really do 4.4, maybe 4.2 (0.07 lu/t)?

**Comment by D-player1** [comment]
Blame the map maker for not putting water blocks

**Comment by GreyMario** [comment]
Blame the issue creator for wanting to ban every single unit and block that he can't use effectively.

Two bucks says he was in a pvp map that was made before tile affinities and now the other guy got 140% water while he gets 30%.

There's nothing wrong with the Water Extractor in its current position, except maybe for its _atrocious_ placement in the tech tree behind Salt Flats.

The Water Extractor exists to enable various builds to work in most locations. If you want to restrict its value, make a map with low affinity tiles. If you want to encourage pumps, _put water in the map._ Even five or six water tiles hiding in a corner near a point of interest will do a lot for inspiring players to run an electrical pump and a pipeline. 60/s per extractor _is_ expensive, even at 140%. Players _will_ install pipelines and pumps if there is a water source and they're building a bigger setup.

**Comment by Slava0135** [comment]
> Blame the issue creator for wanting to ban every single unit and block that he can't use effectively.
> 
> Two bucks says he was in a pvp map that was made before tile affinities and now the other guy got 140% water while he gets 30%.
> 
> There's nothing wrong with the Water Extractor in its current position, except maybe for its _atrocious_ placement in the tech tree behind Salt Flats.
> 
> The Water Extractor exists to enable various builds to work in most locations. If you want to restrict its value, make a map with low affinity tiles. If you want to encourage pumps, _put water in the map._ Even five or six water tiles hiding in a corner near a point of interest will do a lot for inspiring players to run an electrical pump and a pipeline. 60/s per extractor _is_ expensive, even at 140%. Players _will_ install pipelines and pumps if there is a water source and they're building a bigger setup.

I just see a lot of peoples ignoring water sources. That's the problem. They just regret using them...

**Comment by Slava0135** [comment]
Just look on all the schematics - water extractors everywhere. Only small part of them have an actual water input.

**Comment by Slava0135** [comment]
water is not valuable - that's the point

**Comment by itcannotbe** [comment]
Actually, 60/s is negligible if you're running a water extractor to run something that makes power.

Also the extreme convenience water extractor provides outweighs any benefit with using an actual pump.

**Comment by GreyMario** [comment]
_oh no, people are making CONVENIENT SCHEMATICS with WATER EXTRACTORS in them better ban water extractors_

Go build shit on the fly if you want power-efficient water supply.

**Comment by RedstonerKBC** [comment]
The funniest thing is when noobs put 2-3 extractors near a single drill or whatever when it only needs 1. Also funny when they think 1-2 extractors will supply thier schem with enough water.

**Comment by itcannotbe** [comment]
> _oh no, people are making CONVENIENT SCHEMATICS with WATER EXTRACTORS in them better ban water extractors_
> 
> Go build shit on the fly if you want power-efficient water supply.

There are already schematics out there that just requires you to feed ot with water.

Also one multiplayer server tried banning/nerfing water extractors and people actually used pumps.

**Comment by Slava0135** [comment]
The only reasonable way to force people using actual piping is making the extractor 4 by 4 (27 water /sec, 240 energy / sec, 4x cost as well). So you will tend to not place it right next to drill and etc.

**Comment by Bohaska** [comment]
> There's nothing wrong with the Water Extractor in its current position, except maybe for its _atrocious_ placement in the tech tree behind Salt Flats.

Wouldn't be after my pull request in Anuken/Mindustry gets accepted (Ruinous Shores instead)

**Comment by Bohaska** [comment]
> The only reasonable way to force people use actual piping is making the extractor 4 by 4 (27 water /sec, 240 energy / sec, 4x cost as well). So you will tend to not place it right next to drill and etc.

3x3 will be better (14w/s, 120e/s, 2x cost)

**Comment by itcannotbe** [comment]
Actually power cost is not an issue since water extractors stop running when it can't output it's output.

Only size and output only matters.

**Comment by mangblekok** [comment]
> Water extractor is being used in 95% schematics with liquids involved

The reason it's being overused in schematics is because schems are readily available to be used, while water pumps inside schematic are rarely seen because water source are not always available.
It costs space and power to operate them, water extractor also has been nerfed down, so I don't see any problem here...
Thus I disagree with this proposal.

**Comment by Slava0135** [comment]
> > Water extractor is being used in 95% schematics with liquids involved
> 
> The reason it's being overused in schematics is because schems are readily available to be used, while water pumps inside schematic are rarely seen because water source are not always available.
> It costs space and power to operate them, water extractor also has been nerfed down, so I don't see any problem here...
> Thus I disagree with this proposal.

How often do you see drills in schematics? Only if it's some sort of sand->oil maker. And water extractor should be used the same way then. Out of most schematics.

**Comment by Slava0135** [comment]
I don't want to actually nerf the thing. Just make people use it other way. The same wsy they are using drills.

**Comment by itcannotbe** [comment]
> > Water extractor is being used in 95% schematics with liquids involved
> 
> The reason it's being overused in schematics is because schems are readily available to be used, while water pumps inside schematic are rarely seen because water source are not always available.
> It costs space and power to operate them, water extractor also has been nerfed down, so I don't see any problem here...
> Thus I disagree with this proposal.

Actually, in campaign there are actual water block now compared to the previous version.

Also if you forgot. Water extractors are still fucking extremely convenient to use. Cause it's a fucking 2x2 block that provides enough water to the blocks that need them. Since there is no block in the game needs more that 2 water extractors to make that certain block that needs water run at maximum efficiency.

**Comment by Slava0135** [comment]
![image](https://user-images.githubusercontent.com/40753025/100911732-a88c0780-34e0-11eb-833b-59b031d3fe1e.png)
***omg***

**Comment by Slava0135** [comment]
l I t E r A l L y W a T e R a R o U n D

**Comment by Humanoid-X** [comment]
We often see drills in schematics.
But that's only because things like "Copper Extractor" or "Titanium Extractor" don't exist in game.

**Comment by itcannotbe** [comment]
> We often see drills in schematics.
> But that's only because things like "Copper Extractor" or "Titanium Extractor" don't exist in game.

Separator?

Also anything that makes scrap aside from drills have been ruled as OP by the dev.

**Comment by Slava0135** [comment]
> > > Water extractor is being used in 95% schematics with liquids involved
> > 
> > 
> > The reason it's being overused in schematics is because schems are readily available to be used, while water pumps inside schematic are rarely seen because water source are not always available.
> > It costs space and power to operate them, water extractor also has been nerfed down, so I don't see any problem here...
> > Thus I disagree with this proposal.
> 
> Actually, in campaign there are actual water block now compared to the previous version.
> 
> Also if you forgot. Water extractors are still fucking extremely convenient to use. Cause it's a fucking 2x2 block that only requires power and provides enough water to the blocks that need them. Since there is no block in the game needs more than 2 water extractors to make that certain block that needs water run at maximum efficiency.

just look on that shit above... c O n V i N i E n T

**Comment by BlueWolf3682** [comment]
> > water extractor truly should be made a literal last resort in my opinion, with a high power cost and low output (maybe 120pu/s and 4.4lu/s output)
> 
> You can't really do 4.4, maybe 4.2 (0.07 lu/t)?

that sounds amazing

**Comment by BlueWolf3682** [comment]
the steam generator nerf was entirely unnecessary when you think of it - its just wexts being way too op, i found steams to be quite balanced with what they were in v5

**Comment by Bohaska** [comment]
> > > water extractor truly should be made a literal last resort in my opinion, with a high power cost and low output (maybe 120pu/s and 4.4lu/s output)
> > 
> > 
> > You can't really do 4.4, maybe 4.2 (0.07 lu/t)?
> 
> that sounds amazing

Guys, should I ask Anuke for his opinion?

**Comment by Bohaska** [comment]
Never mind, this will never get accepted...

**Comment by YellOw139** [comment]
> l I t E r A l L y W a T e R a R o U n D

It's so annyoing, right? Sadly all you can do is
![image](https://user-images.githubusercontent.com/70975516/101136723-6d8bf000-3616-11eb-9414-7823c734009a.png)

If people want to waste energy and space on extractors, that's what they'll do anyway. No matter how inefficient they become, the problem won't disappear. Something else you could do that won't guarantee the problem will disappear is buff conduits. Drills generally mine much slower than pumps, so slapping 10 drills with a conveyor isn't painful, assuming you match the drill/conveyor tiers decently.

Our real watery problem here is that you can't just slap 10 pumps with a conduit. A normal conduit alone won't ever carry the output of 10 pumps, even when you match pump/conduit tiers decently. The ratios are way off.

Conduits and their low capacity compared to what pumps supply and what liquid consumers need are the real pain, not extractors being too efficient.

As you said yourself, extractors are used even if inefficient. Therefore making them more inefficient won't discourage people from using them. Buffing conduits though should encourage using them. Extractors are easy to use, but conduits are a pain. That's why I prefer slapping down conduits near compact schematics, and near water. If I'm building less conduits, I'm happy. On any given day when my laziness strikes though, I still occasionally waste power and space. And I'm completely guiltless. I know it's bad, but I joined the server to have fun, not to stress myself out. It's not like the next griefer or the next dumb person ruining functional stuff without anyone noticing early enough won't end our game sooner.

Recently I restarted the campaign. Seeing Anuke removed researching items with other items and changed the order of the built-in maps several times, I wanted to start over and see how the fresh v6 experience looks like because I get tired easily with the server toxicity in all multiplayer games I play.

Let's check out the Biomass Synthesis Facility. It's not perfect, but tech is limited and after waves were gone I stopped caring and moved on to other sectors.
![image](https://user-images.githubusercontent.com/70975516/101140002-058bd880-361b-11eb-8f38-75f8fc1d1710.png)

Notice how it takes only 1 conveyor to somewhat efficiently fuel that many power generators, but it takes 2 f***ing  conduits to supply 3 steam gens. It takes 1 conduit per spore press. If I told you to build 1 conveyor per every single factory or drill in the game you'd laugh and ask me what kind of satanic punishments I'm trying to condemn you to.

But when you build at least 1 conduit per every per every single factory, or, at higher tiers, pump in the game, it's all normal. Definitely not painful. Using conduits is absolutely not painful at all. Then using water extractors is, again, painful too, because efficiency, but at least you can easily slap those down, and guess what? They take up less space than 10 useless conduits and 1 correctly balanced pump would.

Now, their low capacity might also be due to price. Solution: I will later submit a suggestion to increase the price and capacity of pumps. Nerfing water extractors solves nothing. It's been done, and can further be done, but pump-conduit-consumer ratios will stay nevertheless screwed.

The liquid system is pretty broken as it stands, and not nerfing nor removing extractors will help.

**Comment by itcannotbe** [comment]
Actually conduits themselve can transfer a lot of fluid, They just look like they don't.

**Comment by Slava0135** [comment]
I'll try to make a smart pipe building (auto bridging). Also fix bridge pipes.

**Comment by YellOw139** [comment]
@itcannotbe Open an issue. According to the game the capacity should be 10 liquid/sec. Provided the game works as intended, that should not happen.

This bug is just an insult for people who try to love their liquids efficiently in a functioning game, not the ones who are trying to move them inefficiently or in a broken game.

**Comment by itcannotbe** [comment]
> @itcannotbe Open an issue. According to the game the capacity should be 10 liquid/sec. Provided the game works as intended, that should not happen.
> 
> This bug is just an insult for people who try to love their liquids efficiently in a functioning game, not the ones who are trying to move them inefficiently or in a broken game.

@YellOw139 When did capacity meant throughput?

**Comment by YellOw139** [comment]
Never mind I'm thinking too conveyorish... Man, I'm tired. Since I said wrong stuff today I'd rather admit it now rather than saying another half-thought thing that's not applicable. I'll see later how much my point still stands.

One thing's for sure: something makes players favor water extractors over pumps, but I'm not sure a water extractor nerf is the solution. They consume more power than pumps, so they are already worse. Why people keep using them is a mystery and I doubt it's as simple as 'because they are still too good, nerf them'. Might be an obvious it's easier, but then this begs the question: can conduits be made easier to use or water extractors harder? The water extractor spam makes it clear that people don't care about water supply efficiency, and the fact that people will spam stuff without checking if there's even enough power means noobs don't care much about that either. This makes me wonder if the game should even be altered just for that. Water is still the source of spores and cryo, and all cooling.

Meta suggestion: Make Tantros a desertic planet. Water extractors were designed to allow for waterless maps. We're in space after all, how common should surface water be?

**Comment by XxsuperdeadlysniperxX** [comment]
LIQUID TANK SPAM ALLLLLLLLLLL DAYYYYYYYYYY SUNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

**Comment by magikcello** [comment]
stfu water extractors make schematics useful and compact bruh i dont wanna something like pipe mess and wasting space with mass water and item bridges. Also nerf was very bad cuz cultivator now needs two water extractors not one.

**Comment by XxsuperdeadlysniperxX** [comment]
@mangblekok 
#1 please don't be toxic

#2 water extractors are for those areas with little to no water _it says this in the discription of the building_ 

_however_ people do disregard the pump by _**placing water extractors near water**_

Oh and yes water extractors are being over used to a infuriating extent

**Comment by RedstonerKBC** [comment]
> stfu water extractors make schematics useful and compact bruh i dont wanna something like pipe mess and wasting space with mass water and item bridges. Also nerf was very bad cuz cultivator now needs two water extractors not one.

You know what we do here in America to kids like you who tell other people to shut the fuck up? We take them to the doctor's, prescribe them pills, force-feed them those pills, and call them cured as long as they take them the rest of their life. All the while your brain is frying on what is essentially legal street drugs, this "illness" goes on your records permanently so that every school, every college, every job you apply for, every government assistance you signup for, and every background check brings this incident up. You'll forever (again this incident stays on your records permanently) be known as that one kid with mental issue that no one wants to associate with. Rip social life. Rip chances of ever finding a job.

Of course if you're an adult we also send your violent ass to jail no top of the above.

If I were you I wouldn't be letting your anger out so easily. Here in America doctors and prisons love fresh meat that they can take advantage of. You keep this up one day you'll be caught and you'll end up just like all the other zombie children who have depression and social issues because they fried their brains with these miracle cure-all pills. This isn't a joke! Bury your anger issues now before it is too late!
