### ISSUE TITLE
Nuclear Production Complex guardian balance

### ISSUE THREAD

**Issue by CitrusWire** [Anuken/Mindustry-Suggestions#1427]
Build 120

The flying guardian on the NPC seems over powered compared to the tech you have, and given the tactic it uses.

You've just gotten Thorium tech, so like a smart little bunny you put down lots of Fuses. They are designed to take out Guardians right? Except with not this Guardian!

The tactic it uses is to hold at its maximum range and snipe your turrets. Just what I'd do if I was it, except you only have two turrets that have enough range to hit it: Cyclone and Tsunami. The Fuse on the other hand you could outrange by just sneezing at it so it's worthless in this fight.
Even then, because of its extreme range, it can just pick them off one by one and only one or two of them will be able to hit at it a time, but they get killed in short order so...

After about 60 seconds I'd taken it down about 5%, and it was just sitting there picking things off...

Fortunately I managed to predictably cheat my way past it using this bug: https://github.com/Anuken/Mindustry/issues/3697

**Comment by the-kido** [comment]
First of all what unit are you talking about second parallaxes exist and although they don't pull very hard on bigger air units they pull them enough to kill them.

**Comment by CitrusWire** [comment]
The Guardian, I don't know what it's called, nor do I know of a way to find out (Enemies no longer appear in the codex).

**Comment by D-player1** [comment]
I don't know parallax yes, and i don't want to put down a lot of menders because who cares, also i don't wanna cover my plast wall with surge because i believe that they can handle it

**Comment by hadron13** [comment]
use your brain, prepare for the battle, use foreshadows, plastanium and phase walls, polys.

**Comment by CitrusWire** [comment]
> 
> 
> use your brain, prepare for the battle, use foreshadows, plastanium and phase walls, polys.

a) The first playthrough you don't know what to expect. I did plan for a guardian but not one with this tactics. Springing a super-powerful enemy on the player with no forewarning as to its nature and no hint that it requires a very specific defensive strategy is bad game design because it almost guarantees the player will lose on first playthrough.
b) You don't have phase walls at this point in the campaign,
c) You don't have "foreshadows" (whatever they are) at that point in the campaign

**Comment by Humanoid-X** [comment]
Eclipse is the strongest air attack unit and are design to be strong. you can fly in front of it to attract it into flying in your direction. You can easily dodge, their rotation are sooooo slooooooow.

**Comment by CitrusWire** [comment]
> 
> 
> Eclipse is the strongest air attack unit and are design to be strong. 

I'd suggest that from a game balance perspective, putting the "strongest air attack unit" on a mid-game map (where you've just got thorium tech), needs a rethink.

**Comment by SarisWinterwisp** [comment]
I agree entirely by the way. Parallaxes need a buff or larger variant for bigger units, there needs to be a better warning system than "guardian in 10 waves, goodluck!" And a better way to beat them through conveyor or mender spam with preferably thorium tech.

I lost this sector twice because I assumed fuses would work with parallaxes. I lost both times because the first time I didn't have enough menders or plastanium walls and the fused didn't do anything against it in time. The second I used parallaxes to pull it over the fuses and over the plastanium wall where it subsequently destroyed all the menders since fuses are a joke to it. I beat it by leading it to the top of the map and putting conveyors under it which caused it to back up and continue to destroy them while I built a wall with 80 menders and a single salvo that slowly killed it. 

Unfortunately this map although nice needs some fixing in this aspect or maybe the game at large. It's frustrating to lose a sector by using the provided tools and then oy winning through extremely memey methods that take away from the game. I suppose I could have teched up to foreshadows but that'd be further frustrating to abandon the sector because it becomes a hardwall in a player's natural progression
