### ISSUE TITLE
PC descriptions on hover

### ISSUE THREAD

**Issue by tihomir-kit** [Anuken/Mindustry-Suggestions#144]
**Describe what you would like changed, and why.**

When you want to read a description of say a tower or any other element, you first need to click on that element and then on the question mark. There are plenty of elements to learn when you're starting to play this game and this UX is tedious and slow. 

**Describe the changes you want to propose. Include possible alternatives.**

On PC, instead of requiring to click on the item and then on `?`, simply implement an "on-hover" tooltip. This would speed up the learning process a lot.

Thanks

**Comment by potatoisagender** [comment]
you could probably put an option to eliminate this, because I think that would be annoying to experienced players. A big dark box popping up? I don't think so.

Also, wrong label.

**Comment by pootzko** [comment]
I thought it was more feedback than feature request.

Also, does this github only consist of smug kids?

**Comment by potatoisagender** [comment]
I might appreciate your idea, but when I'm flying around I don't want my cursor clogging my screen with boxes I don't really need at that moment. 

It's both, but you are asking for a new feature... 'On PC, instead of requiring to click on the item and then on ?, simply implement an "on-hover" tooltip. This would speed up the learning process a lot.'

**Comment by pootzko** [comment]
I wouldn't mind if there was a switch in the settings to turn it off either. And it could probably be done in a non-intrusive way anyway, if it was snappy and showed up on the correct side to not get in the way. Many games have these kinds of tooltips and if it's done well, you don't even notice, it's not in the way.

I can't change the label anymore anyway. Whoever has permissions to change it is welcome to do so, I just wanted to leave the idea here.

**Comment by itcannotbe** [comment]
What info would you even want for present every time for you to even suggest this?

**Comment by pootzko** [comment]
The description (text between the two horizontal lines) after `?` is clicked. And perhaps input and output. For players who have played this for a while this is all probably obvious, but for new players it's not. I found myself in a situation where I'm looking for a specific thing to put down on a map and I had to keep clicking around and opening the details of each item until I found what I needed. With hover it could have been much faster.

**Comment by itcannotbe** [comment]
How many hours in the game would you need to consider it to become an annoyance rather than a help?

**Comment by pootzko** [comment]
If done well it doesn't have to be an annoyance and you wouldn't even notice it being in the way. You shouldn't notice good UX, it should just be there and guide you in using the app. I'm just noticing what could be improved. I work as a dev and this is one of the things that we strive to do in general - remove the friction between the user and the app, make it as easy and as clear as possible for the user to use the app to achieve his/her goal - which in this case is to find the right element to put on the map.

How this is usually done is you turn on these kinds of tooltips after say 1-2 seconds of hover delay and you turn it off immediately. That way it doesn't get turned by accident too much and it's easy to hide it again. And it's still faster and easier to do than 2 extra clicks and then an extra click to turn hide the full description. 

Tooltips are everywhere, websites have them, games have them, they're useful, they don't have to be annoying. Just try to do anything here on github, hover over icon. Within a second, a description will appear. Move the mouse away - it goes away. It's there to help.

**Comment by pootzko** [comment]
I just turned on the game to make a screenshot, and realized that it currently has the kind of tooltip that I had in mind:

![image](https://user-images.githubusercontent.com/535842/81095155-86a3b580-8efc-11ea-8d78-69cae72d1005.png)

It's exactly that, the part I highlighted with red. I just think a bit more info could be fitted in there. I'm sure none of you even notice these tooltips because they're part of the game and you're used to them. 

A potential game setting for this could be called "Verbose tower/item/whatevertheyrecalled descriptions" so whoever doesn't like it could turn it off.

Also, these icons are not very clear, they don't communicate intent and could also have the same type of a tooltip to explain what each one is about:

![image](https://user-images.githubusercontent.com/535842/81095430-e5692f00-8efc-11ea-9e0e-4142355e8867.png)

**Comment by zethnest** [comment]
If this were to be implemented, F1 would be a nice button to make the Hint Tooltip togglable

**Comment by itcannotbe** [comment]
> When you want to read a description of say a tower or any other element, you first need to click on that element and then on the question mark. There are plenty of elements to learn when you're starting to play this game and this UX is tedious and slow.


But why do you need to read the description of the block during gameplay?

Also additional question: What info from the block info (info found by clicking "?") do you always need to know during gameplay?

**Comment by pootzko** [comment]
Because I'm new to the game and there isn't a trivial number of blocks / their uses / resource transformations to remember and what's inside current tooltips is not enough in my opinion. 

I forget the details of each block logic and which resources can be combined into which new ones using which blocks. And I need to remind myself as I'm playing - until I learn it. The game doesn't communicate these things clearly enough in my opinion nor are these things always super logical/intuitive. For example requirements for creation of Pyratite or Spore Pods, or some of the logic / routing gates, you need to keep looking it up at first.

Some people simply prefer to have a bit more guidance while they're playing. I'm one of these people. I don't see anything wrong with that.

I wrote what exactly I'd like to have inside the tooltip in one of my previous replies.

**Comment by marco-trovato** [comment]
I totally agree about having the option. Skilled player can turn it off anytime.
I have several hours of gameplay and still get frustrated by forgetting the right input/output, and having to click the info box is really tedious.
