### ISSUE TITLE
Poly Behaviour

### ISSUE THREAD

**Issue by h3rlihy** [Anuken/Mindustry-Suggestions#1468]
Would be useful if the Poly unit followed the player or fled from enemies. Sometimes they sit idle in the most useless of places & don't respond to the rally command from command centres (which would be helpful for repositioning them). They are pretty valuable units to be lost because they happened to idle right in the path of enemies. Would also be helpful if they automatically repaired damaged structures as we don't have a repair drone now which was absolutely useful to have before

**Comment by antonilol** [comment]
the mega is a repair drone

**Comment by antonilol** [comment]
you can make a poly command center with logic

**Comment by h3rlihy** [comment]
> the mega is a repair drone

But the poly can also repair if you command them & fire at your own buildings, but it doesn't do this on it's own, seems like it should? It has repair capability but doesn't use it

**Comment by XxsuperdeadlysniperxX** [comment]
Quasar has the repair ability as and also doesn't use it

**Comment by thw0rted** [comment]
I noticed that mobile has "auto fire" and desktop doesn't.  I think Poly might also repair automatically on mobile but not on desktop.  Can anyone else confirm this?

**Comment by XxsuperdeadlysniperxX** [comment]
What you mean by repair? @thw0rted

**Comment by XxsuperdeadlysniperxX** [comment]
So on mobile polys can
- 1 rebuild
- 2 has a repair field
- 3 with logic can heal buildings

Btw this game is cross platform

**Comment by XxsuperdeadlysniperxX** [comment]
But that list is assuming they don't seek out a repair point if damaged or use gun without logic

**Comment by thw0rted** [comment]
I'm still pretty new - I played a bit a year or so ago but just came back to 6.0 recently, and anyway I never used to build units very often.

I thought if I made a poly, I'd be able to tell it to stay near a spot, then it would repair any damaged buildings and rebuild any destroyed ones. I think (at least on desktop) it's rebuilding but not using its repair gun. It sounds like that's a known issue, since Anuken said it "doesn't have AI yet" (for using its gun).

**Comment by Kyllingene** [comment]
1: I will not judge, simply state that using the template will drastically increase the likelihood of Anuke looking at your post.

2: If thw0rted is correct, then this issue is known, and could possibly be closed *if you wish.*

Here is the template, I would suggest fitting your (perfectly fine) suggestion to it:
```
**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

```
