### ISSUE TITLE
Balanced T-merge of Plastanium Conveyor/Belt

### ISSUE THREAD

**Issue by connorcrothers** [Anuken/Mindustry-Suggestions#1477]
**Describe the content or mechanics you are proposing.**
![image](https://user-images.githubusercontent.com/16570564/101306061-f8850a00-3811-11eb-8665-02a8ab68d424.png)
^ willful or bug?

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
- Feature adds consistency w/ how other conveyors work.
- Feature adds predictability of plastanium conveyor merge behavior (even after player is aware of this mechanic) when player doesn't know which side will fully saturate first.
- Feature allows for intentional bottle neck (2 lanes =>1 lane), without a loss of variety in resources received.
- W/out feature, plastanium conveyor merges currently easily & unpredictably sneak up on the player (not yet familiar with this difference in behavior) when sudden saturation of one side goes unnoticed, and results in an untimely shortage of critical resource(s).

- W/ out feature, AFAIK, balanced T-merge of plast conveyor requires either: (A) logic, or (B) fully unloading then merging via many pre-v6 belt-types and reloading... and neither will likely be a viable/favorable solution to most players/scenarios.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Try
XXXXX
XXPPP
XXPXX
PPPXX
XXPXX
XXPPP
XXXXX

**Comment by joshuaptfan** [comment]
Players should never rely on consistent merging (without logic) for their designs to function. Mindustry is FPS-dependent, and any frame hiccups can cause conveyor inconsistencies.

**Comment by connorcrothers** [comment]
@itcannotbe , can you define X/P? I'm unfamiliar w/ the notation.

I'm running a `2080ti Founders Edition` AND an `Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz, 3600 Mhz, 8 Core(s), 16 Logical Processor(s)`...

So I'm skeptical of your "FPS induced hiccups" theory.

Also, idk if I'm looking for "consistent" merging so much as "expected". I only said "consistent" earlier because all other conveyor types do this (alternate the recipient belt when both input belts are perpendicular to output belt) already.

**Comment by InvalidError404** [comment]
From what I remember working on my Threshold Unloader fork back in 5.x, the way blocks pick which other block to transfer stuff into is by scanning possible inputs/outputs and offsetting the position it starts checking from with each call to get some degree of rotation going on, some of it being my own patch that got merged in to improve (but not guarantee) output diversity. Still a huge improvement over unconfigured unloaders and similar blocks systematically outputting resources in numerical order of resource ID before then.

If that hasn't changed in 6.0, then the reason why one input belt gets "preferred" over the other is simply that the rate at which the junction is checking whether it can move stuff happens to make the offset line up with the same belt most of the time a spot opens up in your current setup. The behavior may change depending on orientation and the order things are created.

The discrepancy between regular belts and plastanium could be because they use different code paths to handle bulk-to-bulk transfers.

In any case, if you want guaranteed diversity and don't want to wait whoever-knows-how-long for someone to agree with your issue, write a patch for it, get it merged in and pushed out in a new release, your safest bet as josh said is to use ulog to monitor what is on nearby belts and enable/disable belts accordingly. Another option would be to change how the incoming belts are filled to make their aggregate throughput slightly under one full belt and keep that belt rolling so there never is a backlog clogging either side. A third option would be to dump input belts in a vault and repack from there, may still require some ulog to prevent the vault from overflowing

**Comment by connorcrothers** [comment]
Self patch? I could. but pass for now. My lack of familiarity w/ codebase makes delta LOE != delta QOL.

I'm aware of work arounds, just feel work arounds aren't well balanced.

Leaving open for as a potentially low/medium level improvement for Anuken to consider adding to the backlog.
¯\\_(ツ)_/¯
