### ISSUE TITLE
Launch pad is too slow

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry-Suggestions#1503]
The launch pads are very slow at the start of actually applying it to a sector because of the time it takes the launch pads to actually launch
**complete balancing overhaul**

**Comment by XxsuperdeadlysniperxX** [comment]
I don't give a actual f about yalls opinions only anukes opinion actual matters cuz he's the developer the one who made the entire game

**Comment by D-player1** [comment]
Ah yes, i can see that setting up some scatters is super hard

**Comment by the-kido** [comment]
You are basically living in your own world if you think we cant have an impact on your choices. For one i think the waves are fine for the difficulty it is and tbh anuke will not even glimpse at this PR if you dont do 

[x] the goddamn boxes

**Comment by sudobeans** [comment]
Fast waves can be pretty scary, but keep in mind that fungal pass _is_ a high-threat sector (according to [this post](https://github.com/Anuken/Mindustry-Suggestions/issues/1388) anyway, I didn't get to it yet), so it's fitting. Sorry the sector's hard - good luck beating it!

**Comment by Quick-korkc** [comment]
Too fast?
are you ever attack eradication sectors?

**Comment by XxsuperdeadlysniperxX** [comment]
This isn't a feature request you know right?

**Comment by XxsuperdeadlysniperxX** [comment]
> Fast waves can be pretty scary, but keep in mind that fungal pass _is_ a high-threat sector (according to [this post](https://github.com/Anuken/Mindustry-Suggestions/issues/1388) anyway, I didn't get to it yet), so it's fitting. Sorry the sector's hard - good luck beating it!

The sector is a medium enemy base

**Comment by XxsuperdeadlysniperxX** [comment]
> Ah yes, i can see that setting up some scatters is super hard

Finally a person who actually plays the game

**Comment by XxsuperdeadlysniperxX** [comment]
> You are basically living in your own world if you think we cant have an impact on your choices. For one i think the waves are fine for the difficulty it is and tbh anuke will not even glimpse at this PR if you dont do 
> 
> [x] <-- the goddamn boxes

Why are you even trying to legitimately tell me to shut up when you can't even tell the difference between a suggestion/feedback issue verses a feature request

**Comment by XxsuperdeadlysniperxX** [comment]
> Too fast?
> are you ever attack eradication sectors?

Im not setup for eradication level bases plus fungal pass it a medium enemy base with eradication waves does this make sense to you?

**Comment by the-kido** [comment]
First off all i am a total idiot.
 second off all you can never win an argument against an idiot 
i suggest anyone else who will comment **to just not to.**

**Comment by XxsuperdeadlysniperxX** [comment]
> First off all i am a total idiot.
>  second off all you can never win an argument against an idiot 
> i suggest anyone else who will comment **to just not to.**

**have you the goddamn game?**

**Comment by GreyMario** [comment]
OP can't even figure out how to launch with a loadout and build a decent defense with his chosen starting resources.

Sad.

It's a video game. Video games have difficulty curves. Fungal Pass isn't even thst big of a step in difficulty once you understand attack sectors.

If you can't _git gud,_ the answer isn't "nerf it for me because I'm bad".

Thread over.

**Comment by Wetelemon** [comment]
As an old man said some time ago, you will never win an argument against an idiot.

**Comment by the-kido** [comment]
121.1 made fungal pass slightly easier. Happy?

**Comment by sudobeans** [comment]
> OP can't even figure out how to launch with a loadout and build a decent defense with his chosen starting resources.
> 
> Sad.
> 
> If you can't _git gud,_ the answer isn't "nerf it for me because I'm bad".
> 
> Thread over.

This is the area for Mindustry feedback. If someone finds the game to be unbalanced, then they should post about it here. It doesn't matter if they are worse than you, because as a person who plays the game, their opinion is just as valid as yours. You wrote a response where you call OP "sad" and "bad," simply because they had trouble in a video game. Does that make you feel better about yourself?

**Comment by XxsuperdeadlysniperxX** [comment]
> OP can't even figure out how to launch with a loadout and build a decent defense with his chosen starting resources.
> 
> Sad.
> 
> It's a video game. Video games have difficulty curves. Fungal Pass isn't even thst big of a step in difficulty once you understand attack sectors.
> 
> If you can't _git gud,_ the answer isn't "nerf it for me because I'm bad".
> 
> Thread over.

The fick you talking about dude im good at mindustry but when wave 2 is like 30 seconds and its a air wave and theres 2 cores there for two spawn points and the wave is setup to send like 5-10 polys per core then you have 10-20 polys coming at you all while you don't have anti air to combat them so bruh don't call a damn noob and check your own skill

**Comment by XxsuperdeadlysniperxX** [comment]
> As an old man said some time ago, you will never win an argument against an idiot.

🤔 you can put said person in a mental corner if your smart enough

**Comment by XxsuperdeadlysniperxX** [comment]
> > OP can't even figure out how to launch with a loadout and build a decent defense with his chosen starting resources.
> > 
> > Sad.
> > 
> > If you can't _git gud,_ the answer isn't "nerf it for me because I'm bad".
> > 
> > Thread over.
> 
> This is the area for Mindustry feedback. If someone finds the game to be unbalanced, then they should post about it here. It doesn't matter if they are worse than you, because as a person who plays the game, their opinion is just as valid as yours. You wrote a response where you call OP "sad" and "bad," simply because they had trouble in a video game. Does that make you feel better about yourself?

🤦‍♀️boi the tag says balancing/feedback and also im not a noob i legit explained the reason why the first few waves isn't easy until you get to wave 5 or 4 either one and its a medium difficulty base so you gotta know how the timer operates in order to fix it by looking at the timer

**Comment by XxsuperdeadlysniperxX** [comment]
All y'all saying im a **noob** and **is bad** should measure the time it takes to get resources launched from one sector to the next with 0 large launchpads researched

**Comment by GreyMario** [comment]
So the kid... Renames his issue report. Because he gets shot down because he can't figure out how to build a basic defense.

And then completely changes the topic of it to _lAuNcH pAdS aRe ToO sLoW_.

Kid, you're doing nothing but wasting GitHub's server space with this issue. You will literally never convince anyone that your inability to commit basic _Git Gud_ is a reason to change the game so that you don't have to get better at it.

**Comment by GreyMario** [comment]
Oh, and let's go ahead and mention #1526 so that the two issues are inextricably linked.

**Comment by itcannotbe** [comment]
Launch pad is too slow: Use more launchpads.

**Comment by sudobeans** [comment]
> 🤦‍♀️boi the tag says balancing/feedback and also im not a noob 

I never called you a noob, and I'm sorry if my writing made it seem that way. Also, I said _in my comment_ that this is in the feedback section. I wanted to back you up, because people were being mean to you, but now I'm not sure what's going on. Why did you completely change the subject of the thread? If you didn't want anyone to see what you said, you could have kept the thread closed.

**Comment by GreyMario** [comment]
> > OP can't even figure out how to launch with a loadout and build a decent defense with his chosen starting resources.
> > Sad.
> > If you can't _git gud,_ the answer isn't "nerf it for me because I'm bad".
> > Thread over.
> 
> This is the area for Mindustry feedback. If someone finds the game to be unbalanced, then they should post about it here. It doesn't matter if they are worse than you, because as a person who plays the game, their opinion is just as valid as yours. You wrote a response where you call OP "sad" and "bad," simply because they had trouble in a video game. Does that make you feel better about yourself?

oh sup, nice sockpuppet account

**Comment by GreyMario** [comment]
You may enjoy [this YouTube video](https://youtu.be/p_jZ6JXNKmw) which clears pre-nerf Fungal Pass in approximately 33 minutes without outside help of any kind.

**Comment by flarefluffsune** [comment]
I really don't think this is a balancing issue. I think you just need to optimise how you play the game. Generally I can spend a few hours trying to get the most out of every sector I take over to maximize resource income and use a single specific sector which has my most output to launch to a new sector with maximum resources and upgraded core.

**Comment by XxsuperdeadlysniperxX** [comment]
I do not like the toxicity because of a balance/feedback AND BOI I AIN'T NO KID

**Comment by XxsuperdeadlysniperxX** [comment]
Also calling someone a noob for like nothing is wrong people more launchpads does NOTHING for the amount of time till next you toxic little assholes just because you can doesn't you should bully someone gray mario

**Comment by XxsuperdeadlysniperxX** [comment]
> So the kid... Renames his issue report. Because he gets shot down because he can't figure out how to build a basic defense.
> 
> And then completely changes the topic of it to _lAuNcH pAdS aRe ToO sLoW_.
> 
> Kid, you're doing nothing but wasting GitHub's server space with this issue. You will literally never convince anyone that your inability to commit basic _Git Gud_ is a reason to change the game so that you don't have to get better at it.

For one gray mario if your a grown ass man then why tell a 19 year old guy with like 1 or 2+ years (idfk the exact playtime) of experience with atleast 1,000+ pro level schematics that legitimately whent obsolete on a completely overhauled game of mindustry that im a noob and should play the damn game when you for one seemed to just now learning the entire game?

**Comment by XxsuperdeadlysniperxX** [comment]
> > 🤦‍♀️boi the tag says balancing/feedback and also im not a noob 
> 
> I never called you a noob, and I'm sorry if my writing made it seem that way. Also, I said _in my comment_ that this is in the feedback section. I wanted to back you up, because people were being mean to you, but now I'm not sure what's going on. Why did you completely change the subject of the thread? If you didn't want anyone to see what you said, you could have kept the thread closed.
> 

Well it's closed now and it seemed like an attack at me cuz the like 5 toxic people in the comments so im actually sorry if you were attempting to like back me up

**Comment by XxsuperdeadlysniperxX** [comment]
> You may enjoy [this YouTube video](https://youtu.be/p_jZ6JXNKmw) which clears pre-nerf Fungal Pass in approximately 33 minutes without outside help of any kind.

Bruh just stop gray mario

**Comment by XxsuperdeadlysniperxX** [comment]
Nice 30 subscribers gray maria mister different account before the nerf which was like the legit first few waves i had like nothing near core and the wave timer wsa too fast going in to wave 3 so because i legitimately had nothing except copper and lead how is one suppose to fight off lik 10 or so polys that love hugging the player and because you are a smaller Youtuber you seriously underestimate the actual difficulty of those specific waves cuz you used mods to assist or had so DAMN fine luck with the permanent world seed

**Comment by flarefluffsune** [comment]
> I do not like the toxicity because of a balance/feedback

It's really not toxicity. It really is just you whining because the game isn't pandering to how you want it to play for you. Thats clear by the multiple times you edited your opening post changing it from 'The waves are too fast' to 'The launch pad is too slow'. Here is a hint: If you cannot keep up with the waves you aren't expanding and exploiting fast enough!

When I hit fungal pass I had plastanium unlocked and before the first wave hit I was producing Nova's, replaced all the drills with laser drills, put down 26 hail (supplied with graphite from my core) and a couple walls to cover the 12 scatters I had built and had already begun to produce my OWN poly's. By wave 3 I had hails shooting down the turrets and the the CORE in the middle and by wave 9 I was IN the main enemy base shooting everything up with a full group of Nova's.

So yes, this clearly is you and yourself not utilising the games features and buildings to good effect to match the pace of the game itself. So yes you are a **_noob_**. The idea of losing is to push you to rethink your strategy and come back either with more tech, resources or whatever and rethink how you will approach the problem, attacking an enemy base is **MUCH** different than defending against waves because no only do you need to defend against attacking units, you also need to attack yourself and that's going to push your resource management and expandability skills further than just building guns behind a wall.

But, instead of upskilling yourself by trying a different strategy or coming back later to the mission you come here to winge like a child instead. Speaking of which, Noob is now an actual Oxford Dictionary definition. Enjoy being called it often.

**Comment by GreyMario** [comment]
> Nice 30 subscribers gray maria mister different account before the nerf which was like the legit first few waves i had like nothing near core and the wave timer wsa too fast going in to wave 3 so because i legitimately had nothing except copper and lead how is one suppose to fight off lik 10 or so polys that love hugging the player and because you are a smaller Youtuber you seriously underestimate the actual difficulty of those specific waves cuz you used mods to assist or had so DAMN fine luck with the permanent world seed

The entirety of this post just proves exactly how little you actually know about the game.

> 30 subscribers

Fuck if I know where they came from. I use YouTube as a video host, not a content creation platform.

> different account before the nerf

Same account. Not that there are "accounts".

> had nothing near core

You'd be able to rebuild it quickly if you brought a proper loadout. Bring lots of things!

> wave timer was too fast

Well, good news, kiddo. Your incessant whining about being incompetent has saddled the rest of us with a permanent Assist Mode feature that we can't opt-out from. Every time you lose in a sector, that sector's wave delay is increased by 10 seconds.

> legitimately had nothing but copper and lead

And silicon and graphite. You spawn right next to coal and sand, and on first launch it's already rigged up with pneumatic drills and even a power source.
Making Metaglass is also immediately accessible, as shown in the video. The stuff's right there!

> how is one supposed to fight off like 10 polys

Scatters. Metaglass Scatters. The video uses only three for the entirety of defense against the Polys.

> hugging the player

No argument here. Polys have the weirdest combat AI and it's actually quite effectively annoying in its own right.

> smaller YouTuber

Not a content creator of any kind. Irrelevant, anyway.

> underestimate the difficulty of those specific waves

Nnnoooo..? It took me several hours to develop this specific strategy for starting from nothing. You know what happened? I learned what was coming and when. And I used my knowledge to prepare for it on the next runs.

> used mods to assist

It's plain and obvious that the game is unmodded.

> damn fine luck

> permanent world seed

Oh, didn't you know? _Every player gets the exact same planet._ No luck involved here. Every player. Same planet. Same _exact_ planet.

Now, I'd suggest learning something from this exchange. May I suggest that the lesson be that you are complaining because you refuse to _Git Gud_? Because you refuse to put out the effort to learn what you are doing wrong and how to improve upon your strategy? Because you simply want your Participation Trophy handed to you on a silver platter, with absolutely no effort on your part?

Because you **got** what you wanted. You singlehandedly drove Anuke to nerf Fungal Pass so damn far into the ground that it now only has ground-based units. You drove Anuke to subject us to permanent handicaps every time we happen to try a strategy that _doesn't_ work.

Good job. Your only skill finally got you somewhere in life. May it carry you somewhere very, very far away from any technology.

**Comment by aFuschia** [comment]
i love this conversation

**Comment by SMOLKEYS** [comment]
> i love this thread

lmao

**Comment by itcannotbe** [comment]
> i love this thread

Agreed, the only thing the kid has proven is, that he views constructive feedback as toxicity and that's toxic.

Honestly if the developer actually heeded to this bullshit for the many year this existed, we've have a freaking casual game by now. Glad he didn't,

Furthermore, I haven't seen OP actually prove that it's hard (the orginal title), all I see is pointless whining and refusal to actually gitgud.

**Comment by XxsuperdeadlysniperxX** [comment]
> > I do not like the toxicity because of a balance/feedback
> 
> It's really not toxicity. It really is just you whining because the game isn't pandering to how you want it to play for you. Thats clear by the multiple times you edited your opening post changing it from 'The waves are too fast' to 'The launch pad is too slow'. Here is a hint: If you cannot keep up with the waves you aren't expanding and exploiting fast enough!
> 
> When I hit fungal pass I had plastanium unlocked and before the first wave hit I was producing Nova's, replaced all the drills with laser drills, put down 26 hail (supplied with graphite from my core) and a couple walls to cover the 12 scatters I had built and had already begun to produce my OWN poly's. By wave 3 I had hails shooting down the turrets and the the CORE in the middle and by wave 9 I was IN the main enemy base shooting everything up with a full group of Nova's.
> 
> So yes, this clearly is you and yourself not utilising the games features and buildings to good effect to match the pace of the game itself. So yes you are a **_noob_**. The idea of losing is to push you to rethink your strategy and come back either with more tech, resources or whatever and rethink how you will approach the problem, attacking an enemy base is **MUCH** different than defending against waves because no only do you need to defend against attacking units, you also need to attack yourself and that's going to push your resource management and expandability skills further than just building guns behind a wall.
> 
> But, instead of upskilling yourself by trying a different strategy or coming back later to the mission you come here to winge like a child instead. Speaking of which, Noob is now an actual Oxford Dictionary definition. Enjoy being called it often.

No its toxicity also the launchpads only launch when full

**Comment by XxsuperdeadlysniperxX** [comment]
> > I do not like the toxicity because of a balance/feedback
> 
> It's really not toxicity. It really is just you whining because the game isn't pandering to how you want it to play for you. Thats clear by the multiple times you edited your opening post changing it from 'The waves are too fast' to 'The launch pad is too slow'. Here is a hint: If you cannot keep up with the waves you aren't expanding and exploiting fast enough!
> 
> When I hit fungal pass I had plastanium unlocked and before the first wave hit I was producing Nova's, replaced all the drills with laser drills, put down 26 hail (supplied with graphite from my core) and a couple walls to cover the 12 scatters I had built and had already begun to produce my OWN poly's. By wave 3 I had hails shooting down the turrets and the the CORE in the middle and by wave 9 I was IN the main enemy base shooting everything up with a full group of Nova's.
> 
> So yes, this clearly is you and yourself not utilising the games features and buildings to good effect to match the pace of the game itself. So yes you are a **_noob_**. The idea of losing is to push you to rethink your strategy and come back either with more tech, resources or whatever and rethink how you will approach the problem, attacking an enemy base is **MUCH** different than defending against waves because no only do you need to defend against attacking units, you also need to attack yourself and that's going to push your resource management and expandability skills further than just building guns behind a wall.
> 
> But, instead of upskilling yourself by trying a different strategy or coming back later to the mission you come here to winge like a child instead. Speaking of which, Noob is now an actual Oxford Dictionary definition. Enjoy being called it often.

Theres literally no why you had novas ready wave 3 dude theres whats called a build progress so im not a nood and you are a person who is legit useing mods to speed stuff up and i know enemy based are different

**Comment by XxsuperdeadlysniperxX** [comment]
Bulling gets you no where

**Comment by itcannotbe** [comment]
Signs of toxicity:

Using the bullying card. When getting cornered for his nonsense opinions.

**Comment by XxsuperdeadlysniperxX** [comment]
> > Nice 30 subscribers gray maria mister different account before the nerf which was like the legit first few waves i had like nothing near core and the wave timer wsa too fast going in to wave 3 so because i legitimately had nothing except copper and lead how is one suppose to fight off lik 10 or so polys that love hugging the player and because you are a smaller Youtuber you seriously underestimate the actual difficulty of those specific waves cuz you used mods to assist or had so DAMN fine luck with the permanent world seed
> 
> The entirety of this post just proves exactly how little you actually know about the game.
> 
> > 30 subscribers
> 
> Fuck if I know where they came from. I use YouTube as a video host, not a content creation platform.
> 
> > different account before the nerf
> 
> Same account. Not that there are "accounts".
> 
> > had nothing near core
> 
> You'd be able to rebuild it quickly if you brought a proper loadout. Bring lots of things!
> 
> > wave timer was too fast
> 
> Well, good news, kiddo. Your incessant whining about being incompetent has saddled the rest of us with a permanent Assist Mode feature that we can't opt-out from. Every time you lose in a sector, that sector's wave delay is increased by 10 seconds.
> 
> > legitimately had nothing but copper and lead
> 
> And silicon and graphite. You spawn right next to coal and sand, and on first launch it's already rigged up with pneumatic drills and even a power source.
> Making Metaglass is also immediately accessible, as shown in the video. The stuff's right there!
> 
> > how is one supposed to fight off like 10 polys
> 
> Scatters. Metaglass Scatters. The video uses only three for the entirety of defense against the Polys.
> 
> > hugging the player
> 
> No argument here. Polys have the weirdest combat AI and it's actually quite effectively annoying in its own right.
> 
> > smaller YouTuber
> 
> Not a content creator of any kind. Irrelevant, anyway.
> 
> > underestimate the difficulty of those specific waves
> 
> Nnnoooo..? It took me several hours to develop this specific strategy for starting from nothing. You know what happened? I learned what was coming and when. And I used my knowledge to prepare for it on the next runs.
> 
> > used mods to assist
> 
> It's plain and obvious that the game is unmodded.
> 
> > damn fine luck
> 
> > permanent world seed
> 
> Oh, didn't you know? _Every player gets the exact same planet._ No luck involved here. Every player. Same planet. Same _exact_ planet.
> 
> Now, I'd suggest learning something from this exchange. May I suggest that the lesson be that you are complaining because you refuse to _Git Gud_? Because you refuse to put out the effort to learn what you are doing wrong and how to improve upon your strategy? Because you simply want your Participation Trophy handed to you on a silver platter, with absolutely no effort on your part?
> 
> Because you **got** what you wanted. You singlehandedly drove Anuke to nerf Fungal Pass so damn far into the ground that it now only has ground-based units. You drove Anuke to subject us to permanent handicaps every time we happen to try a strategy that _doesn't_ work.
> 
> Good job. Your only skill finally got you somewhere in life. May it carry you somewhere very, very far away from any technology.

#1 there is "accounts" on youtube
#2 launchpads are slow even when full and they look like they launch will im in the sector but no resources appear for an hour
#3 i am somewhat of an idiot i do admit i forgot the resources are not procedurally generated but being an ass about it is wrong
#3 if you post videos on youtube regardless of you think you are/know you are you are marked as a content creater because you make content
#4 i know i have a little less knowledge of the new fungal pass but i was comparing it as best i could to the v4 version so still doesn't justify a grown ass man bulling a 19 year old
#5 i was grown up around using technology so don't mark yourself a genius
#6 bruh at this point your now a cyberbully
#7 only the required sectors are manually built
#8 there are no "handicaps"
#9 i have less knowledge of v6 so shut it
#10 i didn't technically drive him to do it you know that some other guy would have done it still irrelevant to being an ass on github
#11 🤦‍♀️ no ones gonna take github drama outside github and if they do why do you want soneone to kill themselves because they wanted like wave 2-3 slightly easier
#12 why is a grown ass man even trying to tell some rando on the internet to not play
#13 i told you my age dumbass and you choose to tell people to go die in a holde instead of looking your own life and questioning why you this stupid shit and actively ruining someone's life over a one fucking game
#14 you have no actual idea of my actual knowledge because i knew more about v4 than i do v6 i just know that if you are prevented from building a singel building how the fuck do you expect and entire production setup to survive also the polys automatically go for guns so whats your come back
#15 your little i"m better than you" bullshit is getting you no where fast (gray mario quote)
#16 i can also nitpick your skill you damn prick
#17 i could just keep going and going...

You know whats better if i did give a shit about the comments which if im attacked imma going to attack back and who give a damn about the campaign its single player and you can do whatever you want on singleplayer

**Comment by GreyMario** [comment]
> #1 there is "accounts" on youtube

What does YouTube have to do with Mindustry? You're trying to create strawmen.

> #2 launchpads are slow even when full and they look like they launch will im in the sector but no resources appear for an hour

At no point did I ever mention the Launch Pad. Did you forget that you can choose to launch to a new sector with resources _already in_ your Core?

> #3 i am somewhat of an idiot i do admit i forgot the resources are not procedurally generated but being an ass about it is wrong

You were an ass from the very start of this thread, accusing everyone of either "using mods" or "not playing the game". You have literally no place to tell anyone off.

> #3 if you post videos on youtube regardless of you think you are/know you are you are marked as a content creater because you make content

You wrote the number three twice. And no, that doesn't make me a "content creator". And that's not something that someone is "marked" as. What, do actual YouTubers scare you? Is Creslex going to eat you in your sleep? Jesus Christ, kid.

> #4 i know i have a little less knowledge of the new fungal pass but i was comparing it as best i could to the v4 version

Wouldn't you know it, v4 content doesn't matter in the slightest. Hell, there was an entire version between v4 and v6 that probably changed just as many things as v6 did.

> so still doesn't justify a grown ass man bulling a 19 year old

I have to assume at this point that you have never been on the receiving end of something called "parenting". ..Nor actual bullying. Being told you're wrong and shown exactly how is not "bullying".

> #5 i was grown up around using technology

Speaking of parenting and unfortunately for us, your parents seem to have used that technology as a babysitting aid rather than as a learning aid.

> so don't mark yourself a genius

First Launch Pads, now "genius"? How many words are you going to put in my mouth?

> #6 bruh at this point your now a cyberbully

Me and everyone else in this thread except you, huh? An entire community telling you you are literally wrong is not "bullying".

> #7 only the required sectors are manually built

Are you jumping back and forth deliberately, or are you incapable of following a coherent train of thought from one end to the other? You already responded to being told about worldgen.

> #8 there are no "handicaps"

The next release build will have them. Go read the commit log.

> #9 i have less knowledge of v6

Literally nobody is contesting this point.

> so shut it

Nah.

> #10 i didn't technically drive him to do it

I have seen no one else complain about Fungal Pass... and especially not to the extent that _you_ have.

> you know that some other guy would have done it

Nnnnoooo..? Here, let me check the contributors to the Fungal Pass map.
![](https://puu.sh/GX153.png)
..Oh. One contributor. And it's Anuke. In fact, that also completely debunks your initial post (before you edited it, trying to hide from your own stupidity) claiming that "some troll must have set the wave timer lower".

> still irrelevant to being an ass on github

Complaining about being told off for your whiny attitude is not a valid rebuttal.

> #11 🤦‍♀️ no ones gonna take github drama outside github

The entire Mindustry Discord is laughing their asses off at this thread every time a new post shows up in it.

> and if they do why do you want soneone to kill themselves because they wanted like wave 2-3 slightly easier

Show me on the doll where I told you to "kill yourself". You can't, can you? That's because I never said that. Are you done putting words in my mouth yet?

> #12 why is a grown ass man even trying to tell some rando on the internet to not play

Because frankly I think Neopets is more your _speed_. Don't forget to feed them.

> #13 i told you my age dumbass

And? I've met fifteen year olds more respectable than you.

> and you choose to tell people to go die in a holde

hole*
Also, again, where did I say this? Show the class.

> instead of looking your own life and questioning why you this stupid shit and actively ruining someone's life over a one fucking game

It's one thread. On one website. It's not your _entire life_. So cut the crap, this isn't theatre class. No drama, no acting.

> #14 you have no actual idea of my actual knowledge

You can't _possibly_ be any dumber than you're making yourself out to be in this thread. Don't even think to say that you actually are.

> because i knew more about v4 than i do v6

That has fuck-all to do with.. what, exactly?

> i just know that if you are prevented from building a singel building

Huh. You know, I'd swear that there is an entire YouTube video showing that it's perfectly possible to build several conveyor belts, a couple of new buildings, and even a few turrets before the first wave comes.

> how the fuck do you expect and entire production setup to survive

By... defending it?

> also the polys automatically go for guns so whats your come back

Hmm. Polys automatically go for guns, you say?
Well, then. What's stopping them from getting shot down?
Did you forget to _put ammunition in them?_

> #15 your little i"m better than you" bullshit is getting you no where fast (gray mario quote)

It's getting you to make yourself look like even more of a child, which is progress in my book.

> #16 i can also nitpick your skill you damn prick

Can you? Can you really. Can you really do that if you can't even complete Fungal Pass with a massive loadout, which still wouldn't match up in skill to my completion without a single outside resource?

I don't think you can.


> #17 i could just keep going and going...

In circles, maybe.

> You know whats better if i did give a shit about the comments which if im attacked imma going to attack back and who give a damn about the campaign its single player and you can do whatever you want on singleplayer

The rest of us can, maybe, with enough persistence and experience. But you've made it clear to everyone that you can't even beat Fungal Pass. So _you_ **can't** do whatever _you_ want on singleplayer.

**Comment by itcannotbe** [comment]
Upvote this comment if you're a discord member that is also laughing at where this thread already went.

**Comment by D-player1** [comment]
Tbh all this shit wouldn't exist if you learn how to make scatters and novas

**Comment by aFuschia** [comment]
> Tbh all this shit wouldn't exist if you learn how to make scatters and novas

facts

**Comment by ritzip** [comment]
![Untitled27_20201213143245](https://user-images.githubusercontent.com/49394064/102004919-1d1c3d00-3d50-11eb-9347-b24762b57dae.png)

**Comment by flarefluffsune** [comment]
>  you are a person who is legit using mods to speed stuff up

Dude you can literally pull resources from your core. It's a giant Vault. If you actually went in with Titanium, Lead and Silicon you can start building Nova's on wave one.

I'm really concerned, have you actually played the game?

**Comment by XxsuperdeadlysniperxX** [comment]
Just ignore this suggestion for own sake and sanity

**Comment by aFuschia** [comment]
> Just ignore this suggestion for own sake and sanity

oh yes totally not a balancing/feedback

**Comment by flarefluffsune** [comment]
> Just ignore this suggestion for own sake and sanity

So basically you're saying all this was personal issues because 'why isn't the game playing how **_I_** want it to!'

Gotcha.

**Comment by GreyMario** [comment]
> Just ignore this suggestion for own sake and sanity

Mm.. he's reduced to talking to himself.

Himself, the only person left who will listen to him.

**Comment by XxsuperdeadlysniperxX** [comment]
Yall know harrassment is against githubs rules right?

**Comment by GreyMario** [comment]
-clears throat-

> You must be age 13 or older. While we are thrilled to see brilliant young coders get excited by learning to program, we must comply with United States law. GitHub does not target our Service to children under 13, and we do not permit any Users under 13 on our Service. If we learn of any User under the age of 13, we will terminate that User’s Account immediately. If you are a resident of a country outside the United States, your country’s minimum age may be older; in such a case, you are responsible for complying with your country’s laws.

**Comment by itcannotbe** [comment]
Delete and ask @GreyMario then report XD always work.

**Comment by XxsuperdeadlysniperxX** [comment]
Im 19 years old dude theres 0 chance they will ban me being under age cuz im not

**Comment by Bohaska** [comment]
@XxsuperdeadlysniperxX Mindustry, sadly for some people, happily for some other people, isn't a game for casual players.... It's just how Mindustry was designed.

**Comment by GreyMario** [comment]
he deleted every post he made

like that's going to change anything

**Comment by Sky4ce09** [comment]
> he deleted every post he made
> 
> like that's going to change anything

rip legendary threads

**Comment by notrealn** [comment]
i cry

**Comment by SMOLKEYS** [comment]
![SmartSelect_20201228-222525_Chrome](https://user-images.githubusercontent.com/75618732/103220628-aee49680-495b-11eb-99ff-44c357d18bc9.jpg)
14 people were involved with this.

**Comment by genNAowl** [comment]
*Confused Confusing Confusion* 

half of the conversation is gone...

and I see the conversation has continued at https://github.com/Anuken/Mindustry-Suggestions/issues/1564
