### ISSUE TITLE
Make meltdown not use water coolant

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#1539]
**Describe what you would like changed, and why.**
Again - just place water extractors around the meltdown adn that's it. ***Easy mod***. Why can't we use cryo for higher tier turrets as the only coolant option.

**Comment by GreyMario** [comment]
Water is _easy_. Cryofluid is _effective_. That's the tradeoff.

**Comment by Slava0135** [comment]
> Water is _easy_. Cryofluid is _effective_. That's the tradeoff.

Consider that it's not a huge boost, and liquid is ***required*** in order to work.

**Comment by Quick-korkc** [comment]
No coolant, the meltdown will destroying themself
what did you expect from activating a turret who shoot very hot laser without coolant?

**Comment by Slava0135** [comment]
> No coolant, the meltdown will destroying themself
> what did you expect from activating a turret who shoot very hot laser without coolant?

Why did you even write this. I am just saying that basically the meltdown is lancer with an easy extra step

**Comment by flarefluffsune** [comment]
> meltdown is lancer with an easy extra step

It really is not. One requires coolant to function effectively one doesn't, you can use coolant to improve both turrets effectiveness. You can use water which is simple to get giving only minor boosts. Or you can go through the process setting up another factory process to manufacture something more effective.

The idea is the tradeoff, there's a tradeoff with **everything** in the game for instance **Ammo** which you so eloquently decided to trash too. Do you set up multiple processes to keep up with the ammo demand for Blast Compound in high level guns or do you use a very copious lower damage ammo like **Graphite** to keep up with demand while only using what you have for a couple guns.

It's the same with Cryofluid which the factory only makes 12/s which coincidentally is how much practically every gun requires a second to run boosted with it. But Cryofluid isn't only used to boost guns its used for other processes too like power which also requires eating into that per second production requiring you to build further infrastructure just to keep up with the demand so giving you the choice of coolant to use in weapons, like the Meltdown, simply makes sense and your opinion on removing water as coolant for it quite redundant because its a **tradeoff** of what you decide to use. Like with a large amount of other things in the game.

**Comment by Quick-korkc** [comment]
> > No coolant, the meltdown will destroying themself
> > what did you expect from activating a turret who shoot very hot laser without coolant?
> 
> Why did you even write this. I am just saying that basically the meltdown is lancer with an easy extra step

Persistent laser really hit different
why the hell you said meltdown just a lancer with "easy" extra step?

**Comment by Slava0135** [comment]
I just don't like water extractors - that's it... I often see meltdowns cooled by water extractors around. It doesn't mean that cryo is useless or whatever. Actually cryo makes meltdown reload twice as fast.

**Comment by flarefluffsune** [comment]
> I just don't like water extractors 

Your personal dislike of something does not equate to changing the fabric of the game for everyone that plays it. Just don't use water extractors then.

**Comment by Slava0135** [comment]
> > I just don't like water extractors
> 
> Your personal dislike of something does not equate to changing the fabric of the game for everyone that plays it. Just don't use water extractors then.

The thing I prefer playing multiplayer (mostly PVP / Attack) and I just see a lot of people ignoring water sources. However personally I always try to use the as much as possible.

Don't say "don't play multiplayer then", singleplayer and campaign is kinda boring.

**Comment by Quick-korkc** [comment]
> I just don't like water extractors - that's it...

So you just dont like water extractor
But sorry lot of peoples use this thing because very easy to use
Pipes sometimes make another distribution harder
Also all fluids have flow rate make pipe slower to distribute them

**Comment by flarefluffsune** [comment]
> **don't play multiplayer then**

I'm sorry but at this point it's the only thing to say. It seems like a personal issue you're having here not a gameplay issue were players you face are actually taking advantage of the given resources and equipment to them to most effectively utilise their builds while you sit there and cripple yourself because you don't like something. Or that you're just upset because people are defeating you in multiplayer combat by using what they have available.

**Comment by Slava0135** [comment]
> > I just don't like water extractors - that's it...
> 
> So you just dont like water extractor
> But sorry lot of peoples use this thing because very easy to use
> Pipes sometimes make another distribution harder
> Also all fluids have **flow rate** make pipe slower to distribute them

This game is about logistics. And water extractors ruin this part of the game.

**Comment by Slava0135** [comment]
> > **don't play multiplayer then**
> 
> I'm sorry but at this point it's the only thing to say. It seems like a personal issue you're having here not a gameplay issue were players you face are actually taking advantage of the given resources and equipment to them to most effectively utilise their builds while you sit there and cripple yourself because you don't like something. Or that you're just upset because people are defeating you in multiplayer combat by using what they have available.

Actually I am upset that players don't think and just put water extractors everywhere. It just pisses me off. Yes.

**Comment by flarefluffsune** [comment]
> This game is about logistics. And water extractors ruin this part of the game.

No that's part of logistics. First you need the power to even run the extractor meaning you need to set up a power infrastructure to run it. And Multiple pumps to get an adequate amount of water to supply things. Then you need the resources to even build the liquid network said water is going to be used for.

> Actually I am upset that players don't think and just put water extractors everywhere. It just pisses me off. Yes.

I believe it's you not thinking. But I can understand if this is difficult to notice if you aren't. So basically because you're upset because players use water extractors in order to make the most of what they have you're upset. Again, your personal dislike of something does not equate to changing the fabric of the game for everyone that plays it. This sounds entirely personal because you're a mad boy.

**Comment by Slava0135** [comment]
> I believe it's you not thinking. But I can understand if this is difficult to notice if you aren't. So basically because you're upset because players use water extractors in order to make the most of what they have you're upset. Again, your personal dislike of something does not equate to changing the fabric of the game for everyone that plays it. This sounds entirely personal because you're a mad boy.

It's not personal. Some people share my opinion. It's just casuals putting water extractors instead of using actual pumps are against.

For most people water is not even a resource that you can "mine" similar to ores. It's more like a sand on desert maps or something. This is the point.

**Comment by flarefluffsune** [comment]
> It's not personal.

No mate it really is personal you have made that very clear the entire thread. More proof it's your own personal issue:

> "Casuals"

You personally dislike the water extractor because players you face in PvP do not play the game the way you want them to and you feel that you are superior in that way because you do not like using a technological resource given to you yet other players do.

**Comment by Slava0135** [comment]
> > It's not personal.
> 
> No mate it really is personal you have made that very clear the entire thread. More proof it's your own personal issue:
> 
> > "Casuals"
> 
> You personally dislike the water extractor because players you face in PvP do not play the game the way you want them to and you feel that you are superior in that way because you do not like using a technological resource given to you yet other players do.

The players I play with and against are mostly don't know what are they doing. And what is a technological resource? There is a raw resource called "water" and you have to use pumps to get it. Water extractors should be an alternative not effective way of doing it.

**Comment by Slava0135** [comment]
> > The players I play within and against mostly don't know what the hell they are doing.
> 
> Welcome to online gaming with random strangers on the internet, the ultimate in difficulty of a game being a players personal skill. Again, this looks like a personal issue you're having with other people still learning the game or not playing it your way.
> 
> > Water extractors should be an alternative not effective way of doing it.
> 
> They are not an effective way of doing it, you have to use more power for a water extractor than any other liquid pump. You could not run a steam generator with any stability on the fluid output of an a water extractor meaning you have to put **More** resources into simply running Water Extractors than you would just building a thermal pump and making a long pipeline which can be much more vulnerable than simply building a water extractor next to some guns. If you have put in the effort and resources and logistics to generate enough power you have plenty excess of it then you may as well use it. Which unlike you, other players seem to be doing with Water Extractors.
> 
> Again all this seems like is a personal issue you have with people not playing at your skill level.

Actually I agree with this point.
