### ISSUE TITLE
Make Foreshadow turn slower

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#1583]
**Describe what you would like changed, and why.**
At the moment there is no way to avoid the shot even with the fastest ship.
Since Foreshadow is a sniper turret, doesn't it make sense that it will take time to aim (considering 100% accuracy).
Higher tier units are slower so nothing will change about them but this also will make possible to trick the turret with faster units.

Also what's about some sort of aiming "laser" going out of Foreshadow. It's often impossible to tell if you are within it's range.

**Comment by G-mage** [comment]
cool

**Comment by itcannotbe** [comment]
Why not rebalance every thing that rotates under the sun?

**Comment by the-kido** [comment]
Even if this was added the only things foreshadows would hit would be the tougher units which are slower and blocks on the ground, stationary. I _suppose_ this could be added but really there wouldn't be too much impact or at least that's what I think.

**Comment by scarf-generic** [comment]
~~or implement #1282~~

**Comment by RouterChainsSuckk** [comment]
> Also what's about some sort of aiming "laser" going out of Foreshadow. It's often impossible to tell if you are within it's range.
 Foos client lets you see its range but I still think thats a good idea I guess

**Comment by Arackulele** [comment]
Bad suggestion in my humble opinion,like what would a forshadow missing a flare change,nothing?

**Comment by XxsuperdeadlysniperxX** [comment]
I don't approve of this although the foreshadow will prioritize anything with a high value of health aka both blocks and units although idk if it also prioritizes guns too (will test) so this suggestion would have a minimal effect if any effect at all ig this were implemented it would just be annoyingly slow at turning but like since the game is not related to real life _ehm_ then why try to make it slower all you really need to do is spam them

**Comment by SuperficialIntelligence** [comment]
Why would you want to dodge a foreshadow bullet with a flare?

**Comment by XxsuperdeadlysniperxX** [comment]
**_visable confusion_** wait why **_are_** you trying to use a flare to dodge a railgun projectile?

**Comment by XxsuperdeadlysniperxX** [comment]
<It's often impossible to tell if you are within it's range.>

Thats the point of a sniper. In real life you have 0 clues of if a sniper is targeting you because of 
#1 range
#2 instant kill
The foreshadow is a sniper and a single target hitter so if you possess a weaker unit you will not know if your in its range until i shoots and by then your unit is either dead or critically hurt

**Comment by rafaelandrepedro** [comment]
I agree with the suggestion, but the shoot cost should be also reduced.
