### ISSUE TITLE
Add support for arm processors

### ISSUE THREAD

**Issue by Aradionov366** [Anuken/Mindustry-Suggestions#1600]
I have a Steam version of the game, everything works fine on a regular x64 computer, but I would like to run this fantastic game on my raspberry pi. If you try to run minindustry through Steam on this device, you will get an error stating that it cannot open the executable file. I would like to have a version of the game with support for arm processors on the Steam server, and on itch.io as well. Thank you in advance :D

**Comment by sample-text-here** [comment]
If you use steam, it probably wont work ![image](https://user-images.githubusercontent.com/56274831/102689130-a8625c00-41b0-11eb-8d63-ce19ce5e867f.png)

Use the .jar instead if you really want to run it on a pi

**Comment by BasedUser** [comment]
expectations from java:

`write once, run anywhere`

reality:

`write once, realise you need to compile the native libraries for everything, limiting your project to supported platforms only`

if you're capable of doing such a feat, consider making a PR to Arc.

**Comment by DeltaNedas** [comment]
@sample-text-here mindustry natives include a lot more than steamworks
you would need to update arc to make it build arm and arm64 natives for desktop, then add some mechanism for either adding to a universal jar and bloat everything up, or have a special architecture specific release.
at that point you may as well have mindustry <os> <arch> releases rather than having unused native libraries.

**Comment by sample-text-here** [comment]
h
