### ISSUE TITLE
 Increase the difficulty in each sector.

### ISSUE THREAD

**Issue by Fabri2906** [Anuken/Mindustry-Suggestions#1608]
**Describe the content or mechanics you are proposing.**

I think the idea of ​​having fragments of your previous game after losing is fine to facilitate your progress in the next game, but a button to remove all that residue would be fine for players who consider that debris annoying.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Tras haber agregado esto, puedes elegir si prefieres recuperar parte de lo perdido o tener algo mas de desafio para tratar de pasar el sector sin ningun tipo de ayuda.
Con esto los sectores que se consideren faciles  para ciertos jugadores puedan elegir una "dificultad"

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

(thanks you for read, thanks anuke for the awesome game and thanks to google translator)

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Vlexa** [comment]
I played for a while now. This is a gameplay issue and found that in sectors that contain lots of  unwanted block shadows, the automated rebuild becomes useless. That is my main grief with the block shadows. 
This matters most when the base is partially destroyed and rebuild differently. Then unwanted shadows remain. Doing so created unwanted and the rebuild drones become useless or even a nusiance. 

Instead of a button that removes all i suggest a modifier key. A key that modifies the redbox to only select and clear block shadows.

**Usage example:** In a destroyed frontline and partially destroyed base , i want my builder drones to rebuild the base but not the frontline. 
A quick clearout of the frontline shadows would help to have the builders focus on the base parts while i can rebuild the frontline in an improved way.

**Comment by Sp3rw3r** [comment]
Another use would be to counter polys trying to rebuild things at the front. A popular griefing method is placing a lot of belts near enemy spawn so all polys get destroyed, It is next to impossible to remove without a feature as described by Vlexa.

**Comment by Vlexa** [comment]
This feature request has a completely unreleated title...
