### ISSUE TITLE
Pull materials through blocks

### ISSUE THREAD

**Issue by Tripwiregamer** [Anuken/Mindustry-Suggestions#1640]
Allow unloaders to pull materials from the core or vaults through blocks with a „Path of 4 or less", meaning that if you can get to the vault/core from the unloader in less than 5 steps through non-conveyor blocks that still allow material transport, you can pull materials from the core or vault.
Feel free to change the path cap number
![image](https://user-images.githubusercontent.com/45953835/103052028-bb34b200-455d-11eb-936d-cabae51c1134.png)

Allows people who put sorters and junctions around their vaults to still be able to unload

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Unloaders are able to both withdraw from and deposit into many blocks besides vaults, such as drills, power plants, and item and unit factories. What happens when you have an unloader connected many such blocks through sorters/routers/etc? Does it withdraw from all of them and attempt to deposit items into all of them in turn?

1. Nothing in Mindustry works this way, recursively reaching through multiple blocks to "pull" items to them. Items are only "pushed" by outputting blocks through where they are allowed to, otherwise they are not sent at all.
2. This will break many existing schematics.
3. This will make efficient schematics much harder to design due to unloaders passing the same items back and forth between multiple blocks in an endless loop.

You have thought of a single use case (where you have surrounded your core with sorters to increase the contact area), without considering the many, many other situations such a change would affect.

**Comment by Tripwiregamer** [comment]
fair enough
