### ISSUE TITLE
Liquid transportation through waves and tsunamis 

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#1650]
**Describe the content or mechanics you are proposing.**

Hear me out, shooting liquid at a liquid tank should fill the tank with the liquid being shot at it. This finally means liquid transportation by means of air. No need to add any new blocks, instead use the ones already in the game. 

The only people that can make use of this would be users of logic. However, there will quickly be millions of schematics and even if not, it would be very simple to make logic that does your bidding.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Air transportation of liquid is something I think most people would like, and as mentioned before, this idea does not require a new block. This also means more creative ways of moving and attacking enemies through the usage of liquid. Not only that, I think it would look pretty cool seeing beams of liquid around your sector too.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by RedstonerKBC** [comment]
Imagine if instead of building massive pipelines all over the place humans shot their oil through the air and caught it using rain collectors. Lol.

Back on topic, this is interesting. It has many pros and cons you have to weigh. Griefers can fill empty cryo tanks with water stopping reconstructors. But it adds liquid mass drivers without actually adding any blocks and it doesn't need power. Should enemy waves/tsunamis be allowed to spray liquid in your tanks? Should enemy Atraxs be able to pour their slag into your empty tanks? I sort of like this idea but it is really out there. Cool.

**Comment by Yell245** [comment]
Imagine urinating on a toilet sit and expecting urina to go through somehow

**Comment by Kyllingene** [comment]
You do realize the slightest resprite could fix that illusion, and it's not even necessary? It in no way invalidates the request.

**Comment by the-kido** [comment]
rip this

**Comment by Kyllingene** [comment]
so sad *tear*
