### ISSUE TITLE
Easier Logic using

### ISSUE THREAD

**Issue by Anonim-L4T5** [Anuken/Mindustry-Suggestions#1659]
Easier and more functions at logic processors and easier to use logic displays

**Comment by Catchears** [comment]
Try using the format.

**Comment by Legomonster33** [comment]
> Easier and more functions at logic processors and easier to use logic displays

do you realize how useless this information is
instead of just saying
"make it better"
explain *how* to make it better
and why it needs to be better

also use the format

**Comment by SMOLKEYS** [comment]
> Easier and more functions at logic processors and easier to use logic displays

Your supposed to learn how to use it, not complain to make it more simplified. If Anuke actually did this, almost ALL of the creations with logic processors would not function because some of the commands might be changed or removed, therefore breaking the creation. And even if it was simplified, some creations would still be hard such as player-aiming turrets, battery displays, resource graphs, and much more. So i disagree with this feature.

**Comment by Humanoid-X** [comment]
1. EXPLAIN how to make it easier.
2. Why don't you LEARN it yourself? I can say that Mindustry is the easiest programming language I had ever seen. It's like some foreign guy saying "Make English easier because I don't want to learn it".
3. What about all the logic shematics now? Imagine making a super hard logic code and breaking it because of a suggestion.
4. Why didn't you use the TEMPLATE?!?!?!

**Comment by Legomonster33** [comment]
> 1. EXPLAIN how to make it easier.
> 2. Why don't you LEARN it yourself? I can say that Mindustry is the easiest programming language I had ever seen. It's like some foreign guy saying "Make English easier because I don't want to learn it".
> 3. What about all the logic shematics now? Imagine making a super hard logic code and breaking it because of a suggestion.
> 4. Why didn't you use the TEMPLATE?!?!?!

Apart from your third point i agree with all you said

**Comment by SMOLKEYS** [comment]
> 1. EXPLAIN how to make it easier.
> 2. Why don't you LEARN it yourself? I can say that Mindustry is the easiest programming language I had ever seen. It's like some foreign guy saying "Make English easier because I don't want to learn it".
> 3. What about all the logic shematics now? Imagine making a super hard logic code and breaking it because of a suggestion.
> 4. Why didn't you use the TEMPLATE?!?!?!

Who are you specifically talking to, me or @Anonim-L4T5?

**Comment by Humanoid-X** [comment]
@SMOLKEYS
All right, I'm sorry. I'm talking to @Anonim-L4T5 
There is nothing wrong with your comment, I agree with it totally.

**Comment by SMOLKEYS** [comment]
> @SMOLKEYS
> All right, I'm sorry. I'm talking to @Anonim-L4T5 
> There is nothing wrong with your comment, I agree with it totally.

Ok. Just remember to quote the message your replying to so no one could get confused.

**Comment by Anonim-L4T5** [comment]
I know how to use it but its not best

**Comment by Sanya2907** [comment]
B I G  B R A I N
