### ISSUE TITLE
routing mass driver

### ISSUE THREAD

**Issue by jonycoo** [Anuken/Mindustry-Suggestions#1673]
**Describe the content or mechanics you are proposing.**

I would like to use the mass driver like a router so that there is an n to n relationships between mass drivers.
driver #'1 could fire revolving to driver #'2 and driver #'3

there are two methods I could think of:
1. make logic be able to get reachable active mass drivers from connected one and change the target.
2. mass driver can connect to multiple others

being able to receive from multiple mass drivers would be nice too.

**Describe how you think this content will improve the game.**
It would provide an easier long range distribution system (1 to n)
It would Improve utilization of conveyors near the core (n to 1)

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

I think at least the first method would be feasible to implement.

**Comment by swenkeratmicrosoft** [comment]
A single mass driver can already receive from multiple mass drivers - I do that all the time.

**Comment by Kyllingene** [comment]
I do believe they meant the opposite - a mass driver sending to multiple mass drivers. All this really saves is power, a few resources, and some space, but maybe it's worth it. The logic path seems reasonable to me.

**Comment by itcannotbe** [comment]
Want to "route" to multiple mass drivers with logic? Simple.

Use multiples of them surrounding one "receiver" mass driver, then disable the sender if you don't want it to be sending to that mass driver. Simple.

**Comment by jonycoo** [comment]
> Use multiples of them surrounding one "receiver" mass driver, then disable the sender if you don't want it to be sending to that mass driver. Simple.

you mean controlling the receivers instead of the sender..
but I still can't connect one sender to multiple receivers and it doesn't auto connect to the next even if I shut down.

In that case I would still need 5 sender for 5 receiver.

Imagine having to defend a large area from all directions and your primary Ammunition is blast compound..
you need to distribute a small but steady amount of blast compound to all sides

**Comment by itcannotbe** [comment]
> > Use multiples of them surrounding one "receiver" mass driver, then disable the sender if you don't want it to be sending to that mass driver. Simple.
> 
> you mean controlling the receivers instead of the sender..
> but I still can't connect one sender to multiple receivers and it doesn't auto connect to the next even if I shut down.
> 
> In that case I would still need 5 sender for 5 receiver.
> 
> Imagine having to defend a large area from all directions and your primary Ammunition is blast compound..
> you need to distribute a small but steady amount of blast compound to all sides

I won't be using blast to defend all sides then.

Also I do not even get the connect between your example and my point.

**Comment by InvalidError404** [comment]
An alternative to using mass drivers for shipping items to places where other routing methods aren't practical is to use Flare/Poly/Mega to run air mail from core to a conveniently located container, vault or other block with internal storage. That way, you get a steady stream of air drops wherever you need them with container/vault storage to accommodate burst supply during waves. Works quite nicely.

I wrote one for myself (still working out some kinks) and a large chunk of the code is just dealing with the lack of a convenient facility to avoid ripping control from other controllers. I wish there was a ubind variant that only changed the @unit if the previously controlled @unit was lost: set it to a new free @unit if available when the old @unit either died or got hijacked, @null otherwise to simultanously signal loss of @unit control and no replacement available. Would save a dozen lines of code (check if the unit may have died, check for loss of control, flagging, a retry mechanism to bind until a free unit is discovered, internal bound state tracking, etc.) in a typical single-unit control script.

**Comment by Kyllingene** [comment]
> I wish there was a ubind variant that only changed the @ unit if the previously controlled @ unit was lost

```
ubind @mega
set unit @unit
...
jump 0 not @unit unit
jump 2 always 0 0
```

I cannot help with the other problems, but this is 3 lines of code... unless it doesn't check for hijacking, this should be perfect (although it doesn't check in the middle of the prog, but the same would be true for your special ubind).

Also, poor Unit is probably getting notified a ton (lol), could we do something about that?

**Comment by InvalidError404** [comment]
> I cannot help with the other problems, but this is 3 lines of code... unless it doesn't check for hijacking, this should be perfect (although it doesn't check in the middle of the prog, but the same would be true for your special ubind).

ubind simply walks the list of existing units of a given type. You have to do all of the additional checking to avoid hijacking units from other controllers yourself. If 20 units of a given type exist and 19 of them are under control, you may need to call ubind and check unit.controlled==0 20 times to find the one available unit depending on where along the list you were the last time you spammed ubind. If there are no free units whatsoever, I'm guessing the only way to find out is to save the @ unit you start the search with and compare it with each future iteration to detect whether you may have looped around, though this may not work if the starting unit gets destroyed along the way and no longer be in the ubind list.

My variant would eliminate most of that busywork. You call "subind" (single unit bind), subind refreshes the @ unit @ this already controls or most recently controlled whenever possible, a fresh @ unit with controlled == 0 if one is available when the old one isn't for whatever reason (could even have a "replaced" return parameter to test against instead of having to save the old @ unit to detect the unit swap and reset the script) or null otherwise so you know there are no free units available and can quit trying for a while instead of spamming ubind. That would also be a great opportunity for  a "sleep x" function: since there is no need to busy-wait polling ubind to find a unit to control, put the script to sleep for x milliseconds instead of burning virtual CPU ticks if there is some sort of global budget for them... if it doesn't, still gives the warm fuzzy feeling of attempting to do the right thing :)  A sleep function would also be handy when scripts are waiting for units to move between two points, when you want an unloader or other facility to change state only once every few seconds or anything else where the script will have significant periods of nothing to do. Most turrets only fire once every 2-5s, so there is no point in busy-loop checking nAmmo < maxAmmo, the script could easily sleep for 500ms between checks.

Apologies to @Unit :)

**Comment by Kyllingene** [comment]
Just realized we are talking about a whole different issue, should probably talk there xD
