### ISSUE TITLE
Absorption Generator

### ISSUE THREAD

**Issue by Alpha64bit** [Anuken/Mindustry-Suggestions#169]
Its a generator that absorbs enemy attacks and uses it to make a decent amount of power

This will help with front line power generation. It may have a high amount of health but medium to low power generation to balance it a bit.

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by SnakkiZXZ** [comment]
in this case, it should have expensive crafting, at least using the _phase-fabric_

**Comment by DS-3K** [comment]
So basically, a shield projector that instead of using energy, gives energy? I´m not sure about that being all too usefull, as you´d need to rely on enemy units to make power wich can make for a very unreliable or exploitable source (by trapping a few units). This sounds like something better fitting in a mod. It wouldn´t be too hard to code too, you´d just need to set energy cost of the shield to a negative value and there you go, problem solved!

**Comment by jaygamer81** [comment]
Well tbh this a tince op. Cant you just make a 1000 menders and 1000 turrents a 1000 of these absorb gens and make a unit generator?!!? You could power your base with these and keep units firing and reconnect ammo when the units get out of hand.
