### ISSUE TITLE
Add a reset button to logic processors

### ISSUE THREAD

**Issue by Lonami** [Anuken/Mindustry-Suggestions#1702]
**Describe what you would like changed, and why.**

I would like for logic processors to have a way to reset all their state (variables), without having to rebuild and relink them entirely. I'm suggesting this because we don't seem to reach consensus on https://github.com/Anuken/Mindustry/issues/4189 and I *really* believe state should be reset on edits, but if that's not desirable, at least adding a button will go a long way.

**Describe the changes you want to propose. Include possible alternatives.**

Add a new button to reset all the state of a logic processor, which includes removing all defined variables and specially setting the `@counter` to 0.

Alternatively, the `@counter` should be reset automatically when any edits are made, as it happens with any programming language. Well-designed code should not rely on previous garbage state, as long as it starts from the first instruction and not an arbitrary point in the program which is unknown to the user.

With this second approach, a `reset` instruction could be introduced, which users can place at the very top, because we would know `@counter` starts at the beginning.

Honestly I fail to see how preserving the `@counter` between edits can ever be useful (viewing and not editing it is fair enough, I can view my code while it runs and not alter it, but if I want my edits to run, I need to **restart** the program). If someone has additional examples where the current behaviour is useful please let me know.

**Comment by InvalidError404** [comment]
Well, many modern development environments do allow some degree of live-editing code so long as changes do not affect the call stack down to wherever the program counter is at or data structures, so it isn't true that all other programming languages/environments reset execution on edit.

That said, it is cumbersome to have implement some alternate reset mechanism when you do want to reset things after edit. In my scripts, I do a "jump reset == oldreset" to skip my init code (well, I will once the "jump 1==null" and "jump 1 not null" bugs get fixed) and change the "reset" value to something else when I want to re-run my initialization code or have my script do "oldreset++" when it needs to trigger a reset internally because it landed in an invalid state, possibly due to edits moving things around. Another work-around is to put a reset button on the map and sense a state change on it to trigger reset.

My suggestion: put a persistent "always reset processor on edit" checkbox on the code edit screen for people who want to systematically reset everything after every edit and a reset button when you want a "only this once" reset.

Many of my scripts have internal states that often get messed by edits, so I'd definitely welcome automatic reset on edit so I don't end up debugging weird states that aren't supposed to happen but do because I forgot to manually trigger a reset after edit to get things back to a known state with correct init values if I changed them.

**Comment by Lonami** [comment]
> it isn't true that all other programming languages/environments reset execution on edit.

Yes, I was overgeneralizing. One can't always say something is always true, because someone will create a new thing that does it otherwise to prove the original point invalid ;)

> My suggestion: put a […] checkbox

I've considered this option as well. It would definitely be the most flexible, but now it's yet another thing that must be shared and persisted. It would be more straightforward to have a simple button.

Like you said, unless the language is smart enough (detect local changes and don't restart if possible), it's a nightmare to debug and guess what random state the program ended up in because an edit was made in between. And if it sometimes reset and sometimes not, it could be surprising. Always resetting would be the less surprising behaviour, and avoid the most issues in my opinion.

From most to least favourite alternative:

* Always reset on edit.
* Add a "reset" button.
* Add a "reset on exit" checkbox.
* Do nothing.

**Comment by InvalidError404** [comment]
Another surprise factor from not resetting after edit is if you happen to reuse a variable name that you used before but removed at some point and haven't re-created the processor in a while to clear remnants from code changes. Then you may end up with something (not) working only because you had an unintentional initialization from old code that no longer exists.

Deleting and re-creating a CPU can be somewhat of a chore when links get named differently from the last time the CPU was created, pasting the schematic links to random crap that has nothing to do with the original context or links to stuff in the wrong order, then you have to rename all of the linked blocks you were accessing by name unless there is a way to rename the links themselves. Not a particularly pleasant work-around for the lack of a proper reset.

**Comment by Lonami** [comment]
Now that you mention links, it would be amazing to have a second tab (one for code, one for links) to let you rename existing links. This is just a thought and not really related to the reset feature. (It'd also be fun to have a way to "select" things from the real world into variables.)

**Comment by DeltaNedas** [comment]
@Lonami editing code now resets variables, close

**Comment by Lonami** [comment]
Yes, I was just posting in the other issue. Relevant commit: https://github.com/Anuken/Mindustry/commit/2ae864f4d385f032f79424c3d0c44c960b693332. Closing because reset button is no longer necessary.
