### ISSUE TITLE
Why does the water extractor not need metaglass to build?

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#1712]
**Describe what you would like changed, and why.**
Add metaglass to water extractor build cost.

**Describe the changes you want to propose. Include possible alternatives.**
Why not? It's reasonable.

**Comment by Humanoid-X** [comment]
goood

**Comment by Humanoid-X** [comment]
gooooood

**Comment by Nekuna** [comment]
because it falls under the drill category. I get what you mean but it just because it's reasonable doesn't make it a necessary change.

**Comment by DeltaNedas** [comment]
ok then move **water** extractor into the liquids category

**Comment by itcannotbe** [comment]
![Screenshot_20210103_174423_io anuke mindustry](https://user-images.githubusercontent.com/45280919/103475819-84775b00-4deb-11eb-8952-9ddceccb437f.jpg)
![Uploading Screenshot_20210103_174503_io.anuke.mindustry.jpg…]()

Well why then is the water extractor more buildable than an actual pump then?

**Comment by InvalidError404** [comment]
The water extractor is "cheap" because it consumes a crapton of power to barely match the throughput of the most basic actual pump which does not require any power and it likely is in the "drill" category because it is primarily intended for maps where there is relatively little actual water available, in essence squeezing water from rocks. The next proper pump up delivers 5-11x as much water using half as much power when water tiles are available.

The material cost is also increased if you account for all the on-going costs going into keeping them running. With pumps, the initial build cost is higher and you have to go through the hassle of running pipes everywhere but you get 10-20x the efficiency afterward.

I'd say the water extractor's horrible efficiency is a fair enough trade for its use of only basic materials. By the time you can build impact reactors, the material and power costs don't matter much either way. Early in the game where you have to balance the amount of coal that goes to power vs everything else though, the power cost stings quite a bit on its own. No need to tack on the added cost of setting up metaglass on top IMO.

**Comment by itcannotbe** [comment]
And you missed the point entirely.

You can build a water extractor before you can even build an actual pump.

Heck you can even go mid game without ever producing metaglass.

**Comment by Kyllingene** [comment]
> [X] Does this mean I don't?
[X] I am incompetent to use the template, but able to delete it entirely.

*Clears throat*

**Comment by DeltaNedas** [comment]
someone repost the .pl screenshot with the wexts right next to a lake
this is not ok

**Comment by TrinityXYZ4544** [comment]
Alot of of people playing multiplayer wouldn't even care to read about "Efficiency", they will just plop down water extractors 

*even when there's an actual water pool nearby*, the goal of meta glass cost is to encourage use pumps more frequently and only use extractors when necessary

**Comment by itcannotbe** [comment]
Move discussion to #2006
