### ISSUE TITLE
Water collector as alternative for water extractor

### ISSUE THREAD

**Issue by Axzye** [Anuken/Mindustry-Suggestions#1720]
**Describe the content or mechanics you are proposing.**
An alternative to the water extractor that can collect water from rain.
The upside would be that it has higher output and doesn't require power and the downside would be it needs rain to function.
Another idea is it can collect snow but needs power to convert it to water.
Unsure on what size, name or appearance it would have.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
In situations when output from water extractors is too low, and it is impractical to use pumps, and it is raining (or snowing) on the map then it would have a use.
It would also add more variety to custom maps.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
Possibly a little too niche to be worth adding. Cool idea, though!

**Comment by joshuaptfan** [comment]
It wouldn't be very practical on any map that didn't have constant rain/snow.

**Comment by RedstonerKBC** [comment]
To make it somewhat more practical make it cost very little to build, use very little/no power, output a decent amount of water. You want it to compete with water extractors. It also gives more gameplay uses for weather, which significant people see as an annoyance because it covers the screen. Water extractors are overused like mad. Even when water tiles are nearby players prefer water extractors despite their noticable drain on power. Rain collectors should definitely outperform water extractors in rain.

**Comment by itcannotbe** [comment]
Why not just a collector? To collect what the weather gives.

**Comment by Kyllingene** [comment]
That... is the entire suggestion?

**Comment by itcannotbe** [comment]
> Why not just a collector? To collect what the weather gives.

I mean like
Water during Rain
Sand during Sand Storm
Something during Spore

**Comment by Kyllingene** [comment]
Outputting both liquids and items... probably not feasible.

**Comment by itcannotbe** [comment]
Item Collectors and Liquid Collector?

**Comment by Kyllingene** [comment]
Multiple collectors seems clunky, and problematic to a mapmaker who wants to have sandstorms (or doesn't want to have to diable them) but little sand.

**Comment by itcannotbe** [comment]
Weather intensity? Or ban collectors XD.

**Comment by joshuaptfan** [comment]
No matter how awesome you make the output, power drain, build cost, etc, the fact remains that any building whose performance is negatively affected by weather is not practical, due to the rarity of any specific weather. Whatever you connect your water collector to will stop working when there's no rain/snow.

But suppose you try to mitigate that by making the water collector output a fantastic amount of water when it does rain/snow, and you cache that water in liquid tanks. That still does not make it practical because you have no way of knowing if the next rain/snow will arrive before those tanks are drained.

**Comment by itcannotbe** [comment]
This would be a great addition to challenge maps to be honest.

**Comment by InvalidError404** [comment]
> It wouldn't be very practical on any map that doesn't have constant rain/snow.

And pumps aren't practical on maps that have little to no water or water that is nowhere near where it is needed, which are usually where you'd most want an alternative to pumps and extractor.

I could imagine it being a 4x4 tile that produces 6 water/sec base (4X the area cost of an extractor for the same output) and 30 water/s in rain. If water is available, mechanical pump can get you the same output still without using power in 1/3 as much space and no weather dependency.

**Comment by RedstonerKBC** [comment]
> And pumps aren't practical on maps that have little to no water or water that is nowhere near where it is needed, which are usually where you'd most want an alternative to pumps and extractor.

I mean when there's few ores available people just haul it long distances using conveyors to where they need it. How is it any harder to haul water using conduits across the map?

**Comment by Kyllingene** [comment]
Because there is no real way to make alternative ways for ores to be gotten, without making a super inefficient ore generator.

**Comment by RedstonerKBC** [comment]
That's what scrap is for, inefficient ore production. Likewise water extractors are for inefficient water production. They both fill holes in maps that lack needed resources.

**Comment by Kyllingene** [comment]
But, in cases where the resources are in vulnerable, hard-to-collect, or entirely inconvenient places, those two things may also be used, although much less so with the separator, to good effect. All in all, this is somewhat off-topic. The point is that where extractors are not very helpful, or that has a fair bit of weather, the collector could be a helpful tool.

**Comment by InvalidError404** [comment]
> I mean when there's few ores available people just haul it long distances using conveyors to where they need it. How is it any harder to haul water using conduits across the map?

Organizing belts in a somewhat decent manner is already tedious enough as it is even when you don't have any water to worry about, imagine with a heap of pipes on top if the only way to get liquids was from their natural source. You can also use mass drivers to get items across otherwise impossible or highly impractical spots, can't do that with liquids. When chaining multiple buildings, you can also use unloaders to pass items between buildings to reduce the number of belts, can't do that with liquids either.

Having to pipe liquids across the map wouldn't be as bothersome if pipes could be, perhaps optionally as an added cost, buried in an underground layer but that idea has already been shot down.

> The point is that where extractors are not very helpful, or that has a fair bit of weather, the collector could be a helpful tool.

Extractors are always handy since there are very few maps with sufficiently conveniently placed water to rely exclusively on pumps (or weather for collectors) and they are also convenient for putting together perfectly balanced and tightly packed schematics that can be used practically anywhere where all necessary inputs are available.

**Comment by GreyMario** [comment]
Did...

Did ***NOBODY*** mention that Water Extractors (and pumps) already get a performance buff during rain and snow weather?

**Comment by itcannotbe** [comment]
Replying to a closed issue make you look stupid.

**Comment by GreyMario** [comment]
And completely failing to bring up weather bonuses doesn't?

**Comment by Kyllingene** [comment]
Being unnecessarily toxic, a habit both of you seem to enjoy, makes you look like you don't know how civil conversations work. But, unnecessary comments aside, the difference is that some maps are bad for water extractors, but would not be for water collectors.

**Comment by Mothership007** [comment]
> > Why not just a collector? To collect what the weather gives.
> 
> I mean like
> Water during Rain
> Sand during Sand Storm
> Something during Spore

the something you are talking to is a spore pod, the thing you get from cultivators, the thing is, cultivators already get boosted by a spore storm
