### ISSUE TITLE
Server config for core burning

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry-Suggestions#1727]
**Describe the content or mechanics you are proposing.**
have a config option when setting up a server as to whether or not cores should burn excess items

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
makes multiplayer servers less prone to clogging

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Catchears** [comment]
https://github.com/Anuken/Mindustry/pull/4242

Isn't this what you mean?

**Comment by rodrigolitzius** [comment]
Is this only dor servers? If yes it should be a game option too.

**Comment by RedstonerKBC** [comment]
Overflow detectors only cost like 2-5 blocks depending on your design.

**Comment by Quezler** [comment]
@Legomonster33 `rules add coreIncinerates true`

**Comment by Legomonster33** [comment]
> @Legomonster33 `rules add coreIncinerates true`

Ayyyy pog

**Comment by XxsuperdeadlysniperxX** [comment]
> Overflow detectors only cost like 2-5 blocks depending on your design.

The core has chance to clog when full of any item, this is amplified once a greifer steps up or a noob attempts to merge resources on a single conveyor, and even more when you have no more room to put conveyord on the core therefore overflow just contributes to the space issue. I know this because i am staff on a new sever plys banned on a server i already moderate (btw it was a mystery ban) and i've found the core auto incenerator actually both prevents greifs and helps with the clogging issue plus helps resource flow. Im angry it was removed tho 😠
