### ISSUE TITLE
Logic improvements

### ISSUE THREAD

**Issue by bigminigame** [Anuken/Mindustry-Suggestions#1729]
I have some ideas to improve the logic system without altering existing scripts :
-Right now, you cannot test a string in a jump (with a == or a not), this behave in a strange way, you must test the string before, in an operation. If we were able to do so, some scripts could be more compact and readable.
-Memory cells cannot contain objects (@copper, @flare, @surge-alloy, ...), and that's a shame because that would be really usefull, I have a script that could go from 80 lines to 40 with this feature.

Since these would be new features, these shouldn't alter the behavior of existing scripts.

**Comment by Kyllingene** [comment]
Hey, @bigminigame, the template exists so you can fill it out. Anuke will ignore the idea, and people will ridicule you for excluding the template. Here is the template you decided to remove:
```
**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
```

Otherwise, I like your ideas and think they would work well. I would hate to see people mock and ignore you just because you the template isn't there. Consider re-formatting your issue (it should be pretty easy) to fit the template, then fill in those boxes. Happy suggesting!

**Comment by bigminigame** [comment]
NOP, don't wanna do it, if anuken is that close minded, he doesn't deserve my suggestions.
Also, my post is only 6 lines of text, it would be more than the double with this lame template :)

**Comment by Bohaska** [comment]
-[x]  I happen to be able to read the template, but haven't filled it out because I was new to this community and didn't know this. Next time, I will fill out the template.

-[x] This suggestion is good!

**Comment by Kyllingene** [comment]
> NOP, don't wanna do it, if anuken is that close minded, he doesn't deserve my suggestions.
Also, my post is only 6 lines of text, it would be more than the double with this lame template :)

@bigminigame, Anuke is not close-minded, it is that he has 1000+ suggestions to go through a day, and excluding the ones that refused to use the template that makes it easier for him to review (and makes you check things, or lie - the boxes) makes it much easier to go through. And yes, your post may be 6 lines of text, but it still helps Anuke, *who programs most of an entire game by himself, filters through suggestions, balances, etc.* If you have any regard for Anuke's time, then you will agree that the template is a good thing. Either that, or you will (hopefully) bring up good reasons why one minute of your time is worth more than an hour of his.

**Comment by Bohaska** [comment]
I have some ideas to improve the logic system without altering existing scripts :
-Right now, you cannot test a string in a jump (with a == or a not), this behave in a strange way, you must test the string before, in an operation. If we were able to do so, some scripts could be more compact and readable.
-Memory cells cannot contain objects (@copper, @flare, @surge-alloy, ...), and that's a shame because that would be really usefull, I have a script that could go from 80 lines to 40 with this feature.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
1. If we were able to do so, some scripts could be more compact and readable.
2.I have a script that could go from 80 lines to 40 with this feature.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*
I can't fill this out cuz I'm not you

1. - [ ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [ ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [ ] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
Could you check those boxes please?

**Comment by sample-text-here** [comment]
> NOP, don't wanna do it, if anuken is that close minded, he doesn't deserve my suggestions.
> Also, my post is only 6 lines of text, it would be more than the double with this lame template :)

following a template isn't close minded. 

also Bohaska made most of the template for you already, it's not that hard

**Comment by Legomonster33** [comment]
> NOP, don't wanna do it, if anuken is that close minded, he doesn't deserve my suggestions.

[X] Anuke has made a template for a reason

**Comment by Kyllingene** [comment]
> NOP, don't wanna do it, if anuken is that close minded, he doesn't deserve my suggestions.

NOP, don't wanna do it, if bigminigame is that unwilling, he doesn't deserve to get his suggestions implemented.

**Comment by liuxilu** [comment]
Well, from source code to in-game behavior, I can't see what the string-comparing difference of `jump` and `operation` is. Maybe changed?

**Comment by liuxilu** [comment]
String compare fixed https://github.com/Anuken/Mindustry/commit/2bb303e7095a7749bc1e1a327ff1253329eb73b8
