### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by CameraManCR** [Anuken/Mindustry-Suggestions#1741]
**Describe the content or mechanics you are proposing.**

I'm suggesting to add in an "account system"

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I think this will help the game by making progress easier to save, that way, if you play on PC and on mobile, you can have an account linked and have the same progress on both devices without having to export/import, this could also help with multiplayer, being able to add friends, and having an e-mail linked could also give the option to send updates through e-mail.

Another thing that could go with the account system is a "guest account", this would let the people enjoy campaign normally, but would restrict un-account players from going on multiplayer (unless its LAN, everyone can go on LAN).

this could also make it easier to report players, if a player has been repeatedly reported, they could recieve a temporal ban or a permanent ban.

I'm sorry if this is a dumb suggestion, but i thought it would be a good idea

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [ ] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
 I have checked the Trello to make sure my suggestion isn't planned or implemented in a development version.
 I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
 I have read README.md to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by DeltaNedas** [comment]
banning is already a thing

**Comment by DeltaNedas** [comment]
if you want to sync progress use git or something
```sh
#!/bin/sh
cd $HOME/.local/share/Mindustry
git pull
java -jar Mindustry.jar
git add -A
git commit -am "PC $(date)"
git push
```

**Comment by itcannotbe** [comment]
And this suggestion is brought you by a person who does not know the cost and resources required of running a server for this purpose.

**Comment by DeltaNedas** [comment]
@CameraManCR why did you check those boxes if you didnt do what they asked, close this

**Comment by CameraManCR** [comment]
> And this suggestion is brought you by a person who does not know the cost and resources required of running a server for this purpose.
> 
> Every thing in the real world requires money and a lot of people seems to be oblivious to this fact.

correct, i do not know anything about this, im a 14 year old who had an idea, nothing more than that, as i said at the end of the suggetion, sorry if its a dumb idea

**Comment by Kyllingene** [comment]
I understand why you would suggest this, but as DeltaNedas and itcannot be have (rudely) pointed out, servers are really just computers connected to the internet. You must either pay for a company to run them, or have your own servers, which is costly, finnicky, and has poor results a lot of the time. Since this is a game that you can get for free, Anuke sadly cannot afford the time or money to run servers.

**Comment by Kyllingene** [comment]
I understand why one would bring this up, however, as DeltaNedas and itcannotbe have (rudely) pointed out, servers are not a feasible thing to implement. For one, Anuke is a solo dev with little income from the game. This makes it impossible for him to maintain servers or pay for servers. Also, take a look at this line from the [readme](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md#a-few-things-you-shouldnt-suggest), "A few things you shouldn't suggest":

> Built-in cloud sync

**Comment by RedstonerKBC** [comment]
Just what we need, yet another thing on the internet I'd have to make an account for just to use their services. Accounts, those things that you only ever make because you have to not because you want to. Those things I always forget the passwords to because they all have different password rules. I always lose my account because I don't have 2fa enabled or someone hacked my account or whatever reason. Did you know there's even an account to apply for student loans? Yep you guessed it, I can't apply for student loans because I can't get into my federal account. I had 2 Facebooks hacked and another one banned by facebook. I recently just had my youtube account banned without warning and without telling me why it was banned. My school email account was disabled because I missed a semester of school because I can't afford to pay out of pocket because I can't get into the federal account to apply for student loans to pay for it.

These are just a few of the many experiences I've had with "accounts". In my opinion, accounts aren't something that belongs in mindustry, especially since many innocent players get banned on servers instead of griefers.

**Comment by CameraManCR** [comment]
> Just what we need, yet another thing on the internet I'd have to make an account for just to use their services. Accounts, those things that you only ever make because you have to not because you want to. Those things I always forget the passwords to because they all have different password rules. I always lose my account because I don't have 2fa enabled or someone hacked my account or whatever reason. Did you know there's even an account to apply for student loans? Yep you guessed it, I can't apply for student loans because I can't get into my federal account. I had 2 Facebooks hacked and another one banned by facebook. I recently just had my youtube account banned without warning and without telling me why it was banned. My school email account was disabled because I missed a semester of school because I can't afford to pay out of pocket because I can't get into the federal account to apply for student loans to pay for it.
> 
> These are just a few of the many experiences I've had with "accounts". In my opinion, accounts aren't something that belongs in mindustry, especially since many innocent players get banned on servers instead of griefers.

did i forget to mention the "guest accounts" thing? you dont *have* to make an account, you could if you wanted to save progress cross devices, but you wouldnt be forced too

**Comment by CameraManCR** [comment]
> I understand why one would bring this up, however, as DeltaNedas and itcannotbe have (rudely) pointed out, servers are not a feasible thing to implement. For one, Anuke is a solo dev with little income from the game. This makes it impossible for him to maintain servers or pay for servers. Also, take a look at this line from the [readme](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md#a-few-things-you-shouldnt-suggest), "A few things you shouldn't suggest":
> 
> > Built-in cloud sync

Thanks for not pointing it out rudely, and also thanks for giving me a link to the "[readme](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md#a-few-things-you-shouldnt-suggest)", i couldnt find it before but now i've read it, sorry if the suggestion was dumb

**Comment by CameraManCR** [comment]
> if you want to sync progress use git or something
> 
> ```shell
> #!/bin/sh
> cd $HOME/.local/share/Mindustry
> git pull
> java -jar Mindustry.jar
> git add -A
> git commit -am "PC $(date)"
> git push
> ```

The whole point of using accounts would be to make it easier, without having to do this ^

**Comment by Kyllingene** [comment]
> These are just a few of the many experiences I've had with "accounts".

Those absolutely suck. Entirely, ridiculously, monstrously suck. And I totally understand not wanting to go through it again. However, most people do not have experiences like that, so that alone would not be a good reason.

> Thanks for not pointing it out rudely, and also thanks for giving me a link to the "readme", i couldnt find it before but now i've read it, sorry if the suggestion was dumb

No problem, simply using words in a non-rude way gets a lot further than just insulting people for things that arent their fault. And no, it wasn't dumb, just malinformed.
