### ISSUE TITLE
Throughput in logic

### ISSUE THREAD

**Issue by hortiSquash** [Anuken/Mindustry-Suggestions#1755]
Add a new logic sensor, @throughput_ressourcetype or anyway you want to call it, that get the throughput of this ressource in the conveyor block. It is already in the game somewhere, as its displayed when your mouse hover on a conveyor type block, just make it available with logic.

Currently, the only way to get this value is making a fast enough processor probe the conveyor and count the amount of ressources during a delta time, kind of the mathematical derivative way.
This method has **a lot** of flaws, being:
- a single ressource can be counted multiple times, if the conveyor is slow or the belt is clogged, etc
- some ressources can be skipped, if the conveyor is too fast, the processor too slow, etc
- need a very fast processor
- it only works for conveyors, not bridges/phases, because of the storage
- takes at least 4 instructions per cycle at the very least, between memory read/write for the counter, sensor and operation
- terrible accuracy
- need a lot of time to get even roughtly accurate, like 5-15 whole seconds
- being already very long, it takes twice as long to make it count without errors the flow changes

This could help a lot of schematics, like activating additional machines when sufficient input ressources are supplied, etc

**Comment by joshuaptfan** [comment]
Internally, I doubt this value would be accessible at any random point in time. When you see the value in the GUI, there is a startup time where it has to initiate monitoring, because a delta time is needed.

It's technically possible for logic to also initiate this monitoring, and it would be logic users' responsibility to account for the value being `null` during the startup time. However, there can only be one instance of GUI throughput monitoring at anytime, but how would it affect performance if processors ran this monitoring on many different conveyors/bridges at once?
