### ISSUE TITLE
Require copper/lead to respawn core-units

### ISSUE THREAD

**Issue by iLagSoUhax** [Anuken/Mindustry-Suggestions#1778]
**Describe the content or mechanics you are proposing.**
Make core units consume copper, and possibly lead, upon respawning. This would make core units[Alpha-Beta-Gamma] require a small amount of copper, say 200, and *possibly* a small amount of lead, say 80, spawn. Players will naturally spawn upon game start without the need for this small 'spawn-fee', or so I'll refer to it in this suggestion. 

Players, upon the destruction of their core-unit, would have their screens focussed on the nearest core, and undergo a small animation[lasting about two seconds] which would demonstrate their core-unit being made, after which the core-unit would be launched out, ready to be used. The spawn-fee would be consumed during the animation of the core-unit being made.

Only one player would be able to undergo this animation at a time, and players behind the 'animation queue' would have to wait for the players ahead of them in the 'queue' to be remade first[something reminiscent of the v5 wait before a core unit was spawned might work well]. If the required copper/lead is not present in the core, the animation will cease and only resume upon the addition of copper/lead in the core. If multiple players are in the 'animation queue', the one who died first will be respawned first, followed by the one who died second, and so on. It is quite literally a queue.

Might work well as a game rule[like 'units require ammo' or 'lighting']? although I am still in favour of enabling this game-wide, most others might not be.

I would also like to suggest that, in case this is implemented, higher core-units require more copper and/or lead to spawn, adding a small disadvantage to upgrading one's core without having adequate production of copper/lead.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This would mostly bring more balance to the game. a lot, *lot* more balance. Especially in multiplayer, early-game rushing is a very major problem and causes one team to gain an irreversible advantage over the other. After some analysis, I found out that this usually happens close to an early-mid game copper-drain, where copper production fails to match its demand, causing players to not be able to build many structures, the ones which require copper as a building material. This, ironically, discourages rushing, since most structures required[mostly drills, scatters, arcs, lancers, and parallaxes] require either copper or lead, or a combination of the two.[two of the four structures mentioned require lead and three copper]. Nevertheless, the two seem to happen at close intervals. Since the need for copper is unparalleled during the brief spell of time near when rushing seems to happen and rushing causes players to die in their core-units, adding a need for copper and/or lead to respawn will nearly certainly fix this niche

As an addition, it seems fairly uncalled for that one should have an unlimited supply of core units. limiting the spammability of core units through this method would also be a neat addition.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
hmm good

**Comment by Quick-korkc** [comment]
uhhh
why you open 2 same pr?
#1777

**Comment by joshuaptfan** [comment]
What happens if your core doesn't have enough copper/lead to respawn you and there is none going to the core? You wouldn't be able to spawn, you'd just stare at your core until you lost.

**Comment by itcannotbe** [comment]
Auto lose. Simple.

**Comment by SheepCommander** [comment]
Hmm dunno not totally onboard but at the same time if you are dead and there's no coppers/lead left you may as well quit

**Comment by iLagSoUhax** [comment]
> What happens if your core doesn't have enough copper/lead to respawn you and there is none going to the core? (I don't care about how unlikely that is, programming is all about accounting for edge cases.) You wouldn't be able to spawn, you'd just stare at your core until you lost or quit.

well, either your production would gain the core some copper/lead overtime, hence providing enough for a player to spawn and continue, or you'll die[an auto-lose might be cool though].

**Comment by iLagSoUhax** [comment]
> uhhh
> why you open 2 same pr?
> #1777

closed. my bad, the first time I tried to open it, the issue redirected me to a 404 page.

**Comment by DeltaNedas** [comment]
on multiplayer there is never any lead, gamma rushing would mean taking players out more or less for good

**Comment by Thunder33345** [comment]
I want to propose another way out of a "not enough resource" scenario, rather then an "auto death"
though TBH normally you should at least have some passive resource generation, at least enough to cover the respawn fee
but let's say on the off chance that you don't for whatever reason

### Alternative proposal
You will have to wait 30 seconds(value used as an example) for the core to respawn you "anyways", despite your lack of resources
provided your defenses can hold enemies off for >30 seconds

How it works is: it will keep trying to consume resources, until it reaches the amount it wanted, but if you can't generate this much in 30 seconds it will spawn you anyways
If it can consume enough of it in 30 seconds, it will do the next 2 second animation then respawn you

### Why wait timer?
Time is of essence, you would be paying the fee for a faster respawn, or having to be vulnerable sitting duck for a long 30 seconds
Which should be good enough of a disadvantage/penalty that would be avoided regardless
And quite a heavy penalized if it occurred
30 seconds is just an example value, it could be more if needed

### Why not just insta gameover
Because i believe that it's is a good idea to have a chance to overturn no matter how crappy the situation it is
Rather then having the game handing you a "you lost because your core cant respawn you", i rather have lose because my core got destroyed while respawning(which regardless could happen even if i am spawned out)
Implying i still am at fault for having a bad defense, that end up letting them through

### Why should we just use insta gameover
If you need this mechanic to help you, you are probably "very screwed" to begin with, that you are probably already set up to lose

### Closing remarks
Still unsure since considering for the case of having not enough resources, it's a very unlikely one...
But that's what i thought of, as another alternative that doesn't just "auto lose" you
IMO it sounds way better then "oh you will just 100% die"

**Comment by itcannotbe** [comment]
@Thunder33345 Of course auto lose doesn't mean the game ends the game, I just mean you're screwed to die soon unless you're not.

**Comment by Yell245** [comment]
I think if you "teleport" from the core like if your controlled unit died or you just clicked on the core then it shouldn't take resources like if your starter drone was disassembled by core

**Comment by RogueRedHawk** [comment]
This issue reminds me of #1512, where we discuss the timer and respawn mechanics.

Also, I don't like the idea of it consuming resources. On PvP servers there is often some setup of a third team of foreshadows or scatters in the middle that prevents the players from insta-rushing each other. This mechanic might mean accidentally going to close to the center (you might not even know there are turrets there) locks you up in jail for an arbitrary 30 seconds, which does not sound like a fun mechanic.

**Comment by Kyllingene** [comment]
Yeah, I agree with Rogue; the idea of paying money just because you died to literally anything (when not controlling a unit) costing you money seems aggravating. Imagine the enemy team pushing your defenses hard enough for you to swap some copper over to them / are building a lot so have little copper. Suddenly, a rogue air unit gets past and kills you. Not your fault, just a trick of luck. Well, you don't have 200 copper, so you have to wait. Since you have to wait, you lose. You might have been able to recover (you may have had a stockpile of units, for example), but since you died randomly, you lost.

**Comment by itcannotbe** [comment]
Related
#1656

**Comment by catatagun** [comment]
200 copper and 80 lead to much why not 30 copper and 15 lead
