### ISSUE TITLE
Surge Conveyors

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry-Suggestions#1785]
**Describe the content or mechanics you are proposing.**
Surge Conveyors are faster than titanium conveyors but with a few additional properties. They have higher health than titanium conveyors (but less than armored conveyors) and cost at least 1 surge alloy, 3 thorium, and 3 copper **each**. When an enemy shoots them they sometimes shoot electricity like surge walls. When an enemy destroys them they explode damaging all units and buildings (friend and foe) but the explosion is small so that the enemy can't blow up entire schematics by destroying just a few surge conveyors. You want the explosion damage strong enough to deter enemies from getting close but not so strong that it discourages people from building with them.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
You might be thinking "What is the point? We already have plastanium conveyors. Just use those." Plast conveyors have their own issues. Most people agree they can be weird to use and don't mix well with things like routers, gates, bridges, and sorters because they cause plast conveyors to backup and have reduced throughput. Surge conveyors fix this issue because normal conveyors don't get backed up by these. Surge conveyors won't replace plastanium conveyors because although surge are faster than titanium you'd need to make them more than 3x as fast just to beat the throughput of plast conveyors, which is way too fast. I wouldn't make surge conveyors more than 2x as fast as titanium otherwise they become too op. (All of this was tested using mods.)

"Ok but do we really need a conveyor that is literally just a faster titanium conveyor?" I could make the same argument about titanium conveyors being just a faster copper conveyor. I could ask why copper conveyors exist at all if everyone always upgrades them to titanium? Surge won't replace titanium conveyors as easily as titanium replaces copper conveyors though because surge conveyors are much more expensive. Anyone can get titanium within the first 30 seconds of the game, but how long will it take you to get surge and enough of it to upgrade all of your titanium conveyors? (If anything is pointless it's the copper conveyors. They're literally good for nothing but starting the game.) The difficulty between going from titanium to surge conveyors is much much harder than getting from copper to titanium conveyors, but you get a better titanium conveyor that is still easy to use so it's worth the hard work.

All of the high-tier items (plast, thorium, and phase) have their own unique version of the conveyor except surge (Blast compound doesn't count because it's not a "building" material). Unlike plast conveyors they work well with routers, gates, bridges, and sorters without backing up. Unlike phase conveyors they require continuous space to use. Unlike armored conveyors they can receive input from all sides but aren't tough enough to replace armored conveyors in defensive situations as a defensive utility. (Like I said earlier Surge Conveyors explode.) And remember that mass drivers are cheap and don't cost any surge, so they can't be considered the "surge" conveyor.

Surge conveyors are expensive costing at least 1 surge alloy each. This means they aren't going to be replacing titanium conveyors in the early or even the mid-game unless players try to get surge. Most teams rush to get plastanium first anyways because of the conveyors and because of the T4 units. Even if you do get surge it takes a lot of time, power, and items to craft it. Good luck getting enough to upgrade all of your titanium conveyors!

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
very well thought out but as always

*mods.*

**Comment by genNAowl** [comment]
Two things: 
1. Copper conveyors exist for campaign. 
2. You would also have to buff the throughput of junctions and bridge conveyors in order to really make this useful. Buffed junctions are fine, but any buff to the bridge conveyor will make bridge weaving way too powerful

**Comment by sample-text-here** [comment]
the reason why plastanium belts were made instead of just a faster belt was because of [game limitations](https://github.com/Anuken/Mindustry/pull/1260#issuecomment-569469234) (rendering issues)

aside from that, i think a higher tier conveyor would be more interesting if it had different mechanics. plast is fun to work with because of the way it interacts with blocks. if you misuse it, you can tell immediately because throughput slows down, so i think it would be good to add some more info (like plast belts can be unloaded) to the help dialog. if a surge conveyor was added, it would be interesting if it had different logistics as well, so it could get around the limitations.

**Comment by RedstonerKBC** [comment]
> the reason why plastanium belts were made instead of just a faster belt was because of [game limitations]

Ah yes one thing I forgot to mention. Another reason why not to make Surge Conveyors anymore than 2x faster than titanium conveyors is because they move so fast that it doesn't render right.

**Comment by itcannotbe** [comment]
And let's not forget that 2x titanium is basically plast with a single loading dock is.

**Comment by DeltaNedas** [comment]
opore

**Comment by Yell245** [comment]
Phase conveyors: hm wonder what are they talking about

**Comment by Catchears** [comment]
> the reason why plastanium belts were made instead of just a faster belt was because of [game limitations](https://github.com/Anuken/Mindustry/pull/1260#issuecomment-569469234) (rendering issues)


If you want to see these rending issues, join nydus (be only) and wait for endgame as 4000% boosts are not uncommon.

**Comment by iLagSoUhax** [comment]
we do not

we do NOT 

WE DO NOT NEED MORE CONYEYORS OH GOD

**Comment by iLagSoUhax** [comment]
Why This Is Trash
---
I'll start with proving wrong the reasons they listed
> Plast conveyors have their own issues. Most people agree they can be weird to use and don't mix well with things like routers, gates, bridges, and sorters because they cause plast conveyors to backup and have reduced throughput. Surge conveyors fix this issue because normal conveyors don't get backed up by these. Surge conveyors won't replace plastanium conveyors because although surge are faster than titanium you'd need to make them more than 3x as fast just to beat the throughput of plast conveyors, which is way too fast.

Plastanium Conveyors are made finicky and difficult to operate, albeit with more throughput than titanium conveyors, for a reason: just providing raw speed to a conveyor would make the conveyor linage much more linear: for instance, if plast conveyors were just titanium conveyors with more speed, nobody would use titanium conveyors after obtaining plastanium; it would be much worse. RIght now, in most multiplayer servers, plastanium conveyors are used much less frequently than titanium conveyors. This, I suspect, is for the reason I mentioned.
> "Ok but do we really need a conveyor that is literally just a faster titanium conveyor?" I could make the same argument about titanium conveyors being just a faster copper conveyor. I could ask why copper conveyors exist at all if everyone always upgrades them to titanium? Surge won't replace titanium conveyors as easily as titanium replaces copper conveyors though because surge conveyors are much more expensive. Anyone can get titanium within the first 30 seconds of the game, but how long will it take you to get surge and enough of it to upgrade all of your titanium conveyors?

Read the above note. Even though the conveyor system is non-linear after copper and titanium conveyors, the lineage exists for a reason, to provide balance. Anuke wishes for everything to remain perfectly balanced, as all things should be ~~cough cough arcs and lancers cough cough water extractor~~.

> All of the high-tier items (plast, thorium, and phase) have their own unique version of the conveyor except surge (Blast compound doesn't count because it's not a "building" material). Unlike plast conveyors they work well with routers, gates, bridges, and sorters without backing up. Unlike phase conveyors they require continuous space to use. Unlike armored conveyors they can receive input from all sides but aren't tough enough to replace armored conveyors in defensive situations as a defensive utility.

Again, this is just pointless. Not everything good needs to be exported into conveyors, turrets and marketable plushies. In this way, I could argue that there are no turrets that use plastanium, and demand hence a new turret be added solely for this idiotic reasoning. That would be just wrong. Surge Alloy has its own uses, such as making the most durable wall in the game and the turret with the longest range. 

> Surge conveyors are expensive costing at least 1 surge alloy each. This means they aren't going to be replacing titanium conveyors in the early or even the mid-game unless players try to get surge. Most teams rush to get plastanium first anyways because of the conveyors and because of the T4 units. Even if you do get surge it takes a lot of time, power, and items to craft it. Good luck getting enough to upgrade all of your titanium conveyors!

Again, just because they're expensive doesn't mean that they won't be used. Plastanium rarely used before the addition of t4 units and last conveyors, and they have started being rushed, not only in PvE, but also in PvP, as I have noticed. This is because of the fact that the more utility a material has, the more people would like to use it, not vice versa.

Moreover, we really do not need more conveyor types. I, personally, am perfectly content with the starting conveyor, the stock conveyor, the finicky conveyor, and the stronk conveyor, and I'm certain most others are too. Adding more and more content to the game not only significantly slows down more coherent aspects of development, such as bug-fixing and other planned v7 content. 

I think that is it. Since this suggestion nears a shitpost, whether it be intentionally or unintentionally, I request that you close it[since anuke will no longer close issues or comment on them].
Thank you for coming to my ted talk.

**Comment by BlueWolf3682** [comment]
this idea isnt trash, its a valid, good idea that i agree with, but mods exist for this reason

**Comment by Kyllingene** [comment]
> this idea isnt trash,

i agree totall-

> its a valid, good idea

whyyyyyy

did you notice the simple, lone fact that the Mindustry code *cannot handle it*?

**Comment by iLagSoUhax** [comment]
> this idea isnt trash, its a valid, good idea that i agree with, but mods exist for this reason

well good I still think this idea is garbage, but to one their own I guess

**Comment by BlueWolf3682** [comment]
...i could make this in a couple minutes with a JSON mod, the code can fully handle it.

**Comment by sample-text-here** [comment]
> ...i could make this in a couple minutes with a JSON mod, the code can fully handle it.

yes, you could easily make this in a couple minutes with JSON, but the code can *not* fully handle it.

**Comment by BlueWolf3682** [comment]
code would have no issues handling every aspect of it, ive already made faster conveyors with json without a single issue
