### ISSUE TITLE
Server popularity list

### ISSUE THREAD

**Issue by unjown** [Anuken/Mindustry-Suggestions#1794]
**Describe the content or mechanics you are proposing.**
a discord channel or website to view average players per server 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

:) for fun

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
[This](https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v6.json) is the list of official Mindustry servers (in json format), so if you had some way of contacting each server and obtaining the player count (there is obviously some way, as Mindustry checks when you are on the server list); then, whenever the website is opened, it would go through the list, contacting each server on the list to obtain the count, update a file on Github with that new info, then do some calcs. Of course, it would all have to be run client-side if Anuke wanted to use Github pages (which he probably would because it's free and he's an indie dev).

**Comment by alexpvpmindustry** [comment]
This will be kinda unfair for new servers who are starting out, they would be always at the bottom then. People can also use hub to "increase" the number of players. Also, if u use average players per server in a server brand/name, then it will be unfair for those "brands" with more servers listed.
Currently it's arranged by ping and that's good for players who wanna play with less ping. 
Maybe an alternate way would be to allow the *option* to filter by ping or filter by players/popularity

**Comment by itcannotbe** [comment]
I think it would be fair, considering all servers started out from the bottom.

**Comment by unjown** [comment]
> This will be kinda unfair for new servers who are starting out, they would be always at the bottom then. People can also use hub to "increase" the number of players. Also, if u use average players per server in a server brand/name, then it will be unfair for those "brands" with more servers listed.
> Currently it's arranged by ping and that's good for players who wanna play with less ping.
> Maybe an alternate way would be to allow the _option_ to filter by ping or filter by players/popularity

was referring to per total per server 🙂like total hub
