### ISSUE TITLE
Buff Shock Mines

### ISSUE THREAD

**Issue by TheDragonVin26** [Anuken/Mindustry-Suggestions#1804]
**Describe what you would like changed, and why.**
Shock mines are highly inefficient as for now, so i would like it take less silicon to build
Shock mines are also useless against higher tier units, so the shock mine should stun enemies that gets shocked, the shock duration depends the range between the mine triggerer.

**Describe the changes you want to propose. Include possible alternatives.**
If all the suggestion above is impossible, or too OP, just make units can't  attack shock mines, since its kinda dumb when they can just outrange them, and also buff shock mine's hp so that they can at least tank a few explosions from crawlers

**Comment by Kyllingene** [comment]
1: Please finish the template, I am confused as to why you didn't.

2: I agree that they should definitely be buffed in some way. However, this is probably a duplicate (will update this comment if I find any).

**Comment by AnOreo1** [comment]
dude are you insane
you can kill a reign with 129

**Comment by AnOreo1** [comment]
3 can kill a fortress, so on.

**Comment by TheDragonVin26** [comment]
> 3 can kill a fortress, so on.

if fortress doesn't destroy them first

**Comment by Humanoid-X** [comment]
oh, shock mines have been buffed, like, a centillion times.

**Comment by genNAowl** [comment]
The root of the problem comes from the fact that no one uses them correctly. They are not supposed to go in front of any targetable blocks; They are supposed to be standalone defenses that work best by themselves. That said, I do agree that shock mines should be reworked, as the fact that it can be hit by flying bullets while it is underground is a bit annoying.
