### ISSUE TITLE
Sector attacked immediately after defending it

### ISSUE THREAD

**Issue by jimj316** [Anuken/Mindustry-Suggestions#1808]
**Describe what you would like changed, and why.**
While playing in campaign mode (in sector 220) I experienced something very frustrating: I had just completed wave 55/55, capturing the sector (after a very difficult fight), when sector 220 instantly came under attack. The timing was so quick that I never even saw the "sector captured" message, and so I almost thought this was a bug. The wave counter went up to 55/75, and I was instantly wiped by hordes of flying ghost fish robots :( As a new player, this was very disheartening.

**Describe the changes you want to propose. Include possible alternatives.**
There should be a period of amnesty after capturing a sector where it cannot come under attack again; I would suggest giving the player about 3 minutes to enjoy their victory, but this is of course variable.

**Comment by catatagun** [comment]
Wtf wat

**Comment by HaphLife** [comment]
I think it’s that you’re sector can get attacked while you’re still capturing it, and it queues the attack to be right after capture, rather than either increasing the wave count to capture (which would be annoying in a different way) or just removing uncaptured sectors from the pool of attackable sectors (which would be the proper fix)
