### ISSUE TITLE
Новое управление боевыми единицами 

### ISSUE THREAD

**Issue by CiCiRON-MARK-TULLY** [Anuken/Mindustry-Suggestions#1818]
Было бы здорово добавить более детальное управление для БЕ к примеру разделить управление между разными родами войск добавить по больше команд и ввести пару новых БЕ . Например чтобы можно было отдельно отправлять в бой воздушные и наземные войска , можно было бы добавить возможность направлять атаку в конкретное место , но это бы поломало всю суть защиты , По поводу команд , добавить дополнительные блоки возле которых можно было бы собирать армию и настраивать эти блоки под определенный вид войск , желательно ещё добавить хотя бы пару команд для войск .
Так же в игре не помешал бы новый вид войск к примеру подземные и ввести против них новые блоки защиты .Надеюсь свою идею я изложил понятно .Спасибо за уделённое время . Хорошего дня !)

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Translated with Google:

It would be great to add more detailed control for BU, for example, divide control between different types of troops, add more commands and introduce a couple of new BU.  For example, so that you could send air and ground troops into battle separately, you could add the ability to direct an attack to a specific place, but this would break the whole essence of the defense.As for the teams, add additional blocks near which you could collect an army and customize these blocks  for a certain type of troops, it is desirable to add at least a couple of commands for the troops.
 Also, in the game, a new type of troops, for example, underground, would not hurt and introduce new defense blocks against them. I hope I presented my idea clearly. Thank you for your time.  Have a nice day !)

**Comment by Yell245** [comment]
В следующий раз следуй формату предложения: Объяснение идеи / проблема и твои способы её решения, затем твоя мысль, как это повлияет на баланс. К тому же, посмотри на чекбоксы, чтобы у Анюка сохранялось здравомыслие. Старайся опубликовывать предложения со всеми чекбоксами выполненными
Насчёт предложения: процессоры уже могут управлять юнитами, давая гигантские просторы в создании собственного ИИ последних. Однако, я согласен. Мне хотелось бы иметь возможность командовать отдельными классами войск

**Comment by itcannotbe** [comment]
But Mindustry Logic............

**Comment by BlueWolf3682** [comment]
thank the developers of android my phone has an autotranslate button that just knew there was englishn't

**Comment by Humanoid-X** [comment]
Readme.md:
No underground layer, thanks
