### ISSUE TITLE
import backup. 

### ISSUE THREAD

**Issue by remiecole** [Anuken/Mindustry-Suggestions#1828]
You should be able to import your part on another device because I want to change my cell phone and I don't want to lose my backup.

**Comment by genNAowl** [comment]
Hey could you please use the template? It's attached below: 

> **Describe what you would like changed, and why.**
> 
> **Describe the changes you want to propose. Include possible alternatives.**

**Comment by Kyllingene** [comment]
1: Please use the template (found at the bottom of this comment). Otherwise, people will ridicule you and Anuke will automatically filter it out to save him time.

2: This would work better as a feature request, not a balancing/feedback. Please change the label and us the template at the bottom.

3: If you mean cloud storage, look [*here*](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md#a-few-things-you-shouldnt-suggest). You missed this because you chose the template that doesn't have it.

```
**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*


1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.
```

**Comment by GreyMario** [comment]
I don't suppose anyone has ever told you about the magical world of _file transfer_?

**Comment by Quick-korkc** [comment]
i dont know why people delete the template
also export and import save file exist

**Comment by DeltaNedas** [comment]
export save file: am i a joke to you

@remiecole close this you complete egg

**Comment by skvventus** [comment]
go to the settings,game data,export game data,and then send to your other phone,do the same thing but impost game data
