### ISSUE TITLE
Omni-directional bridge conveyors/titanium bridge conveyors & routers

### ISSUE THREAD

**Issue by DAVEtheDuck2287** [Anuken/Mindustry-Suggestions#185]
So, my idea for the 'Omni-directional bridge conveyor" is something similar to the normal bridge conveyor but it is able to transport items over distances DIAGONALLY. And for the titanium bridge and routers, they're just upgraded versions of the already existing bridge and router, but they transport items as fast as the titanium conveyor, and the titanium bridge has a bit more reach.

How will this improve the game? Well, it will give more leeway to new players with jumbled conveyor lines everywhere (Omni-directional bridge) and will reduce bottlenecks in supply chains for users (both ideas). The Omni-directional bridge will also open up the idea of more organization.

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Summet-V** [comment]
Very cheaty

**Comment by potatoisagender** [comment]
actually, there are several problems with this idea. One, it's kinda game breaking. A lot of people who are good at the game use bridges, and this idea makes using bridges really overpowered, kinda like the sorter snek. 
New players should learn how to play the game, not hopelessly use things when they have no idea how they work. The idea is to get them to branch out, not use a single block. Did I mention that bridges in general aren't used that often with beginners, because bridges are janky, and confusing when you stack them. 
Additionally, diagonal bridges will increase the maximum length/distance between bridges (you should know how pythagoreas works) from 3 to about 4.25, depending on how anuken executes it. This is going to make the game a bit more complicated, because now we have decimals involved in positioning blocks. 
Omni directional bridges will just promote bridge mixing, not promote organization, because at some point some idiot is going to feed a bridge into a bridge, and diagonal bridges are just going to excaberate that problem. Griefers are going to have a field day, because they can change the direction of bridges about 5x easier and get away with it really easily. 
It's an okay idea, but I don't think it has been thought through completely.
