### ISSUE TITLE
quick schematic export option

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry-Suggestions#1852]
**Describe what you would like changed, and why.**

currently when you want to share a schematic you have to save it first,
it would be nice if the create button had an export to clipboard button under it:
(pressing it would export it to the clipboard or file, without storing it ingame)

![Screen Shot 2021-01-21 at 20 52 54](https://user-images.githubusercontent.com/3179271/105404897-cd704180-5c2a-11eb-99dd-0e2a3e36af23.png)

**Describe the changes you want to propose. Include possible alternatives.**

being able to shave a few seconds off of sharing builds quickly.

**Comment by DeltaNedas** [comment]
if @Anuken doesnt like this it should be trivial to make a mod for it

**Comment by itcannotbe** [comment]
Why not make a PR for it? XD.

**Comment by joshuaptfan** [comment]
Then what would populate the name field of this quick export schematic?

**Comment by Kyllingene** [comment]
You could have it prompt for a name. The main point seems to be to remove the need to save schematics in order to upload them.

**Comment by QmelZ** [comment]
> Then what would populate the name field of this quick export schematic?

"unknown"

**Comment by itcannotbe** [comment]
The point of this suggestions is to that a user doesn't need to save a schematic before being able to export it.

This just skips the saving part.

**Comment by joshuaptfan** [comment]
Let's walk through required steps to share a schematic currently.

1. Hold "F" and select the schematic.
2. Click "Save Schematic..."
3. Type a name and press "Enter".
4. Click back, or press "Esc".
5. Press "T".
6. Find the new schematic and click the export button.
7. Click "Copy to Clipboard" or "Export File".

7 steps not counting extra steps needed for file export, which are likely not optional.

Now let's look at

1. Hold "F" and select the schematic.
2. Click the shiny new export button (next to "Save Schematic...").
3. Type a name.
4. Click "Copy to Clipboard" or "Export File" (these buttons would optimally be under the name field).

That's 3 fewer steps!... or is it?

What if you copied to clipboard, but then accidentally overwrote the clipboard by copying something else (pretty easy thing to do)? You've now lost the schematic code. Instead of repeating the last 3 painless steps of the current method, you have to re-select the schematic and re-type the name.

**Comment by itcannotbe** [comment]
You forgot the part where you clean up you in game schematics becuase you do it over and over without the actual intent of keeping it.

**Comment by joshuaptfan** [comment]
> You forgot the part where you clean up you in game schematics becuase you do it over and over without the actual intent of keeping it.

It's easy and fast to later delete schematics you don't want to keep.

I propose an alternative, safer solution to speed up schematic copying: put "Copy to Clipboard" and "Export File" buttons in the schematic preview screen that pops up after you name a schematic. This would cause copying to take 5 steps, about the same as OP's quick export suggestion, but safer in that the schematic is also saved so you can overwrite the clipboard without worry.

**Comment by QmelZ** [comment]
> I propose an alternative, safer solution to speed up schematic copying: put "Copy to Clipboard" and "Export File" buttons in the schematic preview dialog that pops up after you name a schematic.

this ^ is an amazing suggestion, also add a "delete" button there so if they want they can just "copy to clipboard" "delete"

**Comment by Kyllingene** [comment]
> (pressing it would export it to the clipboard or file, without storing it ingame)

> safer in that the schematic is also saved

The only problem I see is that I thought the main point was that you no longer have to save (and possibly delete) schematics to share them, but maybe I was mistaken.

**Comment by joshuaptfan** [comment]
> The only problem I see is that I thought the main point was that you no longer have to save (and possibly delete) schematics to share them, but maybe I was mistaken.

Others are saying that not saving is convenient, I say it's safer to have whatever quick export option save just in case

> What if you copied to clipboard, but then accidentally overwrote the clipboard by copying something else (pretty easy thing to do)? You've now lost the schematic code. Instead of repeating the last 3 painless steps of the current method, you have to re-select the schematic and re-type the name.

and delete later if you want since that's easy to do.
