### ISSUE TITLE
Give oct poly ai

### ISSUE THREAD

**Issue by guncatt** [Anuken/Mindustry-Suggestions#1891]
**Describe what you would like changed, and why.** oct has no ai right now and poly ai would be very nice for it

**Describe the changes you want to propose. Include possible alternatives.** give oct the exact same ai as poly or give oct its own ai

**Comment by catatagun** [comment]
When i said poly ai i ment the sharded poly ai where it helps you build and when ai building is on oct acts like a gamma on crux

**Comment by Yell245** [comment]
I think that octs could react to command center. If the mode is rally, they'd see where's the biggest amount of units and go there. They'll follow units and protect them with shield. When on other modes, they'll rebuild broken buildings. I also think that quads could repair damaged buildings on commands other than attack

**Comment by itcannotbe** [comment]
Should this be a feature suggestion because the said unit doesn't even have one?

Also I think the poly ai is unsuitable because the oct is a flying force projector to say the least.

**Comment by catatagun** [comment]
Its still a flying unit and can build i dont really see the problem

**Comment by TheMrAlbert** [comment]
Poly do mend blocks. Oct supports in the offence with it's shields. Consider why shouldn't the exactly the same AI.

**Comment by catatagun** [comment]
> Poly do mend blocks. Oct supports in the offence with it's shields. Consider why shouldn't the exactly the same AI.

Polys dont heal blocks they help build

**Comment by marky0470** [comment]
Do Octs help the player build on idle? If not then I think that would be a good step, the Oct doesn't have to move at all it'll just help with construction and repairs if said actions are within its building range. Octs shouldn't move by default because one of their uses (at least one that I know of and use regularly) is to have them just sit on top of defense for extra shields. 

I don't think it would be useful for them to move to where you are currently building due to their slow speed, by the time they've arrived (if they manage to) your polys would have already completed construction.

**Comment by WinterCrystal** [comment]
> Poly do mend blocks. Oct supports in the offence with it's shields. Consider why shouldn't the exactly the same AI.

The only way that polys repair blocks is if you control them with logic that does exactly that.

**Comment by WinterCrystal** [comment]
The Oct has terrible movement, giving it the Poly AI would pointless because it would just get outrun by the Poly when it comes to building and rebuilding, sure, the Oct can build a lot faster, but it's slow, not to mention expensive to make. You can't easily mass produce Oct as fast the Poly. Lastly, did I mention the materials it requires to make all of the reconstructors just to make one?

**Comment by Kyllingene** [comment]
> Lastly, did I mention the materials it requires to make all of the reconstructors just to make one?

Actually, you did 2 sentences ago:

> not to mention expensive to make

And, so as to say something *constructive* in this comment, I personally thing that having the Oct do something would be nice, but I would rather my giant shields didn't follow me everywhere as I'm building, instead of actually using their natural abilities.
