### ISSUE TITLE
copper -> scrap converter 

### ISSUE THREAD

**Issue by drywrecker87** [Anuken/Mindustry-Suggestions#190]
similar to the smelter
copper goes in and scrap goes out
no liquid required but as a booster
20 power/second

1. - [x ] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by potatoisagender** [comment]
So. You are going to shove one thing in, and get a whole other thing out?? That basically breaks the game, because you don't even need scrap anymore, you just mine copper (which is on every map) and shove into one of these machines, then put the scrap into melters and separate them? Have you even thought this through??

**Comment by itcannotbe** [comment]
So you want a block that actually uses the outputs of the block you want to use for the block you wanted to use...…….

**Comment by nichrosia** [comment]
So...
Copper => Titanium, you are saying.

**Comment by Anuken** [comment]
This is too unbalanced.
