### ISSUE TITLE
block demolisher

### ISSUE THREAD

**Issue by Mieew** [Anuken/Mindustry-Suggestions#1904]
**Describe the content or mechanics you are proposing.**
a block called block demolisher which takes a block from a payload conveyor and crushes it and turns it into scrap and requires power
and would also have a lot of disatvantages so it isnt op

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
sometimes there's no scrap on a map and this would help
adds a reason to place blocks on payload conveyors

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
This goes to the pile of suggestions that takes something and turns it into scarp.

Close this before someone bust out the line where someone tells you that scrapping anything to be turn into scrap is over-powered and is bad for game balance.

**Comment by Kyllingene** [comment]
> Close this before someone bust out the line where someone tells you that scrapping anything to be turn into scrap is over-powered and is bad for game balance.

Yeah, imagine turning copper walls into scrap which gets you more copper, lead, graphite, titanium, thorium, and sand. VERY bad for game balance. However, a very cool idea, and one I would love to see in a mod.

**Comment by RouterChainsSuckk** [comment]
this is a good mod idea, not a good vanilla one

**Comment by RedstonerKBC** [comment]
The last time I suggested a block that can produce scrap I was flocked with angry "Scrap is op" people, all of which I made dozens of scrap-only maps so they can play them and still to this day I haven't received any feedback or requests to try. Makes you wonder if those people are just blowing steam out of their pieholes at people they don't agree with? I've never ever seen servers not use scrap ore because it's op. In fact, I've never ever seen players mine or use the scrap for anything other than ammo for scatters.

By the way my maps are still there on the discord if any of you "Scrap is op" people want to try. I've yet to receive feedback or notice that someone has made it to wave 100. All I'm asking is for them to prove it to me and the community that scrap is op. I just don't see it.

**Comment by Kyllingene** [comment]
Umm, one note: the only "this would be OP" responses specifically said turning *anything* into scrap is OP. I do not personally believe it is currently OP, just a fun gimmick.

**Comment by itcannotbe** [comment]
@Kyllingene I was referring to this

https://github.com/Anuken/Mindustry-Suggestions/issues/535#issuecomment-695152779

**Comment by Kyllingene** [comment]
I understood what you were meant, I was responding to RedstonerKBC about his pro(anti?)-scrap comment.

**Comment by Mieew** [comment]
> This goes to the pile of suggestions that takes something and turns it into scrap. Close this before someone bust out the line where someone tells you that scrapping anything to be turned into scrap is over-powered and is bad for game balance.

ok ill close
