### ISSUE TITLE
Make jumps go to the right line when pasting code into logic blocks

### ISSUE THREAD

**Issue by creezen** [Anuken/Mindustry-Suggestions#1926]
When pasting code into logic blocks jumping to specific lines starts count at 0 which is counterintuitive, as nearly all IDE's or coding environments start at 1. This is very confusing and makes working on logic programs nearly impossible in any proper coding environment.

**Comment by SheepCommander** [comment]
I agree

**Comment by DeltaNedas** [comment]
1. its an address not line number
2. why should it be 1-indexed? `getlink` isnt, along with basically every programming language ever.

**Comment by SheepCommander** [comment]
Ah

**Comment by Humanoid-X** [comment]
//Java testing
String[] test = new String(5){
  "This suggestion is fake",
  "Hello, World!",
  "Welcome to the world of horrible truths",
  "Shut Up",
  "What a niccce houssse you got there... It would be a ssshhhame if sssomething happened to it..."
};
println(test[0]);

**Comment by stuffyAI** [comment]
> as nearly all IDE's or coding environments start at 1

To elaborate on what DeltaNedas said, basically any iterable object in logic-based or machine programming (C's, Java, PHP, Shells) starts it's index at 0, whilst 'programming languages'  with application focus (Mathmatica, Lua, Matlab) usually start them at 1, but even there you can easily set it to start at 0.
I assume the decision in starting at 0 here lies in the base nature of mindustry logic due to it's close application to ingame objects.
