### ISSUE TITLE
Nerf poly range.

### ISSUE THREAD

**Issue by Sanya2907** [Anuken/Mindustry-Suggestions#1927]
**Describe what you would like changed, and why.**

Polies are impossible to counter with scatters. They just outrange them. It doesn’t make sense that support can defeat anything.

**Describe the changes you want to propose. Include possible alternatives.**

Nerf polys range to <20 so it can’t outrange scatters.

**Comment by BlueWolf3682** [comment]
manually fire the scatters.
parallaxes.
menders.

**Comment by Sanya2907** [comment]
> manually fire the scatters.
> parallaxes.
> menders.

I would see how you will place lot of parallaxes while your energy is +150

**Comment by LeoSko** [comment]
> manually fire the scatters.
> parallaxes.
> menders.

This basically doesn't work in PvP, because:
- one scatter can't deal enough damage to poly, and even more - to group of polys
- you will need a lot parallaxes (I tried - poly can just fly away from 3 of them), which cost a lot of energy and resources right now. It is simply not profitable
- mender don't help against a group of polys as well

**Comment by Sanya2907** [comment]
> manually fire the scatters.
Good luck here at pvp server where every second matters

**Comment by Sanya2907** [comment]
> menders.

I don’t want to comment this

**Comment by BlueWolf3682** [comment]
oh youre a salty person who lost a pvp match. youre on your own then.

**Comment by SheepCommander** [comment]
@BlueWolf3682 he still has points based off of personal experience, and not having a response just shows they're right.

Anonymous — 'When the debate is lost, slander becomes the tool of the loser.'

I agree with this suggestion. Even assuming that you can manually fire the scatters or that parallaxes are an effective counter, a support aircraft should not be able to outrange and destroy a defense specifically meant for anti-aircraft (even if early game)

**Comment by DeltaNedas** [comment]
if poly has missiles why not mono

**Comment by RouterChainsSuckk** [comment]
> if poly has missiles why not mono

good point idk why anuke added weapons to pollys as their ai doesn't auto attack or heal (possibly to have a use for them with logic?)

**Comment by G0nTar** [comment]
Well, it makes sence for a **"Support Build/Repair"** Unit, to be _"Less Effective"_ at **"Combat"** but still manage to fence on the battlefield, if a dedicated AA Gun can't take or out-range them, either the _AA needs a range buff_, or Poly needs a _Damage agaisnt Building Reduction_.

**I don't Think** _"Range"_ is an issue here, Poly needs the range otherwise it losses it's main mean of repair buildings, it would make it a pain to be at such a short distance to buildings in order for your Poly Missiles to repair them, wich have really bad accuracy already on it's own.

Final Veredict:
- **Poly Should** **Deal a Bit less Damage** or Dmg Vs Buildings
Or
- **Scatter Needs** a **Small Range Buff** to Shoot Away Air Support Units, like it should in the First place.

**Comment by itcannotbe** [comment]
Scatter is early game anti air IMHO.

**Comment by G0nTar** [comment]
> Scatter is early game anti air IMHO.

What is the mid and late game Anti-Air Battery/Gun then? 

I would love to see a 3x3 dedicated AA Flak Cannon, or any Mid-Game specialized AA, more expensive of course and with greater range if that solves the lack of longer range AA Guns (wich would be great since right now air units controlled by players can out maneuver most defences)

**Comment by itcannotbe** [comment]
And that's a suggestion, which discussion should be outside this thread.

**Comment by Ilya246** [comment]
If you're dying to being kited by polies something is wrong with your defense, not polies
Either way, i think that what needs to be nerfed is poly's health, not anything related to its weapon

**Comment by LeoSko** [comment]
@Ilya246, if you tell something is wrong with defense then you might have an idea how to counter the fact of outranging, right? (tip: there is no way to outrange something that outranges you)

**Comment by Catchears** [comment]
> 3x3 dedicated AA Flak Cannon
Isn't that called a cyclone?

**Comment by marky0470** [comment]
what about using logic to boost their range?

**Comment by LeoSko** [comment]
@Catchears,
To make cyclone compared to polys you will need:
- titanium
- plastanium + a lot of energy, space and time if no tar is available on the map

Also, cyclone requires ammo, which would usually be either plastanium itself (which is already not cheap), or cheaper ammo - metaglass, which would require just another step in order to **defend against support t2 unit**.
2 ineffective or the whole 3 additional resources to make seems quite an overkill for such a simple purpose.

@marky0470,
This seem to be the way to go - like linking hail to scatter and using hail's range for that. But the whole process for that seem like not the right thing to do and more like a hack rather than a proper solution.

**Comment by Catchears** [comment]
> @Catchears,
> To make cyclone compared to polys you will need:
> - titanium
> - plastanium + a lot of energy, space and time if no tar is available on the map
> 
> Also, cyclone requires ammo, which would usually be either plastanium itself (which is already not cheap), or cheaper ammo - metaglass, which would require just another step in order to **defend against support t2 unit**.
> 2 ineffective or the whole 3 additional resources to make seems quite an overkill for such a simple purpose.

I agree that a cyclone should not be needed to fight a poly, but you were talking about a 3x3 AA turret, which is the cyclone. It shouldn't be needed for a poly, but I would definitely call it mid / end game aa.

**Comment by Kyllingene** [comment]
```
>>> parallax.exe
ERROR: could not process command
```

**Comment by mechanarian** [comment]
> > 3x3 dedicated AA Flak Cannon
> 
> Isn't that called a cyclone?

Yeah it legit says that the cyclone shoots clumps of flak in the database 

also if you want turrets to only target air just use logic

**Comment by G0nTar** [comment]
### **Logic is not a solution** to a _PvP Fast Paced Casual Game._

 -Where you can Spam "Early Game" a bunch of Polys **10-15** minutes into the Fight.
  **VS**
 -Wasting **30-45** minutes instead of doing anything else, to get to Late Game Turrets, Factories, Power Generation and so on, JUST to counter a Pseudo "Support/Fighting" Unit + You have to do it in advance and instead of doing anything else if you want it to work, wich is Non-Sence.

But i agree that, **POLY** is **not the main issue.**

 I'm Gonna make a new Suggestion, ADD a Long Range "Early-Mid" Game **"Guided Missile AA Platform"** with ultra low fire rate, fair ammo/energy consuption, to complement Air Defense, since the tractor beams are not working properly for what i've read above (could boost those too either way)

I'll try to fight with and against Poly on sandbox to really check the facts that people are talking about.

**Comment by LeoSko** [comment]
@G0nTar
>Logic is not a solution to a PvP Fast Paced Casual Game.

It may be both the cause and solution. You don't need to make logic while being in a PvP game, you make it beforehand. The problem with this logic is that it is cheaper to make 1 processor for poly logic than making several processors to cover your base with hail+processor+scatter combination.

**Comment by G0nTar** [comment]
Agreed @LeoSko , i have to add, the fact that we missed completly 1 key turret in the whole disscussion, the **"SWARMER"** Guided Missile Turret, it already exists, but it's not used that often (because of it's expensive build materials/ammo cost) it could in theory (it has a bit more range than Scatter) outrange poly, i'm testing it as we speak

**Comment by SheepCommander** [comment]
So this is a lot. The general gist of what I got was
- Poly range isn't the problem, a health/attack debuff would be better
- Adding another early-mid game AA gun could help

**Comment by LeoSko** [comment]
**Swarmer vs Poly is unrealistic scenario** because of yet-another-3-resources (plastanium + titanium + pyratite) that I have to make in order to defend against 2nd tier air support unit.

Poly's range **IS** the problem. Maybe everyone above read it as microing the poly, but no - the issue is when it is being controlled by logic. Here is the example I made into a video (that *should not* be possible): https://www.youtube.com/watch?v=yEu8bavHS3s&feature=youtu.be

**Comment by G0nTar** [comment]
> **Swarmer vs Poly is unrealistic scenario** because of yet-another-3-resources (plastanium + titanium + pyratite) that I have to make in order to defend against 2nd tier air support unit.
> 
> Poly's range **IS** the problem. Maybe everyone above read it as microing the poly, but no - the issue is when it is being controlled by logic. Here is the example I made into a video (that _should not_ be possible): https://www.youtube.com/watch?v=yEu8bavHS3s&feature=youtu.be

I tryed it all on the editor, so it wasn't logic Controlled, I'll check it out asap

**Comment by G0nTar** [comment]
> **Swarmer vs Poly is unrealistic scenario** because of yet-another-3-resources (plastanium + titanium + pyratite) that I have to make in order to defend against 2nd tier air support unit.
> 
> Poly's range **IS** the problem. Maybe everyone above read it as microing the poly, but no - the issue is when it is being controlled by logic. Here is the example I made into a video (that _should not_ be possible): https://www.youtube.com/watch?v=yEu8bavHS3s&feature=youtu.be

Your video is byased, no one builds defences that bad. 

Also you used Thorium and titanium to build turrets but the walls are made out of copper, you don't see copper walls ever, and even before getting to the turrets used om ur vid, everyone uses titanium minimum for defence when they already have thorium tech. 

With the fast forward it seems like it takes around 4minutes to take down a copper wall, for 60+ Polys, wich imo denotes that they are not that over powered, would like to see if you used logic to attack, if you can upload the logic you used to recreate that using what players build in actual games, not good players, but new to normal ones

**Comment by LeoSko** [comment]
@G0nTar, the code can be found in comments if you really want to try this out (an old version though). I have numerous matches in my server (ranked pvp) where people use such logic which has no counters except for the logic that I stated in the video. Those are literally dozens of examples. Other possible counters are all **impractically** more expensive than just spamming polys.
