### ISSUE TITLE
Oil should be burnable in combustion generators and steam engines.

### ISSUE THREAD

**Issue by ziggythomas1123** [Anuken/Mindustry-Suggestions#1957]
**Describe the content or mechanics you are proposing.**
     I think it would be a good idea if oil could be burned in combustion generators and steam engines for power, in the same way coal, pyratite etc. can.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
    One reason is that I think it would make sense to be able to burn oil for power. It would also allow for more power options on maps with limited resources.

   The second is that it would make the oil pools on some maps more useful as well, instead of being just a cheaper way of feeding Wave turrets or coal centrifuges.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category. - could not find

**Comment by joshuaptfan** [comment]
It's currently not possible for blocks to accept 2 liquids, so the steam generator suggestion is not feasible.

**Comment by TheRealIvyX** [comment]
making steam gens being able to accept oil is just going to make oil power overpowered since currently you have to put the oil into coal centrifuges and then put the coal into steam generators which causes the whole thing to generate less power but this suggestion would let you skip the "insert oil into coal centrifuges to make coal" part and make more power than you already can with this method

**Comment by BlueWolf3682** [comment]
oil > coal centrifuge > coal > combustion btw

**Comment by Kyllingene** [comment]
Coal centrifuges take just about no power. Seriously. For something spinning fast enough to condense raw oil into pure coal, it is remarkably cheap. The power drain from the extra centrifuge step is practically unnoticable.

**Comment by Humanoid-X** [comment]
Coal centrifuge exist also, why didn't you read the readme.md?

**Comment by XEN0PHIL** [comment]
Crude oil is not a suitable fuel source if not refined because of many factors which, of course, I won't explain

**Comment by lokyinng** [comment]
how about natural gas just kidding this game don't have natural gas and I went liquid power gen in mindustry

**Comment by G0nTar** [comment]
Since it's not viable for steam gens, i would like to suggest adding a new power generator that uses Oil?

It could be a cheap but use a bunch of space and be dangerous for your base (it explodes and turns ablaze a big chunk of your base) source of power

Wich if you think about it may make waves useful inside ur base for putting fires out in the case it explodes

**Comment by itcannotbe** [comment]
Isn't that called using a coal extractor?
