### ISSUE TITLE
big cyrofluid factory

### ISSUE THREAD

**Issue by Farras-Fadhil** [Anuken/Mindustry-Suggestions#1984]
Like cyrofluid factories in general, but the release of cyrofluid is more profuse and the entry into the factory can be adjusted according to the developer

Maybe this new content will make it easier for players to get more cyrofluid without having to make a big cyrofluid factory please ok

**Comment by BlueWolf3682** [comment]
🎶mods🎶

**Comment by Cherriodude** [comment]
As said, mods. Almost all suggested content that either adds an advanced version of a vanilla block or similar will get shot down by a response. "Mods".

**Comment by itcannotbe** [comment]
Where's the template?

**Comment by itcannotbe** [comment]
What template you ask?

###THIS

```**Describe the content or mechanics you are proposing.**



**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**



**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*



1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.```

**Comment by itcannotbe** [comment]
And basically a duplicate of #1097

**Comment by Humanoid-X** [comment]
genNAowl/Upgrded-Factories

**Comment by SheepCommander** [comment]
👏close👏this👏please👏

**Comment by XxsuperdeadlysniperxX** [comment]
> 🎶mods🎶

@BlueWolf3682 what if someone wanted to go modless yet have a big cryofluid factory?

**Comment by BlueWolf3682** [comment]
then use normal mixers, i have no issues making massive cryo factories with vanilla cryo mixers

**Comment by XxsuperdeadlysniperxX** [comment]
> As said, mods. Almost all suggested content that either adds an advanced version of a vanilla block or similar will get shot down by a response, "Mods". 

@Cherriodude most of the time the idea is better not being a mod cuz mods have to be made and some people either has 0 knowledge on how to make a mod or don't want to waste their time making a mod almost no one will download because either the mod maker has made a malicious mod the crashs the game as soon as the game loads (if your that mods creator plz remove that mod or it will be reported because it crashs people mindustry which if you accidentally download the wrong mod guess who made the mod come to exist) or usually doesn't have great mods to begin with
Summary: this would be a terrible mod by itself

**Comment by XxsuperdeadlysniperxX** [comment]
@Farras-Fadhil for the love of the muffled scream close this please

**Comment by XxsuperdeadlysniperxX** [comment]
Massive factories of like 10 little cryo bois are better than one massive
factory that taking over 5k titanium and over 300 thermal pumps just to
produce maybe 45+ cryo at a slightly slower rate than the small one ( over
exaggeration) blue wolf is right on the small better than big but this
suggestion (if you could even call it that) is actually already in a mod
tho no one is going to make a mod with just this specific block in it

**Comment by XxsuperdeadlysniperxX** [comment]
[X] You have not acknowledged that a template exist therefore unable to read and follow said template yet capable of deleting it entirely therefore making your suggestion invaild thus wasting both anukes time and making the list of suggestions longer than it needs to be

Use the template and follow the template so that your suggestion is acknowledged and then will be shot down cuz this most likely a duplicate of very close to 300 more or less suggestions (over exasperation)

**Comment by sample-text-here** [comment]
> mod cuz mods have to be made

hjson was made for people who don't know how to program

> the mod maker has made a malicious mod

just delete `scripts/` if you're so worried

also, these kinds of ideas are what the purpose of mods is for.
