### ISSUE TITLE
new force projector boost types

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#1995]
**Describe the content or mechanics you are proposing.**
right now phase fabric makes the force projector shield larger. but why not be able to feed different things into projectors for different effects?

ideally, only one boost can be active at a time. these are some concept ideas.
-phase: makes shield larger
-surge: makes shield stronger
-plast: makes shield stop lasers and electric arcs
-thorium: makes shield stop bombs dropped by units
-glass: acts as a wall that stops air units
-titanium: acts as a wall that stops ground/spider/boat units

also, as an example say you feed the projector plast. the projector will still take damage when hit by lasers like plast walls do. they just wont go through the shield.

effects could be visualized via a thin "outline" that's colored differently. not sure with this one though.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
it'll open up new gameplay mechanics and ideas, and lets you defend your base in more interesting ways. it also allows air units to not cheat their way over hallway based pvp maps. in a nutshell: lots of more creative opportunity.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by TheNightglow** [comment]
I wonder about air units, since they dont really have much of a pathfinding right now...
since obstacles would be intoduced for air, they would need to get a simmilar form of obstacle based pathfinding as ground units then, otherwise they will just fly against a wall with the current ai ^^

also from a logical side, its wierd having a force field that prevents air units but not ground units from entering (the titan option), after all, what could possible stop something flying that does not also stop something walking

**Comment by the-kido** [comment]
I very much like this concept. 

> since obstacles would be intoduced for air, they would need to get a simmilar form of obstacle based pathfinding as ground units then, otherwise they will just fly against a wall with the current ai ^^

Maybe phase should make units in its vicinity slower, but not completely breaking their path, that way no one would need to worry about that and I think it breaks the whole "shield units away" thing which has been suggested several times.

**Comment by sup3r87** [comment]
> also from a logical side, its wierd having a force field that prevents air units but not ground units from entering (the glass option), after all, what could possible stop something flying that does not also stop something walking

maybe a shield that has energy diverted upward to stop air units? that way ground units could walk through but the intensity is focused more towards the sky

**Comment by bloool** [comment]
I like the idea a lot, but the actual items you can use are way too many, which would make it very easy to have a better projector since turrets already use that kind of stuff, and when you think about it, putting a piece of glass into a shield doesn't really make that much sense, to what I think are better buffs could be:

Surge - Explodes with lightning when the shield gets destroyed or damaged
Phase - Much larger range and would repel air units, but smaller health
Plast -  Block lasers and such, stop any ground unit, but much smaller range

**Comment by SheepCommander** [comment]
I agree with bloool, cool idea and surprisingly doesn't sound too much like a mod to me, but the items and buffs should make more sense like with blool's suggestion

**Comment by Yell245** [comment]
I think that metaglass should be able to distribute damage of lasers between all buildings in range of field, but 5% of damage more to the force projector itself. Plus projector could overheat faster if this ability is too op. But it won't work so well because the force projector **itself** uses phase to focus energy or smth, so loading something new inside of it won't do things, only if projector would scatter small particles of item into the field

**Comment by genNAowl** [comment]
Slightly off topic, but it is possible to prevent air units from cheating their way around hallway based PVP maps by using enemy spawns. (Of course, you would also need to turn waves on, and also make a wall around the spawns big enough so it doesn't screw with unit AI)
