### ISSUE TITLE
Mecanismo nuevo 

### ISSUE THREAD

**Issue by Hectorzkx** [Anuken/Mindustry-Suggestions#2039]
**Describe the content or mechanics you are proposing.**
Lo que propongo es que al poner un mina ubiera un botón que puedas minar un recurso de otro por ejemplo al poner un minero y sobre uno de torio y también que estén debajo arena minero detecta solo el torio y no la arena y podrían agregar un botón o algo parecido para  así poder minar arena "x"

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatica

1. - [] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
You could have translate both your message and the template so that you and we could understand what you're saying

Podría haber traducido tanto su mensaje como la plantilla para que usted y nosotros podamos entender lo que está diciendo.

--------

Here's the translated version (courtesy of google translate)

What I propose is that when putting a mine there would be a button that you can mine a resource from another for example by putting a miner and on top of a thorium and also that they are underneath mining sand detects only thorium and not sand and they could add a button  or something similar to be able to mine sand "x"

**Comment by itcannotbe** [comment]
But doesn't this fall under....

Additional configuration of blocks?

**Comment by Kyllingene** [comment]
OH, *that's* what they are asking for. They want a button to allow you to mine sand that is under other ores. Mmmm... how about learning to play, instead of asking for something illegal?
