### ISSUE TITLE
changing of game style in strong maps

### ISSUE THREAD

**Issue by Whatisgitbuh** [Anuken/Mindustry-Suggestions#2058]
**Describe what you would like changed, and why.**
As play styles of hard maps of campaign such as planetary launch terminal, players usually use launch pad-core-unloader skill. This is a skill that allows players to be free of constructing drills or finding optimal conveyor way.
It is useful skill, but so easy to use that everyone can use it. This playstyle is far from structures of mindustry intended, so i think it should be fixed

**Describe the changes you want to propose. Include possible alternatives.**
This can be solved when original play is more efficient than L-C-U skill. so I propose to add a final super drill.
A super drill called [(something) drill] is 2×2 size, twice as fast as lazer drill, requires electricity 15/sec and liquid 12/sec to boost. this can be shown overbalance, but in ultra hard map like planetary LT, a special resource [(something)] is formed a few. this substance is material of [(something) drill].

**i want,(something) should be cool name.Like Gitijus, Unoptimanum and so.

**Comment by Bohaska** [comment]
The Anton Drill, named after Anuken's first name

**Comment by Humanoid-X** [comment]
@Bohaska OMG how did you know

**Comment by Kyllingene** [comment]
Incredible. Nobody has ever even considered suggesting More Drills before. This is a revelation. I would never have thought of adding More Drills myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More Drills immediately. (almost an actual quote from Anuken, just swap out Drills for Turrets.)

Anyway, you don't like how easy it is to strategize in hard maps, so you think adding a block you just drop into place will fix everything. How will a late-game block stop early-game launch-padding? How will an expensive block prevent cheap exploits? How will a one-resource drill replace multi-resource importing? Or, in case I misunderstood and the idea is to stop *exporting*, how will making it easier to export items (because it's easier to get them) stop them from getting exported?

I fail to see how the plan (a new drill) solves the harms (L-C-U abuse). Nor do I see the actual harm in L-C-U. Please enlighten me, I am probably mistaken.

**Comment by ShadeStrike62** [comment]
> Incredible. Nobody has ever even considered suggesting More Drills before. This is a revelation. I would never have thought of adding More Drills myself. This idea is so revolutionary, so clear, so simple that absolutely no further explanation is necessary. I will now go and implement More Drills immediately. (almost an actual quote from Anuken, just swap out Drills for Turrets.)
> 
> Anyway, you don't like how easy it is to strategize in hard maps, so you think adding a block you just drop into place will fix everything. How will a late-game block stop early-game launch-padding? How will an expensive block prevent cheap exploits? How will a one-resource drill replace multi-resource importing? Or, in case I misunderstood and the idea is to stop _exporting_, how will making it easier to export items (because it's easier to get them) stop them from getting exported?
> 
> I fail to see how the plan (a new drill) solves the harms (L-C-U abuse). Nor do I see the actual harm in L-C-U. Please enlighten me, I am probably mistaken.

This is true, and your idea has several key flaws. 

Such a drill would be overpowered firstly, as it is small, fast, and would be unbalanced compared to other drills. The only way around this is to make it expensive, but this is just a vicious cycle. In making it expensive, you are making it harder to use, and are just encouraging people to launch resources. 

Next, it would be unbalanced in that it could be used outside of Planetary Launch Terminal. Because this drill would be so efficient, all it would do is INCREASE the amount of materials available to send.

The reality is, adding a single block isn't going to change anything. As an example, I have a sector that launches 20,000 copper per minute. It also has 6 impact reactors, so it isn't going to run out of energy. Nothing, save for a fundamental change in the launch pad mechanics, is going to discourage me from importing my ~300 copper a second to the sector I am trying to beat. Trying to add more alternatives just unbalances the original strategy. Remember that mindustry is not a hard game, and first and foremost, has the appeal that hard work in optimising and expansion will pay off. The effort required to get the materials to launch makes using them the reward.

**Comment by sample-text-here** [comment]
hm, this would be better as a mod
