### ISSUE TITLE
Nuclear waste

### ISSUE THREAD

**Issue by Neil2101** [Anuken/Mindustry-Suggestions#2060]
**Describe the content or mechanics you are proposing.**
What if Nuclear waste or thorium waste was produced when a thorium reactor consumes a piece of thorium? Then when you put it in a container or a storage unit, it will change into unstable titanium and then turn into lead. Unstable titanium can be used in RTG generators.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will make the game more realistic.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by nichrosia** [comment]
Nuclear waste hardly fits the theme of industry. It would add unnecessary items/liquids that add basically nothing to the game.

**Comment by itcannotbe** [comment]
So basically a mechanic that creates an item only usable in one way?

Plus not mention that thorium isn't really used that much in reactors since better options exist.

**Comment by Neil2101** [comment]
well, unstable tit could be used the same way as normal tit, but it'll eventually turn into lead.

**Comment by Neil2101** [comment]
well, unstable tit could be used the same way as normal tit, but it'll eventually turn into lead.

**Comment by DeltaNedas** [comment]
https://en.wikipedia.org/wiki/Thorium_fuel_cycle

**Comment by Neil2101** [comment]
well sure, we could exchange unstable tit for uranium... :flushed:

**Comment by Kyllingene** [comment]
> **Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
This will make the game more realistic.

Ah yes, because who cares if it is unfit for the game, or overpowered (seriously, extra power gen practically for free, just because you used a thorium gen?), as long as it is realistic. 11/10 would balance again (and again and again).

**Comment by RedstonerKBC** [comment]
I'm surprised no one has said "mods" yet.

But yeah I've definitely seen radioactive decay in a mod before.

**Comment by Humanoid-X** [comment]
Remember exploding impact reactor? Mindustry is always an unrealistic game.

**Comment by Humanoid-X** [comment]
Drills and conveyors run without power. You can infinitely respawn without material loss. You can actually drill for water on magma. Slag pool never solidify or cool down. Slag and cryofluid can be placed in conduits right next to each other and travel infinite distance without heat transmission.

**Comment by Humanoid-X** [comment]
Minecraft suggestion : Remove zombies, skeleton, creeper, enderman etc. 
Reason : This will make the game more realistic.

**Comment by RedstonerKBC** [comment]
You don't need power to operate a "mechanical" drill, just physical labor. "Pneumatic" means it's a drill powered by air pressure, so again no power.

Real life magma can contain water vapor trapped in the magma itself, reflected by the greatly reduced efficiency for water extractors.

Conduits are supposed to contain the liquids without significant heat transfer/loss, otherwise it wouldn't be safe to route them near anything. One of the hospitals near my house has an outdoor liquid oxygen tank right next to all of the ourdoor covid patients. Not only does it stay cold enough to store outdoors during the heat of the day in a desert climate but it doesn't freeze the surrounding area. Your car engine is 1-2 meters away from you and you can safely drive the car without getting burned. 

Slag pools though definitely should cooldown/solidify :upside_down_face:

Yes though I see your point about realism and agree. Not everything in Mindustry has to be based irl.

**Comment by Kyllingene** [comment]
> You don't need power to operate a "mechanical" drill, just physical labor. "Pneumatic" means it's a drill powered by air pressure, so again no power.

***AAH***. So, basically, you think that both drills are perpetual motion machines? Power is simply a form of energy. Drills need energy. Explain where the energy comes from and I will concede it is realistic. But seriously, if air pressure requires nothing, then why does my pressure washer take fuel? If physical labor is free, why do I need to expend it?

> Your car engine is 1-2 meters away from you and you can safely drive the car without getting burned.

There is a difference between hot and *literally lava*.

**Comment by Neil2101** [comment]
ahhh i see i just noticed some unrealistic parts of the game, so this might also not fit in but thx for the reasoning :) I'll close this

**Comment by RedstonerKBC** [comment]
> > You don't need power to operate a "mechanical" drill, just physical labor. "Pneumatic" means it's a drill powered by air pressure, so again no power.
> 
> _**AAH**_. So, basically, you think that both drills are perpetual motion machines? Power is simply a form of energy. Drills need energy. Explain where the energy comes from and I will concede it is realistic. But seriously, if air pressure requires nothing to achieve, then why does my pressure washer take fuel? If physical labor is free, why do I need to expend it?

No lol. I assumed some imaginary entity is running the buildings. You don't really think nuclear power plants run themselves do you? lol. If it's mechanical then something has to be physically working it.

> > Your car engine is 1-2 meters away from you and you can safely drive the car without getting burned.
> 
> There is a difference between hot and _literally lava_.

Yes but believe it vehicle engines can get VERY HOT which is why they're designed to disappate heat quickly. Another example is your oven. Ovens MUST contain the heat otherwise they'll light the house on fire D:.
