### ISSUE TITLE
Liquid packing block

### ISSUE THREAD

**Issue by ZEPHYRkin** [Anuken/Mindustry-Suggestions#2068]
**Describe the content or mechanics you are proposing.**
A new type of factory block that will receive liquids as input, and will output transportable via conveyors items of liquids like barrels.  

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Some "assault" type of sectors (eradication/extreme difficulty) closer to the top of the planet lack water pools on the player's side of the map, making it very difficult and tedious to produce tier 4-5 units. Not impossible, but difficult. With new block outputting barrels with liquids, players will gain an ability to transport liquids across sectors. 
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Yell245** [comment]
Was suggested before. It was a reaaaaaaaaaally huge time ago, so it won't be implemented probably

**Comment by itcannotbe** [comment]
#197 be like:

![pikapika](https://c.tenor.com/UZJd1pjj4NMAAAAM/surprised-pikachu.gif)

**Comment by itcannotbe** [comment]
> Was suggested before. It was a reaaaaaaaaaally huge time ago, so it won't be implemented probably

Yes. That suggestion is older than this suggestions repo.

**Comment by RedstonerKBC** [comment]
Why don't we just remove conduits and water tanks altogether since no one seems to like them :upside_down_face:

**Comment by Kyllingene** [comment]
Yeah, seriously, just use the already given liquid transportation, it's more than enough. You need more ingenuity, not more handholding.

**Comment by G0nTar** [comment]
This is unusual but I'm kind of backing this up. 

it's not actual madness, like some sugar overdosed kids shouting they want to see teleporters, planets colliding, dinosaurs, and just shout their mind outloud dropping a poo poo on top of the game "core" gameolay/direction and want "their mad vision" of how they think the game "should be" accepted by all by just shouting and making a ruckus while never listening to most of us who try to talk some common sence into someone who is clearly under aged and can't listen to anyone not even fill a template or search/think before shoving it's nonsense giving Zero F***s about everything and everybody else... 
(i feel Anuken so much after experiencing a lot of that madness)

Going back to the subject (sorry about that catharsis)
I think being able to transport liquids just like you can transport materials makes some sence specially when you don't have "catapults" (Mass Drives) for liquid. 

I'm not interested in moving liquids from sector to sector that much thou it makes sence, but the improved logistic makes sence. 

With such advanced tech i support the idea of expanding on the relatively smaller liquid logistics (compared to conveyors n items logistic).

At least that's my point of view, it adds more ways of building your factories and production zones, along with the defences, would love to see how ppl take more advantage of a Liquid Logistics uograde, since you really don't see anyone using liquids to boost turrets or different buildings that often because of the lack of a better way to delivering these resources...

Laugh at this example, I would rather take a liquid tank as payload and deliver it to the Frontlines who lack of space and space to build, than taking 2-3hs to try n make every pipe get to its destination crossing a horrible bunch F conveyor spaghetti and structures all over the place.

It's not holding hands, it's about giving access to people with tech for making liquid logistics more **Fluid** (pun not intented hahaha)

**Comment by Kyllingene** [comment]
Either there is a liquid unpacking block, or the packed liquids are accepted as liquids. The second is out of the question (they are no longer liquids at that point), and both completely remove the point of conduits, bridges, etc. Why would you ever bother with cross-map conduits or strategic thinking when you can throw it in the plast highway? You just unpack it right next to the receiver. It turns liquids into slightly less convenient items.

**Comment by Bohaska** [comment]
not exactly the same, but https://github.com/Anuken/Mindustry-Suggestions/issues/1566
