### ISSUE TITLE
Holding shift + control and clicking on an item burns it.

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#2082]
**Describe the content or mechanics you are proposing.**

If you hold shift and control (or possibly just control) while clicking on an item in a container (not a core, however) it would burn it by the capacity of your unit and every one second (to avoid burning everything). 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This can be useful when cleaning up conveyors that have been messed up or have an unwanted item. It can also be used to clear up containers and vaults with schematics that use blank unloaders. This also means you don't have to pick up the item and then drag it out of your unit which is very painful. If there can be a little particle display showing that a player is burning items it can be useful in banning players using this feature maliciously.

All criticism is welcome.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by marky0470** [comment]
good qol, though i just put a sorter down and incinerator to the side

**Comment by itcannotbe** [comment]
How about you just drop it to the ground?

**Comment by itcannotbe** [comment]
Also the suggestion is extremely overpowered compared to every method currently existing at the moment.

**Comment by TheNightglow** [comment]
You are kinda contradicting yourself lol

>How about you just drop it to the ground?
vs
>Also the suggestion is extremely overpowered

it literally just does the same as adding it to your inventory and then dropping it to the ground, what is overpowered with that lol

its just QoL^^

**Comment by the-kido** [comment]
> How about you just drop it to the ground?

well maybe if you read the suggestion you would've known that I mentioned and rebutted that. It works, but it is painful to do/slow.

**Comment by itcannotbe** [comment]
> > How about you just drop it to the ground?
> 
> well maybe if you read the suggestion you would've known that I mentioned and rebutted that. It works, but it is painful to do/slow.

And adding faster way is overpowered if compared to how do it currently.

**Comment by TheNightglow** [comment]
> 
> 
> > > How about you just drop it to the ground?
> > 
> > 
> > well maybe if you read the suggestion you would've known that I mentioned and rebutted that. It works, but it is painful to do/slow.
> 
> And adding faster way is overpowered if compared to how do it currently. And you can always use incinerator - unloader.

you never actually presented a single scenario in which this would be overpowered tho... you just keep saying its overpowered because its faster, but with that logic, any QoL is always overpowered^^

how exactly would this be overpowered, give me even just a single example lol....

> Also...
> 
> > This can be useful when cleaning up conveyors that have been messed up or have an unwanted item.
> 
> You don't need this suggestion to do that.

pretty much the definition of QoL... you dont need it, it just makes things less tedious lol

> > If there can be a little particle display showing that a player is burning items it can be useful in banning players using this feature maliciously.
> 
> So it can also be use to grief faster, nice feature. What a great QOL for griefers. It does make their griefing more efficient.

in the same way you might argue that poly and mega shouldnt be able to help you build because that makes griefing faster aswell ;)

but yea, you might want to add a game rule option like 'allow burning core resources' than can be toggled off so in multiplayer griefer dont just burn silicon from the core... (dont really see a problem with non-core resources (like on conveyors or in vaults))

I wouldnt say that burning core resources allows to grief faster tho... have seen ppl just build a bunch of silicon unloaders at the core, which can always deplete the resources faster than the method proposed here

the difference is rather that you can spot the griefer by looking at the 'last access' name of the griefing-buildings, meanwhile the burning, even if it has visuals, would still allow for a quick undetected drive by

this could also be solved by simply adding a burned/dropped-resources list to the player list
as in for every player you can see what resources they burned in the past minute (this might be a good idea in general not just showing the burned resources but also the ones that were used to build stuff, to simply see who is currently wasting stuff^^)
