### ISSUE TITLE
Nerf ripple

### ISSUE THREAD

**Issue by SurgeAlloy** [Anuken/Mindustry-Suggestions#2111]
Ripple is too good for new players and needs to reduce range and damage.

The range would be 30 blocks and the damage would be less for each type of ammunition. The blast compound gives too much damage and graphite too, it's just a very good weapon and you should be a little weaker.

**Comment by nichrosia** [comment]
> needs to reduce range and damage

I think you mean *nerf*

**Comment by SurgeAlloy** [comment]
YES

**Comment by buthed010203** [comment]
The ripple serves the purpose of being a long ranged artillery, there really isn't any alternative to it and its balanced pretty well imo. The further away something is the less damage it does because of the large spread

**Comment by itcannotbe** [comment]
Just give it a no shoot zone in the middle.

**Comment by Slava0135** [comment]
> The ripple serves the purpose of being a long ranged artillery, there really isn't any alternative to it and its balanced pretty well imo. The further away something is the less damage it does because of the large spread

h A i L

**Comment by buthed010203** [comment]
> h A i L

They have significantly less range, if anything they are more op because of how crazy accurate they are.

**Comment by YellOw139** [comment]
Ripple is better when it comes to range, health, DPS and ammo choice.
It's bigger, has a much smaller accuracy and uses more ammo. (Which makes graphite ripples for instance well manageable IMO.)
In terms of blast I'd say it's ok. For blast's price, it's supposed to hurt.

So... what's wrong? Considering the tech level  and the purpose it server you wouldn't expect it to be any worse.

**Comment by RouterChainsSuckk** [comment]
Plast is better ammo, if anything nerf that so its arround same dps as blast or less

**Comment by GreyMario** [comment]
Nerf silicon, it should do more damage than blast

**Comment by genNAowl** [comment]
Upvoting your own suggestion makes you look pathetic.

**Comment by itcannotbe** [comment]
> Nerf silicon, it should do more damage than blast

Confused.

**Comment by buthed010203** [comment]
> Upvoting your own suggestion makes you look pathetic.

I think he realized he was in the wrong when everyone told him this is a dumb idea but he doesn't want to admit it. Either that or he just doesnt know how to close the issue lol

**Comment by GreyMario** [comment]
> > Nerf silicon, it should do more damage than blast
> 
> Confused.

The joke is the original issue title was "buff ripple"

**Comment by stuffyAI** [comment]
The build time and resource investment justify the result perfectly IMO, one can help with tinning out t2 ground units, spamming like 5 ripples costs you 1 minute and a few seconds simply building, which usually is enough to get the plastanium required for the superior firepower.

As for campaign..
ever since the addition of those single strong units, especially bosses, you also only use ripples there for AOE damage, which is their intended purpose.

> h A i L
Hails are actually stupidly strong against few high value targets, the 1x1 size can lead to extreme damage output contraptions, easily out-powering most other anti-ground options for the next few stages of the game should you be able to supply sufficient ammunition. Combine this with their ease of access due to low cost and you should quickly be aware of their actual purpose
