### ISSUE TITLE
Range adaption on other planets, this could allready be planed idk. 

### ISSUE THREAD

**Issue by Bobbystevenson** [Anuken/Mindustry-Suggestions#2135]
**Describe what you would like changed, and why.**
I think that if/when anuke adds new planets the range of different weapons would be ajusted (it makes sense from an irl standpoint cause of different gravitational pulls).

**Describe the changes you want to propose. Include possible alternatives.**
Some combinations of turrets are just too powerfull, they can _**sometimes**_ take the fun out of figuring stuff out (Im looking at you foreshadow), this would help balance things out eg: if there was more range people would use fuses more since their weakness has been reduced or if there was less range people would go for a more close quaters type defense.

A possible alternative is just disableing some turrets on planets, however, some people would have a problem with that (The same people who get pissed at the water extractor changes probably)

**Comment by Bobbystevenson** [comment]
I cant wait for this comment section to be nothing but toxicity

**Comment by Bobbystevenson** [comment]
Huh, nothing bad happened yet. Thats not how it usually goes lol

**Comment by notrealn** [comment]
game ing

**Comment by Bobbystevenson** [comment]
> game ing

gaming

**Comment by Kyllingene** [comment]
I like the main idea (the alternative I feel was just an addon, either way I dislike the idea of disabling turrets on planets)

**Comment by Kyllingene** [comment]
also dont wanna let you down so your toast sucks

**Comment by Bohaska** [comment]
.... I don't have anything to say to this suggestion.

**Comment by Kyllingene** [comment]
Then why did you say something to the suggestion?

**Comment by Bohaska** [comment]
> Then why did you say something to the suggestion?

Fixed

**Comment by Kyllingene** [comment]
Much better.

**Comment by Bohaska** [comment]
I saved this suggestion on the wayback machine

**Comment by Bobbystevenson** [comment]
> I like the main idea (the alternative I feel was just an addon, either way I dislike the idea of disabling turrets on planets)

I would hate that too, but the last time i left part of the template empty my suggestion got taken down.

**Comment by stuffyAI** [comment]
Well why didn't you just use the template, chance for the suggestion to be read by the developer just dropped needlessly because you didn't copy-paste a few lines.
The header doesn't help much either, you have access to the trello (which is linked in the template) so you can check yourself if it is planned.

Remember, you are just a user wanting a chance implemented by a sole developer and a few random supporters, you should at least try to show some consideration and reduce the workload for them as much as possible.

The suggestion itself is good, there are already projectile logic modifiers like drag implemented so you could even manipulate speed, disabling turrets sadly doesn't make sense since we could barely assume that the sprayer towers (scorch, wave, tsunami) use atmospheric gas to propel the fluids.

**Comment by Kyllingene** [comment]
The template they used.

***Has no checkboxes.***

**Comment by itcannotbe** [comment]
> The template they used.
> 
> _**Has no checkboxes.**_

Though feature request template is more appropriate in this regard.

**Comment by Kyllingene** [comment]
They may have had the thought process of "it modifies range, thus it is a sort of balance."

**Comment by itcannotbe** [comment]
It's not even implemented yet, so feature request.

**Comment by Kyllingene** [comment]
I know, I was just theorizing about their thought process.
