### ISSUE TITLE
Better toturial

### ISSUE THREAD

**Issue by userlol2** [Anuken/Mindustry-Suggestions#2173]
**Describe what you would like changed, and why.**
As the title, mindustry is kinda complicated,so it need a better toturial

**Describe the changes you want to propose. Include possible alternatives.**
Use pictures or videos in toturial instead of only words

**Comment by itcannotbe** [comment]
What is this toturial you speak of?

**Comment by joshuaptfan** [comment]
While I agree the tutorial could be improved, pictures/videos ain't happening. This game is ~100 MB, and videos would inflate that download size by several hundred MB.

Besides, pictures/videos aren't interactive, and it's bad when games use them as tutorials. No one's going to pay attention while you pause the game and force them to watch a video or read a powerpoint presentation, they'd rather be playing the game.

**Comment by Lele567** [comment]
I get their point
Overlays showing example buildings (kinda like when a building got destroyed) would be good

**Comment by Humanoid-X** [comment]
Then that's their own problem i think

**Comment by LeoSko** [comment]
I'm not saying this is the best one, but I made small interactive tutorial on Ranked PvP server - it will start automatically when you visit it for the first time and you can complete it without actually going for PvP match.

I made this tutorial because of absense of such inside the game - nothing gives you best practices or even ideas of advancements after you learn to place blocks.

Built-in tutorial is horrible and doesn't explain even simplest things - What is *block*? What does it mean *to route* conveyors? What does it mean *to place* block? Etc. **It needs to be improved** if we want a larger player base with lower barrier to entry.
I made an experiment and gave the game to someone who never played such strategic games - it took him 50 (fifty!) minutes to complete tutorial with hussle and struggling of figuring out what needs to be done.
