### ISSUE TITLE
Alright it won't be worse this time

### ISSUE THREAD

**Issue by 02Oxygen** [Anuken/Mindustry-Suggestions#2179]
**Describe what you would like changed, and why.**
Bring back the old water extractor when the water extractor can supports 2 steam and 2 pneumatic drills since you gave us metaglass for wex

**Describe the changes you want to propose. Include possible alternatives.**
well its because metaglass will run out early in the round since we need 1 steam gen and 1 wex

**Comment by DeltaNedas** [comment]
thats a fair point actually
making wexts annoying for steam was a poor version of what using metaglass accomplishes

**Comment by Fipico2** [comment]
make water extractor exctract sand when not placed in water

**Comment by Kyllingene** [comment]
...but the whole point is that the wex gets water *from* the ground, regardless of water tiles...

**Comment by itcannotbe** [comment]
I don't really get it why people are asking to buff water extractors when metaglass is just part of the building recipe, not used as an input material.

**Comment by XEN0PHIL** [comment]
> ...but the whole point is that the wex gets water _from_ the ground, regardless of water tiles...

Water layer under the ground is not the same everywhere. Tiles show the state of the area, including the one beneath. If the surface is a desert then there's also not much water below

**Comment by the-red-soul** [comment]
Water extractor needed the nerf it got when v6 was released. Many many Mindustry veterans agree (including myself) that it needs to be nerfed more because it is still just too versatile. Having them produce less and have less tiles they are efficient on is a great start, them requiring glass is an even better solution because it forces conduits to be available at the same time to get water, but it is still used a lot lot more than conduits and pumps ever are. Same with oil extractor.

**Comment by itcannotbe** [comment]
To be extremely fucking honest. The only thing metaglass does to water extractors is to delay it's availability.

If you want to actually nerf if, you have to restrict the extraction of water since it's flexibility hasn't actually changed.

Tile affinities (and by extension negative affinities) are a good start.

And no, buffing pumps to try to increase their usage will never work.

**Comment by the-kido** [comment]
> "The only thing metaglass does to water extractors is to delay it's availability."
That is exactly what it did, nothing else.

**Comment by Kyllingene** [comment]
> Water layer under the ground is not the same everywhere. Tiles show the state of the area, including the one beneath. If the surface is a desert then there's also not much water below

So are you suggesting that the water extractor be made useless in its designed use case? I can't imagine you are.

> Tile affinities (and by extension negative affinities) are a good start.

The problem with that is that maps themed towards sand-y blocks thus get their wex's nerfed, despite those being the designed use case (waterless maps), and more water-themed maps get them buffed (exactly the opposite of what we want). If you meant buff sand and nerf grass, for example, the problem then is 1: you can still use it in a lot of dumb places and 2: it's a convoluted system for newbies to learn

**Comment by kiVts** [comment]
Make dirty water - that needs to be passed through filter or if not its a usual water but ddeals damage to towers
