### ISSUE TITLE
Does the game engine allow to adjust gamma/brightness?

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry-Suggestions#2183]
**Describe what you would like changed, and why.**

On my Monitor, I can see all resources in the dark area of the map - just not coal and dark sand.
If that happens, one has to scan the map with the mouse and see if it is somewhere suddenly over a searched resource :-(

**Describe the changes you want to propose. Include possible alternatives.**

Maybe, the game engine allows adjusting Gamma / Brightness is a Game-Config-File.
Otherwise, it would be great if it could be adjusted in the Game-Settings user interface :-) (which is pretty common for games)

**Comment by itcannotbe** [comment]
Stupid question here. If your monitor doesn't allow you to see coal, why don't you change your monitor's setting or better yet acquire a better monitor.

On my ancient phone, bought 10 years ago or my laptop bought 12 years ago I can see coal and other dark colored resource.

**Comment by Axzye** [comment]
Well, maybe you don't want to change the visuals for your entire monitor, which is exactly why there is a gamma setting in most games in the first place.
And just because you can see fine doesn't mean nobody needs this feature. Mindustry also tends to have lower contrast and readability than other games so adjusting gamma for mindustry specifically would be useful
(also liking your own suggestion is really pathetic)
