### ISSUE TITLE
natural distasters

### ISSUE THREAD

**Issue by RouterChainsSuckk** [Anuken/Mindustry-Suggestions#2188]
**Describe what you would like changed, and why.**

id like there to be a thing in the campaign (for player maps its an option) to have stuff like tornados and hurricane
**Describe the changes you want to propose. Include possible alternatives.**
for the tornados basically they will spawn and do dmg to buildings (they can destroy conveyors so that way armored conveyors have more of a use) hurricanes would just do dmg to buildings and stuff. you get my idea. Basically that would make campign harder and make stuff more interesting

**Comment by Kyllingene** [comment]
So just things that come in and do random damage all over with no way to stop it. How about no?

**Comment by MauritanianMapping** [comment]
That sounds like a fantastic way to annoy the hell out of some players and possibly make a losing situation worse if a player simply gets unlucky, and would also require much heavier use of menders as so buildings don't slowly lose all of their HP without the player realizing it. Nothing random in Mindustry is meant to cause uncontrollable damage to your play, nor should it ever. Either the player is annoyed by sometimes how often the conveyors would have to be repaired when they don't have armored conveyors yet (mind you because armors can't take feed from the side other conveyors are still required) some players might be dry of resources while building something and have to go back and fix the conveyors while the constructing buildings could be within the line of fire of enemy units. Adding RNG for the sake of making something more difficult is rarely a good idea for this sort of game.

**Comment by itcannotbe** [comment]
> some players might be dry of resources while building something and have to go back and fix the conveyors while the constructing buildings could be within the line of fire of enemy units.

So multiplayer is a natural disasters. Interesting...

**Comment by RouterChainsSuckk** [comment]
> So just things that come in and do random damage all over with no way to stop it. How about no?

maybe having force projectors block all damage, it will make them more usefull

**Comment by Humanoid-X** [comment]
This should be tagged feature request instead.

**Comment by SpaceSceptralReignPlayz** [comment]
pretty hard to code + ruins the gameplay causing lots of people mad

**Comment by nichrosia** [comment]
Also: https://trello.com/c/ap4Dx5e5/30-random-environmental-events

**Comment by MauritanianMapping** [comment]
> > So just things that come in and do random damage all over with no way to stop it. How about no?
> 
> maybe having force projectors block all damage, it will make them more usefull

Adding something and then giving it a single counter that completely negates it sounds like a pointless feature to add just for the sake of promoting two buildings, I think Anuke doesn't waste time on features like that, especially uncontrolled random ones

**Comment by Kyllingene** [comment]
> maybe having force projectors block all damage, it will make them more usefull

Ah yes, because placing 3x3, power-hungry, not early-game structures all over your map is definitely a good way to counter random damage.

**Comment by genNAowl** [comment]
Players couldn't even deal with the pushing by the sandstorms in the alpha versions of 6.0; How do you expect them to deal with this?

**Comment by Bohaska** [comment]
>Mindustry is always an unrealistic game. Drills and conveyors run without power. You can infinitely respawn without material loss. You can actually drill for water on magma. Slag pools never solidify or cool down.

**Comment by wellsilver** [comment]
Random things that can destroy your base? nah, ill pass

**Comment by Kyllingene** [comment]
![image](https://user-images.githubusercontent.com/69094702/112734662-6ca00680-8f04-11eb-99bc-3f13be8a7c49.png)

**Comment by genNAowl** [comment]
^ Dark theme. Nice

**Comment by Kyllingene** [comment]
The only good theme.
