### ISSUE TITLE
drone factorys

### ISSUE THREAD

**Issue by DeCEll-1** [Anuken/Mindustry-Suggestions#2223]
**Describe the content or mechanics you are proposing.**
drone factorys
its lets you make your own drone its a good idea for relase 127

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
more campain and multiplayer experience

[mindustry - drone factorys.txt](https://github.com/Anuken/Mindustry-Suggestions/files/6230873/mindustry.-.drone.factorys.txt)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MauritanianMapping** [comment]
???????????????

**Comment by PlanetOrca** [comment]
This exists already. Also, it will probably help you to follow the regulations related to COPPA or else the boogeyman will come out of your closet while you're sleeping

**Comment by itcannotbe** [comment]
For those lazy enough not to read the txt file.

**Comment by itcannotbe** [comment]
-DeCell-
DRONES
1)drone maker
2)how to make a drone
3)containers and vaults
4)items
5)weapons
6)liquids
7)factorys
8)energy
9)special drone modules
10)upgradeing units
11)ai modules


1) DRONE MAKER
its a block added at factory category
if u click factory u open a menu
at this menu u can make drones u can use a drone chematic at there, these cheamtics are gonna be opened by chematic menu keybind (not normal chematics are gonna opened this is another chematic menu i am gonna talk abouth them at 7)
every block u place here is half of normal block price and u should place every block sources to drone maker
also u can chose type of drone (ground,flying,spider or ship)


2)HOW TO M AKE A DRONE
at here u can place every block menders to overdrivers everything surely they range are gona be half 
this menu is like map makeing menu 
factory chematics are gonna be at top right and core database too
at left capabilyties of drone (how much hp is gonna have or how much things it can carry etc.)


3)CONTAİNERS AND VAULTS
containers and vaulds is means how much item that drone can carry 
1 container is means 40 item (1 containers is just can have 1 item at once)
1 vault is means 40 ite (the diffrence is vaults can have 40 of every item)
if u have 2 containers or vaults because u will use them ass ammo and resource for factorys for solve dat just make em sortable like if u have 2 containers and u need sand and coal make 1 sand and make 1 coal its wont accept other items 
u need unloaders surely


4)İTEMS
when u have a item in your container/vault and not use it at in the drone it will be normal
if u use item on you (takeing item with unloaders) its will split to 2 (like 1 titanium means 2 titanium at drone) and when placeing them after use at factorys u need place 2 splited items for 1 item
u need a item taker for take items


5)WEAPONS
all weapons are gonna have half of its range and damage and most of em not need ammo (like duo)
and surely u can place unit weapons (they gonna be big because they are for t5 and u shouldnt place that strong weapons to a small drone)
if u not placed a weapon rotator it will shot the way u place


6)LİQUİDS
liquids are used soo many things for thet u gonna use liquid extractor module with that modu u gonna pull liquids and use them (output of liquid is gonna be back of module)


7)FACTORYS
u surely need factorys at game but u can place them at drone too for place factory that u copy on main game is placed with button at top right
u can output them with mass drivers its gonna fire them to another small mass drivers thet u connect at main game


8)ENERGY
energy is can maked at drones and drones gonna use them surely at motors,building modules(etc.)
when u take energy from outside its gonna be split too
u can use surge tower or power nodes to take or give energy (they range too be half)


9)SPECİAL DRONE MODULES
special drone modules are the drone modules that u cant place in main game (like building modules)
building module is let u build things if u place more it will be faster
motor its let you move legs and ship
jet its let you boost or fly if u chose flying type drone
if u place more motors or jets it will be faster but it will use energy or another things too
liquid extractor i talked abouth it soo :/
item taker u need this if u gonna take items if u place more item taker it will have more range


10)UPGRADEİNG UNİTS
u need reconstructer for upgrade its just gonna use normal upgrade things :/


11)Aİ MODULES
for do everything i a drone u should ai (u can make your own with processors)
ground ai its let drone walk 
ship ai it let drone use ship
flying ai its let drone fly
player use ai its let player to control drone
follow ai its follow the nearest player

**Comment by itcannotbe** [comment]
Basically this is called make your own unit.

Not gonna happen. The system is too convuluted to even be considered being developed for the vanilla game, heck even mods can't do this one.

**Comment by PlanetOrca** [comment]
Yeah. Maybe if you have the knowhow, you could make a really nice mod out of this, but never gonna be in the base game. Absolutely never

**Comment by Bohaska** [comment]
> This exists already. Also, it will probably help you to follow the regulations related to COPPA or else the boogeyman will come out of your closet while you're sleeping

tbh there isn't any single way to suggest something to mindustry when your under 13, so sorry kid

**Comment by PlanetOrca** [comment]
Look. I don't know if you're young or if you have a hard time with English, but if you have a hard time with English, then google translate will do a 10x better job than whatever weird translated you're using. If you're a kid though... you have absolutely _no_ business being here. I sent this to someone who specializes in dealing with those who have a hard time with English, even she couldn't figure out what half this meant

**Comment by Bohaska** [comment]
"DRONE MAKER
A menu would be opened when you click the factory thing?
At this menu u can make drones (I'm assuming its like attaching parts and weapons on the unit base). You can use a drone schematic there. These scheamtics can be opened by a different schematic menu keybind 
You can choose the type of drone and attach parts to it.

**Comment by Bohaska** [comment]
also theres no such thing as ship AI. ships and ground and air units share the same AI

**Comment by Bohaska** [comment]
i think he didn't use translate for this
