### ISSUE TITLE
delete mindustry

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry-Suggestions#2232]
**Describe what you would like changed, and why.**
it wasnt worth it anyway

**Describe the changes you want to propose. Include possible alternatives.**
delete mindustry

_(this is an april fools joke if you still cant tell)_

**Comment by joshuaptfan** [comment]
This suggestion is not feasible, for the following reason:

Since Mindustry v7 already exists in the future, deleting Mindustry now will create a time paradox, annihilating the space-time continuum. As such, attempting to delete Mindustry may result in being hunted by robotic time-continuity enforcers from the future.

**Comment by the-kido** [comment]
> This suggestion is not feasible, for the following reason:
> 
> Since Mindustry v7 already exists in the future, deleting Mindustry now will create a time paradox, annihilating the space-time continuum. As such, attempting to delete Mindustry may result in being hunted by robotic time-continuity enforcers from the future.

it has big words so i have to belive it!

**Comment by octopuscaat** [comment]
fish

**Comment by Phinner** [comment]
:^)

**Comment by Bohaska** [comment]
> Since Mindustry v7 already exists in the future

Where is your evidence?

**Comment by Humanoid-X** [comment]
Wow........
