### ISSUE TITLE
Cryo tiles

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2240]
**Describe the content or mechanics you are proposing.**
Tiles that you can pump cryo out of. Only placable in map editor. Function just like slag, oil and water

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Add more options for map makers. You can solve cryo needs entirely by these tiles. Some multiplayer maps could use them very well. 
And I can't see why you wouldn't add them...

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] As far I can tell, not in suggestion list. There are just many.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
And this suggestion essentially buffs higher tier reconstructors and higher tier power production.

See the patern? They're higher tier stuff.

**Comment by Yell245** [comment]
> And this suggestion essentially buffs higher tier reconstructors and higher tier power production. See the patern? They're higher tier stuff.

But slag tiles are op too: you can any resource out of them

**Comment by Humanoid-X** [comment]
good

**Comment by Humanoid-X** [comment]
They probably wont buff reconstructors, just make it super rare/nonexistent in campaign. As for multiplayer, everything depends on the map maker. Slag tiles essentially buff separator and disassembler too, imo.

**Comment by itcannotbe** [comment]
> But slag tiles are op too: you can make any resource out of them

> Slag tiles essentially buff separator and disassembler too, imo.

Not really, you would still need scrap to make stuff from a dissambler.
And you can't turn slag into scrap.

**Comment by itcannotbe** [comment]
> They probably wont buff reconstructors, just make it super rare/nonexistent in campaign.

So basically you want to add it in, without really adding it in?
And you're contradicting yourself (They probably wont ... , just make it ...)

**Comment by itcannotbe** [comment]
> But slag tiles are op too: you can make any resource out of them

Also no, making stuff from slag is harder than using a drill on a ore tile.
This suggestion makes it easier to make stupid amounts of cryofluid, not an alternative, harder way to make cryofluid.

**Comment by TranquillyUnpleasant** [comment]
> > But slag tiles are op too: you can make any resource out of them
> 
> Also no, making stuff from slag is harder than using a drill on a ore tile.
> This suggestion makes it easier to make stupid amounts of cryofluid, not an alternative, harder way to make cryofluid.
> 
> Heck the T4 reconstructor would just use at least 2 thermal pumps if this was implemented.

That argument is a bit moot id say, considering barring natural tiles, cryo is actually easier to mass produce than oil with the current methods, needing only titanium and water, while oil needs a specific floor to place extractors and spore pods are rather inefficient without water tiles. Even though oil is supposed to be the 'lower' tier fluid compared to cryo in the resource chain. 

The usability of a certain resource doesnt always reflect how abundant it is, however adding the option for map makers to be able to make a resource abundant isnt a bad thing in my opinion. It just caters to a different playstyle.

And the cryo lakes themselves would work fairly nicely with ice themed maps, just like slag works with lava themed ones.

**Comment by RedstonerKBC** [comment]
> > And this suggestion essentially buffs higher tier reconstructors and higher tier power production. See the patern? They're higher tier stuff.
> 
> But slag tiles are op too: you can make any resource out of them

Yet another "scrap/slag is op" person. If they were op you'd think separators would be the only thing people would ever need yet you don't see anybody using them in normal gameplay.

**Comment by octopuscaat** [comment]
first off, you dont find slag tiles in campaign,(in my experiance) plus, you can only get basic resources from the seperator, and the disassembler needs both scrapp_and_ slag, and requares power. as for cryo tiles, it would be kind of op because thorium reactor requares cryo and thorium and that with a thermal pump, even with _one_ tile, can power way to much considering they give 900 power. the other liquids kind of have assumptions of where they came from, water is just water, oil/tar can be spilled, slag can be result of some accedent, but where does cryofluid fit on? how did it get there? I like the idea, but it should _only_ be in editor.

**Comment by TheNightglow** [comment]
I also dont see any reason why this shouldnt be added to the map editor

for anyone who says its op:
if its editor only why does it matter wether its op or not
its up to the map creator to make their custom map blanced (or not balanced)

**Comment by PickAPlayerNameFirst** [comment]
Well yes, I'm just going to say this but, check this comment from #2239.

**Comment by PickAPlayerNameFirst** [comment]
"I don't think this is necessary (yet. If v7 adds more things that are cryo-hungry then maybe.). The only reason why T2 graphite and silicon makers exist is because those are used in almost everything. Cryofluid is only used for cooling weapons (even then it's optional) and for units. I know the reconstructors drink it like a teenager addicted to soda but you can easily build lots of T1 cryos and store them in tons of tanks. It's not as easy to build enough T1 silicon and graphite makers to compensate for all of the demand." 
It would be a bit of a stretch,  but we shouldn't add tiles as long as cryofluid becomes TOTALLY useful (eg. making new items, etc.) but if thats the thing,  for units only, lets just wait for v7 to come as they probably add cryo tiles in campaign.

**Comment by Bohaska** [comment]
maybe ONLY add it in the map editor

**Comment by Humanoid-X** [comment]
Okay, maybe it's really OP, I dunno? :shruggie:

**Comment by Humanoid-X** [comment]
Campaign don't have slag tiles afaik...

**Comment by TranquillyUnpleasant** [comment]
> Well yes, I'm just going to say this but, check this comment from #2239.

Adding a higher level cryo factory is not particularly necessary, you can actually stack the current factory fairly effectively to produce a lot more cryo than a t5 factory needs with only two thermal pumps of water, its all about efficient design.

A map tile that provides cryo is entirely different. It isnt a resource that is generally going to be available to you everywhere, its a rare and powerful resource. If a map were to spam it all over the place then thats how the map is structured, it doesnt ruin the balance of any other game played anywhere else.

**Comment by itcannotbe** [comment]
It does ruin game balance by essentially letting you run stupid amounts of T3 and T4 reconstructors and other building using cryofluid (including stupid amounts of turrets) without even doing the hassle of making cryofluid.

**Comment by PickAPlayerNameFirst** [comment]
> > Well yes, I'm just going to say this but, check this comment from #2239.
> 
> Adding a higher level cryo factory is not particularly necessary, you can actually stack the current factory fairly effectively to produce a lot more cryo than a t5 factory needs with only two thermal pumps of water, its all about efficient design.
> 
> A map tile that provides cryo is entirely different. It isnt a resource that is generally going to be available to you everywhere, its a rare and powerful resource. If a map were to spam it all over the place then thats how the map is structured, it doesnt ruin the balance of any other game played anywhere else.

Hmmm, we can implement it, but **The number should be limited to 5 tiles... **

I agree with the OP-ness of the Cryo Tile.

**Comment by TheNightglow** [comment]
> Hmmm, we can implement it, but **The number should be limited to 5 tiles...**
> 
> I agree with the OP-ness of the Cryo Tile.

I dont get it, why do you care how many cryo tiles someone places in their own custom map in the map editor?
wether something is OP or not hardly matters in custom maps, since its up to the map creator to balance them

and even if something is really strong, the map might be balanced in other ways (like giving the player plentyfull resources against powerfull enemies, or restricting other resouces and give plenty of something you usually dont have at all (like a map with no titan, no slag, no scrap but giant cryo fluid lakes))

its up to the map creator to add challenge to their map, there is no point in restricting how much of a tile map creators are allowed to place in their own map

> It does ruin game balance by essentially letting you run stupid amounts of T3 and T4 reconstructors and other building using cryofluid (including stupid amounts of turrets) without even doing the hassle of making cryofluid.

nobody in this thread ever said that this should be implemented in the campaign, so your entire point here is meaningless
the map creator decides how to balance their map, it cant ruin the game balance because the balance is not up to the tools but the person who uses them

if you dont like custom maps with cryo fluid lakes, you dont have to download them from the workshop...

i m really baffled by most of the comments in this thread, it appears like almost noone of you has read the suggestion properly, or thought for a second about what you are writing^^

**because with the same arguments found here, you could say that _item sources_ and _power sources_ should be removed from _sandbox_, because they are op...**

**Comment by PickAPlayerNameFirst** [comment]
Its completely out of the campaign. And only available to map editor. But you'll see, many people will just gonna rely on the tile, and not on the mixer. Still an idea that can change the nature of the mixers.

**Comment by TranquillyUnpleasant** [comment]
> It does ruin game balance by essentially letting you run stupid amounts of T3 and T4 reconstructors and other building using cryofluid (including stupid amounts of turrets) without even doing the hassle of making cryofluid.

Again, ruins the balance *how*? If the tile is not present on the map, or is relatively rare, you have to make the cryo. If the tile is  available then you can use it, much like how oil works at the moment.

Not to mention cryo isnt the only bottleneck for tier 3 and 4 reconstructors.

Also, this is a tangent, but if this were to be added, variable pumping speeds and pumping levels for liquids would be interesting.

**Comment by 1ARC1** [comment]
mods already add this sorta content, I know chaos arranity adds a sandbox cryo only tile

**Comment by TranquillyUnpleasant** [comment]
> mods already add this sorta content, I know chaos arranity adds a sandbox only cryo tile

Mods add a lot of things, however this suggestions repository is about the base game, not mods.

**Comment by 1ARC1** [comment]
> > mods already add this sorta content, I know chaos arranity adds a sandbox only cryo tile
> 
> Mods add a lot of things, however this suggestions repository is about the base game, not mods.

yes, but you shouldn't suggest content that mods can easily add into the game without a unique new purpose or function.
cryo tile is one of them.

**Comment by TranquillyUnpleasant** [comment]
> > > mods already add this sorta content, I know chaos arranity adds a sandbox only cryo tile
> > 
> > 
> > Mods add a lot of things, however this suggestions repository is about the base game, not mods.
> 
> yes, but you shouldn't suggest content that mods can easily add into the game without a unique new purpose or function.
> cryo tile is one of them.

That makes no logical sense. If something fits in with the game content wise then it shouldn't be rejected on the basis of "a mod could do it". Most people don't play modded mindustry, and adding features to the game itself isn't reliant on what mods can or cannot use.

**Comment by Kyllingene** [comment]
> That makes no logical sense. If something fits in with the game content wise then it shouldn't be rejected on the basis of "a mod could do it". Most people don't play modded mindustry, and adding features to the game itself isn't reliant on what mods can or cannot use.

Agreed, with a few exceptions. One is if it would take the developer a lot of time and effort to implement. Another is if it would break other systems that would have to be fixed. However, you make one key assumption: that this fits in with the game. Without commenting on whether or not that is true, the amount of comments on this thread indicates that enough people disagree to make it a controversy. So, if a mod can easily implement it (you have a Github account, if the original link is too weird for people to be expected to download, make your own), then why is it so necessary for this to be implemented? This would have fairly niche use cases, and would make several supporters of the game quite unhappy. So, in the end, is it worth it?
