### ISSUE TITLE
Drone swarm ability

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2266]
**Describe the content or mechanics you are proposing.**

In build 63, dagger mech could release a few mini-flares ti help in battle. Cant see why not add it here. Some units wont have it, course, but some will, I think some dagger tree mechs could use it.

This ability is only triggerable when player controls it, for balance.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Low level daggers arent much of an use. And drone swarm is a really, really fun feature.

**Alternative**

On landing, cores spawn a few units. This happens only if the given unit is researched. At launch, you have a menu at which you can select units, which are bought for normal cost.
Cores have different capacities:
Shard - 3 cargo units
Foundation - 5 units
Nucleus - 8 units.
Max tier you can carry is tier 3.

**Alternative 2**

Cores make a few drones upon landing.
Shard - 2 Monos
Foundation - 2 Monos, 1 Poly
Nucleus - 3 Monos, 1 Mega

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Bohaska** [comment]
I feel like this isn't a good suggestion, but I don't know why...

**Comment by PickAPlayerNameFirst** [comment]
This is a suggestion from discord, still I oppose from that idea, a T1 dagger?  Has a t2 function?

**Comment by Noob17** [comment]
The _alternative_ idea is very interesting, though on practice it may be a little broken or overpowered. You explained that depending on your core you can spawn a certain amount T1-T3's of any class (Naval might be a problem...) with the cost being added to your loadout. Considering how loadout is not universal, (As it once was in V4,) and as long as you have a sector that is extremely stocked, you can spawn a few Pulsars, for example, for a cost that will be easily replenished in a few minutes. 

Or even better, a few Mega that will extremely help you speed up your building, instead of getting the Multiplicative Reconstructor as you were meant to.

This is even stronger for certain **Enemy Base** sectors, as you can get a few horizons, produce Blast Compound, and stock the ships with explosives, then suicide your horizons. Even worse, you can get 8 Zeniths **EARLY GAME** if you have a Nucleus base with a certain amount of loadout materials, which makes Medium and Hard enemy bases look like jokes.

Anyway however, this idea was certainly a good one that rewards players who focus on high production, but even then, you cannot deny the fact even a basic sector can launch a few T3's without the hassle of needing Reconstructors.

**Comment by BorisA11** [comment]
@Noob17 
Cost is higher when you send the like that. 5 times higher. You cant launch 8 Zeniths due to payload capacity of the core.

**Comment by Noob17** [comment]
Alright. you should have included cost multipliers in the suggestion.

**Comment by Noob17** [comment]
(Even though it literally states "Normal Cost")
