### ISSUE TITLE
New Blocks! Thayt will make mindustry cooler

### ISSUE THREAD

**Issue by HJCDstudios** [Anuken/Mindustry-Suggestions#2278]

**Comment by itcannotbe** [comment]
Furthermore, youu forgot this.

[X] I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.

**Comment by DeltaNedas** [comment]
theres no reason to read a string from a keyboard if there are no string operations.
install deltanedas/anuke-logic which adds both.

**Comment by Kyllingene** [comment]
Shameless self promotion is cool and all, but isn't it illegal to name it anuke-logic if, in reality, it is deltanedas-logic?

**Comment by OnyxFinger** [comment]
Deltaneda/anuke-logic is probalby not multiplayer compatible (didn't test), and using mods is just not a way to say "hey this can NOT be added because whatever does whatever in whatever mod already".
The keyboard idea looks like could be cool for logic, like if you have a thing to maybe use a certain unit for something, you would normally have to use either one unit and you need to change the code in it, which not everyone wants to do bc some don't really know much about logic, or to use switches each for one unit (which takes a lot of space), if you could read a keyboard to use the unit that is written in it, it would be dope and space-efficient

**Comment by Kyllingene** [comment]
Well, if space efficiency is a good reason to implement a logic-related thing, then what about loops? Inline math? Why is the print system funky then? Because mlog is supposed to be as simple and as similar to machine code as possible. Adding extraneous, unnecessary things are, well, unnecessary. And for another thing, remember how annoying accidentally drilling a spot was? Imagine being a mobile player in the middle of an enemy attack, and you accidentally press the keyboard block, blocking half your screen and taking over your control. No thank you.

**Comment by HJCDstudios** [comment]
Please read everything carefully
I also said that it can be a message that can be read

**Comment by itcannotbe** [comment]
> Message block: What am I even to you?
> 
> Also what the hell even is a keyboard? Don't you already have one?
> Plus the use case is ...........................
> 
> Furthermore, you forgot this.
> 
>     * [x]  I am incapable of reading, comprehending, and completely filling out the template, but capable of removing it's entirety.

Please read everything carefully

**Comment by HJCDstudios** [comment]
What i meant is if you do not want the 1x1 keyboard block  it can just be
the 1x1 message block

For ex:
you can use the sensor to read text in the message block or keyboard block

**Comment by Kyllingene** [comment]
> What i meant is if you do not want the 1x1 keyboard block  it can just be
the 1x1 message block

So if we already have it, why try to implement it again?

> you can use the sensor to read text in the message block or keyboard block

That has been shot down by the community several times. See #1976 and #666. Note that on #666, DeltaNedas, an involved contributor to Mindustry, was the first to decline the idea.
