### ISSUE TITLE
Modified belt

### ISSUE THREAD

**Issue by MaltairDelsaris** [Anuken/Mindustry-Suggestions#2282]
I think there might be room in the game for an armored belt variant for earlier in the game.  It can be quite tricky in the early game to build in tight confines, and armored conveyors are treated as a T4 conveyor, thus completely out of reach for much of the progression.

Perhaps a normal belt variant that requires lead, and is basically a low tier armored belt?

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
The armored conveyor does more than being tougher.

**Comment by itcannotbe** [comment]
![Screenshot_20210410_121011_io anuke mindustry](https://user-images.githubusercontent.com/45280919/114257928-c40aa000-99f5-11eb-83da-669ce41b6847.jpg)
![Screenshot_20210410_121006_io anuke mindustry](https://user-images.githubusercontent.com/45280919/114257942-d389e900-99f5-11eb-8930-60a71be66bed.jpg)
![Screenshot_20210410_120959_io anuke mindustry](https://user-images.githubusercontent.com/45280919/114257944-d5ec4300-99f5-11eb-8e1e-3b74f348f675.jpg)
![Screenshot_20210410_120943_io anuke mindustry](https://user-images.githubusercontent.com/45280919/114257930-c66cfa00-99f5-11eb-85bc-e5c390dc0b40.jpg)

**Comment by Humanoid-X** [comment]
No.

**Comment by Kyllingene** [comment]
> The armored conveyor does more than being tougher.
And also armored conveyors are as fast as titanium conveyors.

If you bothered to read the post, you would realize they wanted a slower, lower-health conveyor whose only real use is to avoid side inputs. So, explain to me why that is so uncompromisabley terrible?

**Comment by itcannotbe** [comment]
There are multiple ways that exist in the game for a conveyor line not be mixed with other lines or inputs, all you need to use more than 1% of something located in your cranial cavity.

**Comment by Kyllingene** [comment]
In every scenario? I would say not. For example, what possible solution is there for a snaking path between blocks outputting items? Not a bridge (or phase) conveyor, because they would pick up items at the bends; a mass driver is too big; what would you do?

**Comment by itcannotbe** [comment]
There are certain solution for certain situations. All you need is to think through it.

**Comment by Kyllingene** [comment]
And can you think of a possible fix for that? I have had that exact scenario, and the only reason it was ever resolved was because I got attacked and lost a large chunk of my base. Note that that was a very costly thing, and doing it on purpose would have been a terrible idea.

**Comment by stuffyAI** [comment]
Armored conveyors are further down the progression for a reason, let's take for example a map you play from copper to surge in survival, early on you don't have nearly as much need for tight transport of resources,
and even then, you can abuse junctions in many scenarios to transport something right by an omnidirectional out-putter, which really only does not work if you specifically require a conveyor bend adjacent to it, at which point using certain sorter configurations bypass that as well.

Either you can use your smarts to overcome the early struggle with low-tier transport blocks, or you will have to limit your design/output until you reach thorium production, at which point most people rebuild almost everything anew anyway as they upgrade their factory.

**Comment by MaltairDelsaris** [comment]
OK, now, this is a somewhat reasonable and thought out justification for not having it...
But it's one I FUNDAMENTALLY disagree with.

Just because you CAN solve the issue with complicated workarounds, doesn't mean you should be forced to.  To me, a belt that doesn't automerge with outputs shouldn't be some high tier unlockable, it's a common-sense quality of life feature.  I want this for the same reason that all but one sorting and routing block is available from 10 minutes in - it just doesn't make sense to me NOT to have it.

**Comment by Kyllingene** [comment]
> and even then, you can abuse junctions in many scenarios to transport something right by an omnidirectional out-putter

I have always and will always hate solutions that waste items, no matter how few. It honesty aggravates me to no end (possibly unjustifiably) to have to waste items just to send some items somewhere safely.

**Comment by stuffyAI** [comment]
> Just because you CAN solve the issue with complicated workarounds, doesn't mean you should be forced to. To me, a belt that doesn't automerge with outputs shouldn't be some high tier unlockable, it's a common-sense quality of life feature. I want this for the same reason that all but one sorting and routing block (aside from a couple high-tech goodies) is available from 10 minutes in - it just doesn't make sense to me NOT to have it.

Yes.... I get access to better buildings as I process trough the game...... that sounds fine to me?
I already have to use inefficiencies early on to compensate for lack of higher tier buildings, why not have it the same with armored conveyors?

Conversely, aren't we mighty lucky to get all but this one example (and mass drivers and phase stuff, latter of whose is only speed) as early as we can mine lead? To add to that, we really are missing that one block type that is never seen in any good, non-meme schematic?
Most of the time it really only supplements visibility when not using junctions, which barely upholds as you later will do phase conveyor intersecting anyway, dropping that use as well.



> I have always and will always hate solutions that waste items, no matter how few. It honesty aggravates me to no end (possibly unjustifiably) to have to waste items just to send some items somewhere safely.

As mentioned, constantly wasting resources when using lower-tier miners or production buildings gets replaced later equally as much as that **one time 5 resource per junction** investment you do when substituting an armored conveyor with a junction, or even better, that one time 0 resource per sorter 'waste' you get when it's applicable; Progression.

**Comment by Kyllingene** [comment]
> 5 resource per junction

Math much? No matter how much a junction could hold per side, both sides would not add up to 5. And ever since sorter sneks were murdered in their sleep, they became unusable for that. So, explain how one could make a sorter-based armored conveyor workaround?

**Comment by stuffyAI** [comment]
> No matter how much a junction could hold per side, both sides would not add up to 5.

Pardon me, one side holds 12 items.
Alas, let's go for a extreme scenario: 10 belts adjacent, ALL fed by some multi-side out-putter like phase or bridge conveyor;
You lose 12 resource per junction, double that if somehow you feed right into the middle of the belt.
Assuming you don't waste conveyors to append to the start of the line for no reason, you lose 660 total resources, at a point in the game where you have 12 belts of them, one time, and for some reason you don't use better design for core input.

Let's say that one does not utilize such horrendous buildings methods in practice and really only uses junction substitution for armored conveyors next to producer buildings, you at worst get 6x12 or 8x12 item loss for surge or disassemblers, at which point you have access to normal armored conveyors or simply don't care about such little amount.


> And ever since sorter sneks were murdered in their sleep, they became unusable for that. So, explain how one could make a sorter-based armored conveyor workaround?

You'd use sorters as feeder replacements if your input is strictly adjacent to a conveyor which absolutely requires 2 input sides but not the third, no need for sneks here? Please show me schematics, which somehow really need armored conveyors despite not using thorium+ as base.

**Comment by Kyllingene** [comment]
I shall yield that high-skill players have little to no use case for this block. Clever sorter-junction setups can conquer most scenarios, however turning a tight corner with a sorter without bleeding still seems impossible to me.

But, I think the largest problem here is that the discussion up to here is targeting high-skill players. Most of the anti-arguments are based on one having more knowledge. However, many (if not most) players are much worse. This conveyor would fill that place that many people need, because not everyone is trying to become an expert. As there are scenarios in which the only workarounds require a decent knowledge of higher Mindustry concepts, of which many players know little to none, this mildly wasteful conveyor is useless for skillful players. This game has always been optimized for getting good, as any good game should be, but few games, and I believe this excludes Mindustry, disincentivize low-level players from the game. Not that there is no place for such games, but as there are several things left in for new players, young players, and/or players with an interest in, but little aptitude for, strategy games.

If my reasoning is flawed, I apologize and beseech an explanation of how. If my understanding of Mindustry is flawed, again, I apologize and request a correction. However, this is my current standing.

**Comment by itcannotbe** [comment]
I would just like to point out that challenge maps aren't even made for new players.

**Comment by Kyllingene** [comment]
Are challenge maps the only maps on which these are useful? No, of course not!

**Comment by itcannotbe** [comment]
Are challenge maps, the maps that would benefit the most out of this?

If the challenge is right, yes.

**Comment by Kyllingene** [comment]
*If* the challenge is right, then yes. However, as I said, the majority of this blocks use would be for beginners.

**Comment by itcannotbe** [comment]
Um. Beginners don't even build in tight spaces, nor smush their buildings in a tiny space.

**Comment by Kyllingene** [comment]
But they do make horribly inefficient and overly bulky factory designs, which means that they run into this problem regardless of map size (scaling inversely, of course, with map size).

**Comment by itcannotbe** [comment]
Nope they don't. At least that's my experience playing with beginners.

Most beginners even skip small maps.

**Comment by itcannotbe** [comment]
Also you can't be inefficient in Mindustry anymore, aside from wasting tile space. Which is irrelevant if you don't even have the inputs to justify another factory.

**Comment by Kyllingene** [comment]
> Also you can't be inefficient in Mindustry anymore

It would take an entire article to list all the ways in which that statement is wrong.

> Nope they don't. At least that's my experience playing with beginners.
>
> Most beginners even skip small maps.

How many beginners have you played with on their own terms? Chances are, the beginners you encounter are joining larger servers, which (mostly) only beginners relatively confident in their skills would do. Even if it is a "beginner" server, joining a server is still a decently large step to make for many. And as for skipping small maps, that is either a result of overconfidence / previous experience, or it is to avoid the difficulty of a small space.

**Comment by itcannotbe** [comment]
Trust me, most beginners or noobs joins server without even playing a single minute of single player, may it be campaign or custom games.

**Comment by Kyllingene** [comment]
And why should I take your word for it?

**Comment by itcannotbe** [comment]
You don't need to, freely join multiplayer servers for a first hand experience.

**Comment by Kyllingene** [comment]
Except for the fact that that falls into the exact trap that I mentioned? How on earth do you know that sample is representative? How do you know that those players have no previous experience?

**Comment by itcannotbe** [comment]
Case in point.

Nydus server ran a screening system before you can enter the actual server hosting maps with a server plugins and a map that requires you to make silicon.

Many people can't make silicon.

**Comment by Kyllingene** [comment]
Many as in tens, hundreds, thousands? What is the percentage?

**Comment by itcannotbe** [comment]
We don't even know how large is the max concurrent players across all the servers.

Why would we base it on statistics when a large number of active people on social platforms can concur with the observations.

**Comment by Kyllingene** [comment]
> We don't even know how large is the max concurrent players across all the servers.

Thanks for the straw man. I clearly meant the percentage of players *on Nydus*. And if you have other proof, please actually show it instead of just saying that you have it.

**Comment by itcannotbe** [comment]
Um. They never made it into the server but if you stayed on the screening map, you'll encounter an excess of 100 players every hour i think. Disconnecting within 10-30 seconds

**Comment by MaltairDelsaris** [comment]
OK, this is getting out of hand.  Let me lay this out clearly.

I am a newer player.
I tend to fill any given map with stuff, so space just runs out eventually.
I can make any and every resource, so I'm not stupid.

I REPEATEDLY would have found use for a low tier input-refusing belt.  Sometimes, you only have a very tight space to work with, and while I have a solid grasp on basics, doing funky things with junctions and sorters and gates is a bit of a headache for me.  I CAN do it, but it's not FUN.

All of the people just crying "no no no" keep acting like a basic tool like this is some kind of insult or travesty, but what would it actually hurt?  The low level players get a tool to help them build in tight quarters, and high level players get a new tool in their box for early game.

EVERYBODY WINS.

**Comment by itcannotbe** [comment]
You're no longer a beginner. Because you have the knowledge of the basics.

**Comment by Kyllingene** [comment]
That is an overly restrictive use of the word "beginner." Even if it is *a* usage, it is most certainly not *the* usage. Would you rather we called them a professional?

**Comment by itcannotbe** [comment]
Intermediate? But not yet skilled.

**Comment by Kyllingene** [comment]
Intermediate must go pretty low if their explanation of themself is accurate (I mean absolutely no insult, I'm not very good myself)

**Comment by stuffyAI** [comment]
> But they do make horribly inefficient and overly bulky factory designs, which means that they run into this problem regardless of map size (scaling inversely, of course, with map size).

Alright but adding a lower tier armored conveyor only helps them in the moment, since they can use such an easy block they won't learn using the other transport blocks early on, which means later they just get mercilessly crushed by complexity requirements as they cannot use blocks that would actually be needed.

When I wanted to have fun I joined a lot of lower-level players still struggling in early campaign, sometimes I wanted to gauche my eyes right out upon seeing the pure heresy of router chains and similar, but never had I  the feeling that those people could use an armored conveyor in any way to improve their gameplan. In my opinion, giving basically all the transport blocks within lead research at such low cost is kind of counterproductive, as they thus will not even bother going into the actual factory building part of Mindustry, being overwhelmed by the sheer amount of options they basically instantly get.
I however don't believe making an armored early variant accessible is any solution to that, as unlike that type I cannot replicate the other transport blocks easily (except for sorter and flowgate counterparts). Furthermore, if the new player actually wants the effect of an armored conveyor, he instead has now an incentive to utilize substitute blocks, making him think and learn about the different options he now has to use.



> All of the people just crying "no no no" keep acting like a basic tool like this is some kind of insult or travesty, but what would it actually hurt?

Just like adding anything to the game, first of all it adds something; it now must be useful or relevant enough to take space in where it will be added.
Second, someone has to actually code it. This is simple and probably a 5 minute task at most, 90% of which are waiting for stuff to load.

Now, again...
At first you have copper drills, which mine at a certain speed.
Later you get pneumatic drills, which mine a bit faster.
For the same amount of space, your pneumatic drill produces more resources.
So we can say, we practically 'saved' some space by upgrading our low-level building to a higher level one, and you deserve it, after all, you worked for it by acquiring better resources and later constructing it.

Why not the same with armored conveyors?
Your workaround takes up a bunch of space, but you get access to armored conveyors, and now can use the fruits of your progression to save some space.
Let's not even consider that very likely you simply could've used a workaround that would've taken a few more keyboard presses, aka you could compensate metaprogression with skill, that is literally the same thing you are doing the entire time:
Build, Mine, (research,) Refine, Upgrade, and then looping again, until you reach the top of what your current tech level allows.

You always get new ways to safe space, as you also get new ways to use it, be it better drills, faster production buildings, drone support, water cooling and, you guessed, using transport blocks.
I don't see any suggestions complaining about the copper drill being slower than the airblast drill, so why can't we just assume the lack of an early game armored conveyor to be a design decision to endorse progression, it seems to be accepted for all other cases as well?

**Comment by Kyllingene** [comment]
> pure heresy of router chains

you have been banished to the spirit realm

> we practically 'saved' some space

This is a very interesting comparison, but frankly a poor one. The upgrade to pneumatic drills should not save space, as you should already have drills there. The improvement is in output, not in space.

> I don't see any suggestions complaining about the copper drill being slower than the airblast drill

Because in that case, there is an obvious and clear level-up. Even from copper to pneumatic, the only difference (besides cost) is that the pneumatic works faster. Between copper / titanium conveyors and armored conveyors, you see that they cost more with only two differences. One is the added health, and the other is the refusal of side inputs. Health causes the extra cost, but the refusal of side inputs originated as a nerf. Thus, from titanium to armored, the only solid buff is health. Between copper and armored, therefore, the only buffs are speed and health, and thus a slower armored conveyor is in order. This can be thought of more as a bridge conveyor - phase conveyor thing than a copper drill - pneumatic drill thing, as the armored conveyor is heavily specialized.

**Comment by stuffyAI** [comment]
> The upgrade to pneumatic drills should not save space

It was more a rhetorical comparison; You technically save space of ore-fields you no longer have to occupy for equal output.
Naturally, in practice you would already have copper drills there in the exact same fields, but I wanted to take the worst example to show that progression is elementary evident in multiple aspects. Graphite to Multi-Press would be more conclusive examples here, a literal safe in space.



> there is an obvious and clear level-up

This doesn't, didn't and never should apply consistently in a game like Mindustry, as seen in history of denied suggestions and pull requests.

There are active attempts to introduce new content to the game with new gimmicks or alike, since Anuken deemed 'To upgrade something just place a better version of it on top' bad game design after V4. And it prevails, you have few examples where this works, most often an upgrade increments complexity, may it be production like silicon or transport with plastanium/phase.
Naturally, you cannot do much more to mining ore, but in all the new elements you have clear differentiations.

So back to early armored conveyors, there is equally no need for them as a lower speed variant of armored ones. Nobody uses, not even suggested above, that they are used for their health stat, but rather their functionality as input bypassers. 
So see that this is simply another one of those 'upgrades', but instead of faster drilling, you get easier building of transport belts or tighter construction if you needed spacious workarounds before.

**Comment by Kyllingene** [comment]
> It was more a rhetorical comparison

One that makes no sense, and thus is not logically usable.

> This doesn't, didn't and never should apply consistently in a game like Mindustry, as seen in history of denied suggestions and pull requests.

You take my words out of context. I was comparing the level-up from copper drill to pneumatic drill to the "level-up" from titanium conveyor to armored conveyor. Not suggesting that everything needs a clear level-up. You may have thought I meant that, since there is a high-tier armored, there should be a low tier. That was not my point.

> Nobody uses, not even suggested above, that they are used for their health stat, but rather their functionality as input bypassers.

> there is equally no need for them

You can't have your cake and eat it too. Would these be useless, or would they be helpful? Pick one.

**Comment by stuffyAI** [comment]
> Would these be useless, or would they be helpful?

Op is suggesting the restricted input to be helpful, what's your question?
It goes more in hand with


> "level-up" from titanium conveyor to armored conveyor

There is no level up, just a different mechanic, as nobody really uses them for their increased health, given that force projectors are a thing at that point.



> One that makes no sense, and thus is not logically usable.

I compare the progression of using better miners to the progression of getting more/better transport block options, what is illogical about that?

**Comment by Kyllingene** [comment]
> Op is suggesting the restricted input to be helpful, what's your question?

I was asking you. You first stated that the point of armored conveyors is the no-side-input, then stated that copper armored conveyors would be useless.

> I compare the progression of using better miners to the progression of getting more/better transport block options, what is illogical about that?

You were using an analogy of space, which makes very little sense when talking about copper drills and pneumatic drills.

> There is no level up, just a different mechanic, as nobody really uses them for their increased health, given that force projectors are a thing at that point.

Again, you take my words out of context. I was saying that they were different, as copper to pneumatic is a clear level-up, but that titanium to armored is not.

**Comment by stuffyAI** [comment]
> You first stated that the point of armored conveyors is the no-side-input, then stated that copper armored conveyors would be useless.

The 'equally no need' for them was specifically was because I mentioned that there should be no clear 'level-ups'....



> You were using an analogy of space, which makes very little sense when talking about copper drills and pneumatic drills.

For the same amount of space, I get more out of it.
If I don't have to use heavy workarounds with transport belts, either because I have experience or armored conveyors, I also get more out of the same amount of space, as I could, for example, put another belt beside it now.
I really can't make it easier than that right?



> Thus, from titanium to armored, the only solid buff is health. Between copper and armored, therefore, the only buffs are speed and health, and thus a slower armored conveyor is in order. This can be thought of more as a bridge conveyor - phase conveyor thing than a copper drill - pneumatic drill thing, as the armored conveyor is heavily specialized.

You first said the only buff for armored conveyors is health, but that's not their use. And you exactly said that a slower armored conveyor is in order, because you compared the buff between titanium and armored to copper and slow armored. That is literally the 'level-up' we don't want from slow armored to fast armored, just this time you went comparing titanium to armored, then copper to armored, and noted that armored is additionally faster.
To elaborate, with your logic we would also have to make bridge conveyors with the range of phase conveyors; and phase conveyors with the range of normal bridge conveyors:
both types would feature an attribute difference, just like copper/titanium conveyor and slow/fast conveyor between each other.

Which doesn't have anything to do with former point anyway, I was still asking why an armored conveyor cannot simply be progression?
