### ISSUE TITLE
Armored copper conveyor

### ISSUE THREAD

**Issue by N4B3R1USNT** [Anuken/Mindustry-Suggestions#2284]
**Describe the content or mechanics you are proposing.**
Basically an armored version of a normal conveyor that would maybe costs 1 copper 1 lead and 1 graphite and health is maybe only 90 to balance it

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
armored conveyors is hard to use because it is expensive and uses plastanium and armored normal conveyors would maybe get more used because its cheap

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slava0135** [comment]
no

**Comment by itcannotbe** [comment]
Basically a duplicate of #2282

**Comment by MrDuck557** [comment]
wall better

**Comment by SMOLKEYS** [comment]
no

reasons:
- too cheap
- same behavior as armored
- just, no

**Comment by Fipico2** [comment]
If it gets the same speed as a copper conveyor that could make it interesting. 
You go for the easy way, you get your speed reduced

**Comment by N4B3R1USNT** [comment]
I forgot to say that it would be as fast as a regular  conveyors :/

**Comment by PickAPlayerNameFirst** [comment]
But its a bad idea, just... download a conveyor mod pack...

Please close this issue. The steps and opinions are already been given.

**Comment by Kyllingene** [comment]
Why does everyone just says that this is a bad idea, with no explanation? Please, explain *why*.

>  no
>
> reasons:

Ok, so let's see what they are:

> too cheap

Then balance the cost.

> same behavior as armored

That is the entire point: to add a conveyor that can be used in tight circumstances where other cheap conveyors (including bridges) are unusable.

> just, no

Circular reasoning much? "It shouldn't be in the game because it shouldn't be in the game"

**Comment by itcannotbe** [comment]
> Why does everyone just says that this is a bad idea, with no explanation? Please, explain _why_.
> 
> > no
> > reasons:
> 
> Ok, so let's see what they are:
> 
> > too cheap
> 
> Then balance the cost.

So balance the cost so that it costs the same as armored? Since every conveyor doesn't exceed 1 item per type.

> 
> > same behavior as armored
> 
> That is the entire point: to add a conveyor that can be used in tight circumstances where other cheap conveyors (including bridges) are unusable.
> 

You do know that once this is added the block would be a solve all solution like what happened to power cubes because of the addition of the coal extractor right?

> > just, no
> 
> Circular reasoning much? "It shouldn't be in the game because it shouldn't be in the game"

Because almost everyone agrees that the behavior should given only to armored because the fact that armored can't get inputs from the side is actually a nerf given to armored, as far as I can remember.

**Comment by Kyllingene** [comment]
A nerf that is critical to many builds! Have you never used armored conveyors for anything but health? I doubt it. And a "solve all solution" with one critical debuff: it is as slow as copper. Seriously, at that point, anyone who would be using this as a "solve all" will already be hurting themselves enough; it is not overpowered. Power cubes were OP because they were self-sustaining power generators. These are just nerfed copper conveyors that are extremely helpful is several situations. Also, what is wrong with 1 silicon, 1 graphite and 1 lead per conveyor? As previously mentioned, they are not actually better than copper conveyors in most situations, but since you seem to think they are a significantly higher cost seems in order. And that "almost everyone" is 5 people, as far as I have seen. Hardly representative of either the majority or the select few.

**Comment by itcannotbe** [comment]
Why not make it slower than copper conveyors then so that people won't spam them over titanium.

**Comment by TheNightglow** [comment]
I d also like an early game conveyor version that cuts off inputs like the armored conveyor

i again dont really get the reasons givin against it here...

its a copper conveyor that doesnt allow all 3 input directions... how can 1 copper 1 lead and 1 graphite be too cheap for that 

same as the cryo tiles for map editor, the only real reasons against an idea like this would be:
- implementation cost exceeds usefullness
or
- clog up game menus (too many items in selection menu)

for me, i dont think that the implementation cost exceeds usefullness... the "alternatives" for an armor conveyors always seemed like hacky work arounds (like dead-end junctions)
having early game lane-barrier conveyors will make much more sense for new players than the hacky work around with junctions...
I keep seeing Steam Threads being opened where new ppl ask how to avoid conveyor mixing at factories and bridges and they never figgure it out by themself that dead-end junctions are the early game solution (because its a really wierd nonsensical solution)

for the second point, i think it will actually clog up the selection menu.... the one for conveyors is already incredibly full...
but I would rather say the building selection window needs to be reworked (sub categories), than to avoid adding new stuff

**Comment by Kyllingene** [comment]
> implementation cost exceeds usefullness

Adding this conveyor would be easier than making a single-turret mod. Seriously, the conveyor type already exists, so you simply make a new conveyor utilizing it, give it a somewhat revised copper conveyor sprite, and throw some stats at it. Easy as that, as far as the source code is concerned.

> for the second point, i think it will actually clog up the selection menu....

Adding one block will not really clog anything up, as there is an unfinished row there as of now. Thus, no more vertical clogging would take place, and the amount of horizontal clogging would be quite minimal.

However, there is a good point there. If no building window rework is coming, then this slot should be allotted to a more worthy idea.

**Comment by Sector171** [comment]
I Wonder from people who said "No" to such ideas, what wrong with them, nothing to say.
So if I need a basic feature, very basic one like a conveyor not accepting input from sides, I should have plastanium and thorium , amazing!!! That's the normal & balanced situation!

**Comment by SMOLKEYS** [comment]
~~oh god, i probably shouldn't have talked here~~

**Comment by SMOLKEYS** [comment]
~~just forgot i existed here~~

**Comment by stuffyAI** [comment]
Literally copied from the suggestion with the exact same content:
Armored conveyors are further down the progression for a reason, let's take for example a map you play from copper to surge in survival, early on you don't have nearly as much need for tight transport of resources,
and even then, you can abuse junctions in many scenarios to transport something right by an omnidirectional out-putter, which really only does not work if you specifically require a conveyor bend adjacent to it, at which point using certain sorter configurations bypass that as well.

Either you can use your smarts to overcome the early struggle with low-tier transport blocks, or you will have to limit your design/output until you reach thorium production, at which point most people rebuild almost everything anew anyway as they upgrade their factory.


For people complaining that nobody elaborates on their reasons to be against the suggestion:
This is by far not the first of this type, and after some time seeing duplicates like this becomes a clear nuisance; it wasn't accepted before, so if OP doesn't pass reasons on as to why it **now** makes sense, explaining all again why it is bad is equally pointless.
Furthermore, this suggestion plainly makes the game easier; as I already mentioned above, you will barely find situations which require a more spacious workaround when not having access to armored conveyors, and even then you at most use a 3x1 line more than you would with armored conveyors.....

I do not believe that this Use-Case justifies the addition of aforementioned block, and as the Read.me of this Repo states, this must be fulfilled.

**Comment by Sector171** [comment]
We should agree that there is a real need and real problem needs solution, 
I agree that the only issue here: is it really deserve to have new item for that or not, I don't say no, but not yes as well. I just commented cus I saw sharp "No" against real need, which is no sense at all.

> Either you can use your smarts

Come on ofc we are doing so, but first it doesn't work in all situations, second it works until it doesn't when that dead end not dead anymore (either by you by mistake or by someone else) and this always happens making big mess.

> you will have to limit your design/output until you reach thorium production

No sense and not a solution for a problem, some maps has no thorium at all, so you wil live with that the whole game, the others it is very late component which you can have.

> this suggestion plainly makes the game easier
That's not true, the correct: makes it less disgusting not easier and there's big difference between them.

Why I felt as if you consider "not accepting input from sides" as a puff, it is a nerf. Actually the game could begin with such a conveyor which costs only copper and very soon the new player can unlock the normal copper conveyor since it is more advanced & better one because it accepts input from sides. But the thing is it is needed in few situations.
As I said it is not a big issue, and thanks for clarifications.

**Comment by stuffyAI** [comment]
> some maps has no thorium at all

Those maps will only have conveyors that accept input from 3 sides, that is a design choice then.

> Why I felt as if you consider "not accepting input from sides" as a puff, it is a nerf.

Is is a transport block variation, not a nerf. You are basically comparing sorters to junctions, they simply fulfill other premises; tankiness for armored conveyors whilst using only 1 input direction, multiple inputs for other conveyors.



> Actually the game could begin with such a conveyor which costs only copper and very soon the new player can unlock the normal copper conveyor since it is more advanced

This doesn't sound stupid until you get into the game.... I can bypass using armored conveyors practically forever, however I really need the 'normal' ones asap, also from a more realistic perspective conveyor belts that only accept input from other such belts are more complicated, so there it doesn't make sense either, look up any IRL pictures of such stuff.



> Come on ofc we are doing so, but first it doesn't work in all situations, second it works until it doesn't when that dead end not dead anymore (either by you by mistake or by someone else) and this always happens making big mess.

So you are using your smarts, but you are stupid so it doesn't work anyway?
As I said, if you are actually not trying you may have to use an additional 3 squares of space for every armored conveyor you have to substitute, increased by 1 square for every other in the same row, which again only specifically happens if you cannot replace it with a sorter combo, because you use sorters adjacent to the place in question.

There really is a sharp 'no' against introducing this into the game, if not I simply wish not to play multiplayer with newbies who never had to learn how to utilize different transport blocks efficiently, it's awful enough seeing those distributor into armored conveyor contraptions some use to supply multiple production segments.

**Comment by Sector171** [comment]
> that is a design choice then

Haha man are you serious? so the designer will ban the thorium in a map just to prevent you from using a conveyor not accepting input from side hahaha, or is it to ban T3 and above and all strong turrets and ..., whereas losing the ability of using that conveyor is just FORCED UNWANTED SIDE EFFECT?? use your brain and you will know the answer.

> Is is a transport block variation, not a nerf. You are basically comparing sorters to junctions

Wrong & irrelevant comparison, you compared the junction which the designer made it for a specific purpose which is alloying crossed belts to transport their items separately without problem with sorter which has totally different purpose, whereas i compared between TWO CONVEYORS, see?? they are both CONVEYORS the main purpose of them is transporting items, the other features are secondary, so I CAN COMPARE. anyway it doesn't matter, that's not our problem.

> This doesn't sound stupid until you get into the game

your replay doesn't sound stupid until you remember how many things did you unlock exactly few minutes after playing this game for the first time, just few minutes. So ofc it will be researched just few minutes later. Again it is not an issue, both of them will be available from the beginning, are you happy now!

> So you are using your smarts, but you are stupid so it doesn't work anyway?

not exactly, but only when i play online with people like you who converts the dead end of a junction into non-dead one mixing the items and making a mess in the schemes. also SOME SITUATIONS NOTHING CAN COMPENSATE if you use your brain you will find few.

> you may have to use an additional 3 squares of space for every armored conveyor

Is this a joke? Did you ever played in restricted space maps?? did you ever see shared core with unloaders here and there and you want a safe spot to your belt?? also don't tell me the ugly solutions which i know, i am here for the simple true real solution.
It is the same story here: we don't need a lighter or match if we can make fire using stick and stones

> There really is a sharp 'no'

Actually yesterday i wanted to check its importance while playing online since usually i play without focusing just do the things routinely, so i changed my mind, i realized there is a real need for it so "YES" i support it, the only reason why i wasn't sure about its necessity to add new item like this was the speed, if it is 11 no sense since we have the armored one, and if it is 4.1 it solves only about 80% of the problem not all of it and it is not good to add a thing does not solve the whole problem. But nah it is important even if it is slow, in most cases the speed doesn't matter too much here.

Finally NOTHING AT ALL JUSTIFIES to not have a basic feature until we own thorium and plastanium. Why it is OK and important to have a cheap things like distributor (which almost i never used) or overflow and underflow which can find an effective solution without them, whereas it is a BIG "NO" against a cheap conveyor not accepting input from sides??? no sense at all, ofc i am not against those items they make our playing life better, also will do this if added.

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/2284#issuecomment-820734007

Basically empty reasoning.

**Comment by stuffyAI** [comment]
Alright, let's do it step by step again


> Haha man are you serious? so the designer will ban the thorium in a map just to prevent you from using a conveyor not accepting input from side hahaha

Indeed, a map designer not supplying Thorium will restrict you from using armored conveyors. Just like he restricts you from all other Thorium-dependent stuff. And somehow it works, I did beat the campaign even though I did not have Thorium, and thus armored conveyors, on the first (and following, but you get it) map(s). 
Logically, that map does not only lack Thorium to restrict armored conveyors specifically, but if a map maker doesn't consider his map to contain Thorium, maybe he also thought that armored conveyors might not be needed?


> crossed belts to transport their items separately without problem with sorter which has totally different purpose, whereas i compared between TWO CONVEYORS

True, we sure are able to compare armored conveyors with normal ones for terms of transporting. Just as I can compare Distributors and Doors, both take up a 2x2 square.
However, the entire point of this suggestion is to make a lower tier version of a conveyor _which specifically has the ability to block other inputs_, yet you compared it to normal ones.... To elaborate, I could also use a junction where I use a conveyor if we only focus on transporting as you described, but here it is indeed of importance that we discuss a new conveyor block with armored behavior.

> but only when i play online

This thinking by itself is flawed;
In any game that revolves around cooperative multiplayer, even on a base level, the incompetence of others could always ruin it for you. Even worse here, since simple mistakes can halt everything in a Mindustry.
If we were to infinitely adjust Mindustry for multiplayer, we would have to implement increasingly easier ways to compensate for lack of experience... 
The final product could be: My miner directly processes my ore into whatever it wants, then directly teleports it to where I want. Because if it wouldn't be like that, other players or myself may make mistakes, which would stop this process.

Which leads to the actual compensatory value question of this: does an early armored conveyor lack in multiplayer?

Maps without Thorium: if you get people here, that would mess everything up simply due to lacking the armored variant, get better people.This really only happens in public campaign sessions, as those same people don't really make it to servers that have maps without Thorium.

Maps with Thorium: God bless early multiplayer sessions anyway, I do not believe that an early armored variant is able to rescue this. The second the pro players set up their logic-bound Poly-squad, they will wipe everything old clean anyway to replace it with good structure, at which point we got the 'fast' armored conveyors thanks to Thorium.

Alas, we either make multiplayer early game easier, or we try to make people learn something (at least in that phase) so they mess less things up later, because they never had to use good design.


> Is this a joke? Did you ever played in restricted space maps?? did you ever see shared core with unloaders here and there and you want a safe spot to your belt??

Okay but if you have unloaders on your core on a map that doesn't yield Thorium, AND lack the space to use them, perhaps this isn't the games fault a problem arose here? I really don't see a situation in which this isn't plain laziness, since we are talking about needing this before even getting Thorium, at which point like... anything is more efficient than this approach without taking too much thinking.


> Finally NOTHING AT ALL JUSTIFIES to not have a basic feature until we own thorium and plastanium.

What do you mean basic feature, was it advertised on the Steam or Git page? If it didn't exist for 2 years, perhaps nobody has expected it's presence as so important as to call it a basic feature.

> overflow and underflow which can find an effective solution without them, whereas it is a BIG "NO" against a cheap conveyor not accepting input from sides???

No, without logic, you cannot replace overflow and underflow gates in one of their functionalities: They ONLY output items in a certain way when the primary way is blocked in some way (either by being full or not existent). 
A basic example is using excess coal from Graphite production as fuel: My graphite output belt is full and I don't require more, but I also don't want to take out my calculator and make precise adjustments, so I use either xflow gate to feed excessive coal into burners. 
Otherwise my miners simply would work slower, which some deem inefficient and wasteful, as I truly would lack the 'missed production' from when my miners would work fully.
Flow gates are truly unlike early armored conveyors: I have a specific purpose for them I really can not replicate efficiently.

**Comment by Sector171** [comment]
Good, i think the topic now is rich enough that anyone read it will see the different points of view,
I just wanted to say the best solution in my opinion, but since it has side effect i didn't say:
A X conveyor which cost lead, copper , graphite, and silicon. Its speed is 11 NOT 4, but it **can't** accept input from sides, and because of that(i still consider this as nerf, it is different feature but nerf at the same time) it cant replace the titanium one, also it cant transport the items from normal drills(mechanical and pneumatic) with that speed (11) easily since you cant put it between the drills as usual the player needs some tricks for that(laser drill = titanium is available). And making the armored conveyor **CAN** accept items from sides as titanium one(the purpose of armored supposed to be armored=tougher but expensive that's it nothing special), and here is the side effect all schemes that uses armored one(i think that more than >99% of people who used armored one in a scheme they did that because it cant accept inputs from sides not because it is tougher).

That is the best solution as i see.
