### ISSUE TITLE
More small features

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2308]
**Describe the content or mechanics you are proposing.**

I suggest multiple small features related to units.

1) Point defences
-Some large units should have point defence systems. Useful when fighting swarms of enemies. I would suggest adding it to Antumbra and Eclipse, they are the weakest of all tier 5s. 

2) Unit repair points
-Oct has 4 neat hardpoints at the edges. Mount repair points on it. They can replace the repair field, or just add up to its repair capabilities

3) Different thruster patterns
-Flares should have a different, more afterburner-like thruster flame. Eclipses and other capital ships can have more efficient, wave pattern-like thrusters

4) Repairing while carrying
-Payload units should be able to repair health of carried units, quickly.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

It makes the game a better, more immersive expirience.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
1. Requires a whole new unit tree of dubious necessity to be balanced
2. Oct is already a huge, high-capacity, tanky mobile shield and resupply station.
3. That would be a ***lot*** of work for such a minor visual improvement.
4. Which payload units? Not quad, because that is a little early, and not oct, because it's already powerful enough.

**Comment by BlueWolf3682** [comment]
1 and 2 are coming in v7. 3 is difficult to implement, and payloads aren't treated as existing functionally until they are placed back down.

**Comment by stuffyAI** [comment]
It would generally be nicer and easier for Contributors or even Anuken if you make one new issue for every suggestion you have, it also would be easier to discuss them, and make you, hopefully, think a bit more about them.



> It makes the game a better, more immersive expirience.

Yes, but you don't write THAT down, you write down how it does so....
Otherwise everyone could just write it down there and call it a day, I don't believe that's the intention there.
