### ISSUE TITLE
Store any datatype in a memory cell

### ISSUE THREAD

**Issue by TheAtomAnt** [Anuken/Mindustry-Suggestions#2313]
**Describe the content or mechanics you are proposing.**
Right now memory can store ints and floats. If I could store any type of value in a memory cell I would find it much more useful. For example, I can do this:

set myvar @unit
'do some other work, perhaps bind a different unit
'then I could do this
ubind myvar
' this seems to rebind the unit stored in the variable

It'd be nice to store units, or other datatypes in a cell to expand what we can do

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
I am done with a compiler that converts a subset of c# into a running script. complete with methods, parameters, etc. However, I can't get a proper stack to work. I build the compiler using Roslyn, it works great, but I made a bad assumption... I assumed that I could store any type of variable in a memory cell. My stack pointer is an int into a memory. Obviously I can't do this with memory because I can only store floats and ints in the cells. I have tried other options but ultimately I need an array for the stack, and a memory is just such a structure, i.e. accessible by an index. It'd be fun to use my compiler to make advanced programs to control my units! 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Humanoid-X** [comment]
yes

**Comment by Kyllingene** [comment]
Of course, this is excepting strings.

**Comment by Deric-W** [comment]
I really like this idea, it would solve a bunch of existing feature requests:

 #2662 is the same request, just with extra string generator (???) functionality which will probably be unnecessary.
While I think preventing strings to be stored would hinder use cases like function stacks it can probably be implemented without modifying the string (like a normal variable assignment).

#3272, #5224, #982 and #1609 propose some sort of unique unit id which can be stored in a memory cell.
Since this change would allow the unit itself to be stored there is no need for for such an id.

While processors can use the new functionality to pass values like units or buildings between them they would not become gamebreakingly powerful since limits like the maximum distance a processor can interact with a building would still apply.
