### ISSUE TITLE
the Missing Link for puzzle/challenge maps

### ISSUE THREAD

**Issue by KRN-8** [Anuken/Mindustry-Suggestions#2329]
Allow Graphite as another grindable material in Pulverizers. 
scrap > sand
now also graphite > coal
(same 1g > 1c ratio)

IRL graphite is essentially organised coal, and soo it makes sense that if u smash it to pieces u can use it as essentially coal
(also this way u can waste coal by doing coal>graphite>coal u would get down to half input coal back)
this will also make Pulverizers more used

the inventory system already seems to support this soo it would just need to add the if there is graphite make coal instead

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/190#issuecomment-638557083

**Comment by KRN-8** [comment]
that is both copper > scrap which makes 0 sense
graphite was already coal soo makes sense that if u crush it it will come back (at bad rate)

Did u actually read this ?

**Comment by itcannotbe** [comment]
Oh I skipped that part. LOL.

**Comment by itcannotbe** [comment]
But then again, I don't see how can you get graphite without getting coal first. Aside from using the separator.

**Comment by KRN-8** [comment]
cause that would be too EZ
not to mention u need power to get coal to get power this way (u know in v5 u couldnt launch with coal but only graphite)

**Comment by Sector171** [comment]
> But then again, I don't see how can you get graphite without getting coal first. Aside from using the separator.
At this point why don't we just add coal to the separator output?

İt looks that you didn't get the point of this suggestion, I think this exactly the purpose of, to give a possibility to convert back the graphite obtained from separators and (Disasembler also give graphite) to coal, ofc graphite is more important than coal, but sometimes if you have enough graphite this may give you a chance to convert it to coal so that you can use it for something else(silicon..etc).
I think this could be useful in some "Scrap to" schemes instead of getting the coal using the long water-->coal way, it could make the scheme much smaller and less expensive (resources & power).

The owner of this suggestion may clarify why he got this idea, what exactly the problem he faced.

**Comment by itcannotbe** [comment]
Scrap challenge maps is what OP might be referring to, that's why I suggested why just not make separators output coal instead of having the ability to get coal from graphite.

**Comment by Sector171** [comment]
I answered why before you ask, cuz Graphite is more important than coal and generally people will not like such a change, if he suggested so he will get thumb down, also not only separators output graphite, but also Disasemblers.

**Comment by itcannotbe** [comment]
Fun fact: Disassemblers also output sand.

**Comment by KRN-8** [comment]
again they cannot output coal because the material is MELTED (u dissassembling what was LAVA before into items)
yes one of the reasons is scrap only maps (but for that we still missing power stuffs which this also could solve ?)
