### ISSUE TITLE
Units resource item handeling with logic [QOL]

### ISSUE THREAD

**Issue by KRN-8** [Anuken/Mindustry-Suggestions#2331]
**Describe what you would like changed, and why.**
there are commands for picking up and dropping items to/from containers (and Core)
u specify amount to drop or take (and i think they dont if they cannot)

**Describe the changes you want to propose. Include possible alternatives.**
what if, we specify that if the amount is negative number (like -1) then the unit will act like if player did it manually
like take/place max u can, and keep the rest (always successful return)
(-1 is usually used as infinity soo this can be non-confusing to most ppl)

**Comment by joshuaptfan** [comment]
You know that you can already sensor `@itemCapacity` to find out a unit's capacity?
```
sensor capacity @unit @itemCapacity
ulocate building core false 0 corex corey coref core
ucontrol itemTake core @blast-compound capacity 0 0
```

**Comment by KRN-8** [comment]
@joshuaptfan how would u put items to sth like belt ?
where the max u can put on it changes between OP codes (maxCap - containsNow)

**Comment by joshuaptfan** [comment]
I think if you try to put more items in a block than its capacity, the unit will fill the block and keep the leftover items. In fact, you can do the same for `itemTake`, and take 999 to take max.

**Comment by stuffyAI** [comment]
> -1 is usually used as infinity

-1 is 1 (one) with negative signum, -1 is the countersign of 1...
-1 as infinity is most often used in jobs regarding filling fast web forms, where it mostly gets treated as _all_ rather than infinite, which actually is what you mean here, you cannot get infinite items, you just try to get as many as you can.
Now logic is made for advanced users mostly, we can assume 

The user wants to use a dynamic max so either 

a)  He first sensors the max capacity  or whatever to a variable, then optionally subtracts the current item-amount, and now uses the variable, containing the exact number of items needed to fill to do the next step.
This is how someone who often uses low-level languages would operate, as it is truly clean (technically he would also have to check the target for how many items it can take, but there it is more apparent that it doesn't overfill).

b) He simply sets it to any high number like 999 to test what happens. 
Someone first timing this might expect this to either fill up or fail, since he might think that the request to put 999 items into something actually only invokes should the supplier hold (those) 999 items.
But to his surprise  it works just fine, and now knows this for the future.

c) He googles it or asks for it somewhere.

What you are suggesting is basically what I did manually in a), but the program already knows my intent and can internally simply use the player function for fetching and depositing items, aka do until supplier is empty or target is full. I think handling it internally by passing large item numbers is apparent enough, keywords are annoying enough already.

**Comment by KRN-8** [comment]
but this way u save OP codes and its more comfy and readable
(yes thats what i trully meant and sayed with -1 XD)

**Comment by KRN-8** [comment]
like, it is another OPTION how to do this (noone is forcing u to use universal shorthand)
and as i mentioned above, the items move between OP codes soo your A way wouldnt work for EXACT amounts 100% of the time @stuffyAI ;-(

**Comment by itcannotbe** [comment]
If logic was made to be comfy and more readable, it would not be made to be like assembly.

**Comment by KRN-8** [comment]
(and the game already provides this exact functionality for Players soo)

**Comment by KRN-8** [comment]
the thing is assembly's variables dont change mid code tho XD

**Comment by stuffyAI** [comment]
> the thing is assembly's variables dont change mid code tho XD

If you wanna compare assembly then any normal person would do way a) as described in my previous comment, that is (still extremely shortened) low-level clean operation.


> but this way u save OP codes and its more comfy and readable
> (yes thats what i trully meant and sayed with -1 XD)

I believe 999 is not much harder to read than -1, adding that to the understandability of users when meeting a wild -1 as itemamount

**Comment by KRN-8** [comment]
ye but 999 might not be always anough, while -1 is by definition ALWAYS nuff
(if ppl run into sth they dont understand they ask other humans, atleats thats how it works around these parts of the world)

**Comment by stuffyAI** [comment]
> ye but 999 might not be always anough, while -1 is by definition ALWAYS nuff
> (if ppl run into sth they dont understand they ask other humans, atleats thats how it works around these parts of the world)

Yes so....
People will use 9999 then? Because they asked someone how to implicitly use max, which can be any number greater than the practical max amount?

I really don't think using another check to set -1 to the max possible value internally is worth the trouble, it seems so easy to just press 9 a few times.

**Comment by KRN-8** [comment]
u can hold 9
(by now it would take shorter time to implement then read the comment section here kekW)
