### ISSUE TITLE
Commanded unit AI

### ISSUE THREAD

**Issue by numer99** [Anuken/Mindustry-Suggestions#2334]
**Describe what you would like changed, and why.**
Step 1: command some ground/naval units
Step 2: go into a narrow passage
Step 3: Units get stuck on the wall

**Describe the changes you want to propose. Include possible alternatives.**
Make when units that are being commanded follow you around obstacles

**Comment by joshuaptfan** [comment]
Not possible because pathfinding to arbitrary coordinates (such as the player's position) is not supported.

**Comment by MrDuck557** [comment]
Astar is run only once for pathfinding to the enemy to save time. You can't actually pathfind to random coords.

**Comment by numer99** [comment]
Problem:
I make 6 corvus (sandbox attack map)
Go inside of one
Command them
try to go through a narrow valley
some of them get stuck

Answer:
corvus pathfinds around the obstacle to get to the rest of the units that are also being commanded

**Comment by MrDuck557** [comment]
the idea is sound, but the implementation is difficult
especially making it quick enough to not lag phones

**Comment by ShadeStrike62** [comment]
> Not possible because AI pathfinding to arbitrary coordinates (such as the player's position) is not supported.

I hate this community, everyone has this stupidly toxic attitude to things that are coded one way not being able to change. V6 changed lots of things that were coded one way, just because units pathfinder to set coordinates doesn't mean coding more advanced pathfinder is impossible. In fact, it would be fairly easy. At the moment, unit just face toward where they need to go to and drive forwards, if the code was changed to make them constantly pathfinder to the coordinates near a player, they would go around obstacles as be less tedious.

**Comment by MrDuck557** [comment]
do you even know how the pathfinding algorithm works

**Comment by Kyllingene** [comment]
> I hate this community, everyone has this stupidly toxic attitude to things that are coded one way not being able to change

I hate this community, everyone has this expectation of miracles from a solo, nearly unpaid dev

You realize that you are expecting Anuke or one of his volunteer contributors to completely rework the pathfinding system, just for a little convenience?

> if the code was changed to make them constantly pathfinder to the coordinates near a player, they would go around obstacles as be less tedious.

And you can make the algorithm that makes that feasible. Pathfinding to a static position is one thing; constantly running a complicated algorithm that finds the shortest possible path to a moving target is a completely separate thing.

**Comment by joshuaptfan** [comment]
[Someone has already attempted a brute-force implementation by running the pathfinding algorithm every frame.](https://github.com/Anuken/Mindustry/pull/4324) It was rejected with prejudice for good reason.

Complicated problems always seem so simple and easy to solve when you don't understand them, don't they?

**Comment by itcannotbe** [comment]
Imagine every unit running the pathfind algorithm every frame/tick from a position that is on the other side of the map.

Sure it would be bearable with a few units doing it, what if you have a lot of units doing it? The processing power doing the necessary computations would give your pc a slideshow, not mentioning the fact that it would give your mobile device a stroke.

**Comment by joshuaptfan** [comment]
The pathfinding algorithm uses [flow fields](https://leifnode.com/2013/12/flow-field-pathfinding/). Thus, every unit regardless of position can use the same flow field, as long as they are all only pathfinding to a single location. However, for each unique location, you need a unique flow field.

You could precompute a unique flow field for every tile on the map, then look up the appropriate flow field for each situation at runtime, which would trade FPS lag for significantly worse loading time. But let's just say you did. The largest supported map size is 500x500. If every tile was walkable terrain, that would be 250,000 flow fields. But let's say that you accept a degree of inaccuracy in your pathfinding, say within 4 tiles, which allows you to reduce the number of flow fields by 1/16. That's still 15,625 flow fields.

Ok, so you're now computing up to 15,625 flow fields every time you load into a map, which if you're rapidly switching between sectors in campaign, can be quite frequent. But the real time CPU usage problem is now solved, right? Not quite. See, the flow fields have to be recalculated every time the walkable terrain changes, such as when a door is opened/closed. So, every time the player opens/closes a door, the game has to recalculate up to 15,625 flow fields, freezing the game for multiple seconds, heating up your phone and destroying your battery life.

**Comment by itcannotbe** [comment]
I think your forgetting that certain user placed blocks affect the generation of the flow field. You really can't compute it only once.

**Comment by stuffyAI** [comment]
> The pathfinding algorithm uses [flow fields](https://leifnode.com/2013/12/flow-field-pathfinding/).

The path-finding for the distance traveling, from what I see OP doesn't necessary require the shortest path there, but rather a path, since he only needs the units to come with him.

If we accept hidden limitations like range an unit tries to cover to get to the commanding unit, we could use a very small A* style algorithm that only graphs a small radius, 5 blocks for example.
This should satisfy most situations already, as commonly units already get stuck on a singular block.
Naturally, calculating A* nodes, even if local as that, yield annoying performance complexity, hence we could limit invokation to when an unit actually gets stuck, memory can be released after t(v) or when another invoke happens.
I believe this would be vastly more efficient than flow fields, which don't have to be used here, as smaller, faster units could utilize simple obstacle avoiding anyway.

**Comment by joshuaptfan** [comment]
That's actually not a bad idea.

Keep track of the distance between units and their commanders over multiple frames. If the derivative of Δdistance/Δtime is positive, that means the unit is stuck. (We cannot simply check if the unit exceeds some distance from the commander, because it's possible for commanders to move faster than their units, e.g. when a pulsar commands novas, thus causing the distance between them to increase at a _linear_ rate.)

When the unit is stuck, switch to A* pathfinding for the commanded units. We only need to calculate a flow field in a small rectangular area which bounds all commanded units (with a generous radius around them) and the commander. This flow field will be recalculated every frame, but it is small and all commanded units will share one. I can already think of ways to deliberately break this solution, e.g. by closing a door behind you cutting you off from your units, so how well it works depends on the radius around the unit that we are checking.

**Comment by itcannotbe** [comment]
Or just change the AI grouping/movement to fall in line when going through a tight space.

**Comment by stuffyAI** [comment]
> AI grouping/movement to fall in line when going through a tight space

This is not much faster in graph theory than an A* type algorithm, note that the space between blocks is always equal, so the edges on my high-end graph all have the same weight, nodes that are inaccessible (aka walls you cannot move on top of) gain continuers or infinite weight.



> We only need to calculate a flow field in a small rectangular area which bounds all commanded units (with a generous radius around them) and the commander.

If this works fast for Java as well praise be, though for multiple units I'd switch to flock logic combined with strict searches for each grouping.
Assuming we don't want to send our units trough labyrinths AND we assume that players commanding units try to let them keep up, this is relatively fast (almost O(x+(1/Units+Groups)^2))) and should satisfy the high cat, should he agree to another path-finding logic in the first place.
But this might just be bias as I have no experience with flow fields yet.

**Comment by itcannotbe** [comment]
I was suggesting a change of formation pattern when it cannot maintain its current pattern.

**Comment by BlueThecno** [comment]
Something I tought about is, what if the problem isn't being stuck in a wall but rather **trying to walk on deep water**? (At least in the case of daggers, maces and fortress who can actually drown)

**Comment by Kyllingene** [comment]
Doesn't the AI for ground units already treat deep water as a wall?

**Comment by BlueThecno** [comment]
Not when commanded (I had more than one Fortress drown because of these)

**Comment by Kyllingene** [comment]
Ah, ok. That would probably be fixed with this anyway, as it is just like the units running into a wall senselessly, except it kills them.

**Comment by stuffyAI** [comment]
> Something I tought about is, what if the problem isn't being stuck in a wall but rather **trying to walk on deep water**? (At least in the case of daggers, maces and fortress who can actually drown)

Depending on which approach we take we can either give them some avoidance priority, aka try not to walk on slowing terrain, never when it kills you, or total avoidance by treating deep water as impassable.

**Comment by stuffyAI** [comment]
> Or just change the AI grouping/movement to fall in line when going through a tight space.

I actually found a solution similar to this called path coupling;
Instead of each unit trying to find a path to the destination, they now take paths to units that already have a path.

  For example, I command units A, B and C. A has line of sight to me, B and C not.
  A can simply follow me, but B and C have obstacles like walls between us. 
  Luckily, B can see A, so we can just let A tell B that he knows the way.
  
  C is in even worse position, C cannot see the commander nor A.
  Luckily, C can see B, and after A told B the way, B knows the way as well, telling C the way now.

Now let's take another example, this time A,B and C cannot see the commander, like when he is flying over a wall:
  We simply let the closest unit path-find to the closest, valid position near the commander.
  After a path is calculated, this unit now tells all the others to follow him.

This is almost perfect for any realistic situations we can get when commanding units, but it needs additional attention to things like deep water or units pushing each other out of entrances, as neither are accounted for in this algorithm.

**Comment by joshuaptfan** [comment]
> Instead of each unit trying to find a path to the destination, they now take paths to units that already have a path.

This could greatly reduce the use of A* pathfinding by using the simple straight-line paths that units already use, but with multiple waypoints.

> C is in even worse position, C cannot see the commander nor A.
> Luckily, C can see B, and after A told B the way, B knows the way as well, telling C the way now.

C would be given a series of coordinates to walk straight lines to in a specific order, AKA waypoints, which requires no pathfinding.

> it needs additional attention to things like deep water

All you have to do is make the raycast check that units do with the commander consider deep water an obstruction, then proceed with the waypoint system above.

Also, if all units lose LOS with the commander, they can simply waypoint to the last known position of the commander. That leaves only the situations where no LOS is available to any waypoint, such as taking command of units on the other side of a wall, in which you have to resort to A* pathfinding.

**Comment by stuffyAI** [comment]
> Also, if all units lose LOS with the commander, they can simply waypoint to the last known position of the commander.

I more had cases in mind in which the commander yields no valid position radia, like when he flies/boosts over a large mountain or alike. It might be annoying to only have the units path-find to the other side of it after the commander draws valid targets; though this may just become 'a user problem' as we kinda expect to still care for their commanded units.

**Comment by Sector171** [comment]
Thanks for this technical information about this issue now people can know why it is not easy to solve this problem.
Away from technical issues,  I think it is important for Anuke and other people in charge to get a feedback from player perspective since most players i think they don't know who made this game and this details, they just download --> play. their opinion could be:
I don't care, it is not my problem, it is just unacceptable, unacceptable at all.
For me I forgot something called "Dagger" line of units totally the moment I realized this nightmare, finished the campaign without building not even one reign, the same in online games never built this line, I just acts as if it doesn't exist.
So if Dev cares about popularity of this game , this issue MUST be solved.
I played a many of games where the player controls many unit ( such as Red Alert2, Generals) sometimes tens or even more than one hundred of units on a shity PCs (about before 20 years or more), definitely there is a practical solution.

Ah, the units go "smoothly" also to CC ( command centre) not only the enemy core, so...
A temporary solution could be to give a "Delay" for example "3" seconds between 2 pathfinder orders, this means the commanded units will get the order to pathfinder once every minimum 3 seconds ( or more) rather than doing so every moment the player move, within this 3 seconds the unit will not accept any new pathfinder order??, together with using other programming tricks.

**Comment by Sector171** [comment]
Because the solution i suggested is so simple but i believe to high extent it can be a real practical solution with very important feature: **IT DOESN'T REQUIRE ANY CHANGE TO ALGORITHM**, which means (if it was really as a solution) it could be implemented immediately with slight efforts, i want to clarify it:
After the commanded unit receives a "pathfinder" order, it will start to execute it(execute the algorithm), but its state will be "Busy" for 3 seconds, this means within this 3 seconds while the player is moving he will continuously send orders to that unit to pathfinder him (maybe hundred of orders per second) , but these orders will not be executed, so will the unit ignore these orders? not exactly, we have here 2 possible situations:

1- The targeted coordinate of last "pathfinder" order the unit executed is so close (takes less than 3 seconds) , lets say for example it took 1 second only, so the unit reached the target after 1 second but the player still moving and the unit cant execute the pathfinder order in the next 2 seconds, in this case the unit will use **NORMAL MOVE** method to follow the player which means that the units may get stuck, and that's fine since it will accept new pathfinder order after this 2 seconds passes.
2-The targeted coordinate of last "pathfinder" order the unit executed is far(>3 seconds): in this case after 3 seconds the unit will receive new pathfinder order, so it will ignore (cancel) the previous one and start using the new one and so on.(most often both of them will almost identical, OK i don't expect that the player will disappear from a corner then appear in a different corner).

**Comment by stuffyAI** [comment]
> **IT DOESN'T REQUIRE ANY CHANGE TO ALGORITHM**, which means (if it was really as a solution) it could be implemented immediately with slight efforts, i want to clarify it:
> After the commanded unit receives a "pathfinder" order, it will start to execute it(execute the algorithm), but its state will be "Busy" for 3 seconds, this means within this 3 seconds while the player is moving he will continuously send orders to that unit to pathfinder him (maybe hundred of orders per second) , but these orders will not be executed, so will the unit ignore these orders? not exactly, we have here 2 possible situations:

That is fundamentally wrong....
joshua mentioned above that our one and only current pathfinding algorithm is flow fields, aka mapping the entire map with targets (in our case there were always only few) by adding directions to every cell pointing towards that target. 
He also explicitly mentioned that remapping such algorithm for even few units and changes to points is extremely expensive and inefficient, making it unusable for a moving target like the commander.

There literally needs to be a new algorithm to handle this close-range pathfinding we are looking for, and above comments exactly describe solutions that already would work, perhaps you should read them first. Not even your 3 second delay, which in practice sounds horrible to begin with, would help the lowest performing target audience.

**Comment by Sector171** [comment]
> There literally needs to be a new algorithm

>  solutions that already would work, perhaps you should read them first

I totally agree, and i read them and it is nice, but i also pretty sure this topic was opened many times before cus it is so important problem but were is the solution? no solution yet, , ...no solutions because it requires deep thinking and changing the algorithm and kind of serious efforts.

>  Thus, every unit regardless of position can use the same flow field

What i tried to do is to give what i thought is a practical solution (until new algorithm is used) assuming that executing this algorithm every long-enough specific period (3 seconds for example) bearable and not a serious problem.

> Not even your 3 second delay, which in practice sounds horrible to begin with, would help the lowest performing target audience.

First, the 3 seconds is just whatever number i used to explain my idea, second if you read what i did write well, the first situation, which is the most common case where the commanded units close to the player, the units will not be far away 3 seconds from the player, since they will use the normal direct move method, and if a unit gets stuck that's not a problem because after specific period passes it gonna again use pathfinder and so it will get rid of that obstacle. And yes i see it as a "practical solution" if only it was OK from performance perspective **I DON'T KNOW**, maybe the player from time to time has to wait one or more of his units to catch him, but at least he no longer has to do that manually, so yeah if applicable it solves 70-80% of the problem with only slight efforts.

**Comment by GitHubUser-B** [comment]
> > Not possible because AI pathfinding to arbitrary coordinates (such as the player's position) is not supported.
> 
> I hate this community, everyone has this stupidly toxic attitude to things that are coded one way not being able to change. V6 changed lots of things that were coded one way, just because units pathfinder to set coordinates doesn't mean coding more advanced pathfinder is impossible. In fact, it would be fairly easy. At the moment, unit just face toward where they need to go to and drive forwards, if the code was changed to make them constantly pathfinder to the coordinates near a player, they would go around obstacles as be less tedious.

TRUE
