### ISSUE TITLE
Schematic Editor

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry-Suggestions#2353]
**Describe the content or mechanics you are proposing.**

a way to edit schematics, possibly through the schematics window, or a button on the main menu

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

especially for players who don't just have cores sitting around, the ability to more easily edit schematics without having to place them and re-save them would be very helpful

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment]
Did you know... that sandbox is great for creating and testing schematics?

1. Create a new map in the editor
2. Menu -> Map Info -> Generation -> remove all the random terrains and ores
3. Menu -> Resize, make it big
4. Manually paint some special terrain tiles and ore patches for testing on
5. Place at least 1 core
6. Paint a single Enemy Spawn tile in a corner so it will be a valid survival map
7. Save
8. Play -> Custom Game -> select your test map -> Sandbox

**Comment by Humanoid-X** [comment]
close????

**Comment by genNAowl** [comment]
I think he meant a way to edit the schematic without placing it down or resaving it - like a mini sandbox with the selected schematic that one could edit and re-save.

**Comment by joshuaptfan** [comment]
> like a mini sandbox with the selected schematic that one could edit and re-save

Any method to edit schematics would need to fully support conveyor pathing, bridge linking, block configuring, power node linking, etc, so that you can tell that it's a valid schematic. Oh, and you know what else would be nice too? What if blocks actually functioned so you could test if your edited schematic worked?

When you get to that point, you've basically come back full circle to editing schematics _in-game_.

Custom games load quickly. Just do what I do, and have a custom sandbox game to jump into anytime during the campaign to test designs, before saving them for use in campaign.

**Comment by genNAowl** [comment]
Exactly why I don't support this suggestion

**Comment by oinkymoo** [comment]
I currently have 1 sandbox map. it contains a single nucleus. becuase of how tedious it is, I am not particularly interested in going into the editor and adding a foundation

**Comment by joshuaptfan** [comment]
So because you don't want to spend a few minutes editing the map and setting up a new sandbox game, you would rather Anuke or a contributor spend weeks creating this unnecessary feature.

**Comment by oinkymoo** [comment]
yes, that is the problem i have exactly. If i want to replace a single block in a schematic, it should take 30 seconds to a minute, not 5 minutes

**Comment by joshuaptfan** [comment]
Well, I can tell you with 99% certainty that no one is going to implement this suggestion, so you may as well bite the bullet and edit your sandbox map to have all 3 cores now.

Even if you knew how to code and enough about the Mindustry codebase to submit a perfectly implemented PR, Anuke would almost certainly not accept it because it's unnecessary.

**Comment by itcannotbe** [comment]
> I currently have 1 sandbox map. it contains a single nucleus. becuase of how tedious it is, I am not particularly interested in going into the editor and adding a foundation

Ummmm, make a map with different cores if you're basically making core schematics for loadouts, it's that simple.
