### ISSUE TITLE
Remove the possibility of "voiding"

### ISSUE THREAD

**Issue by breadbug23** [Anuken/Mindustry-Suggestions#2377]
In PvP, some players tend to bypass defences by passing into what they calleds the void (it's the dark part which is technicaly outside of the map). The force that is meant to push players to avoid that is far from enough, and need to be increased.

**Comment by PickAPlayerNameFirst** [comment]
The voiding borders are fine. 
A cyclone could reach the void where air units hide. 
If you make smart spectres, then they're easily obliterated.

**Comment by OnyxFinger** [comment]
if the units are forced to void in order to get through correctly, then there is problem with the map itself, if the voiding gets fixed in a map where it ends up being force, then the map will be confrontationnal and so, about who rushes the game ending unit on this map the fastest.
>A cyclone would reach the void where air units hide
>If you make smart spectres, then they're easily obliterated

You're right, but tech rushing spectres and cyclones when having the same pace than your enemy will just not work, because T3s are truly game-ending and you can't cover your whole base ; if you get units, you're slowed down and the enemy just get's more units, reaching T3 units is essentially the point where the entire game becomes about managing units and just trying to make more in order not to get overrunned, if you try anything fancy you'll just get stomped because placing fancy things aren't easily deployable, so you try to get fancy stuff that wont do much for you, which is bad. However you are right saying that using smart guns can work : smart scatters and salvos can pick off units on the sides.

I would also like to add that if your enemy can attack you via void freely, then it means you have no army to defend it with, which is usually not a thing, if your micro withu units is good enough, when they'll try to void and reach your base you'll have units here too, and they'll either barely deal any damage or lose all of their offensive power at once

**Comment by sup3r87** [comment]
A better idea would be to make the void push strength an adjustable thing in the map editor, so we still get fluid voids unless the map maker intends it not to be that way.

**Comment by OnyxFinger** [comment]
idk, sounds like an unnecessary change to do. poeple might do such a low void strnegth in their map that cheesy things will happen all the time, nothing more frustrating than a good map but the guy who made it is stupid enough to make it cheesable, and I'm sure it would happen, also teh mechanic itself is just fine as it is.

**Comment by PickAPlayerNameFirst** [comment]
I just, tend to increase the defence. 

Like this, 
When you reach the wall near the void area, 
Build/spam more turrets perpendicular to your defense, facing the void wall. That way, no one would attempt to go there. 

With the zeniths tho, zeniths aren't fast enough to dodge all the bullets. 

The one that needs fix was FLARES and HORIZONS. Flare-Logic and Horizon-Logic buildings are a real threat in the early game because Flares are speedy bois and can resist the force of the void, like a spaceship resisting the gravity... 
And the curving attempts can ruin the accuracy of turrets, where most of its bullets could be easily dodged.

**Comment by breadbug23** [comment]
just so you know, you can bruteforce a "void" defence with a lot of flares.

**Comment by Somka000** [comment]
In my opinion this should be removed, acause flying in a void seriously destroy pvp

> A cyclone could reach the void where air units hide.

No

**Comment by OnyxFinger** [comment]
> just so you know, you can bruteforce a "void" defence with a lot of flares.

nope. not if there are units like zeniths.
And usually flares are used to send items, cuz it's not as good as factories but it's way easier to setup. Why'd you wasted them all for a useless prupose while they can help you make your life easier and faster ?

>In my opinion this should be removed, acause flying in a void seriously destroy pvp

>   A cyclone could reach the void where air units hide.

>No

it depends. If you talk about the void on the very side that you can't remove, anything can defend, if you talk about the one that appears when you place too many walls, WHY WOULD YOU STRIP AWAY AIR'S PROTERTY TO DO AIR THINGS ?
If your maps have issues with it, make more space around this area / add a bit of 3rd party to it so that it's harder to get units to important points. The fact that there is an issue about this is because you designed the map incorrectly, not because the game is unbalanced af (though the game is unbalanced af still).
The real destroyer of PvP is logic, and unit control, it's fun to snipe things, but too much like a normal RTS, the thing that made me play mindustry PvP is it's sort of.. difference, to still be playable with only command centers as a limited way to make untis do what you need to do / just the way PvP worked in general.

NOw it's oogabooga logic FTW
