### ISSUE TITLE
Some additions to units displayed on the map

### ISSUE THREAD

**Issue by SaltyBeggarBR** [Anuken/Mindustry-Suggestions#2385]
**Describe the content or mechanics you are proposing.**
The more damaged an unit is, the more intensively it will blink (just like how their health is displayed outside of the map), and when they die they'd do a little explosion. It could be a circle that pops out of it and dissappears over time, particles that pop out of it or something else.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It would help to see how good your defense is doing by just opening the map, and also just for being fancy, since the way the units dissappear when they die in the map is kinda weird.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Are you referring to the minimap or the actual map?

Also this would be more annoying that helpful. To be honest.

**Comment by the-red-soul** [comment]
The current minimap is fine as is. if a bunch of random icons were flashing it would signify something of importance or an alert, and having an army of units flashing irregularuly will lead to a lot of confusion.

As for a death effect why does the unit need to "pop" on a map overview? If the unit dies the icon dissapears because it does not exist anymore. If the defence is good the icons all go out one by one. If your defence is failing the icons stay and advance past the wall.  Its simple and effective indication of what is going on.
