### ISSUE TITLE
Change "Units" Category to "Payloads", move Payload Conveyor and Related Blocks Respectively

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry-Suggestions#2390]
**Describe the change.**
Here's an interesting idea - changing the Units block category to the more general Payloads Category. 

**Describe how this will improve the game.**
I've always felt like the Payload blocks belonged into a category of their own, instead of being split across many different ones like transportation, crafting, etc; I also think the changing units category to fit that purpose is the best way to implement this; 
If you don't agree, feel free to downvote or leave a hateful comment. Cheers!

**Place an `X` in the boxes.**
1. - [X] I have made sure this is not a duplicate
2. - [X] I have made sure this isn't planned
3. - [X] I have played the latest version of Mindustry
4. - [X] I have read `README.md`

Ehh this suggestion is very likely to get bonked but I'll post it anyway

**Comment by oinkymoo** [comment]
what building in the crafting tab produces payloads? they all produce items (or in 3 cases, liquids). 

also, to my knowledge, the only payloads are: ground units, air units on payload conveyors, and any building that has been picked up by a mega, quad, or oct

**Comment by genNAowl** [comment]
The block factory (Currently experimental, BTW) is in the crafting tab. Also, many BetaMindy blocks are in there too, and they don't really look like they belong

**Comment by genNAowl** [comment]
Now that there are payload sources, I also think that this could be a possible category for that, instead of maybe transportation or crafting.

**Comment by SheepCommander** [comment]
👍 I would prefer this

**Comment by Humanoid-X** [comment]
I agree :-)

**Comment by OnyxFinger** [comment]
yes I would like it but... right now there are ten cathegories, turrets, drills, item transport, fluids, power, walls, factories, units, support and logic. These ten correspund to the ten numbers from your keyboard : 1 2 3 4 5 6 7 8 9 0
"yes but why not use composite numbers for hotkeys ?" >>>> the game already does, the first number is always the only to give the cathegroy, as there are ten of them, and the one-tow behind precise what block. Now imagine you're using the hotkey for payload conveyors, 316. Are you using the 6th item of the 31th cathegory or the 16th item of the 3rd cathegory ? of course there will never be 31 cathegories, but there can be things like 111 for segments, that is also the 1st item of the 11th cathegory, and an 11th cathegory is just what you're asking for.
"yes but hoetkeys are useless, we can get rid of them" >>>> No, hotkeys are really good, especially in PvP, and for now, even know Anuke isn't focusing on PvP but on campaign instead, it's not a reason to make PvP more complicated, especially since V6 left a huge scar in it.
RIght now, the system is totally fine anyway from my POV, I don't have any issue remembering anything, even when I use it almost never.

**Comment by oinkymoo** [comment]
> Also, many BetaMindy blocks are in there too, and they don't really look like they belong

that's an issue to take up with the mod creator, not anuke

> Now that there are payload sources, I also think that this could be a possible category for that, instead of maybe transportation or crafting.

i agree, this would probably be better in a tab other than crafting, but i still think the units tab is fine for this. block payloads seem to be only useful when you have units to carry them, otherwise they just sit forever on your payload conveyors

**Comment by Kyllingene** [comment]
> block payloads seem to be only useful when you have units to carry them, otherwise they just sit forever on your payload conveyors

Anuke is prototyping a payload launcher right now.

**Comment by OnyxFinger** [comment]
> Anuke is prototyping a payload launcher right now

Anuke protoyped a payload forge, loader and unloader and it had no use. same for that one, units aren't hard to make without payload launchers at all, and launching blocks is probably useless.

**Comment by Kyllingene** [comment]
> Anuke protoyped a payload forge, loader and unloader and it had no use.

Yes, because they all were hard to make and were quite buggy. They very well could come into Mindustry proper later down the line (they are still in some dev branch I do believe).

**Comment by OnyxFinger** [comment]
>     Yes, because they all were hard to make and were quite buggy. They very well could come into Mindustry proper later down the line (they are still in some dev branch I do believe).

the concept is also quite useless

**Comment by Kyllingene** [comment]
Tell that to Anuke. I think it will be able to shoot blocks into the world, but as that could lead to long-range thorium-reactor bombing, maybe not. Either way, transporting blocks, say across a dangerous space in the middle of the map, or across an intentional gap in your defenses, to be moved by other units on the other side sounds useful to me.

**Comment by OnyxFinger** [comment]
>Tell that to Anuke. I think it will be able to shoot blocks into the world, but as that could lead to long-range thorium-reactor bombing, maybe not. Either way, transporting blocks, say across a dangerous space in the middle of the map, or across an intentional gap in your defenses, to be moved by other units on the other side sounds useful to me.

Amzing, everything that you said, is completely wrong. Well, probaby completely wrong xD.
1) why not transport ressources ?
2) how would you get the blocks you launched ?
actually by a reciever ok that was a dulb point
3)long range thorium reactor bombing is cool, but not very mindustry-ish, it's more like a meme than something that will ever happen. We know nukes are coming for v7, but not what kind / it's probably not gonna get thrown without a special launcher.
This just doesn't fit into the game in my opinion.

**Comment by itcannotbe** [comment]
To be honest the concept of moving blocks via units or conveyors have some merit, it's just the scale of distance is stupid in mindustry. Stupid enough that it's not actually needed.

**Comment by qwerytty** [comment]
an 11th cathegory is just what you're asking for.

I think he meant CHANGE the unit category to payloads and not keep units and add payloads.

I think this would be useful when you want to build payloads and units and they aren't in the same category as of right now(v6) payloads can only carry units. Also, hotkeys are pretty useful.

**Comment by SheepCommander** [comment]
I don't know about you guys but it's very very clear that he wants to "Change `Units` category to `Payloads` and move Payload Convery and Related Blocks Respectively"

**Comment by OnyxFinger** [comment]
> > an 11th cathegory is just what you're asking for.
> 
> I think he meant CHANGE the unit category to payloads and not keep units and add payloads.
> 
> I think this would be useful when you want to build payloads and units and they aren't in the same category as of right now(v6) payloads can only carry units. Also, hotkeys are pretty useful.

I looked at both options.

**Comment by SheepCommander** [comment]
o.0

**Comment by qwerytty** [comment]
O

**Comment by genNAowl** [comment]
Welp it was implemented in 7.0 anyways
