### ISSUE TITLE
Nerf quasar

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#2397]
**Describe what you would like changed, and why.**
Quasar should be nerfed - currently it's OP *both* in PVP and survival.
There's no viable turret-counter to quasar that has the same "tech level" as quasar, mostly due to its range: quasar simply outranges any turrets that would be otherwise viable against it, (in survival) forcing you to use plast wall - and even then, (in pvp) it can just kill ammo/power feeds right after landing, plus it can go and land *anywhere,* which means you can't even properly defend against it as it can just fly around your defense, and to defend from that, you'd have to cover your entire base in either antiground defenses that are not vulnerable to ammo/power feed snipes or insanely powerful antiair defenses, which is usually too hard to perform cost-wise.

**Describe the changes you want to propose. Include possible alternatives.**
+ Nerf quasar range to, say, 15 blocks
+ Make quasar unable to fire momentarily after landing

**Comment by itcannotbe** [comment]
For those thinking otherwise, bullets takes time to fly, laser on the other hand are instant.

**Comment by RedstonerKBC** [comment]
This is why plast walls were added, to shield against laser attacks. Quasar can't shoot while flying. It can easily be taken out in pvp by revenants (a popular offensive choice in pvp) because it's slow. Plast isn't hard to get.

**Comment by Ilya246** [comment]
Yes, you can use plastanium wall against quasars, but in pvp, considering that quasar can go anywhere, you need to place plast walls everywhere too, not even considering that the quasar can just fly over the walls
And the problem with "Just build anti-both-ground-and-air turrets" is that it simply won't work - those turrets generally don't either have the required range or DPS - currently the most suitable turret for killing quasars would be salvo, and that won't work - to outrange quasars you __have to__ use logic or manually control a salvo, which is usually inconvenient, and even then the quasars can just kill your ammo feed, which can quickly disarm a salvo as salvos are an ammo drain

**Comment by OnyxFinger** [comment]
Anuke was already made aware. 
The problem here is however, that players found ways to counter them and quasars don't even have the capacity to cheese the game's mechanics unlike enemies with high speed and bullets (using bullet velocity mechanics to have farther reach) or AOE range increase (shoot way too far for your shot to hit but it still releases AOE which then does hit.)
What I mean by that is that quasars first off can't be used as cheese.
It doesn't have much range (it needs a little more range for this factor to be useful) and movement speed is very low, so it's not that good in a logic environment.
In a non logic environment, it does crush, however, it is still counterable with guns, as most of the units are usually not as price-efficient as guns, so they can get stuck on those. Of course you can't place guns everywhere in your base if you have an actually good map but I doubt many have a good definition of "good map" anyway and prefer small confrontational ones for no reason. in the case of a confrontational map, of course they will also be broken because they and fortress mechs are the best confrontational units. 

Now I'm kinda going nowhere like that so I'm gonna just put it simply : they are broken for non logic, but get dominated with logic.

The problem in my opinion is that other units aren't useful enough copared to quasars, though quasars should get nerfed a little still, having piercing guns with 54 dps, a giant shield and the ability to fly is kinda broken.

**Comment by itcannotbe** [comment]
> This is why plast walls were added, to shield against laser attacks. 

This is a lie.

**Comment by OnyxFinger** [comment]
Not entirely, but pretty much wrong.

**Comment by itcannotbe** [comment]
@RedstonerKBC how fast can you make enough plast walls to be able surround your base vs make enough corvi to destroy a base without plast walls?

**Comment by RedstonerKBC** [comment]
> > This is why plast walls were added, to shield against laser attacks.
> 
> This is a lie.



> > This is why plast walls were added, to shield against laser attacks.
> 
> This is a lie.

Oh yes you're right. They were later changed to have the mechanic of blocking lasers. I just forgot.

> @RedstonerKBC how fast can you make enough plast walls to be able surround your base vs make enough corvi to destroy a base without plast walls?

You only need 1 corvus to destroy a base. All you need to do is hope they don't have plast walls (most don't because nobody likes plast walls except when they need them).

Generally I don't use plast walls for quasars in pvp. I use scatters or swarmers because they're almost always coming in via flight.

**Comment by LeoSko** [comment]
A note from Ranked PvP as I just calculated some data from 2322 matches of current season and 5693 matches from 1st season: quasars don't contibute to the win anymore as of the current season. Their win contribution back in season 1 was 70% [of teams with quasars who won], while now it is 40%. People just adapted to how to counter them.

Still, 40% is a high percent considering the game has 6 unit trees, so *ideal* perfect number would be ~17%.

**Comment by IVV-NCX** [comment]
I did testing. It literally takes 2 meltdowns at full coolant to destroy 30 of them. 100 takes 4. And this is concentrated fire. In a larger base, it's going to be insane to fight. 

650 surge, 650 silicon, 600 graphite, 700 lead, and 2400 copper. This is extremely expensive, and very hard to supply in live combat. A single impact reactor consumes coolant and blast, and supplies up to 6 of them, not including other machines, like the drills, etc.

I don't play PvP, but seriously, the pick rate of units (by tier) should be 1.666... percent, or ~16% like Leo said.

**Comment by MrDuck557** [comment]
meltdown sucks against higher tiers, it's mostly good for clearing cannon fodder
try using cyclone or lancer to test

**Comment by IVV-NCX** [comment]
Alright, testing weapons with 2 layers of plast, and 1 layer of thorium, with coolant, and 1 healing dome. Versus 100 enemies of one type. 

Lancer x6: Capable of destroying dagger tree tiers 1-2, barely able to destroy tier 3s. Can destroy 100 quasars, but annihilated by Velas. Able to destroy up to t3 of the crawler tree. Able to destroy up to t2 of the naval tree (WTF is that annihilation power?)

Swarmer x6: Anything t2 and below. Sucks at t3s, even with surge. Able to defeat spirocs. Stronger than lancers at t2 naval, but can't even defeat a bit of t3s.

Salvo x6: Actually useless against t2s and virtually everything. Too weak vs multiple enemies. Even with thorium

Fuse x5: Too little range to properly test with this base design. However, managed to destroy most t2 and some t3s before getting overloaded by range.

Ripple x5: Weak against t3s, decent against t2s. Can't handle naval units. Used a tsunami with cryo to buff it, due to the effect of blasted.

Cyclone x4: Able to handle most t2s and some t3s to an extent. T4s destroy them.

Foreshadow x3: Can handle one of every t5.

Specter: Strong, but weak to t3+ swarms.

**Comment by IVV-NCX** [comment]
Welp. I say Quasar is fine RN, but turrets should receive a buff, but small.

**Comment by IVV-NCX** [comment]
Also, do note that this was against swarms of 100, so it's not practical to use this as a baseline.

**Comment by LeoSko** [comment]
@IVV-NCX, more than half of your conclusions are wrong so I believe there was something wrong with your testing. From experience - turrets are much more viable than what you said.

Did you try to manually control units?
Did you use logic for units autoretreat?
For turrets range extension?
For units range extension?
Did you try going with quasars into real handmade structures like in PvP within the same turret tier? From side to the back of the base when there are no turrets?

Making conclusions from non-baseline tests seem like a bad idea.

**Comment by IVV-NCX** [comment]
Alright. First, all of them used 0 logic, no manual, all of them are automatic. There were 0 unit healing, and the turrets used the most powerful (subjective), and the enemies were summoned from the front. The turrets had only coolant to increase DMG output. Everything else was automatic. I can simulate an actual base if desired, however, give me a few hours, and your discord username so I can DM more info about each test, @LeoSko.

**Comment by LeoSko** [comment]
@IVV-NCX, there is no need in this. All that I described is constantly happening in ranked PvP in real matches and I've seen numerous examples of that.
