### ISSUE TITLE
Starting units

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry-Suggestions#2399]
**Describe the content or mechanics you are proposing.**

When starting a multiplayer map or when launching cores you should be able to pre spawn units. In single player when launching cores you should be able to take 1 or 2 monos with you. And in the map editor for multiplayer games you should be able to start off each team with a certain amount of certain units. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

The single player addition is not very useful in itself because you can always just build a factory and a rtg. But in multiplayer games the early game, especially for pvp, is very hard. Being able as a map creator to give players 10 monos at the start of the game will make it easier for the map creator to make the early game easier and allow for less mental pain for the people playing the map.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
this would be hell to balance for if you can do it whenever you launch a core

**Comment by MrDuck557** [comment]
Loadout is already broken in campaign, do you want to do the same with units? (aka launching with zenith and being able to kill cores within 10 seconds)

**Comment by OnyxFinger** [comment]
I agree, however unit transport for campaign is already planned, adding it to the map editor is also good, since it is supposed to be doable > soon < in campaign.



> Loadout is already broken in campaign, do you want to do the same with units? (aka launching with zenith and being able to kill cores within 10 seconds)

I agree but don't agree. Loadouts ARE broken but the whole campaign system is just bad in my opinion. The capping mechanic kills the idea of waves as attack sectors attack very slowly sometimes and are easily destroyed, the only fun in it is to have a giant sandbox world where you can make pointless mega factories, and unit loadouts can make it faster to actually destroy attack sectors for the sake of that sandbox world.
If loadouts were to be nerfed or stay as they are, the campaign better just go back to v4-v5 age, where you would play the game as it was designed.

**Comment by genNAowl** [comment]
...
You actually can, just grab DeltaNedas/Unit-Factory, go to editor>map>edit in-game, and then spawn the unit you want; Exit and save, and bam - when you start a new game those units are there.

**Comment by Ineedause** [comment]
hmmmmmm, maybe you should read the suggestion and not the title
