### ISSUE TITLE
Not the core

### ISSUE THREAD

**Issue by MrDuck557** [Anuken/Mindustry-Suggestions#2414]
**Describe what you would like changed, and why.**
If a unit is close enough to the core while mining with logic, it will deposit its items to the core when it has full items. This can interfere with logic. Players will be confused because they didn't program it in

**Describe the changes you want to propose. Include possible alternatives.**
Just remove it. Or add a boolean to automatically deposit to core

**Comment by Bassem-Const** [comment]
Ok, so mono control.

**Comment by Sector171** [comment]
Not an issue which deserves to care about because:
1- it happens in rare case: where the player wants the unit to mine to a storage instead of the core, and the ore being mined close enough to the core.
2- you can easily overcome this by ordering the unit to stop mining when it has Max-1 items.

Anyway, having the ability to change this default behaviour using logic will not hurt.
