### ISSUE TITLE
folders for schems

### ISSUE THREAD

**Issue by fox1104-therealone** [Anuken/Mindustry-Suggestions#2450]
**Describe the content or mechanics you are proposing.**
folders for schems

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

folders for schems

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [y] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [y] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [y] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
\*doesn't follow template*
just name the schems well

**Comment by Anuken** [comment]
a revolutionary idea

**Comment by RedstonerKBC** [comment]
Try this naming convention:

[Purpose]-[How many]-[Attributes]

A few examples: "Surge-1-Tilable", converts scrap to surge alloy. No description necessary, since its inefficient and you can tell just by looking at it what it does.

"Surge-4-logic", you can guess what that does. No need to put "tilable" because it uses logic so obviously its tilable.

"Cryo-16-tilable-plast", uses plast conveyors to make a :hankey:load of cryo.

"Pyra-Blast-16-Driver", combines a pyratite schem with 16 blast makers to make blast. Inputs are mass drivers.

**Comment by IIINSTINCT** [comment]
Oh God this have suggested many times ago (including 
me) and yet we are here again.... I dont think anuke want this thing in the game since if he does. this feature should be already in the game

**Comment by Humanoid-X** [comment]
just use  some sort of suffix in their names, then use search bar

**Comment by SMOLKEYS** [comment]
![SmartSelect_20210523-131639_GitHub.jpg](https://user-images.githubusercontent.com/75618732/119249185-221bcd00-bbc9-11eb-949a-8b4780c73dc2.jpg)

 Come here and let me shoot you in the face.
