### ISSUE TITLE
Some T6 Unit ideas

### ISSUE THREAD

**Issue by Random-internet-person** [Anuken/Mindustry-Suggestions#2459]
**Describe the content or mechanics you are proposing.**

T6 UNITS!!!!1!111! 
Reconstructor Name: Geometrical Reconstructor
NAMES:
Reign->Tyrant
Toxopid->Macrothele
Corvus->Sagittarius
Eclipse->Corona(then again, maybe not)
Oct->Dec
Omura->Bowhead

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

T6 units would be awesome in the game (and don't you dare say "MoDs").

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BlueWolf3682** [comment]
Mods.
***:)***

**Comment by D-player1** [comment]
Yes make insanely overpowered units and don't give a fuck about a turret counter

**Comment by Random-internet-person** [comment]
> Mods.
> _**:)**_

FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU

**Comment by BiggerBrainYT** [comment]
I don't think the developers needs name ideas, maybe stop contributing to the mass amount of "name ideas" in suggestions and maybe suggestion something useful if anything at all.

**Comment by DarkBrick** [comment]
This post is just an excuse to say some random words you came up for units

> Yes make insanely overpowered units and don't give a fuck about a turret counter

Ah yes reacting with thumbs down to that is against your point. T6 Units just don't fit in with the current game and would be really broken. You can't constantly creating bigger and bigger units just because it would be fun. 

Side note can you imagine how big the reconstructor would need to be

**Comment by DarkBrick** [comment]
Even stats would be barely more usefull then random names, although still completely pointless. The real answer to this suggestion is:
Mods

**Comment by IVV-NCX** [comment]
Mods. Except in v7, assuming the new planets are extremely hard, there could be a possibility of t6 being useful. Even then, strategy and t5s will almost always be sufficient. Not to mention the balancing problems. And the size, the stats, materials used, it's all just a recipe for disaster.

**Comment by OnyxFinger** [comment]
T6s simply don't have a niche in this game. T5s are enough and more will be more pain to balance for no reason, along with more coding and spriting even bigger things, which would take ages. Ths names are cool, but there will never be a point into what they come with.
as always guys stop spamming "mods", even know this would be the awsner, you NEED to explain why, at least a little.

**Comment by RedstonerKBC** [comment]
Reconstructors are based on addtion.
Additive reconstructor - Addition, combining the value of two numbers (1 + 1 + 1) + (1 + 1 + 1)
Multiplicative reconstructor - Multiplication, repeated addition 3 + 3 + 3 + 3
Exponetial reconstructor - Exponentiation, repeated multiplication 3 * 3 * 3 * 3
Tetrative reconstructor - Tetration, repeated exponentiation ((3 ^ 3) ^ 3) ^ 3
[Side note: Notice that tetration isn't the same as a power tower hence why I put parenthesis. A power tower is 3 ^ 3 ^ 3 ^ 3. This is because of the order of operations. 3 tetrated to the 4 is 7,625,597,484,987 but a power tower of 3's 4 tall gives 1.50... * 10^9391.]

The T6 reconstructor should follow the same logic,no?
Pentative reconstructor - Pentation, repeated tetration 3 v 3 v 3 v 3 (I can't notate tetration. Just pretend the 'v' means to perform tetration.)

**Comment by RedstonerKBC** [comment]
> T6 units would be awesome in the game (and don't you dare say "MoDs").
I agree with both statements but bro you have to understand something. RIP balance! v6 Mindustry gameplay is already defined by units. Units can get through pretty much any defense. Imagine what would happen if we made units even more OP? Let's find out :D

> T6 UNITS!!!!1!111!
> Reconstructor Name: Geometrical Reconstructor
> NAMES:
> Reign->Tyrant
Reign sucks, not gonna lie. It's good for tearing up weaker bases but that's about it. I can understand the need.
> Toxopid->Macrothele
This is one of the most OP units already! It can build, suck health from things, has long ranged attack, and it can destroy things just by stepping on them. Did I mention I can walk over water? No! Did I mention it can walk on slag without burning its legs? What could possibly make this unit any scarier?

Ok but for real though, imagine if the Macrothele could shoot a web projectile that lasts a long time or until a unit comes into contact it in which case it slows them dramatically and saps their energy. If it had close range vemon fangs that do very high damage but have tiny range. That'd be cool.

> Corvus->Sagittarius
Corvus has insane range but doesn't do much damage and can walk over liquids without getting debuffed. Sagittarius is a archer I think? I can't imagine anything stronger than a literal nuke laser beam shooter on legs.

> Eclipse->Corona(then again, maybe not)
Also kind of sucks but not as bad as Reign. I can understand a need.

> Oct->Dec
Octs are OP because they just don't want to die. They love living and hanging around doing nothing. What could make this unit more OP? If it had healers?

> Omura->Bowhead
 Omura is super OP but its water constraint keeps it in check, I guess.

If theoretically we do add T6's we'd have to add new stronger defenses to counter them. Spectres, Meltdowns, even multiple Foreshadows would struggle with T6's.

**Comment by MEEPofFaith** [comment]
> > Toxopid->Macrothele
> 
> This is one of the most OP units already! It can build, suck health from things, has long ranged attack, and it can destroy things > just by stepping on them. Did I mention I can walk over water? No! Did I mention it can walk on slag without burning its legs? > What could possibly make this unit any scarier?

(Toxopid doesn't have lifetsteal but that doesn't matter it's still really strong)

**Comment by MEEPofFaith** [comment]
> > Corvus->Sagittarius
> 
> Corvus has insane range but doesn't do much damage and can walk over liquids without getting debuffed. Sagittarius is a archer I think? I can't imagine anything stronger than a literal nuke laser beam shooter on legs.

Vela, Corvus, and Sagittarius are constellations.

**Comment by Humanoid-X** [comment]
1. Why geometrical? according to consistency, it should be named pentative.
2. Stop giving random "name ideas". This does not help to develop the game.
3. T6 = insanely overpowered
4. Mods
5. Go f* yourself.

**Comment by RedstonerKBC** [comment]
> 5. Go f* yourself.

And they wonder why I'm a hater. People always making everything sexual when there's no need to be. Fucking disgusting! I don't care if you call me out for hate speech or not, that comment is nasty and uncalled for!

**Comment by BlueWolf3682** [comment]
> > Mods.
> > _**:)**_
> 
> FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU

hehe :)

**Comment by BlueWolf3682** [comment]
> > 1. Go f* yourself.
> 
> And they wonder why I'm a hater. People always making everything sexual when there's no need to be. Fucking disgusting! I don't care if you call me out for hate speech or not, that comment is nasty and uncalled for!

That's not being sexual, "go f*ck yourself" is meant as an insult, not a suggestion.
You're mainly being a hater for things you have no knowledge about because you have misconceptions - DM me about that on Discord if you want a full explanation of the true backgrounds of the communities I know about.

**Comment by Random-internet-person** [comment]
> 5. Go f* yourself.
>
Is there some sort of report button? I'm not offended, but still.
