### ISSUE TITLE
Group Control of Turrets

### ISSUE THREAD

**Issue by ustcpetergu** [Anuken/Mindustry-Suggestions#2473]
**Describe the content or mechanics you are proposing.**

Now we can press "G" and control a bunch of unis together, it would be nice if we can do the same thing for turrets -- since 
single turrets can be controlled manually, it's natural to command a bunch together by pressing "G". For example one 
possible design is to control all other turrets in range with tier less than the main one you are controlling. 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

I know this could be done via logic, but native support is more natural. For example to shoot some Spectra bullets out of its 
original range, to the back or middle part of a line/bunch of enemies -- I expect this to be very hard for logic coding. 

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [x] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
Yes please.

**Comment by Random-internet-person** [comment]
YESSSSSSSSS

**Comment by Weathercold** [comment]
Yes
We also need group control of routers

**Comment by OnyxFinger** [comment]
> Yes
> We also need group control of routers

of course.




















I also think guns should be curseable

**Comment by OnyxFinger** [comment]
> > Yes
> > We also need group control of routers
> 
> of course.
> 
> I also think guns should be curseable. And routers of course, for f#ck's sake !

**Comment by Kyllingene** [comment]
Logic? You can just make a preset processor (maybe with a button, too) that makes all the nearby turrets mimick a particular one; then just control that one.

**Comment by Weathercold** [comment]
> Logic? You can just make a preset processor (maybe with a button, too) that makes all the nearby turrets mimick a particular one; then just control that one.

Build-in support is always better than making a logic. With logic you must first have the schematic, which means new players who don't have it will be at a disadvantage, then you must build the processor, which is not available in early game, then you need to link it to the turrets, which costs time, not to mention the firing delay due to processor speed limit.

**Comment by Kyllingene** [comment]
> not available in early game

Why do you think that silicon is late-game in any way? And, if it isn't, then is that not the mapmakers decision?

> then you need to link it to the turrets,

If you pre-link it to every potential place for a turret before copying the schematic, it will automatically link to each available block in its radius. It then loops through the connections, and sets each one's firing details. If it isn't a turret, it doesn't actually change anything. Did I mention I do very little logic?

> not to mention the firing delay due to processor speed limit.

Unless you are controlling a sea of solid duos, there should not be a delay longer than the turrets reload time. Bigger processors with more range also get more speed.

**Comment by Weathercold** [comment]
> Why do you think that silicon is late-game in any way?

I know silicon is not late game, however with silicon you can only build micro processors, which as I said are slow. If you want to build logic processors, you must have thorium, which I would consider to be mid game.

> If you pre-link it to every potential place for a turret before copying the schematic, it will automatically link to each available block in its radius. It then loops through the connections, and sets each one's firing details. If it isn't a turret, it doesn't actually change anything. Did I mention I do very little logic?

That will significantly decrease the processor speed, even if you use jump to not execute code if the linked block isn't a turret.

> Unless you are controlling a sea of solid duos, there should not be a delay longer than the turrets reload time. Bigger processors with more range also get more speed.

As I said, you can't build bigger processors in early game. And there are likely much more turrets in late game, so you would link a lot more of them, which practically cancels out the hyper processor's speed bonus.

**Comment by Kyllingene** [comment]
> If you want to build logic processors, you must have thorium, which I would consider to be mid game.

Why would you need that much turret control early-game?

> That will significantly decrease the processor speed, even if you use jump to not execute code if the linked block isn't a turret.

Not significantly, again considering the turret reload speed, and the fact that *they keep shooting between updates*. If you need the extra speed, you can manually delink.

> As I said, you can't build bigger processors in early game. And there are likely much more turrets in late game, so you would link a lot more of them, which practically cancels out the hyper processor's speed bonus.

Why would you need faster processors in order to handle slower-firing turrets that take up more space, resulting in fewer of them?

**Comment by Kyllingene** [comment]
![turretcontrol](https://user-images.githubusercontent.com/69094702/119900442-61b02500-bef9-11eb-8f52-3f09947c165e.gif)
Do you really think that a small sacrifice in setup is worse than a ton of effort on the part of Anuke to allow us to, without using any level of skill or intelligence, use turrets in a way not intended?

**Comment by Weathercold** [comment]
> Why would you need that much turret control early-game?

As you said, for a sea of duos.

> Not significantly, again considering the turret reload speed, and the fact that *they keep shooting between updates*.

I never tested that, but there will still be a start and stop delay. The logic implementation will never be as smooth as built-in support.

> Why would you need faster processors in order to handle slower-firing turrets that take up more space, resulting in fewer of them?

I don't think Tsunamis and Spectres are slow-firing turrets. Yes, early game turrets are small, but that doesn't mean you need more of them, because the enemies are also weak. In late game, you would need multiple defense lines in order to handle toxopids and flying units. TL;DR, the number of turrets still increases.

**Comment by Kyllingene** [comment]
> As you said, for a sea of duos.

That's your first mistake; a sea of duos would be impossible to feed early-game.

> The logic implementation will never be as smooth as built-in support.

Of course not; the point is that, since this is already possible, making Anuke spend precious time on it is frivolous.

> I don't think Tsunamis and Spectres are slow-firing turrets.

But they keep firing anyway, so those area-of-effect turrets should be fine.

> In late game, you would need multiple defense lines in order to handle toxopids and flying units. TL;DR, the number of turrets still increases.

Then use more processors? The maximum amount of late-game turrets a hyper processor can manage to get to should be perfectly manageable. Either way, a turret group function larger than that would be overpowered.

**Comment by Weathercold** [comment]
> Do you really think that a small sacrifice in setup is worth than a ton of effort on the part of Anuke to allow us to, without using any level of skill or intelligence, use turrets in a way not intended?

How is controlling multiple turrets "a way not intended?" And why do you care about the level of intelligence used to operate a bunch of turrets? I would argue that once you have the turret control logic, you don't need much intelligence to use it either.

**Comment by Kyllingene** [comment]
> How is controlling multiple turrets "a way not intended?"

I simply feel that the whole concept of a resource-management tower-defense game isn't supposed to help you fight the enemies yourself. Sure, controlling a unit and making an attack on an enemy base is one thing; but manually defending your base by mass-controlling turrets sounds iffy to me.

> And why do you care about the level of intelligence used to operate a bunch of turrets?

Because Mindustry is an intelligence-based game.

> I would argue that once you have the turret control logic, you don't need much intelligence to use it either.

No, but unless you bother to learn the tiniest bit of programming, you will get less-than-optimal results; so, to get good results, it takes effort. To get unoptimal results, it takes little.

**Comment by Humanoid-X** [comment]
Hey, I'm thinking... Maybe this type of suggestion is why low intelligence human still survive on Earth...

**Comment by OnyxFinger** [comment]
> ![turretcontrol](https://user-images.githubusercontent.com/69094702/119900442-61b02500-bef9-11eb-8f52-3f09947c165e.gif)
> Do you really think that a small sacrifice in setup is worse than a ton of effort on the part of Anuke to allow us to, without using any level of skill or intelligence, use turrets in a way not intended?

this is the problem. The gap between logic users and not logic users is way too big. This is probably no supposed to be a thing. Stop letting it get wider. Also if you think about this, unit control has no point into existing since logic for smarter stuff is easier to do. There is also no point into making this kind of logic since it useless just about enough of the times you woont spend your time on it, but just about useful enough that you want it.
I think this is still alright

**Comment by OnyxFinger** [comment]
> Hey, I'm thinking... Maybe this type of suggestion is why low intelligence human still survive on Earth...

maybe YOU are the example.
As much as it is painful, you need to explain why you think this.

**Comment by Kyllingene** [comment]
> Hey, I'm thinking... Maybe this type of suggestion is why low intelligence human still survive on Earth...

Hey, I'm thinking... Maybe this type of comment is why toxic humans still survive on Earth...

**Comment by BorisA11** [comment]
Agreed. Should add.
