### ISSUE TITLE
Game meta on multiplayer

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry-Suggestions#2490]
I have played many multiplayer games, mostly on Attaner server, and I noticed some patterns that always repeat in these games. I'll try to list as many here, whichi might help with future plans and balancing. Also listing common issues that lead to various unfun things in game.
Overused:
-Mega ships for building (not a bad thing, just they are really overused)
-Flare swarming with logic (and their kamikaze attacks with blast, because explosives can be taken via logic)
-Zenith spammin'
-Sand-to-sili schematics (every sand you can find is covered in these)
-Quads. (and sometimes quad nuking if in neutral terittories.)
-Logic increasing range of turrets (mostly Salvo and spectre, not neceserily a bad thing)
-Foreshadow siege and spamming (carry a container of surge and pipe some water, and enemy team is in big trouble)

Underused:
-All spiders except t1 and t5 are literally never used. They are sometimes made, but dont do anything
-T4 naval and assault air units (Sei is like better Antumbra, and Antumbra is mostly bad. Considerably worse than a Quad or a Reign)
-Solar power
-Shock mines

Issues:
-Foreshadow defending the core from basically everything. 
 On all multiplayer maps with more tha 1 core, the last remaining one is fortified with plastanium swarmers and usually 1 foreshadow. That bad boy repels everything heavier while smaller ships cant pass due to swarmers. This leads to stalemates and the clear winner needing to take down the last flippin' core. Then this side needs a few tier 5s which take a long time to make.

-Vaults explode near cores, annihilating them. This leads to vaults and containers being used only by some beginners, while are almost never used by expirienced players.

Where did the Xs go?
Anyway, I checked it all.

**Comment by itcannotbe** [comment]
This will be a pain to discuss.

**Comment by itcannotbe** [comment]
Solar panels are purposely underpowered because:
Free energy
Easy spammable

The only thing holding it back from being spammed is it's measly power output.

Plus it's use case is shot out of the gate.

Want a tiny amount of power?
Well, ~use solar panels~ **Extend your power grid to the place where you need it**

Now there's that.

**Comment by itcannotbe** [comment]
Exploding vaults you say?

I'm sorry but it seems you it had explosive/flammable items inside of it.

**Comment by itcannotbe** [comment]
> Where did the Xs go?
Anyway, I checked it all.

You're extremely delusional if you have claim that you checked them. Even a single one.
Schedule an appointment with a psychiatrist, ASAP.

**Comment by OnyxFinger** [comment]
> I have played many multiplayer games, mostly on Attaner server, and I noticed some patterns that always repeat in these games. I'll try to list as many here, whichi might help with future plans and balancing. Also listing common issues that lead to various unfun things in game.
> Overused:
> -Mega ships for building (not a bad thing, just they are really overused)
> -Flare swarming with logic (and their kamikaze attacks with blast, because explosives can be taken via logic)
> -Zenith spammin'
> -Sand-to-sili schematics (every sand you can find is covered in these)
> -Quads. (and sometimes quad nuking if in neutral terittories.)
> -Logic increasing range of turrets (mostly Salvo and spectre, not neceserily a bad thing)
> -Foreshadow siege and spamming (carry a container of surge and pipe some water, and enemy team is in big trouble)
> 
> Underused:
> -All spiders except t1 and t5 are literally never used. They are sometimes made, but dont do anything
> -T4 naval and assault air units (Sei is like better Antumbra, and Antumbra is mostly bad. Considerably worse than a Quad or a Reign)
> -Solar power
> -Shock mines
> 
> Issues:
> -Foreshadow defending the core from basically everything.
> On all multiplayer maps with more tha 1 core, the last remaining one is fortified with plastanium swarmers and usually 1 foreshadow. That bad boy repels everything heavier while smaller ships cant pass due to swarmers. This leads to stalemates and the clear winner needing to take down the last flippin' core. Then this side needs a few tier 5s which take a long time to make.
> 
> -Vaults explode near cores, annihilating them. This leads to vaults and containers being used only by some beginners, while are almost never used by expirienced players.
> 
> Where did the Xs go?
> Anyway, I checked it all.

As an experienced 1v1 player (spare me the fact that 1v1 isn't like team pvp, team pvp is about rolling a dice for enough good teamates, because if you get some bad ones, things will go south), I have a good knowledge of what is balanced and what isn't in this game. You said things that were true, especially PvP being OVERLY unbalanced, however, a lot of what you are stating here is severely flawed by lack of experience.

so you're just saying what everyone knows clap clap
Flare kamikaze is easily dealt with because they'll die too fast
Megas because WHY NOT ? POLIES ARE MORE SPAMMABLE AND UP UP BEING AS EFFICIENT, WHILE YOU SPEND ALL OF YOUR RESSOURCES ON T3 JUST FOR MEGAS (this is important, T3 needs a lot of ressources to be built and run, you better make offense instead of megas that can be replaced by builders), megas need a buff in general, since there is no point into dropping units with them, and even if you could try for an advantage, it is, as I said, too pricy, you wont get enough out of them with it.
Sand to sili < Normal sili, sand to sili is far less price efficient
Quads suffer from force projector being able to block all of their AOE, making them useless against anyone with a bit of knowledge about bullets and how to block them / reduce their damage.
Logic increasing the range of turrets : Generally I'd say it's quite good, however it is for now needed as too many units can outrange a bunch of guns and blablabla, but once this outranging issue ever gets fixed, it should get nerfed. This means the unit range issues have to get fixed for V7, as range upgrades with logic are patched.
FS in PvP, where you can kill the oponent with T3, but nah, let's tech rush first then get killed by an overwhelming amount of units. FS is kinda broken still though.

Underused : all spiders blablabla : Correct. These are bad because they're only good if they get close, which they wont, except arkyids, but T4s in general suffer too much from the time by which you can get them, which is just about high enough that people can start getting FS, which pulls them back.
T4 assault air and naval : this one is interesting. T4 naval is limited, but has extreme dps, health, and better speed. Other T4s all suck because of what I explained earlier, especially antumbras, they terrible.
Solar panels : yes. ItCannotBe said that it was balanced, but quite frankly, anyone who has a bit of experience knows it's not the case, solar panels suck.
Shock mines : Lack of experience. Shock mines deal ~200 damage per shot, and even know they take a while to place, with a few builder units, this time is reduced by a lot. 1v1 players can just place shock mines under the feet of ground units, and deal a tone of damage to them, which is why ground is so unused : its units get hit very hard, and are too slow to retreat. 

Issues : 

FS : you will need a lot of FS for crowd control, and protecting your power, where then they will be drainable because of how much they take per shot, but you simply wont have enough ressources even before getting this many.

Vaults exploding near core : yes. There was just a suggestiong about vaults and containers getting more HP when being near a core, but for some reason, the idiots that are in this place and basically don't play the game enough / the specific gamemode enough to have a worthy word to say about it turned it down. idk that's very stupid if you want my opinion.

**Comment by OnyxFinger** [comment]
> Solar panels are purposely underpowered because:
> Free energy
> Easy spammable
> 
> The only thing holding it back from being spammed is it's measly power output.
> 
> Plus it's use case is shot out of the gate.
> 
> Want a tiny amount of power?
> Well, ~use solar panels~ **Extend your power grid to the place where you need it**
> 
> Now there's that.

not cost effiecient. The end. There is no way this is useful, and noone with a bit of brain uses these. THey should purposefully not be as good as other generators, but not underpowred, since underpowered = lack of balance. idk you seem to like things being unbalanced bruh.


> Exploding vaults you say?
> 
> I'm sorry but it seems you it had explosive/flammable items inside of it.
> 
> Also you don't need to stock pile a lot of resources. Just end the game as fast as possible by actually pushing offense early on, not dragging and letting your enemy turtle their core/s.

That's not easy and the games will go up to T3 many times, at least that, and because of this, thorium, which will blow up. Just make the explosions not destroy friendly buildings just like units don't kill each other, and everything is fine. Why would you make something blow up on you when it has at least on of the idk how many flammable and explosive ressource in the game, this is purposefully making it bad.

> > Where did the Xs go?
> > Anyway, I checked it all.
> 
> You're extremely delusional if you have claim that you checked them. Even a single one.
> Schedule an appointment with a psychiatrist, ASAP.

No u. Also you are a nice person and I want to be friends with you, may I ask if there is a report button ?

**Comment by itcannotbe** [comment]
> > > Where did the Xs go?
Anyway, I checked it all.

> > You're extremely delusional if you have claim that you checked them. Even a single one.
Schedule an appointment with a psychiatrist, ASAP.

> No u. Also you are a nice person and I want to be friends with you, may I ask if there is a report button ?

There isn't any checkboxes to be checked @OnyxFinger
If you also manage to find check boxes. That's called a delusion. I would highly advise for you to also consult a medical professional regarding the matter.

**Comment by BorisA11** [comment]
> > Where did the Xs go?
> > Anyway, I checked it all.
> 
> You're extremely delusional if you have claim that you checked them. Even a single one.
> Schedule an appointment with a psychiatrist, ASAP.
@itcannotbe I mean I checked for keywords to see if these arent reported already

**Comment by itcannotbe** [comment]
The balancing/feedback template doesn't have a checkboxes.

The template only contains the following:

`**Describe what you would like changed, and why.**



**Describe the changes you want to propose. Include possible alternatives.**`

That's it.

**Comment by OnyxFinger** [comment]
> > > > Where did the Xs go?
> > > > Anyway, I checked it all.
> 
> > > You're extremely delusional if you have claim that you checked them. Even a single one.
> > > Schedule an appointment with a psychiatrist, ASAP.
> 
> > No u. Also you are a nice person and I want to be friends with you, may I ask if there is a report button ?
> 
> There isn't any checkboxes to be checked @OnyxFinger
> If you also manage to find check boxes. That's called a delusion. I would highly advise for you to also consult a medical professional regarding the matter.

still very mean. VERY mean.

**Comment by itcannotbe** [comment]
The truth hurts, deal with it.

**Comment by OnyxFinger** [comment]
> The truth hurts, deal with it.

Like the fact that you keep on talking like if you had any bit of experience about what you're talking about but you don't ? Yes. It does hurt. I'm very sorry for you.

**Comment by BorisA11** [comment]
@OnyxFinger I know each of the said things are useful, and can be used. I just said they are not. And some are just overused. Not saying that anything needs direct balance, although it could use it. Like Antumbras, poor ships, almost never used.

**Comment by BorisA11** [comment]
@OnyxFinger I personally really like to use Seis, although they never work as good as others. Not to talk about the tier 4 spider, its even weaker.

**Comment by oinkymoo** [comment]
> > > > Where did the Xs go?
> > > > Anyway, I checked it all.
> 
> > > You're extremely delusional if you have claim that you checked them. Even a single one.
> > > Schedule an appointment with a psychiatrist, ASAP.
> 
> > No u. Also you are a nice person and I want to be friends with you, may I ask if there is a report button ?
> 
> There isn't any checkboxes to be checked @OnyxFinger
> If you also manage to find check boxes. That's called a delusion. I would highly advise for you to also consult a medical professional regarding the matter.

there are checkboxes in feature request but not in balancing/feedback, which is likely why @BorisA11 was confused

**Comment by OnyxFinger** [comment]
yes
