### ISSUE TITLE
Live turrets on payload conveyors

### ISSUE THREAD

**Issue by dyussss** [Anuken/Mindustry-Suggestions#2534]
**Describe the content or mechanics you are proposing.**
Turrets that actually function while on a payload conveyor, so you could have some turret trains that loop around the map 

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

Its useful if you have limited resources and cannot place down turrets everywhere to shoot enemies down and circling turrets might help

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [ ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
units can do that

**Comment by Noob17** [comment]
This would likely not be implemented, but the concept is pretty interesting. Someone could use this to make a custom map involving running after 'trains,'

Much like StarCraft 2's 'Great Train Robbery'

Balance wise, this would be a little problematic since people could just load strong turrets and move them into weak portions with ease.

**Comment by OnyxFinger** [comment]
> This would likely not be implemented, but the concept is pretty interesting. Someone could use this to make a custom map involving running after 'trains,'
> 
> Much like StarCraft 2's 'Great Train Robbery'
> 
> Balance wise, this would be a little problematic since people could just load strong turrets and move them into weak portions with ease.

pretty much yes
I like this idea, but there is no way it's balanced in my opinion : 
It wouldn't (probably) really matter in survival, it would be... very useful in attack, and in pvp, very OP, as normally in this game, guns are stronger than units, so the unit's only shot at doing well is either being in an overwhelming group, being a stronk unit, or going around stuff
In PvP, well, unless you play team pvp with this giant wall, you want go to T3, because you can and it's way faster than higher tier units, which would drag out matches and make them annoying (this is why I would love team pvp to either get yeeted off the mind of players, or to not have gigantic walls), which means.. you don't want to go T4, cuz it just gives boring gameplay, and you'll die before (to mass T3)
you can't go around the guns anymore since they move (yes, they're slow, but it is possible to stall the units with walls or idk), so this solution is bad, last option though, mass T3, works, but it would take long to get ~~and mass moving guns ohno~~

**Comment by skipydog** [comment]
> Balance wise, this would be a little problematic since people could just load strong turrets and move them into weak portions with ease.
This can already be done with the Mega. I don't see how this could be a problem if the Mega could already do this and it has never been a problem.

**Comment by itcannotbe** [comment]
> > Balance wise, this would be a little problematic since people could just load strong turrets and move them into weak portions with ease.
> 
> This can already be done with the Mega. I don't see how this could be a problem if the Mega could already do this and it has never been a problem.

Does the turrets that the mega is carrying can shoot?
No. You need to place them down first.

**Comment by skipydog** [comment]
> > > Balance wise, this would be a little problematic since people could just load strong turrets and move them into weak portions with ease.
> > 
> > 
> > This can already be done with the Mega. I don't see how this could be a problem if the Mega could already do this and it has never been a problem.
> 
> Does the turrets that the mega is carrying can shoot?
> No. You need to place them down first.
It's still a lot fast movement than payload conveyers and they can be placed down without delay, not to mention how megas can go over blocks and don't even need a path of blocks to take a turret from one place to another. This can also easily be used with logic to make them automatically place them down on sight of an enemy.
