### ISSUE TITLE
Import / Export Emotes Button

### ISSUE THREAD

**Issue by Nicky-Pixel** [Anuken/Mindustry-Suggestions#2552]
Works like Import/Export schematics, but with images to be available on schematic tags and sector emote page. It's just to give more creativity and organization to the players. For example, Imagine separate sectors from difficult with Geometry Dash difficulty icons lmao

whatever, that's infinite possibilities with this feature.

(sorry my english, just tried)

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
template plz

**Comment by rodrigolitzius** [comment]
Why do people always forgot about the template?

**Comment by Humanoid-X** [comment]
1. template
2. basically, a texture pack? ~no one else except you want this feature, go make a mod yourself~

**Comment by Kyllingene** [comment]
The problem: how do others (in a server, for example) see your emotes? How are they stored? Normally, you could assign each emote a number, and just send/store that number; but when you can import emotes, you must change everything so that you actually send/store that emote in its entirety, which is a lot more space (and, 99% of the time, the wrong choice).
