### ISSUE TITLE
Different Unit Formations

### ISSUE THREAD

**Issue by SeaPuppy2006** [Anuken/Mindustry-Suggestions#2553]
The addition of new unit formations (when controlled by a player) specifically single file and V formation.

This will help with manuvering groups of ground units through spaces with alot of blocks in it, as often they get stuck and slow everything down. It can also help during attacks with certain defenses that the units arent next to the player.

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Hyrotrioskjan** [comment]
logic exists but i guess this is a good idea too.

**Comment by MrDuck557** [comment]
Two questions
How do you change formation?
How do you know which formation you have selected before commanding?

**Comment by RedstonerKBC** [comment]
I hate to go off on a tangent but I don't want to make an entirely new issue so closely related to this one. This suggestion gave me an idea.

What if you pressed a button that lets you select a formation? The button brings up a list of formations (like the schematics folder) that you can customize. It would solve three issues: 1. How to change formations 2. How to get different formations with different groups of units. 3. Units no longer bump into you when you command them (unless you put them too close). Selecting no formation makes units do the default circle that they already do now.

This would require an editor that lets you customize formations. The editor should be (in my opinion, for convenience) in-game rather than through a menu (May or may not be a good idea. Let me know what you think. We can always make it an editor through the menu similar to the map editor). It's very simple. First, you can either manually select the number of units to command or select a unit which automatically sets it to that unit's command limit. Then you can drag the yellow dots (representing the commanded units) around and place them relative to where you want them. A line in the center white dot shows the direction the commander is facing for reference, similar to how the maps in the Hitman games show current heading. You can then save it as a unit formation file, similar to schematics. Pressing a button in game lets you choose from the list of command formations. Clicking one automatically sets it to that. When you command units they'll try to follow that formation no matter which units you command. The circle formation is the default fallback when players select no formation.

**Comment by OnyxFinger** [comment]
> Two questions
> How do you change formation?
> How do you know which formation you have selected before commanding?

UIs go weee
this would cause a problem to phone players though, who won't have much space left, so I guess your point is still valid

**Comment by Kyllingene** [comment]
Do you know just how hard it was to make formations? And how much effort it would take to make *customizable* formations?

As to the original issue, the only problem I see is the UI problem.

**Comment by SeaPuppy2006** [comment]
> Do you know just how hard it was to make formations? And how much effort it would take to make _customizable_ formations?
> 
> As to the original issue, the only problem I see is the UI problem.

It doesnt have to be customizable, just a few varieties if custom ones arent possible. In terms of UI, I was thinking about a dropdown with the top left UI that only appears when using formations.

> How do you know which formation you have selected before commanding?

The formation should reset to the currently used (default) formation every time it is disbanded
