### ISSUE TITLE
Launch pad nerf

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry-Suggestions#2570]
**Describe what you would like changed, and why.**
Launch pads, as of now, are really op.
They're useful for maximizing the potential of sectors, but it makes capturing sectors too easy, allow me to elaborate:
This is based off my experience with the campaing, you can just launch to a sector, have your main sector constantly launch resources to the sector you're currently playing on, build some defenses, and unload off the core for the ammo, and bam, you won the sector, something similar applies to enemy bases too.

**Describe the changes you want to propose. Include possible alternatives.**

Make launch pads not work on sectors that are under attack, both import and export, or some sort of tax/increased cost to launch to sectors like that.
Maybe make the launch pads on those sectors go off-course and land somewhere placing a contairner/vault with the items somewhere on the sector, requiring you to get it instead of being sent directly to the core.

**Comment by Ineedause** [comment]
I disagree, right now launch pads suck because they are supposed to update every minute but they update every 10 instead, this is inefficient when trying to capture sectors because you have to wait 10 mins before you get 5k resources, and before you say, sitting in the sector with the launch pads will result in a loss of the sector you are attacking.

**Comment by OnyxFinger** [comment]
woopsy
I should intervienned, one guy talked about how they are OP (true), the other talked about how their mechanics suck
