### ISSUE TITLE
improve Air unit ded effect

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry-Suggestions#2602]
**Describe the content or mechanics you are proposing.**
make Air Unit when they dead and fall into a liquid pool make some w a v e  e f f e c t
**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
make unit ded effect better (and cause more lag to the game)
**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
You know, I'm starting to believe that that line that used to be in the template actually *did* help, because nobody nowadays seems to check suggestions. Anyway, *pleasepleaseplease* try searching something as simple as [`is:issue death effect`](https://github.com/Anuken/Mindustry-Suggestions/issues?q=is%3Aissue+death+effect) (try clicking the link). This is a duplicate of soooo many other issues, including one that was made today (or maybe the notification caught me late and it was yesterday).

**Comment by SMOLKEYS** [comment]
Poll:

Should anuke place these types of suggestions on:
"A few things you shouldn't suggest:"?

Like seriously, i've seen so much of these suggestions its starting to get annoying.

**Comment by Kyllingene** [comment]
yes please, there nothing new to be brought to the table

**Comment by vinhsad** [comment]
yea, sorry

**Comment by oinkymoo** [comment]
the best part is that this suggestion was posted 3 hours after another suggestion suggesting the same exact thing except more

**Comment by Humanoid-X** [comment]
lol
