### ISSUE TITLE
Vehicle Factory

### ISSUE THREAD

**Issue by PASyther** [Anuken/Mindustry-Suggestions#2610]
Is there a reason there are no car or tank type units in the game?

I feel like it's a pretty obvious and simple addition that would just flavour things a little more.

If you need ideas that's a different case, I've got a few and I'm sure other people could suggest some too - We desperately need a long range land unit.

**Comment by BlueWolf3682** [comment]
1. Template.
2. No, it wouldn't.
3. No, we don't.
4. If you want it, add it in a mod or find one that does.

**Comment by oinkymoo** [comment]
why would a vehicle unit exist? all the units can move independently, which is why mechs are used. also, the dagger tree probably already does whatever you suggest the vehicle tree would do

**Comment by OnyxFinger** [comment]
but these would need a driver, **except that the only organic thing in the game's lore is stuff like spore or grass**

**Comment by Bottinator22** [comment]
> but these would need a driver, **except that the only organic thing in the game's lore is stuff like spore or grass**

Vehicles in games aren't always driven by something, look at some RTS games for example, like Planetary Annihilation.

**Comment by Kyllingene** [comment]
> We desperately need a long range land unit.

No, not really. Why? Because, as things stand, you use the different classes for different things; you use land mostly for brute-force attacks (except for leg units, which are great for special ops), air both for heavier assaults and as support (they especially shine in logic schems), and you use water for long-range destruction and heavy damage, where it's available.

It really bugs me how many people want to homogenize and flatten the Mindustry unit system. It is not designed to be simple, it is designed to be flexible and powerful when used right. If you don't like strategy, play a different game.

> I feel like it's a pretty obvious and simple addition that would just flavour things a little more.

Exactly how? What would faster land units bring to the table? Would you rather have 50 different types of soda in your fridge, all clogging it up, but only 2-3 that you actually like? Or would you rather have 5 different kinds of drink, all of which you like for different situations? Apply the same logic to *everything you can*, including Mindustry.

###### ~thank you for coming to my ted talk~

**Comment by itcannotbe** [comment]
> ###### ~thank you for coming to my ted talk~

####### I do not regret coming to your ted talk.

**Comment by Humanoid-X** [comment]
**good ted talk tbh**
