### ISSUE TITLE
Merch

### ISSUE THREAD

**Issue by Fabizocker456** [Anuken/Mindustry-Suggestions#2635]
**Describe the content or mechanics you are proposing.**
Mindustry Merch

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It's a great way for fans to show themselves, as well as, maybe?, introducing more people to the game

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
And Anuke would get this money from where? Certainly not the $5 it takes to buy the game on Steam, the only paid platform; and not from donations, since that would certainly not support merch.

**Comment by BorisA11** [comment]
That aint a bad idea. We all want plush gammas.

**Comment by genNAowl** [comment]
There's a high chance that this suggestion will go up in flames. Time to subscribe!

**Comment by Fabizocker456** [comment]
I was thinking about corvus t shirt but ok

**Comment by Fabizocker456** [comment]
Sorry accident

**Comment by BorisA11** [comment]
I am thinking of shirts, and mini models, like 3D print ones. That would sell as crazy. Imagine a real Eclipse model, or a rotatable Spectre model. Pretty cool, huh?

**Comment by Bottinator22** [comment]
> And Anuke would get this money from where? Certainly not the $5 it takes to buy the game on Steam, the only paid platform; and not from donations, since that would certainly not support merch.

Merch means "merchandise" - he can sell the merch for a profit, like most people do, I'd think

**Comment by Kyllingene** [comment]
Certainly the merch would generate revenue; the problems being, of course, both that he has to shell out cash for a non-guaranteed return, and that at any moment he could lose a bunch of green if people stop buying it enough. Any risk of losing money to a nearly-unpaid solo dev is a big risk, and one you can hardly expect them to take. I mean, really, who are we to tell Anuke what to do with his money?

**Comment by itcannotbe** [comment]
Merch is bad because you actually need to spend money a significant amount of money, to make a small amount of money after costs in return.

Without the guarantee of every single item being sold. Which is basically wasting your money.

Let's not forget that you need to find people to buy the raw materials, and people whom will actually make the merchandise. And the headache of dealing with product returns.

Also you will need run a website to sell the merch on, then lose a portion of the selling price to transaction cost with payment processors, then also deal with the headache of charge backs.....

My advise to anuke. Just don't. It's not worth the headache for a single person to deal with.

**Comment by OnyxFinger** [comment]
W T F F  is this\

**Comment by notMEEPoffaith** [comment]
gib alpha model
