### ISSUE TITLE
Sandbox wall

### ISSUE THREAD

**Issue by Fabizocker456** [Anuken/Mindustry-Suggestions#2653]
**Describe the content or mechanics you are proposing.**
An indestructable sandbox wall that neither lasers nor air units can pass

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
When I want to test unit hp, immunities or similar stuff in sandbox, I always need to use elaborate defenses that have a lot of health but deal no damage. A single block could fix that.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
3. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Are we just basically recycle suggestions now?

**Comment by Fabizocker456** [comment]
--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.

**Comment by oinkymoo** [comment]
i agree with the reactions on discord; this would be much better in a mod than the base game

**Comment by oinkymoo** [comment]
building off what i said earlier. think about everything that is currently changed in sandbox. instant build time. infinite build range. build for free. sources and voids. no wave timer. what do all of these things have in common? they allow you to do things faster, (or in the case of the removed wave timer, at your own pace) either by literally doing things instantly when they otherwise would take time, or by allowing you to skip steps, such as gathering resources or setting up power

**Comment by Kyllingene** [comment]
As itcannotbe implied, this suggestion has been suggested multiple times before. Anuke, please bring back the checkbox!

**Comment by BiggerBrainYT** [comment]
Although this seems to be a repeat suggestion, I think it would make a great suggestion, especially with building maps with friends. Rather than swapping between editor and sandbox to test out things, it would save a lot of time in inviting your friends over and over. I don't understand why people say this feels modded.

**Comment by oinkymoo** [comment]
@BiggerBrainYT i really do not see how what you're saying is relevant to the suggestion. the wall being suggested i the defensive kind, not the terrain kind. they are different

**Comment by SupremeTurtle** [comment]
You could just set block health extremely high or unit damage extremely low.

**Comment by Fabizocker456** [comment]
The point is that it should block lasers and air units, and should be truly invincibleAm 11.07.21, 15:13 schrieb Gwapo ***@***.***>:

   
  You could just set block health extremely high or unit damage extremely low.
