### ISSUE TITLE
RTG generator balance 

### ISSUE THREAD

**Issue by Kryvytsky** [Anuken/Mindustry-Suggestions#2655]
**Describe what you would like changed, and why.**
Make RTG on Phase worth to use. Just like Steam generator could use different materials to work. 
**Describe the changes you want to propose. Include possible alternatives.**
Make it work on Phase by 100% power, but much longer or something like that. It shouldn't be meta, but make it worth to use.

**Comment by itcannotbe** [comment]
I don't get it why you just didn't use the active thread for this. Seriously? 😑

It literally #2654

**Comment by Kryvytsky** [comment]
#2654 talking about building cost of RTG. I have another issue.

**Comment by itcannotbe** [comment]
> #2654 talking about building cost of RTG. I have another issue.

No it's talking about RTG with respect to game balance.
Which basically mean the whole block, not parts you dislike about it.

**Comment by itcannotbe** [comment]
Furthermore why would phase give more power to RTG when it's less radioactive than thorium?

**Comment by Kryvytsky** [comment]
1 Phase consist of 4 thorium.
I said already. Why not make alternatives? Juts like Steam generator use different materials, so why not RTG?

**Comment by Humanoid-X** [comment]
again this is not a game about realism so **I** say no to 400% radioactive phase

**Comment by Noob17** [comment]
The phase power option for the RTG generators is just a huge scam, as it gives off way less power, and works at the same efficiency rate as thorium generation. By this rate, a player should already have a steady flow of thorium nearby and should utilize that, so why is phase even an option?

**Comment by itcannotbe** [comment]
> The phase power option for the RTG generators is just a huge scam, as it gives off way less power, and works at the same efficiency rate as thorium generation. By this rate, a player should already have a steady flow of thorium nearby and should utilize that, so why is phase even an option?

Because phase fabric is also radioactive.

**Comment by Kryvytsky** [comment]
Curently Phase fabric producing 50% of RTG power. To craft it we use 4 thorium. So 1 Phase worth 1/8 (12,5%) Thorium.
So why not make it actual good option. Maybe this would be used on campaign or in schematics if that have buid in Phase factory.

**Comment by RouterChainsSuckk** [comment]
i suggested all these ideas before, (bulid cost and phase being useless) and everyone said it was stupid...

**Comment by oinkymoo** [comment]
you should probably mention phase in the title for clarification

**Comment by notMEEPoffaith** [comment]
the radioactivity affects it, and nothing else, you know that, right?

**Comment by Sector171** [comment]
First, the cost of RTG  from part and efficiency of phase as input for it from the second part are two different things so you did the right thing by using new thread(where i disagree with cost issue since RTG is really over powered and need to be expensive to compensate, but i agree with the suggestion in this thread)

Lets see how RTG work :

> Use the heat of decaying radioactive compounds to produce energy at slow rate

This mean one item of thorium should produce the same amount of power regardless if it is pure or part of another compound like phase.
Also the comparison between using another items like blast or pyratite as input for steam gn and this is totally wrong, cus using coal to make new compound could make the new one more or less flammable or even non flammable that's ok, but nothing can affect the radioactive feature of thorium (on normal chemical level)

If we take one gram of thorium and one gram of phase, the gram of phase will produce about 28% of thorium one since this is the percentage of thorium in phase but ....
WE ARE NOT TALKING ABOUT GRAMS, BUT ITEMS. and one item of phase has 4 items of thorium so...

1-either one phase should give x4 (1080) of what one thorium give with the same production time.(the best)
2-or one phase give 28% (75) but it lasts about 200 seconds!
3-one phase give the same (270) but last x4 (56) seconds

The first case will make it so useful in some situations (especially campaign when conquering new sector) , also will decrease number or RTGs required to 25% if there are massive production of phase, but could make it so powerful.

Anyway in normal cases no one will use phase as input to rtg even if one of this gets applied since using thorium is simpler and give the same amount of power , but in selective cases could be a great solution.
