### ISSUE TITLE
Register shader layers

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry-Suggestions#2734]
### Describe the content or mechanics you are proposing.

Mods should register shader layers (e.g. Layer.shield, Layer.buildBeam) to the renderer, instead of drawing shaders themselves.

A method in Vars.renderer would accept a shader, and return its float layer value. It should be placed around the shield layer, and optionally be disabled by the draw shields settings.

Of course, this would only apply to the in-game draw type shaders, not the weird ones that apply to the whole screen.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Currently, mods (well, PU) does shader layers this way, but when other mods also do this (well, BetaMindy or the like) things are gonna get ugly because there is no way the 2 mods can avoid each other's layers (e.g. Layer.bittrium may be same or similar to Layer.blueGlennThingy) and things will get ugly.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Anuken** [comment]
> It should be placed around the shield layer

Why? What if a mod wants to place it somewhere else, like on the ground, or above other specific effects?

> would accept a shader, and return its float layer value

Layers have to be spaced out properly, and if more than a few are added you'll start running out of room or encroaching over built-in layers. Furthermore, registering layers this way will lead to unpredictable and potentially buggy layer order, since mod load/registration order may vary depending on client.

I don't see many people even needing to use layers this way; many effects can just be drawn to a framebuffer and rendered without any potential conflicts. In the rare case that a conflict does occur, it would be better to coordinate it between the two mods rather than use some super-specific registration system that doesn't support many valid use cases.

**Comment by sk7725** [comment]
> Why? What if a mod wants to place it somewhere else, like on the ground, or above other specific effects?
I meant for only shaders that should render in the same manner as Shaders.shield or buildBeam, as they are layer-dependent and there is a good chance that 2 mods will try to "fight" layers

**Comment by sk7725** [comment]
shaders that are used in various other levels (like unitBuild) are no problem, as those are used by Draw.draw and do not conflict with each other.

**Comment by Anuken** [comment]
> as they are layer-dependent

My points still apply. Build beams and shields need specific numeric layers, they can't simply be rendered "somewhere around shields".

> there is a good chance that 2 mods will try to "fight" layers

I've already addressed this.
