### ISSUE TITLE
pin logic displays to your hud

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry-Suggestions#2735]
### Describe the content or mechanics you are proposing.

(mildly inspired by the comments at #2731)

i do know its a pipe dream for several reasons, but it would be super super cool to be able to pin logic displays so you can easily look at them from anywhere:
![pic1](https://user-images.githubusercontent.com/45698812/126731870-5500f8ca-cd59-445e-ba06-df5c056393e3.png)
![pic2 v2](https://user-images.githubusercontent.com/45698812/126731943-d8098c0e-363c-4e68-89fd-d83ffcf1e6db.png)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

There are a few clients out there now that let you have power, exact unit health and a bunch of other information in your hud and this would make it possible to do that in vanilla. Seriously, you could do  SO MUCH with this, just to give a few examples; be immediately alerted if a defense gets damaged no matter where you are, track if you have enough resources to research something, you can put up a clock, etc. etc. etc.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I would take to take this moment to say that Logic Displays are 🤮

**Comment by itcannotbe** [comment]
If you are great with logic there are a lot of different ways to get your attention without using displays. Plus Logic sound is still on the trello.

Not adding the fact that additional viewports also takes system resources to render.

**Comment by SMOLKEYS** [comment]
![SmartSelect_20210723-112838_GitHub.jpg](https://user-images.githubusercontent.com/75618732/126734416-ee9e0707-cedc-4433-bd91-8e498bfa9f5e.jpg)
do not

**Comment by Anuken** [comment]
Do not assign issues to me. Any further unnecessary pings will get you blocked from this repository.

**Comment by oinkymoo** [comment]
this would probably not be at all viable on the already-cramped mobile ui

**Comment by Kyllingene** [comment]
> Not adding the fact that additional viewports also takes system resources to render.

Yes, it would take more resources to display extra stuff, but why would you need a viewport to do so? It's a very small display (at max 176*176), so really, you could dramatically increase efficiency by making a custom texture from reading the displays state directly (although I may be totally wrong about the source, and this could be impossible/impractical).

> I would take to take this moment to say that Logic Displays are 🤮

Wrong. They are highly versatile (and well-made) tools that are more than what we could expect from a free resource-management tower defense game. If it is negative coordinates you are complaining about (or rather, the lack thereof), that has already been handled. If not, please, elaborate in a new issue.

However, how would you select a display to pin? How would you order them on the screen? How would you handle a lot of pinned ones? And no, the answer "don't pin too many" doesn't work because you may pin a reasonable amount for your screen size, then resize your screen ever so slightly and suddenly have logic displays flooding over your screen.
