### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by YarikPro2** [Anuken/Mindustry-Suggestions#2743]
### Describe the content or mechanics you are proposing.

Думаю правильнее сделать так, чтобы буры не выводили ресурсы во все стороны, а в одну. Сделать стрелку как направление выхода ресурсов из бура. И возможность заблокировать некоторые стороны выхода из распределей, машрутизаторов, мостовых конвееров и т. д. Больше изучений, к примеру скорость добычи буров, ёмкость аккумуляторов, и чтобы изучение было не моментальное, а занимало время. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Возможность закрыть выходы из конвеерных систем и выход ресурсов из бура в одну сторону, а не во все позволит создавать более компактные заводы. Больше изучений разнообразит игру. Время, требующиеся на изучение добавит реалистичности. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [ ] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
![Screenshot_20210725_201304](https://user-images.githubusercontent.com/45280919/126898547-e4b96aa0-6cf1-4077-bd45-ba7d51acf12f.jpg)
![Screenshot_20210725_201254](https://user-images.githubusercontent.com/45280919/126898561-db4be721-c00a-4e93-8b02-10e5f87a71a1.jpg)

**Comment by itcannotbe** [comment]
Translated:

Describe the content or mechanics you are proposing.

 I think it would be more correct to make sure that the Boers do not withdraw resources in all directions, but in one direction.  Make an arrow as the direction of resource exit from the drill.  And the ability to block some sides of the exit from distributors, routers, bridge conveyors, etc. More studies, for example, the rate of production of drills, battery capacity, and so that the study was not instant, but took time.

 Describe how you think this content will improve the game.  If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

 The ability to close the exits from the conveyor systems and the exit of resources from the drill in one direction, and not in all, will allow the creation of more compact plants.  More exploration will diversify the game.  The time it takes to study will add realism.

**Comment by Yell245** [comment]
> Translated:
> 
> Describe the content or mechanics you are proposing.
> 
> I think it would be more correct to make sure that the Boers do not withdraw resources in all directions, but in one direction. Make an arrow as the direction of resource exit from the drill. And the ability to block some sides of the exit from distributors, routers, bridge conveyors, etc. More studies, for example, the rate of production of drills, battery capacity, and so that the study was not instant, but took time.
> 
> Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
> 
> The ability to close the exits from the conveyor systems and the exit of resources from the drill in one direction, and not in all, will allow the creation of more compact plants. More exploration will diversify the game. The time it takes to study will add realism.

But it is not i/o config?...

**Comment by itcannotbe** [comment]
> But it is not i/o config?...

It is. Read again.

**Comment by Humanoid-X** [comment]
define "Boers"...?

**Comment by YarikPro2** [comment]
> определить "буры"...?

Что? Я так не писал

**Comment by itcannotbe** [comment]
> буры

You did write that though.

**Comment by Kyllingene** [comment]
> define "Boers"...?

Drills. Anyway, please *please* make a different title than "Title". Whether or not it is English, make it descriptive.
