### ISSUE TITLE
Remove Cyclone

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#2764]
### Describe what you would like changed, and why.

Swarmer is the biggest disappointment in the game. Why do we have like 2 essentially same turrets - Swarmer & Cyclone. Yes swarmer has homing and is 2 by 2 but that's the only pros. What cyclone has - more dmg, more ammo types, it's more ammo effective. Finally, they cost about the same and do the same thing - air & ground AoE. Why do we need both of them?

Why cyclone and not swarmer? Because cyclone is (scatter + ripple) while swarmer has homing rockets instead of bullets making it somewhat different.

### Describe the changes you want to propose. Include possible alternatives.

h

**Comment by the-kido** [comment]
Instead, maybe change the plastanium in swarmers to something else like titanium. Or, make cyclone use a harder-to-get material.

**Comment by Noob17** [comment]
Replace Cyclone with a better idea, perhaps. Maybe a turret that shoots a toxopid-like pellet, or a improved version of the fuse, with longer range?

**Comment by Bottinator22** [comment]
Alternatively, just make some balance. No need to remove any turrets

**Comment by funkychicken493** [comment]
Swarmers are more early game, like duos.

**Comment by oinkymoo** [comment]
> Swarmers are more early game, like duos.

This is untrue. They both require titanium and plastanium, but while swarmers cost a little less, they require silicon and graphite while cyclones require only copper (along with tita and plast ofc)

**Comment by GamerMoment69** [comment]
> Describe the changes you want to propose. Include possible alternatives.
h

so the change you want is just h? ok then

**Comment by Kyllingene** [comment]
> Describe the changes you want to propose. Include possible alternatives.

You seem to have mixed up "title" and "explanation of changes", an easy mistake; so next time, instead of vandalizing the template, *use it for its intended and obvious purpose.*

**Comment by oinkymoo** [comment]
This discussion came up before, and we reached the conclusion that both of these turrets serve a similar function (general rapid-fire crowd-control) at the same tech level (plastanium) but swarmers are way worse at it. The solution we came up with was to either a) buff swarmers (which has now happened, ammo consumption was reduced) and/or b) give one of the turrets a different purpose

**Comment by GamerMoment69** [comment]
so anyway, one thing about swarmers and cyclones, it turns out surge ammo swarmers have somewhat more dps than surge ammo cyclone. I ran an experiment and here were the results.
<s>_No units were harmed during this experiment_</s>
<img width="389" alt="SwarmerIsBetter" src="https://user-images.githubusercontent.com/87551951/127393425-d8e60195-2809-4249-ab07-672072be4052.png">
the test dummy used for the turrets was a 50k hp dagger

**Comment by GamerMoment69** [comment]
swarmer got a minor range buff [here](https://github.com/Anuken/Mindustry/commit/fa0f1611064657480f9febc64346afb5a457f6ba)

**Comment by OnyxFinger** [comment]
swarmers don't have worse DPS (in fact, swarmer might be ahead in my opinion, since it probably has more dps with water synergy)
You say there is a difference of like 1-2 but it doesn't change much
~~ammo type generally doesn't matter since both would either use blast or surge~~
and finally, how do aiming bullets make thing different ? You're not gonna try to clean up buildings with swarmers are you ?
I think either cyclones or swarmers should be changed into an AA gun.

**Comment by the-kido** [comment]
just change the point in progression swarmer is in and all of the discussion above won't matter
or, make cyclone harder to get/ later in the game's progression. nothing needs to be removed and only minor rebalancing should happen

**Comment by EclipsePlays** [comment]
Swarmers are heck of a late game turret, its compact but compensates on the ammo usage. 

Compare: 

- 4 block turret that has 500 DPS (bcomp) 
- 9 block turret that has 650 DPS

What makes swarmers very underrated is its ammo, pyratite and blast compound are hard to get material and is also underrated, while surge alloys are too expensive to be used as an ammo. 

Maybe add a new ammo to swarmers, say **metaglass**? 

With frag but has 0.75x fire rate.

**Comment by stuffyAI** [comment]
> Maybe add a new ammo to swarmers, say **metaglass**?

Tbh blast Swarmer with Cryofluid Tsunami to get the 18 full-armor-piercing bonus slaps enough, all my homies hate armor.

**Comment by OnyxFinger** [comment]
> just change the point in progression swarmer is in and all of the discussion above won't matter
> or, make cyclone harder to get/ later in the game's progression. nothing needs to be removed and only minor rebalancing should happen

I don't it would do much. Generally playstation using/needing weapons aren't limited because they need plast but because they are late game, you could just make another ressource (in my opinion), the main issue is that there wouldn't be a window of usefulness for cyclones/swarmers still, unless waves are very tight which I have only seen once then got too much better for the map.
