### ISSUE TITLE
Logic pathfind X and Y coordinates

### ISSUE THREAD

**Issue by Dhaerlkl** [Anuken/Mindustry-Suggestions#2769]
### Describe the content or mechanics you are proposing.

There would be spots to put an X and Y coordinate into the pathfind unit command for logic.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

This would simply make it easier to use logic in controlling ground units. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
How would you omit the coordinates and revert to the current behavior?

**Comment by joshuaptfan** [comment]
As far as I know, not currently possible because [pathfinding to arbitrary coordinates is not supported.](https://github.com/Anuken/Mindustry-Suggestions/issues/2334)

**Comment by MrDuck557** [comment]
literally uncodable in reasonable time

**Comment by stuffyAI** [comment]
> literally uncodable in reasonable time (I mean runtime not writing the code)

Basically this, we currently do not pass any hierarchical grids on map modifications (placement of blocks etc.), making path-finding intolerable.

Something _like_ this could be implement at very little expense, allowing ground units to at least reach the target if they are able to, however allowing this target to be set with logic obviously gives you the ability to re-call the function over and over in very short spans of time, at which point it because intolerable again.
