### ISSUE TITLE
water extractors eat into groundwater table

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#28]
**Describe what you would like changed, and why.**

currently there is an infinite amount of water underground and water extractors can fill up a map with no decrease in efficiency
i think that efficiency should be reduced corresponding to how many extractors are placed/active
(tile efficiency isnt affected because ice isnt part of the groundwater table)

groundwater should be finite*ly efficient*  to prevent spam of certain power schematics and to promote sharing water or using pumps which are neglected unless its for tar

**Describe the changes you want to propose. Include possible alternatives.**
`efficiency = 100 * 0.9 ^ (placed extractors) + tile efficiency`
or for active extractors but yeah thats my idea

**Comment by KK6DOC** [comment]
I acctualy agree to this ... Water sources will probably be better to use and it's kinda a good thing because most industry irl is always near water and they don't extract it

**Comment by DeltaNedas** [comment]
ok added more deep lore
placed extractors means extractors in some radius
so placing a bunch of extractors away from base doesnt affect it

**Comment by itcannotbe** [comment]
I can already hear the pitchforks of those die hard schematic builders.

But yes. Pumps on water are one of the rarely seen things in multiplayer probably singleplayer too.

**Comment by CaptainCosmotic** [comment]
I'm one of the die-hard schematic builders and this will render most of my designs (100+) useless 
On the other hand, it will provide a new challenge for any new schematic.
If this feature will be implemented I strongly suggest doing the same with oil drills since it falls basically under the same rules and oil drills need a nerf anyway (some servers deactivate oil drills because they are overpowered)

**Comment by RogueRedHawk** [comment]
0.9 seems a bit much, but I agree. Maybe e=(base efficiency) × 0.93 ^ (number of extractors - 1) + tile efficiency? Or even 0.95.

Also, nerfing oil extractors in a similar fashion would be great.

**Comment by MapleWheels** [comment]
> I'm one of the die-hard schematic builders (Sir Silicon) and this will render most of my designs (100+) useless
> On the other hand, it will provide a new challenge for any new schematic.
> If this feature will be implemented I strongly suggest doing the same with oil drills since it falls basically under the same rules and oil drills need a nerf anyway (some servers deactivate oil drills because they are overpowered)

This is not true for Oil. Underground oil reserves are under extreme pressure and drills actually don't "pump out" the oil, they crudely filter the raw oil and re-inject the unneeded materials back into the well to maintain pressure. The crude oil is self-extracting.

**Comment by itcannotbe** [comment]
Actually the source code hints fracking with the oil extractors which is another different method of extracting oil from the ground.

**Comment by DS-3K** [comment]
Wouldn´t make sense as all other material sources are unlimited. I get that
water extractors are over used but that wouldn´t be a good solution for the
game mechanics.

Am Fr., 24. Apr. 2020 um 18:16 Uhr schrieb itcannotbe <
notifications@github.com>:

**Comment by itcannotbe** [comment]
Actually resources are limited via max extraction rates based on the quantity of ore tiles, actual liquid blocks present.

Even solar panels are limited by their low power output and physical foot print on the map.

but water extractors and oil extractors ate placeable anywhere and leads to spammable schematics.

This is made possible by their negligible input requirements and placement requirements.

**Comment by MWestfall** [comment]
I think the idea of having to "think real hard" about how to build stuff because water is globally nerfed would not be a lot of fun.  Plus it's not something that's easily trackable, for instance, every time you build a water extractor you gotta go check if your other water is suffering???? UGH  at Minimum if this happens we need Liquid mass drivers so we can get our "efficiently harvested water" further away without drawing lines of conduits that just drop pressure for no reason.

In real life water pressure only drops when you pull water off or go up hill.  For whatever reason, when you draw a long conduit line in Mindustry, the liquid just "doesn't get to the other end" even if you have no branches off.

**Comment by Codepoii** [comment]
Could just buff water sources so that it's generally a better idea to get water from actual sources before resorting to spamming extractors. Maybe have 0.5x multipliers on volcanic areas, 0.8x on sand, etc. Maybe not allow extractors to be placed on actual water at all.

**Comment by itcannotbe** [comment]
> In real life water pressure only drops when you pull water off or go up hill. For whatever reason, when you draw a long conduit line in Mindustry, the liquid just "doesn't get to the other end" even if you have no branches off.

Actually IRL you pull out water from something called a ground water table or an aquifer which actually has extraction limits. Also putting pumps close to each other pulling water from the same source isn't a great idea.

I suggest doing some research before saying the term "in real life.."

**Comment by itcannotbe** [comment]
> Could just buff water sources so that it's generally a better idea to get water from actual sources before resorting to spamming extractors. Maybe have 0.5x multipliers on volcanic areas, 0.8x on sand, etc. Maybe not allow extractors to be placed on actual water at all.

That's easier said than done. Currently it is more convenient to spam water extractors than to get it from actual water. Being said that. Simply increasing the output from pumps will not solve that particular problem.

**Comment by itcannotbe** [comment]
If anyone claims that conduits suck. They don't. They just suck when you use bridge conduits or phase conduits. Conduits and  Pulse Conduits currently can transfer a lot of liquids per second.

**Comment by MWestfall** [comment]
@itcannotbe in real life people usually properly read and respond to things too.  I said "Water pressure/flow does not drop from one end of a conduit segment to another"  And you go "BUT IF YOU PULL THINGS OUT OF A WATER TABLE ....."   yeah no shit, I didn't say it didn't.  And I regularly draw conduit lines with no bridges or using phase conduits and the liquid simply does NOT travel to the other end.  I can put 10 water extractors on a tank, run a long conduit, connect it to something that only needs say three water extractors, and the conduit will not stay full.

**Comment by itcannotbe** [comment]
Actually in IRL pipes, the further you are from the pressure source the longer it takes for pressure to equalize when you compare the source and your point of measurement.

Plus if you are discussing another another topic or a different suggestion all together you make yourself a new issue, not hijack this one.

**Comment by stuffyAI** [comment]
> Actually resources are limited via max extraction rates based on the quantity of ore tiles or actual liquid blocks present.

The amount of Water and Oil extractors are limited by the amount of space you have.
One of the biggest challenges in late game is having enough space, and trust me, any decent player will utilize water pumps.
Removing water extractor rate sounds like an unfun concept as it adds an essentially random factor of "maybe this will work long enough before I have to rebuild it" and "Oh boi, sure be hoping that the pumped water will randomly prioritize my thorium cryo supply". 
Also no, Ores etc. are not limit, my drill doesnt stop working after some time. That is the definition of unlimited. Their extraction rate is limited, but what you are suggesting would actually lead to eventual almost-zero extraction of water.

It should be given in the name of the game that a system that losses efficency over time is absurd, this isn't a real life simulator.
Feel free to suggest removing water extractors or putting a hard limit on them, either by "you cant build more than x in an area of y" or just limiting the block amount (which again, makes no sense).



> Also you need to know that the production of ten water extractors is far from the maximum that conduits can handle. Simply put it your not putting enough of liquid through to make the pipe be "full".

Just no, the conduit should still fill up as he is producing more than he is consuming.
To overpressure it by adding vastly more producers than consumers is impossible as you then would simply not have enough water or would require so much space that people would literally just use water for the essentials and nothing else.

**Comment by itcannotbe** [comment]
You actually didn't read the point of the discussion.

1. They are still unlimited to extraction.
2. The point is the more water extractors you place inside a certain radius of each other the less they will output.
3. Most maps the are played on multiplayer are actually open maps. The point of maps being resource limited is blown out the window. This actually makes people rely less on water extractor and lean towards to actual pumps since the fact of the matter is water extractors are extremely convenient. To the point the less and less people actually use pumps.

**Comment by stuffyAI** [comment]
You didn't read my post:


> 1. They are still unlimited to extraction.

So are Ores, as mentioned.

> 2\. The point is the more water extractors you place inside a certain radius of each other the less they will output.

The point I made is that this will lead to unforeseen behaviour as one really cannot calculate the new rates on the fly. That's why I suggested making them hardlocked or something so you can always assure that placed ones work fully, imagine placing one block to close to thorium cooling and stopping it....


> 3\. Most maps the are played on multiplayer are actually open maps. The point of maps being resource limited is blown out the window. This actually makes people rely less on water extractor and lean towards to actual pumps since the fact of the matter is water extractors are extremely convenient. To the point the less and less people actually use pumps.

So you wan't to further make the good players suffer by letting lower experienced players place water extractors slowing everything else down. 
To Min-Max you have to use Pumps as they easily replace many many extractors, but you also have to use extractors. I suggested region locking, because reducing the rate at which water is pumped would be extremely detrimental to any high end builds. That is why deserts don't reduce extraction rate, in an game where the higher level of play requires you to go through the numbers you cannot take such pseudo-random effects like reduced water extraction rate because "oh fk, I accidentally placed Plastanium water production to close to throrium which now need additional extractors to balance it out, but oh wait, that will reduce plastanium extraction rate again..."

**Comment by itcannotbe** [comment]
Actually the point is to make water extractors unvaiable to be used in close proximity to each other. Therefore your situation presented in point 3 is the worst thing to do.
Using pumps is the far better option in that regard.

Pumps, as a fact, are rarely used. In fact they are used as a last resort or if they are really close to the user block (Still they prefer to use water extractors.)

And I can summarize your responses in a simple statement.

I don't want this being implemented as this will be harder to use something that I use frequently since it is extremely convenient to use and their cost is negligible also many meta build/schematics will suffer from this.

**Comment by MapleWheels** [comment]
Wow, this is still going in August. Didn't even notice. 

Okay stop. Here's the fundamental problem. A lot of this game's player base relies on the simplicity and intuitiveness of most of the mechanics. As in, if something is doing X, it will continue to do X unless I directly change something it's interacting with. This is the fundamental issue you guys are missing here. You can have region-based efficiency, like extractors already do have, because it makes sense to players very easily when they read the tooltip.

The problem with extractors is that they are convenient. They make lazy schematic pasting possible because the entire schematic is self-contained and there's no need for macro logistics planning for pipes and the like. If you want to nerf extractors, you need to reduce their inherent convenience. Most people **do not** care about efficiency after a certain point. If the schematic works then that's all that matters. You need to fundamentally change this if you want to stop extractor spam.

The answer? Reward efficiency more. The problem is that the fact is that **you can spam extractors and it will work _good enough_**. This is all that matters in PvE multiplayer because usually you will succumb to slow building before you do due to inefficient production design.

You need to reward smart macro-map logistics planning and use of pipes more to make extractors a no longer _good enough_ solution. This means that _blind schematics spam_, _**which is the real issue here**_, is less of a problem. Extractors are just too easy to use for being _good enough_. 

Honestly, have two options here;
1. You need to make it so that a low amount of pumps can saturate a conduit and bridge conduits' flow limits are based on the I/O pipes connected to them. If you attach a Pulse Conduit to them, they will flow at the same rate. The only thing to note is that all Bridges in this game have an internal buffer that makes their output delayed, but the transmission rate is still the same. 
OR;
2. You need to make the usage of an extractor more complicated, similar to how Oil Extractors require sand. This is not as desirable because it will not be as intuitive to use. Like, what does a underground water extractor _really_ need besides power (and keep it simple)?

The truth of the matter is that this game makes lazy building (such as schematics spam) easy to get away with and this isn't entirely Anuke's fault either. Multiplayer map designers are exceeding the original balancing scope of this game. Think of the campaign maps, you can't spam nearly as hard there as you can in custom maps because of resource placement, space constraints and terrain. Maybe the game needs to include these in it's balancing? But then that also has a host of issues to contend with, that, frankly speaking, are not Anuke's direct responsibility.

The short answer is make pump logistics less complicated (?) and more rewarding to use.

**Comment by Anuken** [comment]
(I'm not going to read this whole discussion but the groundwater table thing is not being implemented)
