### ISSUE TITLE
Aircraft carrying

### ISSUE THREAD

**Issue by CaptTex** [Anuken/Mindustry-Suggestions#2808]
### Describe the content or mechanics you are proposing.

I noticed that air units will go straight through turrets (I know that this could be changed with logic but some maps ban logic) I wondered what if air units could land on water units like they do in real life. Im saying like a t2 water can hold a t1 air and a t5 water can hold a t4 air something along those lines.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would give the game more tactical option ls for attacking. Getting around flak guns by landing on water units also allowing them to "sneak" past. Making it seem like there are more options when taking down a base.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
this could be interesting if the boats themselves could carry a lot of units, else we have a mechanic like droping with megas, which isn't very useful

**Comment by Ilya246** [comment]
air units can carry themselves, plus nobody really would put only flak - in case there is only flak, just destroy it

**Comment by OnyxFinger** [comment]
> air units can carry themselves, plus nobody really would put only flak - in case there is only flak, just destroy it

T4 and T5 carrying units are fine, but an early game kind of carrying would be very fun, since right now megas suck a lot at this job

**Comment by Anuken** [comment]
This has been suggested countless times, but I have yet to see a good reason for its implementation; *"aircraft carriers exist in real life and it would be cool"* is not enough. Real aircraft need places to refuel and resupply; Mindustry's don't. 

"sneaking past enemy lines" isn't a valid use case; artillery out-ranges flak, and I don't see many bases having a line of *only* flak guns at the front lines, with no other AA defense past that point. It would take an incredibly specific set of circumstances to make this mechanic remotely useful.

**Comment by OnyxFinger** [comment]
> This has been suggested countless times, but I have yet to see a good reason for its implementation; _"aircraft carriers exist in real life and it would be cool"_ is not enough. Real aircraft need places to refuel and resupply; Mindustry's don't.
> 
> "sneaking past enemy lines" isn't a valid use case; artillery out-ranges flak, and I don't see many bases having a line of _only_ flak guns at the front lines, with no other AA defense past that point. It would take an incredibly specific set of circumstances to make this mechanic remotely useful.
>
> Aircraft are always more mobile than naval units; with no effective range limit, there's simply no reason to store them anywhere.

early artillery guns such as hails have much less crowd control than scatters, the early game flak/AA gun. 
on the topic of mobility, air units should be, for having more mobility, should thus be weaker than ground units (kinda like how naval units are stronger than other units because they have lower mobility), so putting them inside of naval units, which are from common sense of balance stronger (or should be), makes sense, since they would probably be tankier and thus able to sneak through. But this "increase" in strength that air units would get is more balanced by the fact that you would need more units, meaning more ressources.
You can also make it so that since it isn't really possible for a carrier unit to be carry another carrier unit you can make it carry a lot of units. Currently, dropping is terrible because you can't really put a lot of units inside of a mega, you can in a quad or oct, but at this point you want to load up a strong unit like a T4 or T5, but you can't really carry many of those either

This idea definitely seems weird to me too, since carrying the most mobile class of unit with the most immobile class of unit doesn't make a lot of sense, but there is some potential with it.
