### ISSUE TITLE
Orbital Weapons/Support device

### ISSUE THREAD

**Issue by enosia** [Anuken/Mindustry-Suggestions#2833]
### Describe the content or mechanics you are proposing.

Very expensive (and limited) weapons/machines that can be launched from a cleared sector to sit above the planet and be moved around different sectors at the player's discretion. There are two potential uses:

1. Use as a weapon, for example: once fully charged (with energy transferred via laser from a sector that is in range or perhaps supplied by launchpad with a physical resource) it can launch a single devastating and wide range attack on a sector that's currently in the middle of a wave. Required a long cooldown.
 
2. Use a support device. For example: when the device is sitting about a sector, it confers benefits to that sector and surrounding sectors. I.e. 'protection': it deters attacks from hostile surrounding sectors; 'weather control': allows the weather to be tamed to a degree (weather itself must be developed for this to make sense); unit boosts: boosts speed or firepower of units; health regeneration, provides slow health regen over a wide area for buildings and units.

Perhaps the amount once sector can power an orbital device can be limited, such that multiple sectors must contribute in order for maximum use to be conferred.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

1. With the advent of additional planets, I think it would make sense for the space realm to be utilised. 
2. Plus, this would increase cross-sector cooperation, making sectors more useful once conquered and providing an incentive to continue conquering instead of relaxing once all immediate threats are dealt with. 
3. Providing a late-game objective.
4. Providing an 'ultimate weapon' which this kind of game always has.
5. For prudent players, it provides a last-ditch attempt at saving a sector that has been under threat from being retaken.

p.s. I really love this game!!!!!!!!

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
this used to be in the trello, even know I can't seem to find it anywhere anymore
but I think that if Anuke wasn't open for suggestions about this, he would have just shelved the idea, so your suggestion is still valid ?
I kinda like the idea of an orbital station for campaign though, even know it would probably not be very useful (I'm not 100% sure still, since we haven't yet had a peek at how planets would work and how difficult they would be
I think having a big late game objective after the accelerator makes sense

**Comment by Kyllingene** [comment]
Both of the suggested effects are quite boring and lackluster; simply annihilating a wave isn't very fun, nor is simply "units go brr." *If* this was implemented, which I doubt because I don't personally think it fits the game very well (and no, "other games have it" is not a good reason), it would need a much more potent but fun ability, which isn't readily forthcoming.

**Comment by enosia** [comment]
> "simply annihilating a wave isn't very fun"
But... that's what the game is about? Marshaling resources to destroy waves of enemies?
Big booms are cool, if only for the spectacle.

**Comment by Kyllingene** [comment]
Mindustry is about careful planning and adapting, not "big gun go boom," and most *certainly* not about spectacle; if it were, why are the unit deaths of even the largest units just a mediocre explosion, despite the amount of issues suggesting more complex death visuals?

**Comment by enosia** [comment]
> Mindustry is about careful planning and adapting, not "big gun go boom," and most _certainly_ not about spectacle; if it were, why are the unit deaths of even the largest units just a mediocre explosion, despite the amount of issues suggesting more complex death visuals?

Not sure why you're being so combative. I didn't say Mindustry is 'about' big guns going boom and spectacle. I said that those things are cool.
You can't deny that part of the allure of this version of Mindustry are the awesome weapon visuals and sounds, for example, those of the Meltdown, which blew me away the first time I saw and heard it.
A lot of this is opinion-based, so there's not much point in telling me Mindustry is not about what I think it is, in other words, agree to disagree.

In essence though, my suggestion is about providing a late-game objective (a superweapon) that increases cross-sector reliance and cooperation (and providing an incentive to conquer more sectors).

**Comment by Kyllingene** [comment]
My point still stands; Anuke clearly thinks that spectacle is not a priority, otherwise the unit death animations would be cooler. Either way, though, [this](https://trello.com/c/1ZdJ8Z5p/655-1-2-sector-superweapons) Trello card clearly shows that Anuke is already planning to add superweapons, so half of your suggestion is invalid either way; the other half is still just a lackluster, broad buff to units, which isn't very fun.

**Comment by enosia** [comment]
> My point still stands; Anuke clearly thinks that spectacle is not a priority, otherwise the unit death animations would be cooler. Either way, though, [this](https://trello.com/c/1ZdJ8Z5p/655-1-2-sector-superweapons) Trello card clearly shows that Anuke is already planning to add superweapons, so half of your suggestion is invalid either way; the other half is still just a lackluster, broad buff to units, which isn't very fun.

Why would the one example of death animations (which I think are pretty sufficient by the way) prove your point? You're not considering the fact that 'spectacle' does not necessarily just mean aesthetics. And you're also not really thinking about the hierarchy of prioritisation, where death animations would probably be low. 
I really think you should work on your attitude, it is not constructive at all and too combative. It is not conducive to a productive conversation.

**Comment by Kyllingene** [comment]
> You're not considering the fact that 'spectacle' does not necessarily just mean aesthetics.

![image](https://user-images.githubusercontent.com/69094702/129076345-19b09c97-b776-4c16-a289-aaa8827c26ff.png)

> not really thinking about the hierarchy of prioritisation, where death animations would probably be low.

Why would one of the easiest things to change, which would have one of the largest effects on the visuals of the game, be a lower priority than a superweapon that doesn't even exist yet?

> which I think are pretty sufficient by the way

I agree, because they are not meant to be *spectacle*. They are meant to convey a meaning, that meaning being that the unit was destroyed in a violent manner.

And, either way you slice it, you still failed to find that Trello card which invalidates the half of the suggestion you seem to actually want.

**Comment by OnyxFinger** [comment]
> My point still stands; Anuke clearly thinks that spectacle is not a priority, otherwise the unit death animations would be cooler. Either way, though, [this](https://trello.com/c/1ZdJ8Z5p/655-1-2-sector-superweapons) Trello card clearly shows that Anuke is already planning to add superweapons, so half of your suggestion is invalid either way; the other half is still just a lackluster, broad buff to units, which isn't very fun.

but the rellot card doesn't say what kind of weapon etc.. It's like suggesting on that could be in; "superweapons" are also not all just orbital sations with big lasers and pew pew boom boom like the death star.
Lastly, campaign doesn't require much planning in the late game, and if the orbital stations have a good enough cooldown, then you can't just spam them and go pew pew boom boom ka-paw bratatatata with them

**Comment by enosia** [comment]
> > You're not considering the fact that 'spectacle' does not necessarily just mean aesthetics.
> 
> ![image](https://user-images.githubusercontent.com/69094702/129076345-19b09c97-b776-4c16-a289-aaa8827c26ff.png)
> 
> > not really thinking about the hierarchy of prioritisation, where death animations would probably be low.
> 
> Why would one of the easiest things to change, which would have one of the largest effects on the visuals of the game, be a lower priority than a superweapon that doesn't even exist yet?
> 
> > which I think are pretty sufficient by the way
> 
> I agree, because they are not meant to be _spectacle_. They are meant to convey a meaning, that meaning being that the unit was destroyed in a violent manner.
> 
> And, either way you slice it, you still failed to find that Trello card which invalidates the half of the suggestion you seem to actually want.

That is pretty ridiculous and funny, you send a print screen of the definition of spectacle alone without text as though it's a slam dunk that proves you completely correct... and yet you don't even see the definition is so broad it doesn't even support your point. When I say 'spectacle' I don't mean pure aesthetics which should actually already be extremely obvious as I'm referring to the entirety of this new superweapon I'm proposing as a 'spectacle', from the sounds and visuals to the mechanics.

I don't know what anuke is thinking, but perhaps he also thinks the death animations are sufficient and wants to work on new content? Not to mention... I completely disagree with your opinion that it would be 'one of the largest effects on the visuals of the game', simply in terms of how often we would see it (that is assuming that you mean the death visuals for the bosses only would be revamped). 

Also, like Onyx said, while superweapons is already a card there are no specific plans. And I'm suggesting something specific. And even if half of it is 'invalidated', so what? I hate to be a parrot but again I have to say the points you make are really unproductive/pointless/ill-conceived.

**Comment by itcannotbe** [comment]
> I really think you should work on your attitude, it is not constructive at all and too combative. It is not conducive to a productive conversation.

![No U](https://c.tenor.com/nXdXpZIZbN8AAAAM/no-u-keanu-reeves.gif)

No seriously, if you want a productive conversation try working on decent counter arguments.

**Comment by itcannotbe** [comment]
> A lot of this is opinion-based, so there's not much point in telling me Mindustry is not about what I think it is, in other words, agree to disagree.

Not really, as a general rule, anything that isn't seen in the game is not what mindustry is.

Weapons that causes massive damage over a stupid large area or supportive statuses/boost given on demand or weather control is not part of the game nor resembles anything in the game.

**Comment by Kyllingene** [comment]
> When I say 'spectacle' I don't mean pure aesthetics which should actually already be extremely obvious as I'm referring to the entirety of this new superweapon I'm proposing as a 'spectacle', from the sounds and visuals to the mechanics.

And explain why a generic "no more wave" gun is somehow a mechanical spectacle; it wouldn't feel fun or rewarding, it would feel like you turned on godmode after a relatively small amount of effort (most people get to that stage of the game with astonishing rapidity).

> I don't know what anuke is thinking, but perhaps he also thinks the death animations are sufficient and wants to work on new content?

And programming an instant-death mechanic is hard *how*? The hard part is figuring out how you would activate it, which is difficult but in the least interesting way possible. The most time-consuming part (besides the aforementioned problem you haven't even attempted to answer) is the *visuals and audio*, making it feel like a sufficiently big gun to actually do that; of course, sensory spectacle is not what Mindustry is about (as previously stated), and I would argue that Mindustry is about mechanical spectacle either.

> that is assuming that you mean the death visuals for the bosses only would be revamped

Why would you assume that? Why would only the boss deaths be revamped?

> something specific

I highly doubt that Anuke needed you to tell him "wave go boom" for him to think of it.

**Comment by enosia** [comment]
> > I really think you should work on your attitude, it is not constructive at all and too combative. It is not conducive to a productive conversation.
> 
> ![No U](https://camo.githubusercontent.com/e8a438cea11a50c564e1525b73538e582c46525630756aaf6f280dba0a1a062c/68747470733a2f2f632e74656e6f722e636f6d2f6e586458705a495a624e38414141414d2f6e6f2d752d6b65616e752d7265657665732e676966)
> 
> No seriously, if you want a productive conversation try working on decent counter arguments.

It's not productive when one person is essentially saying 'your opinion is wrong' or something very vague which has unclear consequences such as 'half your suggestion is invalid'.

**Comment by enosia** [comment]
> And explain why a generic "no more wave" gun is somehow a mechanical spectacle; it wouldn't feel fun or rewarding, it would feel like you turned on godmode after a relatively small amount of effort (most people get to that stage of the game with astonishing rapidity).

But what makes you think it would be a 'relatively small amount of effort'? The idea is that it would be time-consuming to make and its use would have a long cooldown. 
The thing is though, I WOULD find it fun and rewarding. This is a point we just have to agree to disagree with. 



> And programming an instant-death mechanic is hard _how_?

This makes no sense to me. No one was talking about the difficulty of programming being the determinant to the next feature created.



> Why would you assume that? Why would only the boss deaths be revamped?

Oh, my bad then I thought I saw you mention bosses only.



> I highly doubt that Anuke needed you to tell him "wave go boom" for him to think of it.

Ok, well clearly I'm not just suggesting 'wave go boom'.


> In that case, every single issue opened on this Github is correct and should be implemented, as at least one player thinks of Mindustry as that.
> 
> What? Is that statement ridiculous? Well, considering every other similar issue has been booed down, the community evidently thinks this is not a good idea; the lack of support on this issue reinforces that. So please, stop assuming that everyone wants this.

It's like you guys read one sentence, imagine up the most (personally) provocative context and then start smashing your keyboard. I don't understand what you're even talking about. I have not been assuming everyone wants this, I have no idea where you got that from. I feel like I'm being trolled.

**Comment by Kyllingene** [comment]
> This makes no sense to me. No one was talking about the difficulty of programming being the determinant to the next feature created.

As in, it wouldn't be interesting or fun to implement. 

> Ok, well clearly I'm not just suggesting 'wave go boom'.

Yes, you technically did suggest some even more boring and unfulfilling support options. 

> I have not been assuming everyone wants this

Really?  Because all that talk about what Mindustry is about implied that that is what you believe Mindustry to be; and given that you seem to be a smart individual, you would only make this suggestion if you believed it had a fair chance of being desired by more than yourself (a notion dispelled by the fates of other similar suggestions; but no matter), logically concluding with the assumption that you believe that a sufficiently large number of others believe that this is what Mindustry is about.

**Comment by enosia** [comment]
> As in, it wouldn't be interesting or fun to implement.

Good thing you're not a programmer working on Mindustry then.


> Yes, you technically did suggest some even more boring and unfulfilling support options.

Your point was I didn't need to suggest 'wave go boom' for Anuke to think of it. But I did not only suggest 'wave go boom'. Sure, that would be the end result for players, but the unalterable fact is that I did not _just_ suggest 'wave go boom'. This is an example of a pointless point.



> Really? Because all that talk about what Mindustry is about implied that that is what you believe Mindustry to be; and given that you seem to be a smart individual, you would only make this suggestion if you believed it had a fair chance of being desired by more than yourself (a notion dispelled by the fates of other similar suggestions; but no matter), logically concluding with the assumption that you believe that a sufficiently large number of others believe that this is what Mindustry is about.

ahhh, so is that where these random points are coming from? Your (incorrect) assumptions? 
1. Ok, consider this: I do not follow this github, I have no knowledge of previous suggestions. I am only aware of the trello and the 'what not to post' list.
2. I did not consider at all what other people want. I didn't think this was a 'community voting' thing because the average number of comments seems to be low. I assumed this was a Anuke takes what he likes kind of thing.
3. After a quick glance I see that the same few names keep popping up in the comments: itcannotbe, oinkymoo, Kyllingene, joshuaptfan and some others. Aside from these people, other commenters are more sporadic and less consistent, NOTE I AM NOT SAYING THESE ARE THE ONLY PEOPLE COMMENTING. BUT in any case, I interpret this now to mean that this github is not representative of the opinion of the 'community'.

So, to sum up, I don't think the few people here represent the opinion of the community and I assumed regardless if the few people here were unhappy with an idea, if Anuke liked it he would consider implementing it.



> Excuse me, I was saying that your opinion was seemingly not shared by the rest of the community, which in this case _does_ imply that it is as "wrong" as an opinion can ever be. Which is, indeed, constructive.

Again, after my quick scan through, I don't believe the opinions of the few people in this github repository (or whatever it's called) is representative of the entire community. And regardless, only facts can be right or wrong, objectively. Unless that opinion is somehow based on or related to a fact, you just cannot say it is 'wrong', you can only disagree with it. Similar to how I can't say my opinion is true for everyone, you can't say my opinion is wrong for me. It's like your saying I'm wrong for my favourite colour being red, instead my favourite colour should be blue because 55% of the community prefers blue. It does not make sense.



> As for "half your suggestion is invalid," yes, it is; according to the rules of the template, half of your suggestion should never have been made. So yes, it _is_ constructive.

I struggle to believe that you're serious about this. You are saying that no one can suggest a specific idea relating to a superweapon because the vague and unspecific card of superweapon exists in the trello. A vague idea existing in the trello does not preclude a specific iteration of the idea from being suggested. 

I think you're well-spoken but you've made a common mistake with your argumentative style, that is, you're too focused on talking and less focused on paying attention to what the other person means. And you seem dishonest, maybe a better word would be toxic?

**Comment by Kyllingene** [comment]
> Good thing you're not a programmer working on Mindustry then.

Unfortunately, Anuke is, and he is a busy man with a completely free game that people still expect him to work on on his hands.

> This is an example of a pointless point.

Huh? So you made an entire argument, then said it was pointless? Or are you referring to my argument?

> Ok, consider this: I do not follow this github, I have no knowledge of previous suggestions. I am only aware of the trello and the 'what not to post' list.

Then try searching for previous suggestions. Tip: don't filter out closed ones.

> because the average number of comments seems to be low.

That would be because most issues don't merit more comments.

> BUT in any case, I interpret this now to mean that this github is not representative of the opinion of the 'community'.

On the contrary; the majority of those names (not including mine) represent the most involved members of the community, also including a few contributors to the games codebase. Either way, this is the closest to an orderly representation of the community you're gonna get.

> if Anuke liked it he would consider implementing it.

Indeed; however, the fact that he has neglected to act on the numerous other suggestions of similar kind (not that you knew that, since you didn't search for them) indicates that he does not seem to put much stock into this kind of idea.

> And regardless, only facts can be right or wrong, objectively.

Exactly why I took pains to indicate that it could not truly be called "wrong," pains which you seem to have ignored. By "wrong" (note the quotation marks) I indicated that it was not shared by others, a critical fact for the fate of this issue.



> I struggle to believe that you're serious about this. You are saying that no one can suggest a specific idea relating to a superweapon because the vague and unspecific card of superweapon exists in the trello. A vague idea existing in the trello does not preclude a specific iteration of the idea from being suggested.

You would have to ask Anuke; after all, he wrote the checkbox, not me. I am simply expressing the wishes of the template.

> you're too focused on talking and less focused on paying attention to what the other person means. And you seem dishonest, maybe a better word would be toxic?

If I am, I am sorry; I carefully comb your comments to pick out the main sentences representing each individual point, read them carefully, then respond how I see fit. If I fail in that, I am truly sorry. However, I fail to see what relation "dishonest" and "toxic" have to each other.

**Comment by enosia** [comment]
> Unfortunately, Anuke is, and he is a busy man with a completely free game that people still expect him to work on on his hands.

And then, this raises the question: who are you to decide what is fun enough for Anuke to implement? Who are you to even decide what his priorities are when it comes to implementing features? For all you know all Anuke might care about is the success and wider uptake of his game. Unless I'm missing something and you know him personally perhaps?

Hmm, maybe you could consider this a slam dunk of sorts: somehow you're unaware that this game is not free on steam (and I did buy it btw). Not that I think that that justifies any entitlement at all (before you decide to make that one of your assumptions!)


> Huh? So you made an entire argument, then said it was pointless? Or are you referring to my argument?

I essentially refer to the root point you made which was this:


> I highly doubt that Anuke needed you to tell him "wave go boom" for him to think of it.

Because it's just such a ridiculous misrepresentation that is destined to waste time and produce no useful conclusion. This is the conclusion from that point you made: the point was moot to begin with because it wasn't what I said. And it is so obviously not what I meant. That raises the question: what was the point of you saying that to begin with?


> On the contrary; the majority of those names (not including mine) represent the most involved members of the community, also including a few contributors to the games codebase. Either way, this is the closest to an orderly representation of the community you're gonna get.

Ok, it depends on what you mean by community. By community do you refer to the playerbase? Someone involved with the games codebase is in a good position of authority to suggest which ideas are practical and which are not, but their opinions of what is most 'fun' are not necessarily representative of what the 'playerbase' would find the most fun.
It seems that 23 people are watching this repository, 
A quick glance at steam shows 8000 total reviews (not downloads or purchases JUST REVIEWS). This does not even include the people who play on mobile.
23 people, perhaps 40 max, cannot be representative of 8000+ (in terms of deciding what is most fun or what is the most desired feature).

It's like your saying only 1000 people should be able to vote for who's going to be the president of the USA and this is a totally and fair representation of what the whole country thinks. And those 1000 people happen to just be the loudest.   




> Indeed; however, the fact that he has neglected to act on the numerous other suggestions of similar kind (not that you knew that, since you didn't search for them) indicates that he does not seem to put much stock into this kind of idea.

I checked the first 8 pages of closed ideas, did not see anything similar. If you could find something it would be helpful? If not, then in this facet of the argument I can only rely on your knowledge, and, excuse me if I don't consider you to be particularly reliable.


> Exactly why I took pains to indicate that it could not truly be called "wrong," pains which you seem to have ignored. By "wrong" (note the quotation marks) I indicated that it was not shared by others, a critical fact for the fate of this issue.

Except you said it was as close to 'wrong' as it could possibly be. So... you are at the very least saying there's a spectrum and I'm closer to the wrong end. I am saying this spectrum does not exist or make sense.
And also, I would say what I think the purpose of the game is is actually not as relevant as the objective fact that is you MUST destroy waves of enemies whether you want to or not, you will lose if you refuse to.
So, I am actually kind of wrong, because my opinion is somewhat rooted in the fact that you must destroy the waves of enemies.



> You would have to ask Anuke; after all, he wrote the checkbox, not me. I am simply expressing the wishes of the template.

What a copout. Absolving yourself of responsibility is the last step in acknowledging defeat implicitly. You are not expressing the wishes of the template because I did not simply say 'add a superweapon'.



> If I am, I am sorry; I carefully comb your comments to pick out the main sentences representing each individual point, read them carefully, then respond how I see fit. If I fail in that, I am truly sorry. However, I fail to see what relation "dishonest" and "toxic" have to each other.

Toxic is a general word that can mean a lot of things. I tried to be specific at first but changed my mind, but if toxic doesn't make sense to you then just stick with dishonest, it works well too.
But I acknowledge your apology and if it's genuine then I will acknowledge that there was no malice in your attitude and approach, just ineptitude in interpretation or something.

**Comment by Kyllingene** [comment]
> who are you to decide what is fun enough for Anuke to implement?

I'm not; I'm simply making an educated guess as a programmer.

> somehow you're unaware that this game is not free on steam

Actually, I bought it on Steam as well, and have made good use of its features.

> Not that I think that that justifies any entitlement at all

So what was the point of that argument?

> Ok, it depends on what you mean by community

The players listed were some of the most active community members, and also very representative of what Anuke seems to consider the target audience for this game.

> And those 1000 people happen to just be the loudest

And those 1000 people happen to just be the ones who bothered to vote.\*

Not to mention that that was the precise method set up by the founders of the U.S.A., except with even smaller numbers.

> If you could find something it would be helpful?

#2204 #813 (that one is almost identical) #2064 #557 (point 4)

I seem to recall more, but even those 3 (4, technically) should be enough to inform you of this issues fate. By the way, those were all found via searching `is:issue orbital`; there could be a few more that weren't listed.

> Except you said it was as close to 'wrong' as it could possibly be. So... you are at the very least saying there's a spectrum and I'm closer to the wrong end. I am saying this spectrum does not exist or make sense.

You get my point; this is ultimately an argument over wording.

> You are not expressing the wishes of the template because I did not simply say 'add a superweapon'.

I disagree; we will have to agree to disagree.

> Toxic is a general word that can mean a lot of things

But dishonest? Really, I'm not offended, just confused.

> if toxic doesn't make sense to you then just stick with dishonest

But what do you mean by dishonest? I have been expressing my opinions and beliefs truthfully, and haven't misrepresented those of anybody else that I know of; I have not willfully deceived you about any facts; so what do you mean by that?

> But I acknowledge your apology and if it's genuine then I will acknowledge that there was no malice in your attitude and approach, just ineptitude in interpretation or something.

To be entirely honest, ineptitude is sort of my thing; I wouldn't be surprised if I have misunderstood you for half of this debate.

Either way, I feel like we are going nowhere. If Anuke wants this, he can add it; our continued squabbling (most of it on my side) is not helping anything. If you feel like it, you can keep going. You can take this as me quitting due to losing, if you wish; I'm not entirely sure how inaccurate you would be.

**Comment by enosia** [comment]
> Either way, I feel like we are going nowhere. If Anuke wants this, he can add it; our continued squabbling (most of it on my side) is not helping anything. If you feel like it, you can keep going. You can take this as me quitting due to losing, if you wish; I'm not entirely sure how inaccurate you would be.

I wasn't thinking of this as a competition to be won or lost, especially when... most of the things you're saying make no sense. Quick example: you revealed you also bought the steam version... so then why did you try to use the game being free as part of your argument? You wonder why I think you're being dishonest?
Another quick example that I have to mention: the previous examples of orbital weapon suggestions, you have previously said they were shot down by 'the community' and yet each one only has 2-3 people commenting max (including you in one or two), not to mention they are closed due to becoming 'stale' rather than explicitly rejected. Again, this just seems like dishonesty. 



> To be entirely honest, ineptitude is sort of my thing; I wouldn't be surprised if I have misunderstood you for half of this debate.

It's like you have the writing style of a freshman college literature student (bit generous) but the comprehension and reasoning skills of a five-year-old...

**Comment by Kyllingene** [comment]
> I wasn't thinking of this as a competition to be won or lost

Neither was I; but arguments always have an end, and that can usually be quantified as a "win" or "loss" for either side.

> you revealed you also bought the steam version... so then why did you try to use the game being free as part of your argument?

The game is free for every device (except iOS, not much can be done there though) if you go to the itch.io page. So yes, you *can* buy it and yes, I *did* buy it, but yes, it *is* free-to-play.

> they are closed due to becoming 'stale' rather than explicitly rejected

I presume you missed this notice in the README.md:

> Manually closing invalid or completed requests is tiring. I'm not going to explain why I don't like your suggestion anymore - I just won't do anything. If I think it's good, you'll see it in the game soon enough, and it's your responsibility to close the issue if you so choose.

> It's like you have the writing style of a freshman college literature student (bit generous) but the comprehension and reasoning skills of a five-year-old...

I'm sorry, but after acknowledging my faults and apologizing for them, you still come up and insult my intelligence? Honestly, I think I know where the title of "toxic" fits here. Are you the same person chiding me for not being "constructive"?

**Comment by GitHubUser-B** [comment]
> > Mindustry is about careful planning and adapting, not "big gun go boom," and most _certainly_ not about spectacle; if it were, why are the unit deaths of even the largest units just a mediocre explosion, despite the amount of issues suggesting more complex death visuals?
> 
> Not sure why you're being so combative.

Unfortunately, almost everyone here is, and I also want to know why, but i'm not one of them :) the community of this game makes me not think this game is fun anymore, seriously, there was one time in a team PvP match where the enemy team had won and then almost every member of the opposing team had said GG EZ or stuff like that, and then everyone who had said these things left the game, and since i thought that was absurd, i complained about it and said i would ban them all if i could, and then some guy votekicked me and i got kicked out! With that passive-aggressive message saying "you got kicked out, goodbye", and there was also a case here, where a guy named xxXsniperXxx was DESTROYED by the community for complaining about a SIMPLE LEVEL of the game! If you show a humble opinion against the game, you'll have to say goodbye to your happiness, showing how rude this community is and the community is full of mod makers who say that everything suggested can be done by mod, leaving the game dead, looking like a conspiracy that they are trying to get players to download their mod! And I have an opinion about the game too, and it's about the """""strategy""""" called rush, which is (unfortunately) used a lot in mindustry PvP, which is you spend your time making as much weak units as you can as fast as possible, and then you send everything to the enemy, and I think this is bad because it looks a lot like "cheese" (tactics that take advantage of flaws in game mechanics), and also because the matches get really boring, like you expect an epic battle of tactics and strategies but actually you have a bunch of units going to your base with no time and chance of you being able to defend against it, now i will start chaos. That's all I have to say/warn with you, and I'm sorry about the "bible" I made, it's because I had it all to say, lol.

**Comment by GitHubUser-B** [comment]
Anuke takes what he likes kind of thing.

TRUE, I THINK THE SAME THING

**Comment by GitHubUser-B** [comment]
>I assumed this was a Anuke takes what he likes kind of thing.

True, I think it's like this: I didn't like it, it WON'T BE IN MY GAME BECAUSE I DIDN'T LIKE IT EVEN THOUGH IT MIGHT MAKE THE GAME BETTER 😡

**Comment by GitHubUser-B** [comment]
>I assumed this was a Anuke takes what he likes kind of thing.

True, I think it's like this: I didn't like it, it WON'T BE IN MY GAME BECAUSE I DIDN'T LIKE IT EVEN THOUGH IT MIGHT MAKE THE GAME BETTER 😡

I think Anuken behavior in the comunity is the same, because he already said that: don't make suggestions that are from different languages, otherwise I won't BOTHER ME READING THIS, MORE RESPECT ANUKEN!!! JUST USE GOOGLE TRANSLATOR DUDE, RESPECT THE NATIONALITY AND LANGUAGE OF OTHERS!!!

**Comment by GitHubUser-B** [comment]
>After a quick glance I see that the same few names keep popping up in the comments: itcannotbe, oinkymoo, Kyllingene, joshuaptfan and some others.

Ooooh yeeees, these people are pessimistic and almost always complain about the suggestions of others, but when they are the ones who make those suggestions, they always get along well. They look like squires to Anuken, they act like this: bad suggestion for them: show up. The group: THIS SUGGESTION IS THREATENING THE KING ANUKEN, LET'S COMPLAIN ABOUT IT

**Comment by itcannotbe** [comment]
> > After a quick glance I see that the same few names keep popping up in the comments: itcannotbe, oinkymoo, Kyllingene, joshuaptfan and some others.
> 
> Ooooh yeeees, these people are pessimistic and almost always complain about the suggestions of others, but when they are the ones who make those suggestions, they always get along well. They look like squires to Anuken, they act like this: bad suggestion for them: show up. The group: THIS SUGGESTION IS THREATENING THE KING ANUKEN, LET'S COMPLAIN ABOUT IT

Wow, your understanding is peak saltiness.

**Comment by enosia** [comment]
> > After a quick glance I see that the same few names keep popping up in the comments: itcannotbe, oinkymoo, Kyllingene, joshuaptfan and some others.
> 
> Ooooh yeeees, these people are pessimistic and almost always complain about the suggestions of others, but when they are the ones who make those suggestions, they always get along well. They look like squires to Anuken, they act like this: bad suggestion for them: show up. The group: THIS SUGGESTION IS THREATENING THE KING ANUKEN, LET'S COMPLAIN ABOUT IT

Ahahahaha, yeh I got the impression that the kylie guy was friends with itcannotbe because of that ridiculously moronic thing itcannotbe said.

**Comment by itcannotbe** [comment]
[Actually I said what I said because this](https://github.com/Anuken/Mindustry-Suggestions/issues/2262#issuecomment-852294250)

**Comment by enosia** [comment]
> [Actually I said what I said because this](https://github.com/Anuken/Mindustry-Suggestions/issues/2262#issuecomment-852294250)

Christ, just stop, I can tell you're a slow one too. It doesn't feel fulfilling to explain basic things.

**Comment by GitHubUser-B** [comment]
> > > After a quick glance I see that the same few names keep popping up in the comments: itcannotbe, oinkymoo, Kyllingene, joshuaptfan and some others.
> > 
> > 
> > Ooooh yeeees, these people are pessimistic and almost always complain about the suggestions of others, but when they are the ones who make those suggestions, they always get along well. They look like squires to Anuken, they act like this: bad suggestion for them: show up. The group: THIS SUGGESTION IS THREATENING THE KING ANUKEN, LET'S COMPLAIN ABOUT IT
> 
> Wow, your understanding is peak saltiness.

Why?

**Comment by GitHubUser-B** [comment]
> [Actually I said what I said because this](https://github.com/Anuken/Mindustry-Suggestions/issues/2262#issuecomment-852294250)
> 
> @GitHubUser-B if you want endlessly rant about something this repository isn't the place to do it.

Oh no, it's just that I was shocked by the presence of the anuken.

**Comment by GitHubUser-B** [comment]
> [Actually I said what I said because this](https://github.com/Anuken/Mindustry-Suggestions/issues/2262#issuecomment-852294250)
> 
> @GitHubUser-B if you want endlessly rant about something this repository isn't the place to do it.

Man, this is what you and the others in the group do the most!
