### ISSUE TITLE
Liquid Driver

### ISSUE THREAD

**Issue by Grayson-code** [Anuken/Mindustry-Suggestions#2853]
### Describe the content or mechanics you are proposing.

Its  basically a liquid driver which sends liquids in packages to other drivers works same way as normal mass drivers

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

will make it easier to transport liquids like oil to other side of the map. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by MrDuck557** [comment]
what if this has already been suggested before

**Comment by joshuaptfan** [comment]
More likely to happen in the future via disposable liquid tanks + payload propulsion tower.

**Comment by MrDuck557** [comment]
#2512 #2068 #1735 #1650 #384

**Comment by OnyxFinger** [comment]
> More likely to happen in the future via disposable liquid tanks + payload propulsion tower.

So ? This is for the future as far as I know

**Comment by OnyxFinger** [comment]
> #2512 #2068 #1735 #1650 #384

two of the 5 suggestions weren't even about it
2 of the 3 left were closed because they were duplicateds, which makes no sense since duplicates shouldn't be auto closed if they do have a new point to discuss still, or better arguments
the last one was closed because the main argument was liquid throughput and pumps not being very useful due to routing, which is pretty much not an argument anymore, since pumps are now useful and liquids will end up being way more throughput limited, so this suggestion can still come through even as a duplicate

**Comment by itcannotbe** [comment]
Wasn't there a pr that attempted to put liquids into containers and it got rejected?

**Comment by itcannotbe** [comment]
> > More likely to happen in the future via disposable liquid tanks + payload propulsion tower.
> 
> So ? This is for the future as far as I know

Not really, the only reason why the PR got rejected for disposable containers, is it uses deprecated classes.

**Comment by Grayson-code** [comment]
> what if this has already been suggested before

I really don't know but um ok... will look out..

**Comment by OnyxFinger** [comment]
>       More likely to happen in the future via disposable liquid tanks + payload propulsion tower.

>    So ? This is for the future as far as I know

> Not really, the only reason why the PR got rejected for disposable containers, is it uses deprecated classes.

So, his point doesn't matter then ? Also this suggestion isn't for liquid containers

**Comment by joshuaptfan** [comment]
> Also this suggestion isn't for liquid containers

Are you dense? The suggestion is asking for a way to transport liquids a long distance. Disposable liquid containers + PPT is exactly that. Why would the game still need liquid mass drivers after that? Stop insisting on redundant solutions to problems that already have a solid planned solutions.

**Comment by RealYeet** [comment]
If that is the case, maybe se should get rid of  mass drivers as well

**Comment by RealYeet** [comment]
Just saying

**Comment by OnyxFinger** [comment]
> > So ? This is for the future as far as I know
> 
> > Also this suggestion isn't for liquid containers
> 
> Are you dense? The suggestion is asking for a way to transport liquids long distance. Disposable liquid containers + PPT is exactly that. Why would the game still need liquid mass drivers after that? Why are you still arguing?

or are you being more stupid ?
mass drivers are way more cheaper anyway, and already exist, compared to an unnecessary system that for now only exists because it's cool, and has for only use to have unnecessary throughput at a high price, pretty much a waste of time and ressources right now... And as I said, if it was balanced, it would still not be at the same tech level... "Why are you still arguing?"
