### ISSUE TITLE
New Command Centre Option?

### ISSUE THREAD

**Issue by Marchosaur** [Anuken/Mindustry-Suggestions#2867]
### Describe the content or mechanics you are proposing.

In almost every multiplayer game I have played, while I am being attacked, there is an army of friendly units sitting somewhere in the base and it pains me to think that they cannot do a thing about it without player control. What I am suggesting is a defensive engagement option or "defense" where any units that are located at this command center attack nearby enemy units that are within or close to friendly structure boundaries. Although I am somewhat aware that logic processor shenanigans could do this (I have no idea), a method of unit defense should be simplified for a wider player base.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Units should be able to put up a simple offense and a defense without player control, it's just the defense part in my opinion is missing from the game. This could create a new type of unit if implemented that focuses on defending a friendly base, and the extra option could make single-player and multiplayer games more dynamic and allow a team to not get fully destroyed once a defensive breakthrough occurs. I could see a bigger focus on air and naval units, and maybe this could be extended to where two naval forces can engage in a gripping battle. Ground units could be excluded from this option, as they are too slow and might not make it to the enemy unit's location because of structures that might be in the way.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Marchosaur** [comment]
Wait has this been suggested a lot?

**Comment by itcannotbe** [comment]
Yes, but it doesn't matter.

Also one of the primary purpose why a **logic system** was put into the game is for people to customize the behavior of their units.

Furthermore how does one even determine _friendly structure boundaries_ ? Even people adept of using the logic system doesn't or can't define that.

And to complicate things further, this is unviable because command centers cannot direct a set of units, the command everything.

And to top it of, such a feature 
### WILL NOT HELP YOUR USE CASE.
Because in multiplayer, you are dealing with humans not a program that has a set of instructions and rules to follow. It will be easily circumvented.

**Comment by Kyllingene** [comment]
Ultimately, the same fate that befalls so many other issues befalls this one: *no pathfinding to arbitrary locations*.

**Comment by Marchosaur** [comment]
f
