### ISSUE TITLE
Cyclone minigun-like warm up

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry-Suggestions#2870]
### Describe what you would like changed, and why.

Again the problem - Cyclone is too similar to Swarmer. And it doesn't have anything special about it - just a Ripple + Scatter basically.

### Describe the changes you want to propose. Include possible alternatives.

So the idea is to make Cyclone act like a minigun: slow initial fire rate, it grows as turret keeps shooting (let's say it 5 seconds until reaching original fire rate). On the other side initial accuracy will be higher, decreasing as turret warms up (not sure if it's technically possible tho).

This makes Swarmer a decent alternative to Cyclone, probably...

**Comment by itcannotbe** [comment]
How about we differentiate the two further, like the swarmer a slower reload, in a sense that it refills ammo slowly. Like a missle battery of sorts. While it can fire at a fast rate, reloading them will be a chore.

**Comment by Nils101** [comment]
I really like this suggestion because it adds a new mechanic whitch -to my knowledge- is not in the game yet: increased damage over time

I imagine what this would do is it would make hit and run strategies a viable strategy against cyclone forts.
Swarmer would just take the role that cyclone had since the beginning: an all around solid anti-everything turret.

Itcannotbe's suggestion is also interesting, but both of these require a big rework of base mechanics.

My personal take on this would've been to increase swarmer's range and decrease firerate, but I like this better.

**Comment by OnyxFinger** [comment]
> This makes Swarmer a decent alternative to Cyclone, probably...

swarmers are more space efficient and cheaper, idk why all of you keep saying it's worse than cyclone

though maybe cyclone can become slightly better after shooting for a while, we'll have to see

**Comment by Kyllingene** [comment]
I really like this suggestion, but I fear it could invalidate the existence of cyclone since swarmer is so similar. Maybe a buff to its ammo efficiency as well?

**Comment by genNAowl** [comment]
Just an idea, but if your gonna make it into a minigun, maybe give it a barrel rotation animation as well.

**Comment by Marchosaur** [comment]
How bout we chuck this mechanic on larger t5 or t4 units like an Antumbra or Eclipse?

**Comment by OnyxFinger** [comment]
> This makes Swarmer a decent alternative to Cyclone, probably...

swarmers are already a better gun.. More damage in a smaller space, only issue is the ammo consumption ~~but then just place less guns and more other stuff~~

**Comment by OnyxFinger** [comment]
it's DPS needs to go higher than swarmers
this makes cyclones ultimately better in the late game though, unless the mapmaker didn't put shield in the waves (I like it that way since shield isn't necessary)
