### ISSUE TITLE
some visual improves and ideas

### ISSUE THREAD

**Issue by TugaChan** [Anuken/Mindustry-Suggestions#2876]
### Describe the content or mechanics you are proposing.

-visual effects (camara slightly glitches wen you get hurt, and it wil get more glitchy dependent on your health; beter explosions and post-processing)

-units damage (like block, units also can have the broken texture, also the can drop debris wen killd, and biguer units can have small explosions befor they explode, the ground unit get bigher we they fly to make a 3D efect)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

i think this would be a good improve in the graphics and would also make killing big units more epic, and, to be honest, the game now is looking kinda plane

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Kyllingene** [comment]
> camara slightly glitches wen you get hurt, and it wil get more glitchy dependent on your health

No. There is no way in heck that Anuke is going to ruin your vision, especially on mobile.

> beter explosions and post-processing

Why? This isn't supposed to be a beautiful, realistic game; adding those things would simply be more work, and result in more work for the processor, thus slowing down the game; a very, very bad thing for Mindustry, since there are a ton of things that are frame-based.

> i think this would be a good improve in the graphics and would also make killing big units more epic, and, to be honest, the game now is looking kinda plane

*It's supposed to look kinda "plane."* That's called an *aesthetic*. It's something you do on purpose. Also, killing big units might feel epic in early stages, but when they start coming 5-6 at a time, you *really* don't want a bunch of computationally-expensive, screen-covering explosions.
