### ISSUE TITLE
Propulsion Tower/ Mass Driver cooling

### ISSUE THREAD

**Issue by ThomasThings** [Anuken/Mindustry-Suggestions#2879]
### Describe what you would like changed, and why.

I think you should be able to cool the Payload Propulsion Tower block and the Mass Driver blocks, so that they can shoot at a faster rate. This should be able to be done because they are technically turrets, even though they aren't classified as turrets.
![image](https://user-images.githubusercontent.com/89316672/130331651-ba135132-c584-45a4-aaeb-2b6003b45bb0.png)

### Describe the changes you want to propose. Include possible alternatives.

Now, I'm not saying that you should be able to launch 30 crawlers directly into an enemy base, but a smaller increase in cooldown for the blocks could be very useful in some cases without being too op, like maybe water being a 1.3x or 1.4x reload and cryofluid being a 1.7x or 1.8x reload increase or something like that.

**Comment by EclipsePlays** [comment]
We have overdrive projectors though...

**Comment by OnyxFinger** [comment]
> We have overdrive projectors though...

eh I don't think the power needed for OD is worth the throughout...
if you just add another mass driver, it's just more power efficient (unless you use phase but then ye gotta count the phase cost in and I don't wanna do the math)
you get it, ODing isn't actually worth, unless you have low space

**Comment by Dinistor** [comment]
OD lets you create hub of MD's instead of liquid spaghetti, and also you will anyway use OD for schem that you transfer items into so +1 OD is not a problem. If power is issue than you just don't have enough power, thats it. OD is ultimate whan you have massive line of MD's like this where 1-2 ODDs is enough for all MD boost. Now think bout liquid cooling - i would have to create cryo source, and transfer 2 liquids to drilling section - cryo for MD and water for boosting drills. OD lets you have all - boosted drills, hub of MD's and boost of MD troughput
![pic](https://user-images.githubusercontent.com/73835049/130518243-42f10ba7-ee9a-460b-82af-79d658de08d0.png)
