### ISSUE TITLE
About Unit

### ISSUE THREAD

**Issue by GuestUser25** [Anuken/Mindustry-Suggestions#2919]
### Describe the content or mechanics you are proposing.

Anuke you should make some base defender bots to defend the base, if there is no enemy, they will automatically reload bullet from containers beside it, when enemy spawned, they should go and shoot at the enemy but they are going to need bullets because they are defenders. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think this will improve the game because it can make the game more fun and exciting. Most of the unit they only can attack, gather but not defend. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
if you are using units for defense, its much easier to put them around the enemy spawnpoint. also just use logic, or better yet, the thing that was literally designed for defense, turrets

**Comment by Ymabert** [comment]
@GuestUser25 would be an idea, because if the cost of Robot factories decreased, I could use what I don't use to create a small amount of Robots they defend and it would be nice if they are just defending robots, they run randomly in the village limits, they are created as once, so with the factories for T1, T2 and T3, all by land that move if someone is about to place a Scheme, if one has no defenses but only has a lot of silicon, defenses are created Thanks to the robots, in my opinion not it is a bad idea, if there are not 50 defenders per nucleus it can also be there, they would be useful for the fact that they signal an attack on the village and therefore in the meantime oppose a minimum of defense, just to give time to create the appropriate defenses and not to be totally destroyed by a small mistake.

**Comment by GuestUser25** [comment]
Basically, what I am thinking is that when the turrets got jammed or something like that, the bots could be a back up plan. When the boss arrived, they could distract the guardian not just like a average bot just keep standing in the spawn point doing nothing. Also, isn't it nice to have more droids in a factory?

**Comment by Humanoid-X** [comment]
Wow no thats what logic do. This is basically op ai.

**Comment by SoMall-dumpling** [comment]
Logics can do anything.
But maybe we can have a Command Center 2.0 which have this feature (and so many other useful commands like digging ores).

**Comment by oinkymoo** [comment]
yeah if your turrets fail you and you have units you want on defense, then use logic or manual control

**Comment by Ymabert** [comment]
@SoMall-dumpling it would be a great idea to have a command center with which we can better manage the troops, obviously not to make the processors useless, but it would be nice to have access to the control of each type of troop and also to a specific quantity per type, if I want that my T2s are divided into two Farming groups of the type some go to collect copper and the rest lead, then if it happens that buildings are destroyed they stop doing this and go to repair and rebuild, if instead the buildings are under the range of an enemy turret already built I can decide whether to let them continue building at that point or not.  Then it would also be cool to be able to have a pre-set attack strategy, so that if the enemy while I attack him, he attacks me I don't necessarily have to stay by my troops but I can go and see how to defend, and to the defense it would also be nice to be able manage a minimum of defense robots, if one day they exist, such as if they are always around randomly, I would like to be able to decide if I want them on the edge of the village, only on defenseless and distant Farms, only on points still to be defended and so I place them warning me if there are attacks, an evolved command center, then another command center, would be a great idea in my opinion, especially when one has the village ahead and cannot think about primary materials since they need it have a Tier 5 as soon as possible.
