### ISSUE TITLE
Spiroct buff

### ISSUE THREAD

**Issue by OnyxFinger** [Anuken/Mindustry-Suggestions#2923]
### Describe what you would like changed, and why.

Right now, spirocts are considered as the worst T3 : they have good dps and lifesteal, but NEED to get close to their enemy, so they kinda just get killed everytime, because when they can't shoot, they can't do stuff lol.
even if you get them in range or something, they would have taken too much damage already, and die.

### Describe the changes you want to propose. Include possible alternatives.

After talking about it in #balancing, I was given the go-for to suggest these changes : 

spiroct speed : 0.4 to 0.75/0.7
spiroct lifesteal : ~50/sec (I actually don't know the exact stats oof) to 65/sec (I also don't know which guns steal how much health, but I would prefer if the guns with the most range got buffed)

eh sorry if it's kind of confusing, I'm not all that good at english

**Comment by Ymabert** [comment]
@OnyxFinger I would add a turret that shoots fireballs, like T2, only with much more range, so at least when I use them in addition to penetrating the fire village even where I do not pass, so I cause a lot more damage.  Or it would be good to have 1/3 more life, because if you do not produce in large quantities you do not combine anything, instead with the other T3 you can at least break down the main defense and if you are good you get even further, but with these little spiders from two pennies cannot even be tactical since they cannot be used to strategize, they are not even useful as a shield, or to waste all the ammunition on the defenses.

I'm not English either (I'm Italian) so I don't know if you'll be able to understand what I wrote.

**Comment by OnyxFinger** [comment]
closed because refused

**Comment by OnyxFinger** [comment]
> @OnyxFinger I would add a turret that shoots fireballs, like T2, only with much more range, so at least when I use them in addition to penetrating the fire village even where I do not pass, so I cause a lot more damage. Or it would be good to have 1/3 more life, because if you do not produce in large quantities you do not combine anything, instead with the other T3 you can at least break down the main defense and if you are good you get even further, but with these little spiders from two pennies cannot even be tactical since they cannot be used to strategize, they are not even useful as a shield, or to waste all the ammunition on the defenses.
> 
> I'm not English either (I'm Italian) so I don't know if you'll be able to understand what I wrote.

eh the fireballs would be rework, but the 1/3 hp would've been nice..

**Comment by OnyxFinger** [comment]
reopened because I'm stupid and Anuke was just not here ***AAAAHHHH***

**Comment by Ymabert** [comment]
@OnyxFinger why did you close this suggestion? in my opinion it is right to warn Anuke of the fact that they are the most useless T3s in the game, but not because no one wants to produce them, but because they are of no use at all😂.

**Comment by CDNexus** [comment]
With logic in place Spirocts are great for clearing out "The Flood" levels with logic, but yeah, I would never build one to approach turrets, perhaps to sneak over a hill or wall into the enemy base... but there are better options there.

**Comment by Ymabert** [comment]
@CDNexus the T2 Mace and Atrax and the T3 Spiroct are the least used troops because having to get very close to the enemy defenses to be able to attack them many times they die first, or in any case if they reach the enemy turrets they do not inflict great damage, in fact they must be used to open holes in the blind spots i simply as a shield, it is rare to beat someone if you have these droids, it happened to me in the FFA yesterday to continue taking damage and losing cores due to a T1 Flare spammer, instead I had a group of Mace and Atrax I went direct against the cores and I defeated him definitively, but I had lost a lot of materials, sectors and repair drones because of his attacks, in fact I lost because the other player that no one was attacking had made an army of T3 Fortress and had defended everything as well as possible, so I can say that these droids I used are useful, but being destroyed and then slowly going to take down the enemy is certainly not the  best strategy, in fact this guy lost because he didn't build defenses for ground troops, this game is still too developed for flying droids, who expects slow attack from ground? none, it's easier for one to use air troops given which are much faster and if used well they attack even from a distance, not to mention the fact that they can go straight to the core if you use a processor (this bores me a lot, I always hope that no one has that processor, because at least one core I do always destroy).

**Comment by OnyxFinger** [comment]
> With logic in place Spirocts are great for clearing out "The Flood" levels with logic, but yeah, I would never build one to approach turrets, perhaps to sneak over a hill or wall into the enemy base... but there are better options there.

it's the flood, not an actual gamemode...

**Comment by OnyxFinger** [comment]
> @OnyxFinger why did you close this suggestion? in my opinion it is right to warn Anuke of the fact that they are the most useless T3s in the game, but not because no one wants to produce them, but because they are of no use at alljoy.

I thought Anuke was gone for some time...
