### ISSUE TITLE
Robots Control (when i build a Command Center).

### ISSUE THREAD

**Issue by Ymabert** [Anuken/Mindustry-Suggestions#2929]
### Describe what you would like changed, and why.

it would be useful to be able to direct the troops simply by selecting them and indicating where they must go, even when at the spawn, instead of making them stay in front of the spawn I indicate using the appropriate setting (like a symbol of a flag that gives me the possibility to indicate the point in where the troops will have to go, simply with a click) where I want them to go, then if with the command center active the "O" and not the "X" the troops group together as they do now and if the attack is active they simply attack .

### Describe the changes you want to propose. Include possible alternatives.

the advantage would be that I can move the troops as I want and I don't have to select them one by one to move them where I want, I simply have the setting to select (as there is for example on Age of Empires) and then with the appropriate button I move them where I want, if I have the possibility I also shoot the troops that have weapons, build those they build, produce materials those that have the possibility to do so, in doing so the game will be complete and the processors will not become obsolete, I just ask you to give me the ability to move troops faster and be able to make the most of them without adding too many things.  I now move the troops one by one and then the Command Center will set it on attack, it would only change that the game is complete and I don't have to invent strange things to win, since then I waste time and the enemy evolves in the meantime.

if then having a control of the troops is asking too much then I am satisfied even so, but I ask you to add these things because in my opinion the game is more complete and simplified, the important thing is that the processors do not become obsolete and with these settings they do not they will become.

**Comment by OnyxFinger** [comment]
so, with this and #2927, there is one issue : this was originally planned on the trello, but has been shelved, for unknown resaons, probably the control difficulty on some devices. since Anuke "checks the repositroy daily", I hope to get a clarification on why exactly it was shelved, after what I will be able to give my definite statement.

I personnally think that it is, if implementable, a good change, because the game (especially PvP, PvP fanboiiii forever !!!) would get some micro potential, which would make it feel less plain (right now, PvP in mindustry is very macro-based, making it sometmes feel plain, even though it feels more dynamic in v6).
