### ISSUE TITLE
Multiplayer Pause

### ISSUE THREAD

**Issue by MMT007** [Anuken/Mindustry-Suggestions#296]
**The Multiplayer Pause : [ Its a Pause for Lan or Community servers ] Mechanics: [ A vote for pause the game, can be pressed like in single player (or space bar), then under the map will be a voting for pause] Voting Mechanics : [ 2 players : [ both need to vote ] 3 players : [ 2/3 players need to vote ] 4 players : [ 3/4 players need to vote ] and so on..]**

Can improve the issues of losing right when you enter in a server/wait for someone in Lan to ### enter

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
I think this should only be implemented as so far as waiting for more players. Not as a pause in during multiplayer gameplay.

**Comment by Anuken** [comment]
Duplicate.

**Comment by itcannotbe** [comment]
For reference.
This is a duplicate of #56 or #261

**Comment by abaines** [comment]
Not sure if I'd be better asking for this issue to be revived, or making a new issue, but I would like to see a real multiplayer pause functionality, kind of like _AI War: Fleet Command_ (if you are familiar). Any player can pause or un-pause whenever they want.

Ideally two different key-bindings for pausing and un-pausing, so if both players decide to "toggle" pausing at the same time, they do not cancel out.  There are several aspects of the single player that would be really enjoyable and fun during coop, like the planning and fluid strategic thinking instead of chaotic rehearsed frenzy builds. It seems like a mechanic that work really great here.

Many Thanks! 🧡

<sub>P.S. Please let me know if this would be better made into a new issue, or if this one could be revived/revisited.</sub>
