### ISSUE TITLE
Tokamak Fusion Reactor and Inertial Confinement Fusion Reactor

### ISSUE THREAD

**Issue by Usernames-Are-Not-Available** [Anuken/Mindustry-Suggestions#2978]
### Describe the content or mechanics you are proposing.

I'm proposing a new kind of power source that could fit some kind of niche that hasn't been implemented so far.
We have the Thorium Reactor and the Impact Reactor (both great ideas). I'm proposing two ideas, of which hopefully one might be chosen. Both of them being fusion reactors. 

The Tokamak is the magnetic confinement type of fusion reactor, which is being used at KSTAR and the ITER. I'm thinking that it could possibly be the best power source in the game, but at a cost of a 7x7 area for the reactor, a constant supply of water and cryofluid (or the reaction would stop, but the reactor wouldn't explode), a large amount of Thorium, more than the Thorium Reactor requires, and a large amount of power to kick-start the process (more than the Impact Reactor needs). In other words, a mix of the Thorium reactor and Impact reactor.

The inertial Confinement reactor could be much smaller than the Tokamak, but at a cost of much less energy being produced, and that it has a brief period where it won't produce energy as the next batch of Thorium is loaded into the reactor chamber.

In terms of energy production, the Tokamak could produce 10000 units of energy a second, more than the Impact Reactor, but use 3000 units of energy every second for one minute to start producing energy. The Inertial Confinement could produce 6000 units of energy, but only using 200 units of energy per second for 10 seconds (the time when it won't produce energy) to kick-start the process, every time a batch is loaded. That is a good compromise considering that the size of the Inertial Confinement could be just one block big. 

In terms of resource costs to build, for the Inertial Confinement, I'd prefer something similar to the Thorium Reactor. For the Tokamak, I'd prefer double or treble the costs to build the Impact Reactor.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

In terms of improving the game, it could make getting more resources a bit quicker if they can build them. The Inertial Confinement could be used in small locations where building bigger power sources may not be feasible. The Tokamak could be used if the player wanted lots of energy for filling batteries quickly or if a turret with an insane energy requirement was added.
It could fill some niches as nuclear fusion is only just starting to gain popularity again and this is implementing real-world ideas into a game for all to enjoy. It could (probably not, but still) help the movement in some way. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Didn't we beat this to death in #163

**Comment by Usernames-Are-Not-Available** [comment]
This is a different idea to that. That was about reactor explosions. I didn't talk about that, or making them more realistic, I was talking about adding one other reactor that is more like a fusion reactor but with no explosion.

**Comment by genNAowl** [comment]
Is this really needed though? The impact reactor already creates more than enough power late game, and not too many of use had problems with power in small areas. This definitely feels like it belongs in the realm of modded content, and until a real need comes up for a even larger reactor, I can't see this being added to the game.

**Comment by Feilong-Mindustry** [comment]
This is extremely volatile idea. Mindustry won't be enjoyable game witihout Thorium and Impact reactors in v5. There is massive trade off in either opting for using "dangerous" power with Thorium reactors or be in a constant threat of blackout with Impacts. Energy management is the core mechanich in the game and should not be treated lightly. v6 changes with mlog thrown a massive wrench in the power mechanics. Nowadays thorium reactors are safe, however much less usable, since all thorium is typically required for phase matter production to dome boost massive production, ammo and defenses. Combined with more power hungry bases, this left impacts as an only viable option.
It's essential to treat every new change in power direction with caution. Every new reactor type should be difficult to build and dangerous to use to keep things interesting. By creating "Better Impacts" working on less types of resources you'd kill power management completely.
I'm big on both better representation of nuclear power and every new realistic reactor concept, but not at the cost of gameplay.
