### ISSUE TITLE
A way to generate Scrap

### ISSUE THREAD

**Issue by Anakousmos** [Anuken/Mindustry-Suggestions#2995]
### Describe the content or mechanics you are proposing.

I think we should have a way to generate Scrap. Perhaps a machine that accepts sand and filters out scrap metal from it, as in, a reverse pulverizer, or a building that extracts scrap particulates from the ground, similar to a water extractor?

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think it will improve the game by providing a way to get resources in sectors without many natural resources. I personally don't believe that Scrap is currently used enough, and adding this will open up a completely new avenue for schematic designers and will allow players to further optimize their bases 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Has been rejected before.

**Comment by RedstonerKBC** [comment]
2 things that really tick me off: GitHub's 2FA requirement and the argument that scrap is op. Scrap is not OP or else it would be one of the only things people mine for and I almost never see people mine it except the noobs and the schematics design challenges.

**Comment by RedstonerKBC** [comment]
Oh yes and by the way, I still haven't had any of you Scrap is OP people try my scrap only challenge maps (I got rid of them months ago so it's too late now). Maybe I'm just not using scrap properly but scrap is pretty useless.

**Comment by begginerr** [comment]
> Oh yes and by the way, I still haven't had any of you Scrap is OP people try my scrap only challenge maps (I got rid of them months ago so it's too late now). Maybe I'm just not using scrap properly but scrap is pretty useless.

alone yes, its only scatter ammo, but look at separator and dissasembler. in v5 scrap was op but not as op as now because it couldn't make thorium. but v6 came and it can now! you can make a scrap to absolutely everything, all items, all fluids (except water because water extractor) all units. it is impossible to even get copper with just scrap and no other ore available, but with enough resources to make melters, disassemblers and separators, its possible to beat the map.

**Comment by begginerr** [comment]
i understand if you reject my opinion, thats normal. but even anuke himself said that making a scrap factory would be way too op

**Comment by OnyxFinger** [comment]
scrap isn't used enough because it's pretty much just bad, what can I say ?
it's good if you're out of ressources, that's it, that's actually the point if you want my opinion (also because it's from ruins but t's old "version" wasn't so eh)

**Comment by vinhsad** [comment]
how tf you extract scrap from the ground scrap is trash metal

**Comment by genNAowl** [comment]
> even anuke himself said that making a scrap factory would be way too op

Not because scrap was op. Only because being able to make anything from just *space* and *power* was op.

**Comment by OnyxFinger** [comment]
> > even anuke himself said that making a scrap factory would be way too op
> 
> Not because scrap was op. Only because being able to make anything from just _space_ and _power_ was op.

depends on how efficient it is, actually. Still, there is literally no need for this in my opinion

**Comment by TranquillyUnpleasant** [comment]
> I think it will improve the game by providing a way to get resources in sectors without many natural resources.

Have you perhaps not researched the launchpad? Moving resources between sectors is relatively easy. Also, that entirely ruins the point of sectors whose main aim is to be hard because of resource starvation, thus just making the game more homogenous.

> I personally don't believe that Scrap is currently used enough

Scrap is sort of a last resort resource, its not supposed to be used for main production unless theres no other options, its in the name itself, its *scrap* to be reused if theres nothing else to use, so it not being used much is sort of intended.

> adding this will open up a completely new avenue for schematic designers.

Not really no, instead of `scrap to x` it will just become `sand to x` or whatever resource makes scrap tacked on, without changing the way it is used, likely with more efficiency costs and even less in game feasability.

> and will allow players to further optimize their bases.

How would introducing a less efficient option allow people to optimize bases? All it does is make sand more necessary, which is already needed a lot.

**Comment by OnyxFinger** [comment]
> > I think it will improve the game by providing a way to get resources in sectors without many natural resources.
> 
> Have you perhaps not researched the launchpad? Moving resources between sectors is relatively easy. Also, that entirely ruins the point of sectors whose main aim is to be hard because of resource starvation, thus just making the game more 

actually good argument, at first I was kinda like "meh it's not great" but then after thinking about it, it's entirely valid
