### ISSUE TITLE
A personalized UI

### ISSUE THREAD

**Issue by Theoneflop** [Anuken/Mindustry-Suggestions#3020]
### Describe what you would like changed, and why.

The UI of the game is rather static and follows norms such as "show fastest server on the top" but a fast server being fast doesn't mean I play on it. Most players do not join servers that have zero players inside. On another side note, there are many types of players, in which some just play offline, some just online, some on a specifc server and some just custom maps they made.

### Describe the changes you want to propose. Include possible alternatives.

The change I propose is as follows:

1. Instead of showing the fastest server on top, show the server that the player joins the most on top.
2. Balance the categorization of servers to be sorted depending on how much players are playing on it & how much the player ACTUALLY plays on it. Speed should be the least to worry of. (a server that has 0 players will surely be fast)
3. The game should highlight(maximize/brighten) buttons the player uses the most (such as Campaign or join game).

All these changes are made so that the player focuses more on the game's experience rather than searching in a complicated UI.

**Comment by the-red-soul** [comment]
>     1. Instead of showing the fastest server on top, show the server that the player joins the most on top.
 
By fastest im assuming you mean lowest ping, which is generally a good thing to prioritize as playing on a server where you have even 300ms ping can be a pain in the ass. this is true for all games. As for "show the server that the player joins most on top" hide other server groups with the eyeball icon to the right.

![image](https://user-images.githubusercontent.com/31638088/134825764-bd4e7885-0c29-4b40-84ab-3edc4993fb78.png)


>     2. Balance the categorization of servers to be sorted depending on how much players are playing on it

This would absolutely kill any new servers or servers with a low playercount if all people see are servers with high playercounts. Forcing people to scroll to lower pop servers/games. Terrible idea. 

>  how much the player ACTUALLY plays on it.
> 

again, hide servers you dont play on with the icons.

> Speed should be the least to worry of. (a server that has 0 players will surely be fast)

Untrue. Again it is sorted by ping not tps or speed. If i were to connect to a russian server with zero players i would have a worse time than if i were to join a NA server with say 10 players due to the latency.

>     3. The game should highlight(maximize/brighten) buttons the player uses the most (such as Campaign or join game).
> 

What purpose does a shiny button serve? im sure that if someone likes singleplayer they will click on singleplayer. Do you need your doors in your house to light up to know what doors you frequently enter/exit? no. This does not exist in any game, why here? its pointless.

> 
> All these changes are made so that the player focuses more on the game's experience rather than searching in a complicated UI.

The ui is not complicated in any way. its a scrolling list where you can hide groups of servers and is sorted by ping. I fail to see how this is in any way complicated for the average player to understand..
