### ISSUE TITLE
Crawler tree and omura needs rebalance

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3022]
### Describe what you would like changed, and why.

Crawler, atrax and spiroct are not usefull. Players almost never build them. Only toxopid is strong. And omura ability to build flares is useless. It just saves you a bit of silicon

### Describe the changes you want to propose. Include possible alternatives.

Increase range of crawler explosion to make it effective against walls and big crounds of units

Make atrax set buildings on fire more easily. So it would be more effective to have a few of them in a squad

Give spiroct mini version of paralax and maybe give arkyid a bigger parallax to take anti-air nech, because now only air units are effective against air units

It would also be nice if omura would have it's own limit of 8 units independent of core limit. It never even builds them because at endgame you already have 24 flared.
Flares would follow it and when omura is shooting the would go to that place and atack targets there. They could not be controlled by procesors or command center because they are connected to amura instead of core

And maybe make quad atack heal ally units because it's not very supportive supporter

**Comment by OnyxFinger** [comment]
> Make atrax set buildings on fire more easily. So it would be more effective to have a few of them in a squad

yes

> It would also be nice if omura would have it's own limit of 8 units independent of core limit. They would follow it and when omura is shooting
the would go to that place and atack targets there. They could not be controlled by procesors or command center because they are connected to amura instead of core

no. omura is strong because it is very limited. It's quite balanced rn, firstly because at no point in a game I want to go for long enough to make one, it should be game ending

**Comment by Dangleos** [comment]
> no. omura is strong because it is very limited. It's quite balanced rn, firstly because at no point in a game I want to go for long enough to make one, it should be game ending
Did you have a stroke?

Its ability to build flares is useless. It never even builds them because at endgame you already have 15 silicon. It looks like it isn't finished. I thought that anuke fixed it before

**Comment by begginerr** [comment]
he didnt have a stroke, look at its railgun. 1350 damage PER SHOT. sure, making flares is pretty useless but omura is op by itself

**Comment by the-red-soul** [comment]
> Crawler, atrax and spiroct are not usefull. Players almost never build them

Crawlers are great in groups. they are fast and have the most health out of all t1 units, and the most damage. A big enough group of them reaching a wall can absolutely devastate a defense and easily cause a breach. 

Atrax can just walk over top of your walls and defenses going into your base, or just taking a completely different route to your core(s) that are not available to other units. Its weakness is in its weapon which cannot hit air or fly over top of enemy walls. Maybe yes it should generate a bit more fire but it is still unique.

Spiroct has lifesteal on its attacks making it a LOT LOT harder to kill once it actually is dealing damage to something. On top of it being able to just walk over your walls can be very very dangerous. Air is its weakness due to its range which is one thing to balance it out. Giving it parallax would put it into the support tier (green tier) which it is not. It CAN reach zeniths and deal damage to them, healing itself in the process.

Arkyid can destroy almost all of the t5s in the game in a 1v1 situation. This includes Eclipse, Reign, Corvus, Oct, and Omura. It cannot kill Toxopid due to Toxopid being an even bigger Arkyid. Why can it do so much? Because of the lifesteal on this unit being the strongest in the game. Toxopid has less lifesteal than Arkyid but a lot lot more damage. If an Arkyid gets to your defense and you don't have Spectres or Fuse to deal with it, kiss your defense/core goodbye.

> Only toxopid is strong. 

I have clearly proven you wrong with the paragraphs above. That being said Arkyid is honestly more survivable and can deal more damage than Toxopid. Toxopid has a lot less lifesteal since it is only on the howitzer and not the main shotgun. If it was it would be 100% unkillable. You come off to me like all the other new players who see the giant spider and think they are the best unit in the game, when it is not. It has to get up close to deal damage like the rest, and then it will destroy the defense by its foot damage and shotguns. But if you destroy it before then it is pointless. Most pro players stay away from Toxopid because by that time people usually have foreshadows up which can take care of Toxopid before they get anywhere near, and any other spider for that matter.

> And omura ability to build flares is useless. It just saves you a bit of silicon

24 flares is 360 silicon. A moderate amount depending on your setup.

Why are you complaining about free units? All it takes is for one flare to fly around and break that one integral power node. Or snipe that one important belt. The planes go where Omura cannot, Over land. Most naval units are quite strong, Omura is no exception. 

Did I mention it is the only unit that can out range foreshadow?


> It would also be nice if omura would have it's own limit of 8 units independent of core limit. It never even builds them because at endgame you already have 24 flared.

So if you have 24 Omuras each with their own limit of 8 flares, that is 192 flares...... seems totally reasonable and not unbalanced.

> Flares would follow it and when omura is shooting the would go to that place and atack targets there. They could not be controlled by procesors or command center because they are connected to amura instead of core
> 

You can do this with logic to automatically control massive groups of units to go where you want and attack. Either manually while you are sitting in a turret. As for making them uncontrollable by logic or the command center can lead to undesired behavior and sounds like a pain to implement into the game for one unit. Not to mention a specific ai for only these flares and not for all flares.

> And maybe make quad atack heal ally units because it's not very supportive supporter

Your initial suggestion talked about Crawler, Atrax, Spiroct, and Omura. Why are you including Quad?  I guess you also included Arkyid  and Toxopid indirectly so who cares at this point. Not like there is a template or format you butchered.

Vela is getting the ability to heal units in v7. Quad is in a very good spot right now and does not need any tweaks to its damage. Its projectile actually received a rework I believe so it would be doing more consistent damage throughout. It also heals buildings. Some rediculous endgame defences have a ton of quads sitting ontop of the defences healing them alongside the menders.


Close this suggestion.

**Comment by OnyxFinger** [comment]
> > no. omura is strong because it is very limited. It's quite balanced rn, firstly because at no point in a game I want to go for long enough to make one, it should be game ending
> 
> Did you have a stroke?
> 
> Its ability to build flares is useless. It never even builds them because at endgame you already have 15 silicon. It looks like it isn't finished. I thought that anuke fixed it before

and ? it doesn't make them OP
if someone's having a stroke, it's you before me (though I wouldn't saying anyone is having a stroke)

**Comment by OnyxFinger** [comment]
> > Crawler, atrax and spiroct are not usefull. Players almost never build them
> 
> Crawlers are great in groups. they are fast and have the most health out of all t1 units, and the most damage. A big enough group of them reaching a wall can absolutely devastate a defense and easily cause a breach.
> 
> Atrax can just walk over top of your walls and defenses going into your base, or just taking a completely different route to your core(s) that are not available to other units. Its weakness is in its weapon which cannot hit air or fly over top of enemy walls. Maybe yes it should generate a bit more fire but it is still unique.
> 
> Spiroct has lifesteal on its attacks making it a LOT LOT harder to kill once it actually is dealing damage to something. On top of it being able to just walk over your walls can be very very dangerous. Air is its weakness due to its range which is one thing to balance it out. Giving it parallax would put it into the support tier (green tier) which it is not. It CAN reach zeniths and deal damage to them, healing itself in the process.

aaannnnddd no. atraxes are way too slow and have laughable dps, crawlers die on impacts which pretty much makes them useless, and spirocts die before or shortly after reaching it's targets.

**Comment by OnyxFinger** [comment]
> Why are you complaining about free units? All it takes is for one flare to fly around and break that one integral power node. Or snipe that one important belt. The planes go where Omura cannot, Over land. Most naval units are quite strong, Omura is no exception.

he isn't complaining about those, he is complaining about how useless that is. First off, the silicon omura gives you is very low
Then, once you have an omura, flares aren't supposed to snipe your nodes, nor anything. In fact, nothing is supposed to snipe anything, unless the map is way oversized.
