### ISSUE TITLE
Standardize hotkeys with common functionality

### ISSUE THREAD

**Issue by maxshowarth** [Anuken/Mindustry-Suggestions#304]
**Describe what you would like changed, and why.**
Certain categories contain blocks which perform a similar function, but for a different material or scenario. 

For example, the conveyer/sorter category [Hotkey 1] and the pump/conduit category [Hotkey 4] both contain blocks to produce a material and transport/sort material. However, the hotkeys for blocks that perform the same function are different in each category - see the table below. 

| Function | Conveyer/Sorter Hotkey | Pump/Conduit Hotkey|
| --- | --- | --- |
| Regular Transport| 3-1 | 4-3|
| Fast Transport | 3-2 |4-4|
| Router | 3-7 | 4-5 |
| Junction | 3-3 | 4-7|
| Bridge | 3-4 | 4-8|

Having similar functionality with different hotkeys adds an unnecessary element of uncertainty for new players as they are gaining footing, and is just kind of inconvenient for older players. I can see how this wouldn't matter on a touch screen device, but it does cause some issues when using hot-keys. 

**Describe the changes you want to propose. Include possible alternatives.**
Possible solutions:
1. Rearrange/remap the Pump/Conduit category to match the conveyer/sorter category (e.g. move the pumps to the end, etc.)
2. Allow users to set their own hotkeys/positions within a category

I feel like option 1 is the most feasible, and honestly would be fine for most people mods notwithstanding. If implemented I would also say the old configuration should be selectable as an option for seasoned players!

**Comment by kingb74** [comment]
Please don't make crawlers cost blast please even if they cost 20 coal it's just not blast because blast is expensive to make and crawlers don't do much other than explode and please daggers just can't cost lead please put it back o  just silicon please lead is not always there and it will make making daggers harder than it should be and also titan cost is a little excessive don't u think but for second level crawlers that cost makes sense same goes for fortress and 3level crawlers so for the 2 and 3 upgrade u should make the different units cost different prices and please a manual shoting system on mobile that doesn't require me to go to settings a set keyboard controls plus u can't even move while using keyboard controls on mobile so please
