### ISSUE TITLE
Remove the spaceblock instakill feature, if ur boxed in 5 layers of spaceblocks and u spawn in there, u can't escape

### ISSUE THREAD

**Issue by Weptlogdotzip1** [Anuken/Mindustry-Suggestions#3048]

**Comment by itcannotbe** [comment]
That's called a bad map design.

Also who even uses the shitty github app anyways?

**Comment by itcannotbe** [comment]
Also haven't it occurred to you that you can use **FLYING** units?

**Comment by Kyllingene** [comment]
@itcannotbe, be more productive next time

@Weptlogdotzip1, he is right on all accounts; this is a map-specific issue, and the Github app doesn't support issue templates; therefore, you completely bypassed an otherwise required template that prevents issues like this existing. The title is a title, not a description; next time, use the website.

**Comment by itcannotbe** [comment]
> be more productive next time

I am that lazy. XD.

**Comment by Weptlogdotzip1** [comment]
> Also haven't it occurred to you that you can use **FLYING** units?

ALL TYPES OF UNITS GET KILLED BY SPACE BLOCKS

**Comment by itcannotbe** [comment]
> > Also haven't it occurred to you that you can use **FLYING** units?
> 
> ALL TYPES OF UNITS GET KILLED BY SPACE BLOCKS

Prove it.
