### ISSUE TITLE
If disable the Schematic, Logic Codes copy&paste disable

### ISSUE THREAD

**Issue by FreezeMandu** [Anuken/Mindustry-Suggestions#3087]
### Describe what you would like changed, and why.

Added schematic disable rule to ban logic schematic while making PvP maps. 
However, I was able to circumvent this rule by pasting the code.

### Describe the changes you want to propose. Include possible alternatives.

I want to disable the code pasting when disabling the schematic

**Comment by acoaco** [comment]
Flare/horizon controller only few lines if it's doesn't need flag check
The real problem is in map ban schematic people think it's a no logic game,so ban logic on that map will much easier

I think only a scrap pvp map ban schematic now?I forgot on what server,ban schematic is pretty unfriendly for mobile game players

TBH disable the Schematic even doesn't work now,plugin like pvp notifis already show it's only blocked schematic menu's button,thing like plugin or custom client can easily by pass it just like players can mine sand in custom client,I will suggest reimplement check disable schematic feature in server side to do it

**Comment by itcannotbe** [comment]
If you really want to ban schematics. Just make it impossible to place them down (Like scattered random environment walls.)

**Comment by end-me-please** [comment]
Just ban processors/other logic blocks...problem solved
