### ISSUE TITLE
Just make mods to load on-the-go

### ISSUE THREAD

**Issue by NHABB2TFNX0P83UK82SK** [Anuken/Mindustry-Suggestions#3113]
### Describe what you would like changed, and why.

Trying to get more fun on servers through getting mods installation on-the-go. 

### Describe the changes you want to propose. Include possible alternatives.

I'm tired of normal games and wanted more content IDK why there are no modded servers. So I ask you to make mod content load quickly like till the window is open (or just stored in RAM) and (or maybe) do cleanup. Easier for server owners and players.

**Comment by OnyxFinger** [comment]
Seapy reacts to suggestions so fast...

**Comment by LeoSko** [comment]
> Seapy reacts to suggestions so fast...

@OnyxFinger, only to some random things that **I also really really want** ~~and cry about in rainy weather~~.

**Comment by the-red-soul** [comment]
>>I'm tired of normal games

Then try something different. Not our problem.

>> IDK why there are no modded servers

Because no one hosts modded servers. Dont want the extra hassle of dealing with them. You need custom modded maps which take time, and then balancing of mods and it is a whole shitshow. Is it possible? yes. Do most of the community play with mods? doubt it. Not worth their time for so few players.

>>So I ask you to make mod content load quickly like till the window is open (or just stored in RAM) and (or maybe) do cleanup. 

You want the game to load mods without the game restarting? Funny how the game was made to forcibly restart whenever mods are enabled/disabled to ensure everything is loaded properly. When it didnt restart automatically players had to do it themselves or be faced with inconsistencies and bugs with the mods they were using. Making it a mandatory restart fixed a lot of issues and is not really an inconvenience due to how fast the game loads anyways.

>>Easier for server owners and players.

mods are already stupidly easy to install with the steam workshop or importing from github. Hell you just go to the mods tab and browse and WOAH LOOK MODS. Dont see how it can be easier than it already is. 


I just now looked and saw you wrote a response on the trello that LeoSko linked. 
![image](https://user-images.githubusercontent.com/31638088/137995675-05e80ffb-f34b-48b7-bca6-2421e4393a71.png)

You want Anuke to recode and restructure an entire part of the game, breaking all mods currently made and pissing a lot of people off. When v6 came out almost all mods were made incompatable due to modding changes and Anuke does NOT want that to happen again for obvious reasons. The second half of your statement proves you have no idea how mods work since well, THATS HOW THEY WORK. Different textures on items that are coded in hjson using a list of presets. Its how vanilla items are programmed and how modded ones are.


Close this suggestion
