### ISSUE TITLE
enemy spawning border to be highlighted in the map

### ISSUE THREAD

**Issue by zxavier01** [Anuken/Mindustry-Suggestions#312]
**Describe the content or mechanics you are proposing.**
as mentioned in the title, enemy spawning border should be highlighted in the map, one pixel highlight is not sufficient

![sample image](https://user-images.githubusercontent.com/68508691/87878796-2e6b5280-ca19-11ea-808a-3275d65b73b1.png)

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
so the player who is unfamiliar at the map doesnt need to search/go around the entire map which saves time.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
But finding where enemies spawn is actually part of the game.

**Comment by Anuken** [comment]
> the player who is unfamiliar at the map doesnt need to search/go around the entire map which saves time.

Why is this a problem? Exploring the map and finding out where everything is part of the challenge. You have to know the terrain a little before placing down turrets.

**Comment by klutt** [comment]
> > the player who is unfamiliar at the map doesnt need to search/go around the entire map which saves time.
> 
> Why is this a problem? Exploring the map and finding out where everything is part of the challenge. You have to know the terrain a little before placing down turrets.

I belong to the camp that think this is a problem. 

By design, the game is not like Starcraft, where you expand outwards. In Mindustry, it rather makes more sense to start building far away and expand inwards. And when you do that, it's much more critical to know where the enemy is early on. Another big difference compared to Starcraft is that you can build scout units early in the game to do the exploring. 

I cannot really explain why, but it just don't feel like a good and relevant challenge in this game. It's just a frustrating thing. In Starcraft, the exploring part feel fun, exiting and relevant. 

Just as a comparison. Imagine that you're playing Super Mario Bros 1, and at each stage there are things you need to do in the beginning that will have a huge impact when you reach the end, but you need to get to the end to find out what you should have done in the beginning. That would simply not make sense. But that is exactly the feeling I'm getting here.

A workaround right now is to start exploring, find the enemy drop places, die and restart. And I don't get the feeling of cheating. I only get the feeling that I'm working around a bug. And if a player gets that feeling, it's not a good sign. As they say: "Given the opportunity, players will optimize the fun out of a game."

I do like the game in general, but this particular detail is actually pretty annoying.
