### ISSUE TITLE
Mindustry Launcher

### ISSUE THREAD

**Issue by Jerzozwierz123** [Anuken/Mindustry-Suggestions#3154]
### Describe the content or mechanics you are proposing.

I think that you could do mindustry launcher. It would allow you to play different versions of mindustry without having to install them manually. You would be able to switch folders that your game data is stored in etc. Just like minecraft launcher.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think that mindustry launcher could be good option because you would be able to play old and new versions. If you don't like latest update? No problem! You can play older version. Or you maybe don't want to update yet (Steam)? No problem you can finish what you started and then update! It would be also good for old players who feel nostalgic to older versions.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
I wonder, where are you even gonna get the files for every version that existed from. Apparently they don't come from nothing right? They would be needed to be retrieved from somewhere right?

**Comment by Jerzozwierz123** [comment]
Maybe not every version but most. You can find those files in releases.

**Comment by itcannotbe** [comment]
> I wonder, where are you even gonna get the files for every version that existed from. Apparently they don't come from nothing right? They would be needed to be retrieved from somewhere right?

Sarcasm Removed:
Where do you expect to host the files from?

**Comment by IxGamerXL** [comment]
This is actually a pretty nice suggestion. Much like the minecraft launcher, you could download versions of the game, and play the versions you have installed. 

I don't see any difficulties or issues besides maybe the versions themselves and if they still exist in archive.

**Comment by Kyllingene** [comment]
Aside from the storage that this would require, there is a very serious issue regarding networking. Anuke, to make this work, would either need to exclude Steam from the VC system or make each version work with the Steam servers.

The first option is obviously a poor one as it would entail Anuke losing a good chunk of his already paltry revenue from the game that comes from it being simple. Unless you want Anuke to be fiscally impacted for the sake of your convenience, this is not an option.

The second option is at best incredibly tricky, and at worst physically impossible. Since Steam forces you to update before playing, there has never before been any problems with clients of different versions trying to play with eachother; but, if this was implemented, Anuke would need to add that double-checking to each supported version, which would be impossible if he were utilizing the Releases tab, since there is no way to edit those. Anuke would need to host them elsewhere, which would invariably be a large hassle and potentially require yet another monetary investment into a free game.

Ultimately, you failed to keep in mind the different platforms and their networking differences, and have accordingly made a suggestion that is impossible to do without immense effort and potentially even money for a small amount of convenience.
