### ISSUE TITLE
Хорошие варианты дополнения для Mindustry

### ISSUE THREAD

**Issue by Maxim953** [Anuken/Mindustry-Suggestions#3172]
### Describe the content or mechanics you are proposing.

Здравствуйте. Я предлагаю добавить другие ископаемые или смесь какие-нибудь ресурсов. Так как имеется солнечная система я со своим другом (возможно и другие игроки) хотели бы новые планеты, а это значит новая сюжетка и новые материалы, к примеру как магний, сера, висмут, золото и др. Так как если будете добавлять новые планеты то нужны новые и очень сильных мобов. А что-бы их побеждать нужны новые оружия которое делается из новых ресурсов. Было-бы хорошо добавить улучшения к своей технике и отдельно можно улучшить юнита, к примеру (добавляет хп но отнимает урон, уменьшает дальность но прибавляет урон). ну или менять на специальном месте оружие.
Было-бы хорошо что добавили для реалистичности   луну, и какую-ту модификацию на красивую графику (если возможно). Прикольно было иметь свой личный участок, для того чтобы смотреть на  заблокированной карты, примерное местоположение появления мобов, и какой будет страж. И были бы какие-то просьбы или мисии от друга или кого ещё. Игру можно сделать более тяжелой если включить режим, который можно включить (по желанию),(придумаете сами. не хватает у меня фантазии что-бы придумать), При включения режима говориться что нельзя строить или использовать материал. Если игрок захватит все планеты полностью то он не забросит игру так как на его часто будут       нападать враги с отдельных  планет, на которые нельзя напасть, ну или может но будет очень тяжело.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Добавил хоть чу чуть интереса, были бы просьбы что нужно сделать. Некоторым нравятся сложные игры где нужно ломать голову (как я), в этом поможет новый режим который можно включить по желанию, добавит новые возможности за пределы 1-ой планеты расширется сюжетка. Будут часиые наподении (если игрок захватывает участок, и то с каким-то %).
новые ресурсы из которых можно делать смеси и получать новый болей крепкий материал. изменится графика будет красивей (если будите менять). добавиться новая механика по изменения характеристики персонажа.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Maxim953** [comment]
я отвечю на ваши вопросы почему именно так

**Comment by begginerr** [comment]
translation: Hello. I propose to add other fossils or mix some resources. Since there is a solar system I and my friend (and probably other players) would like new planets, and this means a new storyline and new materials, for example as magnesium, sulfur, bismuth, gold, etc. Since if you add new planets we need new and very strong mobs. And what to fight them need new weapons, which is made of new resources. It would be nice to add improvements to its equipment, and separately can improve the unit, for example (adds xp but takes damage, reduces the range but adds damage). well, or change the special place weapon.
It would be nice to add to realistic moon, and what would modify the beautiful graphics (if possible). It would be cool to have your own personal area, to look at the blocked map, the approximate location of the appearance of the mobs, and what will be the guards. And there would be some requests or missions from a friend or who else. The game can be made more difficult if you include a mode that can be included (if desired), (I do not have enough imagination to come up with), When you include a mode said that you can not build or use material. If a player takes over all the planets completely, he will not abandon the game, as it will often be attacked by enemies from individual planets that can not attack, well, maybe, but it will be very difficult.
Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
Added a bit of interest, would have been to ask what needs to be done. Some people like complex games where you have to break your head (like me), this will help the new mode that can be enabled at will, add new features beyond the 1st planet will expand the storyline. There will be hourly assaults (if the player captures the area, and that with some %).
new resources from which you can make mixtures and get new stronger material. the graphics will change will be more beautiful (if you will change it). new mechanics to change the character characteristics will be added

Translated with www.DeepL.com/Translator (free version)

**Comment by oinkymoo** [comment]
this game does not have any biological entities larger than a spore, any fossils would probably just take the form of oil or coal anyway
