### ISSUE TITLE
Core Launching

### ISSUE THREAD

**Issue by SwitchLikesMlog** [Anuken/Mindustry-Suggestions#3223]
### Describe what you would like changed, and why.

Currently, the way that you can launch from sectors to others is quite confusing, the game doesnt tell the conditions of what sector you are launching from. 

### Describe the changes you want to propose. Include possible alternatives.

Just make every sector can launch to/from anywhere. 
Should be simple i hope.

**Comment by SwitchLikesMlog** [comment]
im 99% sure that this idea will get downvoted, but who knows

**Comment by SwitchLikesMlog** [comment]
this idea might get thrown into hell but eh, ill sacrifice one for the team

**Comment by Kyllingene** [comment]
Your issue needs clarifying. You can currently launch to any unlocked sector from any captured sector. When you launch, you take the resources for launching from the sector you launch from. 

What are the 'conditions' you don't get to see? If you mistyped and meant you can't see the conditions of the sector you're launching *to*, then you just need to know how it works; you can launch to any regular sector as long as you have at least 1 captured sector next to it. You unlock named sectors by beating other named sectors and/or (depending on the sector) unlocking certain tech; check the tech tree to figure those out.

You could also have meant that you don't know what the sector you're launching to is like, and that's intentional; you can launch a lone shard core to a sector to scout it out, and it will tell you the available resources in the sector.

**Comment by IIINSTINCT** [comment]
This is a thing before on beta v6 stages and it was changed 

Meaning this will not happen again

Reason:its OP

**Comment by SwitchLikesMlog** [comment]
> You can currently launch to any unlocked sector from any captured sector. When you launch, you take the resources for launching from the sector you launch from.

thats not really true
for example, i want to launch to sector 47 (which is right next to the shoreline) from tar feilds, but the game forces me to launch from shoreline instead

i dont know if there is a way to launch from tar feilds instead of shoreline.

**Comment by SwitchLikesMlog** [comment]
> This is a thing before on beta v6 stages and it was changed

Meaning this will not happen again

Reason:its OP

in that case, im just gonna close the issue because its useless
