### ISSUE TITLE
Ground unit pathfinding

### ISSUE THREAD

**Issue by myutin** [Anuken/Mindustry-Suggestions#3228]
### Describe the content or mechanics you are proposing.

I haven't looked at the code, but here's what I understand of the current algorithm for ground units under the "attack" command (or wave-spawned ground units):
- find the shortest route to an enemy core (e.g. by A-star),
  - slowing tiles (e.g. water) count for extra distance, as does the health of any building with collisions (e.g. walls),
- look for enemy units/buildings in range, and attack the nearest one (with priority for enemies that can attack back),
- recalculate for all units at the same time, every 40 ticks.

I suggest the following improvement to their intelligence:
- find the least damaging route to an enemy core, and find the fastest route of equally-damaging options. (Since it's not possible for A-star to optimize two route costs at the same time, instead have the travel time be added on to the damage value, multiplied by a small coefficient),
  - turrets get a DPS value if they have ammo/power (the DPS is augmented by coolant/overdrive), and a route that spends time in range of a turret accumulates damage cost,
  - enemy units might also get a DPS value (although it would be hard to calculate the time spent in range),
  - slowing tiles cost more time to traverse, and the a building with collisions costs time to destroy,
  - the unit in question knows its own DPS, and calculates how long it would take to destroy a building with some health,
- look for enemy units/buildings in range, and attack the nearest one (with priority first for buildings blocking the route, then for damage sources, then any other targets)
- have a group of the same unit share the calculation, to save time (e.g. one unit is the leader, and the rest follow, and their DPS is combined)
- recalculate any time a building with collisions is created/destroyed, capped at once every 40 ticks

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

The current mechanic encourages a defense strategy wherein the you wall off all chokepoints around the drop zone, but choose just one to defend with turrets (or units), and "fortify" the rest with extra walls. It also allows for certain cheeses, e.g., you put a gap at the end of your line of walls to make the enemy walk down the whole length. This results in an underwhelming PvE defense experience, wherein you win only by taking advantage of the enemy's stupidity.

The new mechanic would force you to look for and address weak points in your defense, making for more engaging gameplay.

It would also change the balance of the game. If you're forced to properly fortify all parallel chokepoints, which would increase the resource cost and build time for defenses, with knock-on effects reducing the resources and time available for the economy. Generally, it makes the game harder, and forces you to properly manage your resources in this resource-management game. Other mechanics could address the balance problem, but this one has the benefit of allowing another option for balance through map design.

This mechanic would encourage a mobile defense of allied units. Currently, this strategy is unviable --- it's expensive, takes a while to set up (unless you have a core schematic with unloaders in the late game), and is susceptible to enemies with AOE attacks (unless you have units with shielding), but with nerfs to static defense, it might become more useful in campaign. An example of this is already present in Windswept Islands, where deep water prevents you from walling off all chokepoints.

This mechanic would not make Desolate Rift any harder: there's still only one chokepoint to defend, there's still infinite power for free, and you still have an overwhelming tech advantage over your enemies, but that's a separate issue. This mechanic would also make logic-less units almost viable in PvP, but logic will always have the advantage.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Darkness6030** [comment]
It would also be a good idea to add the ability to add/remove blocks that the unit will not step on (or vice versa, on which it **should** step)

**Comment by Anuken** [comment]
> It also allows for certain cheeses, e.g., you put a gap at the end of your line of walls to make the enemy walk down the whole length. This results in an underwhelming PvE defense experience, wherein you win only by taking advantage of the enemy's stupidity.

That is not "cheesing", it is how tower defense *works*. You win by out-DPSing the enemy; it is **not** about making sure every single path to your base is well-defended.

> I suggest the following improvement to their intelligence:

This would take a complete rewrite of the pathfinding system and **orders of magnitude** of increased complexity. I do not use A*, and taking into account this *absurd amount of information* when routing units will take months of work to get working properly, which is to say nothing of the performance implications of such a system. It has taken literal *years* to iron out (most) of the bugs in the current pathfinder - I would be throwing that away for something much less stable.

Even disregarding all technical issues, *this is not a good mechanic*. 

What you (and others making the same suggestion) do not realize is that *units bypassing your defenses is an incredibly frustrating experience*, especially for newer players. If I am a relatively inexperienced player fortifying a certain path, I do *not* expect units to avoid every route I place turrets at. There's nothing *fun* about units walking around your turrets and blowing up your base repeatedly. With the current mechanics, it's fairly easy to figure out *why* an enemy path changes - simply don't block off the entire path. **Mindustry does not need a steeper learning curve.**

> making for more engaging gameplay.

I don't find this engaging; it would be more like *"spam turrets everywhere because it's not humanly possible to know which route they will take"*. If you really want a challenging game against someone with a brain, play PvP instead.

> It would also change the balance of the game.

This is not a good thing. All PvE maps - *not just campaign maps* -  with multiple paths would have to be re-designed for this mechanic.
