### ISSUE TITLE
allies and search bar

### ISSUE THREAD

**Issue by memepeoples** [Anuken/Mindustry-Suggestions#3242]
### Describe the content or mechanics you are proposing.

First idea: setting two teams as allies so they wont attack each other.

Second idea: taking the search bar from when choosing a map to edit and adding to choosing a map to play.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

First idea: Have two bases near each other without them attacking each so that you can have multiple enemies to fight and so that you can give the player team an ally that spawns units that wont get destroyed by griefs or turned in to a t5 factory 5 seconds after we start making surge.

Second idea: just a quality of life feature for people with lots of maps.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Why aren't these suggestions in separate suggestions issues in the first place?

**Comment by memepeoples** [comment]
couldn't be bothered to

**Comment by OnyxFinger** [comment]
Both have been suggested plenty of times, though I will need an explanation as to **why are allied teams not a thing when most of the people that give their opinion want it**

**Comment by itcannotbe** [comment]
> Both have been suggested plenty of times, though I will need an explanation as to **why are allied teams not a thing when most of the people that give their opinion want it ?**

Probably needs a lot of work to e done to properly make it a reality.
Plus the issue on how would the AI work.

Again, mindustry isn't the game where what most people want, will get for obvious reasons (like balance concerns or op suggestions)
and for the not so obvious reasons like, takes too much time to do.

**Comment by Anuken** [comment]
> why are allied teams not a thing when most of the people that give their opinion want it ?

Because:

1. "some people want it" is never a good enough reason to do anything on its own, most people aren't game designers and don't even know *what* they want, let alone the consequences of a certain feature - just look at the amount of people wanting gate chaining back
2. it's very difficult to implement (I can no longer just write team != otherTeam to determine enemies, and this is done in hundreds of places)
3. it will be very *performance*-degrading (for the reasons above)
4. it will be very buggy, due to the massive amount of changes required and edge cases needed
5. it's mostly pointless, just play on the same team instead
6. it's ambiguous as a concept (should power networks connect to each other? should they *auto*-connect? should connections should be possible at all? what about items? resupplying? inventory access? should you be able to deconstruct their stuff? you may have answers to some of these questions, but they are nowhere near obvious or intuitive)
7. it's fundamentally flawed - griefing is already bad when someone is on your team, but when someone else is an "ally", you can't deconstruct their crap or kick them

**Comment by OnyxFinger** [comment]
> it's mostly pointless, just play on the same team instead

No ? Playing on the same team means that a player can block the whole team early on, by consuming ressources in order to make pointless stuff. If the said player does that in another team, he won't softblock everyone else.

> it's ambiguous as a concept (should power networks connect to each other? should they auto-connect? should connections should be possible at all? what about items? resupplying? inventory access? should you be able to deconstruct their stuff? you may have answers to some of these questions, but they are nowhere near obvious or intuitive)

It is not. You are making it ambiguous by thinking that it should be close to the current team system.

> it's fundamentally flawed - griefing is already bad when someone is on your team, but when someone else is an "ally", you can't deconstruct their crap or kick them

This depends. Just like with bad teamates, you can't do anything about it, but you do not risk getting softblocked entirely.

**Comment by Anuken** [comment]
> No ? Playing on the same team means that a player can block the whole team early on, by consuming ressources in order to make pointless stuff. If the said player does that in another team, he won't softblock everyone else.

Allies can do the same with space or ores. They don't make the issue disappear.

> It is not. You are making it ambiguous.

Once again: **"you may have answers to some of these questions, but they are nowhere near obvious or intuitive".** There's a very real irony in you arguing with me that a definition of a mechanic is *not* ambiguous. **I** would expect allies to be able to share power or resources in some way, and so would others.

> This depends. Just like with bad teamates, you can't do anything about it, but you do not risk getting softblocked entirely.

You cannot get "softblocked entirely", as votekick and/or admins exist. 

Even if they don't, you also need to consider that, unless teams consist of **exactly** one person each in **all situations**, *there is always a possibility of you having a griefer on your team*. You're not magically making these people disappear by splitting them up into groups. If there's any sort of team switching - and people *will* want team switching - the griefer can simply hop between teams and wreak havoc as they wish.

The only way to completely eradicate griefing (without direct supervision) would be to place each player on a separate plot of land that only *they* can control, with no access to other people's land, items or resources - and *that* can be accomplished with server plugins, you don't need some elaborate new ally mechanics for it.

> If having allied teams can have bad consequences, why not make it possible to disable it as most suggestions suggested ?

How could allies *not* be an optional mechanic, and how does having it be optional address points 3-5? (*It doesn't.*)

> The community wants this gamerule due to an issue

Issues have multiple solutions; this is not an acceptable one. In any case, allies, *as a concept*, fail to address this issue.

> the difficulty and time to make it work is the only problem with it

No.
