### ISSUE TITLE
Custom colours for everything

### ISSUE THREAD

**Issue by darthmatt69** [Anuken/Mindustry-Suggestions#3296]
### Describe the content or mechanics you are proposing.

So basically I think I would be good idea to add custom colours. When you build something you can just change its colour by adding some other material. Example: I want blue towers so when I am building it I will need more Titanium and so on. I would work on troops too.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Well I think that most people like me don't like colours of some things. Everybody have different taste in colours so I think this would be good idea. We could have more customisation options.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
colors are already used by many buildings to indicate team, so this probably isn't happening

**Comment by Ymabert** [comment]
Skin?

**Comment by IxGamerXL** [comment]
This could work with Conveyor Belts and other usually non-team colored blocks. I support it for that case, since it makes organizing assembly belts much more cleaner and much more refurbished, and this could probably also work on team-colored blocks and units _(if there's a way to make sure that coloring it doesn't camouflage it)_.

Blocks that are colored can have a color change inside the map, but only if you are in the same team as those blocks, and this applies to units as well.

You could apply units with color if you use the respective payload block, and you can apply color to blocks through a paintbrush button that allows you to color a block to one of the existing items' colors _(requires 1 of the material you're painting with, taken from the core's inventory)_, or a complete RGB-255 color picker if you have Sandbox mode enabled, or if you build a Paint Mixer and get a Paintbucket from it and have it in your unit's inventory _(Each bucket can paint up to 100 blocks with the color you chose, and the bucket can be recycled for refilling with paint)_. If you place a paintbucket into a payload painter block, it'll use that paintbucket instead of a item color, and color up to 9 payloads per bucket.

Hopefully you can revise your review with this retake.
@oinkymoo

**Comment by NrkSed** [comment]
The Idea in itself isn't really bad, but I dont think it should require materials

**Comment by itcannotbe** [comment]
You do realize that most colors are made on the the sprite right? And you want 16.7 million colors available?

**Comment by the-red-soul** [comment]
dont texturepacks exist?

**Comment by IxGamerXL** [comment]
> You do realize that most colors are made on the the sprite right? 
> 
> > complete RGB-255 color picker
> 
> And you want 16.7 million colors available?

Can't units and blocks get colored over with a slight white overlay? Sprites can optionally have their own custom overlay.

Also, I think in Sandbox, Survival, and Attack, if it's just an overlay texture above the sprite, there's likely no backlash in terms of adding an Alpha setting when painting or mixing paint, which would determine how full the color is.
