### ISSUE TITLE
Nearby Nodes auto connect to nearby buildings if the Node connected to those buildings get destroyed.

### ISSUE THREAD

**Issue by DARK0717** [Anuken/Mindustry-Suggestions#3305]
### Describe what you would like changed, and why.

When a node gets destroyed, currently all turrets/buildings are gonna be unpowered. I propose that nodes be updated so that nearby nodes to the one previously destroyed will auto connect to those the destroyed one was connected to.

### Describe the changes you want to propose. Include possible alternatives.

Nearby Nodes auto connect to nearby buildings if the Node connected to those buildings get destroyed.
Alternatives: None

**Comment by LeoSko** [comment]
There are far too many configurations when it simply won't work, how are you supposed to approach this?

**Comment by itcannotbe** [comment]
Smells like #3104

**Comment by Ymabert** [comment]
yes, it basically suggests the same thing I asked, probably it's a problem that can be solved by putting in the program that every time a beam is disconnected not manually by the player the node starts the reconnection part, like when you place it again. ... I have no other ideas to improve this idea ... sometimes it is a problem to have the necessary energy to make something work and to have the right number of nodes and therefore a number of rays to be able to cover everything, but not to be able to do get energy everywhere.

**Comment by itcannotbe** [comment]
And magically all the points discussed don't apply to this because magic?

**Comment by Ymabert** [comment]
as another solution a "node with radius" could be implemented, therefore a node that does not connect to the various blocks to make them work but simply if this node receives energy and has electronic blocks within its radius, it powers them.

**Comment by Ymabert** [comment]
it wouldn't be magic, otherwise you would have to say the same when you place a node for the first time, because it connects automatically ...

**Comment by itcannotbe** [comment]
> as another solution a "node with radius" could be implemented, therefore a node that does not connect to the various blocks to make them work but simply if this node receives energy and has electronic blocks within its radius, it powers them.

That's not even a solution.

For that to work, the game would have to check every node's radius and reconnect them is it become disconnected. Also the game cannot tell if a human disconnected it vs an attacker force your node to become disconnected.

**Comment by itcannotbe** [comment]
![Screenshot_20220113_015110](https://user-images.githubusercontent.com/45280919/149194788-92ac914b-dcd1-4745-86b7-4b52c97d8336.jpg)

**Comment by Ymabert** [comment]
I read the reasons why it made no sense to add this, but now I think I have given new reasons, more sensible and achievable.

**Comment by Cleanup-Crew-From-Discord** [comment]
> as another solution a "node with radius" could be implemented, therefore a node that does not connect to the various blocks to make them work but simply if this node receives energy and has electronic blocks within its radius, it powers them.

that removes the point of having node link limit. Powering an area with nodes makes them too powerful in many compact designs, where nodes take up otherwise vital spots due to how many you need

**Comment by Ymabert** [comment]
For me its a good suggestion

**Comment by DARK0717** [comment]
"if your defenses start failing, theres nothing a reconnect node can help stop that". Failing defenses arent all the same. Defenses also fall because of just one node getting destroyed by some stray air unit, meanwhile there are nodes nearby, well within range to connect to turrets, wouldnt it be great if those nearby nodes auto connect to those dozens of turrets who lost connection from that one node.

**Comment by itcannotbe** [comment]
> "if your defenses start failing, theres nothing a reconnect node can help stop that". Failing defenses arent all the same. Defenses also fall because of just one node getting destroyed by some stray air unit, meanwhile there are nodes nearby, well within range to connect to turrets, wouldnt it be great if those nearby nodes auto connect to those dozens of turrets who lost connection from that one node.

I wonder what front line defense blocks need power.....

Menders, Mend Projectors. If those go out then your defenses will fall in some form or fashion.

As for turrets, well aside from the foreshadow, most turrets that use power only targets ground based enemies. If somehow your power nodes gets destroyed beforehand it's rarely because of ground units.

And lastly, I'm not stupid enough to just rely on one node to connect to my defense wall.

Also just get better with you defense wall design so that you prevent people from guiding their flying units bypassing your defenses.

**Comment by Ymabert** [comment]
because many talk as if getting around a problem wasn't a problem, ok ... sometimes it's okay to get around a problem because it's just part of the game, but many other times, especially for a matter of fairness certain things should be fixed, like in this one case the nodes that connect automatically in a random way (if possible obviously) when something to which they are connected is destroyed.  The problem would be that if it is rebuilt by the Poly, for example, that block would no longer receive energy, this would change the constitution of your strategy, however badly, so this would be a problem, the node would then have to register the blocks connected manually, it shouldn't auto connect then when the player goes to disconnect the node manually.  These are the problems of applying this suggestion, but if they are solved it would make sense and it would be right to implement it in the game (it is a problem that generates problems, but solving everything would greatly improve some defensive strategies, then the fact that the nodes do not connect to two energy blocks that are already part of the same energy system says it all about how advanced the program is already, so I hope to ask for something achievable).
