### ISSUE TITLE
Menders/Mend Projecters Unable to Repair Things when taking fire

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry-Suggestions#331]
**Describe what you would like changed, and why.**
Right now menders arent repair blocks they are literal combat medics. We should really change this since its so OP that you can just spam walls and menders. Menders should do their current ability only after 2.5 seconds of not taking fire (2 seconds for mend projecter and 1.5 seconds for phase-boosted mend projecters)

**Describe the changes you want to propose. Include possible alternatives.**

Maybe we could nerf things like how much energy they take or how much they heal. Or maybe they cant stack on eachother too much. This could be some good alternatives

**Comment by RoyalFunnyDude** [comment]
But...if you are spamming walls + menders, the menders would be at the back...so this would be useless unless it's ripples/hail/meltdown, in which case it would also be useless because ripples can take down the menders.

**Comment by Phantasm0915** [comment]
Yes it's Overpowered, but nerfing it this way will make it useless, the main purpose of the Mender is to make something last longer in a wave, making it unable to repair something that is being damaged won't affect much in the early game, since enemies rarely destroy or severely damage walls, but what if in the late game? As waves last longer and has more units, giving walls no time to repair at all? It literally eliminates the Mender's use of Lengthening survivability in later waves, as Enemies appear more than often in 50 enemies per wave, nerfing the mender will allow them to push through a defensive line in seconds

**Comment by MapleWheels** [comment]
The problem really is that they effectively increase max HP by constantly healing (thereby adding extra effective HP). The reason this is a problem is that they've effectively stopped Shield Projectors from being viable by replacing their primary function. Also, Mend Projectors are usually protected so the out of combat healing function won't work as they were never taking damage to begin with. This also wouldn't be good because when your Mend Projectors are taking damage that means that your wall is breached, which is when you need them the most and a nerf here would mean a single breach would be unrecoverable.

The problem here is a fundamental game flow issue, once you get to mid-late game, it becomes a constant fight so anti-burst items, such as Shield Projectors (even if buffed?), are not useful as there is no window for recovery. This makes Mend Projectors king, as there's no down time.

Mend Projectors also have a much higher tile efficiency than Shield Projectors (4 tiles vs 9 tiles). If you want to nerf Mend Projectors, **_you need to first_** change the game flow to _make anti-burst a viable game mechanic_, and then, nerf Mend Projectors to make them a _secondary mechanics after the anti-burst mechanic has done it's job_. 

The issue here has come down to people realizing that phase-overdriven Mend Projectors are the only thing viable late game and that Shield Projectors' health pools are not high enough as opposed to just putting another layer and a half (3 tiles) of wall.
