### ISSUE TITLE
Mend Dome

### ISSUE THREAD

**Issue by Salty-Potato133** [Anuken/Mindustry-Suggestions#3314]
### Describe the content or mechanics you are proposing.

A version of the Mend Projector that is a 3x3 block. It looks and behaves similar to the overdrive dome in that it:

- Require phase fabric and silicon to operate
- More range than a mend projector with phase fabric
- Repairs faster than the mend projector with phase fabric
- More expensive to build than a mend projector
- Costs more power to operate then a mend projector
- Has more health than a mend projector
- Unlocks in campaign when you unlock the overdrive dome

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think the game needs a Mend Dome because it would make having a larger base that you want to be on full health easier to designed and more power efficient. It would also be a good alternative to spamming down mend projectors to repair something quicker, and it would also be nice to have a late-game mender.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by myutin** [comment]
In combination with #3240 , this could extend the progression of heal quality into late game

**Comment by itcannotbe** [comment]
So how sure are you that this block won't be spammed the same?

> In combination with #3240 , this could extend the progression of heal quality into late game

Maybe not this suggestion, sound too an easy to use late game block

**Comment by myutin** [comment]
I agree. With the game as it is, the mend dome would be very easy to spam. With a healing rework, it might instead be a positive addition to the game.

**Comment by itcannotbe** [comment]
> ### Describe the content or mechanics you are proposing.
> 
> A version of the Mend Projector that is a 3x3 block. It looks and behaves similar to the overdrive dome in that it:
> 
>     * Require phase fabric and silicon to operate
> 
>     * Has the same range as an overdrive dome
> 
>     * Repairs faster than the mend projector with phase fabric
> 
>     * More expensive to build than a mend projector
> 
>     * Costs more power to operate then a mend projector
> 
>     * Has more health than a mend projector
> 
>     * Unlocks in campaign when you unlock the overdrive dome
> 
> 
> ### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.
> 
> I think the game needs a Mend Dome because it would make having a larger base that you want to be on full health easier to designed and more power efficient. It would also be a good alternative to spamming down mend projectors to repair something quicker, and it would also be nice to have a late-game mender.

You never mentioned "healing rework" in your suggestion.

Also "healing rework" is still just a suggestion also which no means will guarantee that it will be implemented.

**Comment by myutin** [comment]
I brought up the healing rework discussion, because i thought it was relevant to this suggestion. You won't find any reference to it in the original suggestion. 

If it's bad practice to reference other discussions when encouraging a suggestion, i will refrain from doing so in the future.

**Comment by itcannotbe** [comment]
Not exactly, I just pointed out to OP that his original suggestion didn't even consider it.

But still a higher tier healer block would be a good addition, if the "healing rework" did get implemented.

**Comment by Salty-Potato133** [comment]
This would be more difficult to spam than other menders because it requires phase and silicon like an overdrive, it also costs more resources and power, but I do agree spamming down menders needs to be nerfed

**Comment by OnyxFinger** [comment]
I am pretty much sure that more late game menders are unnecessary, however there can be a case of use where it is better over the normal mend projector without breaking the game (kinda like using monos when there aren't enough ore patches. If you are part of the extreme majority that turned off its brain and decided that monos>using drills, you're definitely wrong drill based economy can be placed much faster and this is better only use monos if drills are too hard to get (because of the amount of ores, or how scattered and annoying to grab they are).).

Anyway, what I mean is  that there can be a win-win deal with mend projectors being more useful in some situations and mend domes being better in some others. For example, I think that maybe it would be more efficient but take more space, so that it's not as good as mend projectors. This would (I think) make them better in small chokes (because there is no space to stack the smaller ones). In the current state of the game, menders (normal 1×1 menders) are actually better than mend projectors in very tight chokes, but :
         ⋅This doesn't come into use because the choke has to be too small
         ⋅Menders as an early game healer are fine as they are, and them having this "potential" (not quite useful) is weird, especially while it could fit in this case.

**Comment by OnyxFinger** [comment]
![Capture d’écran de 2022-01-14 17-54-30](https://user-images.githubusercontent.com/68511236/149554112-6e54cebe-ea88-45bc-83ad-2c0889899cdf.png)

Do not mind the laziness, I could've added more lines but it was unnecessary effort
With something like this, there can be a lot of menders in a line. With phase, nearly all of them can heal most of the walls.
This is due to their range (insanely high). If the mend dome is more efficient, but has less range, then on big surfaces like this, it wouldn't go well, because you can stack quite as much healing in the same place.

![Capture d’écran de 2022-01-14 17-58-47](https://user-images.githubusercontent.com/68511236/149554740-7fdaf292-e225-48e1-bf8a-0d31b4579c07.png)

If the choke becomes smaller, then you can't "abuse" the range of mend projectors, because there is no space for it, and thus the mend dome is better, because ;
                      ⋅ Even though you can't stack it's healing quite as much, stacking insane amounts of healing isn't a thing anymore
                      ⋅ It has more powerful healing per tile, so it is, of course, better.

**Comment by Salty-Potato133** [comment]
My concept of a mend dome is supposed to have more range AND effectiveness than a mend projector at the cost of it requires more power, phase and silicon to operate, and more materials to build. It is supposed to be a much more late-game mender than the projector.

**Comment by OnyxFinger** [comment]
>  My concept of a mend dome is supposed to have more range AND effectiveness than a mend projector at the cost of it requires more power, phase and silicon to operate, and more materials to build. It is supposed to be a much more late-game mender than the projector.

Yes but this wouldn't work, because it's not necessary. If my idea doesn't make any sense, then just swap mend proj and mend dome in my idea.

**Comment by Salty-Potato133** [comment]
Your idea could work too. All I was really proposing was a late game mender.

**Comment by Ander292** [comment]
You all know how override and menders work. Now, imagine override effect stacks like mending effect stack. If it was like that, nobody would use domes, when you can just spam smaller overrides. Now, imagine mending effect isn't stacked, or is limited to a certain amount of stacking. In this case, mending dome would be necessary.

**Comment by rawsewage38** [comment]
> You all know how override and mending work. Now, imagine override effect stacks like mending effect stack. If it was like that, nobody would use domes, when you can just spam smaller overrides. Now, imagine mending effect isn't stacked, or is limited to a certain amount of stacking. In this case, mending dome would be necessary.
I think the Mending Dome should be a support block that has extremely long range, but low healing power, instead going for more general area effectiveness than intensity. Kind of like how the Surge Tower has long range but only can join two buildings.
