### ISSUE TITLE
core schematics get broken by terrain (not sure if its really balance)

### ISSUE THREAD

**Issue by goodsofa** [Anuken/Mindustry-Suggestions#3319]
### Describe what you would like changed, and why.

the core schematic sometimes just gets broken by the terrain which leads to wasting of the material 

### Describe the changes you want to propose. Include possible alternatives.

i would propose to add a warning that the current core schematic is overlapping with the terrain and propose an option to rotate it (in some situations this could help) or to add a preview of the bit of the map where the core is (basically just show if there's a mountain in the way)

**Comment by SwitchLikesMlog** [comment]
finally someone addressed this problem

**Comment by itcannotbe** [comment]
> finally someone addressed this problem

See #1839

**Comment by itcannotbe** [comment]
> ### Describe what you would like changed, and why.
> 
> the core schematic sometimes just gets broken by the terrain which leads to wasting of the material
> ### Describe the changes you want to propose. Include possible alternatives.
> 
> i would propose to add a warning that the current core schematic is overlapping with the terrain and propose an option to rotate it (in some situations this could help) or to add a preview of the bit of the map where the core is (basically just show if there's a mountain in the way)

Sectors aren't even generated before you start playing most sectors (the only exceptions are named sectors).

**Comment by myutin** [comment]
Based on the discussions in 1839 and 2145, most of the proposed solutions involved either
- changing procedural generation to make sure there's space for the core
- or giving the player the ability to choose how their schematic is placed

I agree that both of these are noble goals: if the game's core schem limit is 15x15, it's a bruh moment when there's no space for it, and if your core schematic produces units, it's annoying if they're stuck between blocks and terrain. However, in the previous discussions, we concluded that both options are fundamentally flawed.
(another possible solution is that it refunds the materials for failed blocks, but that could still end up wasting materials in a full core, and it also fails to save the player construction time - which is the point of a core schem)

A middle ground between the two options, is that the game places your core for you, after the sector is generated, but before gameplay starts. This doesn't introduce any ugly shapes into terrain, doesn't give the player any cheese, and solves the main issue at hand.

The game would search for locations near the default core placement, until it finds one that can fit the schematic. Better yet, it finds a location that can fit a 15x15, regardless of the schematic's actual size; the player doesn't get any more by adding a ring of walls to their small schem. Once it finds this location, it centers the schem on the center of the 15x15, and places copper under the drills as needed.
(this could even search for a 17x17, if we want to give the player room to bring resources into their shem)

One way to choose a suitable location would be a greedy search, prioritized by how few blocks of terrain intersect the 15x15, and run with a pqueue instead of a stack (to prefer locations close to the default placement). In most procedural sectors, this should find a location after searching through twenty candidates or fewer.

**Comment by AMindustryPlayer** [comment]
> Based on the discussions in 1839 and 2145, most of the proposed solutions involved either
> 
> * changing procedural generation to make sure there's space for the core
> * or giving the player the ability to choose how their schematic is placed
> 
> I agree that both of these are noble goals: if the game's core schem limit is 15x15, it's a bruh moment when there's no space for it, and if your core schematic produces units, it's annoying if they're stuck between blocks and terrain. However, in the previous discussions, we concluded that both options are fundamentally flawed. (another possible solution is that it refunds the materials for failed blocks, but that could still end up wasting materials in a full core, and it also fails to save the player construction time - which is the point of a core schem)
> 
> A middle ground between the two options, is that the game places your core for you, after the sector is generated, but before gameplay starts. This doesn't introduce any ugly shapes into terrain, doesn't give the player any cheese, and solves the main issue at hand.
> 
> The game would search for locations near the default core placement, until it finds one that can fit the schematic. Better yet, it finds a location that can fit a 15x15, regardless of the schematic's actual size; the player doesn't get any more by adding a ring of walls to their small schem. Once it finds this location, it centers the schem on the center of the 15x15, and places copper under the drills as needed. (this could even search for a 17x17, if we want to give the player room to bring resources into their shem)
> 
> One way to choose a suitable location would be a greedy search, prioritized by how few blocks of terrain intersect the 15x15, and run with a pqueue instead of a stack (to prefer locations close to the default placement). In most procedural sectors, this should find a location after searching through twenty candidates or fewer.

Actually, the game could simply remove the terrains that blocks the placement. However, the game should limit the size and the type of the schematics to be launched so that we can reduce the exploit

**Comment by itcannotbe** [comment]
> > Based on the discussions in 1839 and 2145, most of the proposed solutions involved either
> > 
> > * **changing procedural generation to make sure there's space for the core**
> > * or giving the player the ability to choose how their schematic is placed
> 
> Actually, the game could simply remove the terrains that blocks the placement. However, the game should limit the size and the type of the schematics to be launched so that we can reduce the exploit

Actually you don't have to point out something that has already been pointed out.

**Comment by AMindustryPlayer** [comment]
> > Based on the discussions in 1839 and 2145, most of the proposed solutions involved either
> > 
> > * changing procedural generation to make sure there's space for the core
> > * or giving the player the ability to choose how their schematic is placed
> > 
> > I agree that both of these are noble goals: if the game's core schem limit is 15x15, it's a bruh moment when there's no space for it, and if your core schematic produces units, it's annoying if they're stuck between blocks and terrain. However, in the previous discussions, we concluded that both options are fundamentally flawed. (another possible solution is that it refunds the materials for failed blocks, but that could still end up wasting materials in a full core, and it also fails to save the player construction time - which is the point of a core schem)
> > A middle ground between the two options, is that the game places your core for you, after the sector is generated, but before gameplay starts. This doesn't introduce any ugly shapes into terrain, doesn't give the player any cheese, and solves the main issue at hand.
> > The game would search for locations near the default core placement, until it finds one that can fit the schematic. Better yet, it finds a location that can fit a 15x15, regardless of the schematic's actual size; the player doesn't get any more by adding a ring of walls to their small schem. Once it finds this location, it centers the schem on the center of the 15x15, and places copper under the drills as needed. (this could even search for a 17x17, if we want to give the player room to bring resources into their shem)
> > One way to choose a suitable location would be a greedy search, prioritized by how few blocks of terrain intersect the 15x15, and run with a pqueue instead of a stack (to prefer locations close to the default placement). In most procedural sectors, this should find a location after searching through twenty candidates or fewer.
> 
> Actually, the game could simply remove the terrains that blocks the placement. However, the game should limit the size and the type of the schematics to be launched so that we can reduce the exploit

Another alternative way is make the game 'pre-load' the maps of the sectors so the game can warn the players that their core schematics may not be complete if the terrain blocks the placement

**Comment by itcannotbe** [comment]
> Another alternative way is make the game 'pre-load' the maps of the sectors so the game can warn the players that their core schematics may not be complete if the terrain blocks the placement

You can't preload something that isn't generated yet.

**Comment by AMindustryPlayer** [comment]
> > Another alternative way is make the game 'pre-load' the maps of the sectors so the game can warn the players that their core schematics may not be complete if the terrain blocks the placement
> 
> You can't preload something that isn't generated yet. Since there is nothing yet to load-in in the first place.

pre-load = generate a map automatically first, you misunderstood it.
