### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by LeCoqBeau** [Anuken/Mindustry-Suggestions#334]
**Describe what you would like changed, and why.**
Add an button Quit & Save in the editor interface because it piss me of when I quit without saving and loosing all my progress in my maps.

**Describe the changes you want to propose. Include possible alternatives.**
It'll add an Quit & Save button or maybe add an option to add an autosave with different timer : 30 seconds, 1 minutes, 5 minutes...

**Comment by TranquillyUnpleasant** [comment]
While the quit and save button is useful, auto saves would make it impossible to revert major changes in a map that the map maker is just trying to test.

But yes just adding save and quit as an option would be very useful specially because the unsaved edits warning does not track in game changes. Either that or making the warning happen every single time someone pressed the quit button, regardless of changes.
