### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by jonnyboi365** [Anuken/Mindustry-Suggestions#3340]
### Describe the content or mechanics you are proposing.

Basically menders when placed next to the enemy block and is powered it deals damage to it. With the repair point and the repair turret  when an enemy unit goes into its radius it damages it.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

I think that this will give better use to the repair turret and repair point and the mender one would be cool to. Also you could make it do half as much damage as it does healing.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by SwitchLikesMlog** [comment]
why? Menders and Repair Points are alreadly incredibly useful, no need to make them even more powerful

im pretty sure the Repair Points/Turrets are gonna become unbalanced-ly OP

while Menders are gonna be very weak against enemy buildings

**Comment by oinkymoo** [comment]
if anything, the opposite should be true, especially for menders. menders aren't smart enough to distinguish buildings, walls, and open air, instead firing off a wave of healing in all directions. i see no reason why that healing wave would not have the same effect on enemy buildings. as for repair points, healing and damaging are 2 entirely unrelated functions. the healing should work the same on identical units, though they seem to actually have some brains behind them with which to locate and repair nearby units so they might not do anything

**Comment by Cleanup-Crew-From-Discord** [comment]
...why????

from a logic standpoint, how the hell would turrets and blocks designed solely for healing be able to inflict damage

and from a game standpoint, to use menders offensively you would have to somehow build them close enough to an enemy building without getting shot up. If you did, phase 2x2 menders could just shred anything. it is simultaneously OP and useless

**Comment by SuperThunder958** [comment]
Now the repair point the way you described it it sounds so pee it sounds overpowered but the mender he could stay in a chance I mean you really happen to risk yourself to put it up to like a high-powered high-powered powered and save its able to damage like the conveys that that will be the only good useful things but I can I can see the the mentors damaging other structures to have a good opinion but if he's called a mentor mender which amender is made to fix stuff not demolish so when we have to make a whole new block called a demolisher which slowly deals high damage and I say slowly as in every 10 seconds it does like 250 damage I mean that's 10 seconds to spare that means be a tear a thing 5 or 6 units just laying out balms in the garage bullets on a damaging it I mean we can put the health on the block for like a hundred and 120 and make it we cannot be minted by minute and if you put them by a mentor they will both blow up so that way it's a so that way we have an overpowered block that can not be healed but has a long delay like 10 seconds or 20 seconds and can I be over can I be overdriven by overdrivedone dome
