### ISSUE TITLE
Frontal shields

### ISSUE THREAD

**Issue by Mcmiko05** [Anuken/Mindustry-Suggestions#3349]
### Describe the content or mechanics you are proposing.

Idea comes from the new unit coming in V7. The frontal shield would be a stronger version of the normal shield, but it can only block shots from a single direction. It can be rotated to face any of the 4 directions. The shield would be projected about 8 tiles into the chosen direction and stretch 8 tiles more into said direction. Phase fabric would not change the projection distance but it would make the shield much wider. Cooling could boost the shield just like the normal one. Additionally in end-game surge alloy could boost shield health greatly. The last idea is a possible addition but in no way required. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

There has always been a feeling that the shield projectors have been a bit underpowered. The idea is that the normal shields would work whilst fighting air units. The frontal shield would be used for fighting against ground units and the increased shield health would help there. Additionally the possible surge alloy boost would give high-tier players a new way to boost their shields. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Shield protect against air, not ground.

**Comment by OnyxFinger** [comment]
Force projectors are fine as they are. Since they aren't very healthy but block AOE damage entirely, there is a kind of balance, as you want to use it wisely, in the right spot that covers the most blocks inside of your defenses, but while it can't get hit by direct fire. 

It makes the force projector not that weak, just slightly underpowered compared to players' vision of its necessary strength in the current way things are balanced (basically, it is somewhat situational, while many players think that it should almost be a substitute/direct support to walls)
