### ISSUE TITLE
Background simulation

### ISSUE THREAD

**Issue by zmeyka3310** [Anuken/Mindustry-Suggestions#3369]
### Describe what you would like changed, and why.

I'd like to background wave simulation be reworked, because its hella strange. some good defenses just dont work because of they work on synergies+additional effects (like arc + water wave), but on the other hand you can spam walls and turrets mannually loading them via dropping resources to cheese the sector. (like the screenshot below
![Screenshot from 2022-02-03 11-54-03](https://user-images.githubusercontent.com/78418657/152447089-cba8795f-cc96-43b1-bada-db9813856ca8.png)
![Screenshot from 2022-02-03 11-54-17](https://user-images.githubusercontent.com/78418657/152447095-88a5e848-315a-48e0-b0e9-79744f963932.png)
)

### Describe the changes you want to propose. Include possible alternatives.

As a reworking idea, i just think about all the enemy's ai the works the right way(like when you are in the sector), or jsut load the sector (simply dont render it). i think that will be a good option because of big maps are easily loaded, and the sectors are smaller than big maps. also maybe for very slow computers can be added the option, like dont simulate other sectors in background or smt

**Comment by itcannotbe** [comment]
Not rendering visuals is going to give you the performance leeway you need to run additional sectors on mid/low end devices.

**Comment by itcannotbe** [comment]
Not rendering visuals is not going to free up system resources you need to run additional sectors on mid/low end devices.

**Comment by 50275** [comment]
from anuke, no idea which post "... and Mindustry is fundamentally incapable of running multiple instances"

**Comment by zmeyka3310** [comment]
> Not rendering visuals is not going to free up enough system resources you need to run additional sectors on mid/low end devices.

also maybe for very slow computers can be added the option, like dont simulate other sectors in background or smth
wanna read the end?

**Comment by Facosa99** [comment]
Anuke has said many times that keeping sectors loaded on the background is a no-no. 

However you right here, the current system is quite unreliable. Many times i have come back to a sector with impacts no longer working, even tho it was a non vulnerable sector with stable power production/consumption and plenty of backup batteries

**Comment by aquach** [comment]
Here's some humble suggestions for how to make this less painful:

* In the sector info, display the estimated DPS, health, and regen computed from the [sector simulation code](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/maps/SectorDamage.java). That way people at least get feedback on how strong their simulated defenses are, which might minimize "my processor-based defense built in the wrong place fell instantly!!" because they would see that their efforts are not contributing to estimated DPS, regen, or health. Seems relatively easy without requiring a rewrite or deep change in the sector simulation code.
* Display a countdown timer to next launchpad launch recomputation. That way I can see when I open a level how long I need to leave it open to get the launches to update.
