### ISSUE TITLE
Make finite resources

### ISSUE THREAD

**Issue by Tema0** [Anuken/Mindustry-Suggestions#3374]
### Describe the content or mechanics you are proposing.

Make all ores and liquids exhaustible

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

So game will be about not just kill enemy core, but more about fighting for resources, so, kill enemy eco strategy will be not just sad joke... Cuz u know, u can just spam unit miners and make infinite amount of every basic res with no ground expanding (except thor ofc)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
If the game wanted to be like factorio, then it would, but it's not

**Comment by oinkymoo** [comment]
at most, this should be an option for map creators. this would completely redefine how this game plays and would require significant reworking of the ore mechanics for it to even be an option

**Comment by LeoSko** [comment]
> significant reworking

Not at all, changes for that would be very easy. I'm already planning to implement this gamemode on ranked pvp server regardless acceptance in vanilla after v7 release.

Simply spamming units **shouldn't** ever work, lets get some brains working.

In any strategy game you do resource management to conquer new places on the map, but Mindustry lacks this option hence we get senseless PvP and even less understandable survival mode.

**Comment by LeoSko** [comment]
*Max* unit count has no connection to resource management, what do you mean with that?

**Comment by AzhurniyBaklan** [comment]
If this thing was customizable, then maybe - in the current version of the suggestion - garbage.

**Comment by EclipseTheOldOne** [comment]
you're denying how the game work

**Comment by NrkSed** [comment]
> > significant reworking
> 
> Not at all, changes for that would be very easy. I'm already planning to implement this gamemode on ranked pvp server regardless acceptance in vanilla after v7 release.

No it would require significant reworking, because then after like an hour of gameplay you will run out of resources, and have to go to EVERY sector you have and place down a new set of drills and deconstruct the old ones. And then such basic resources will run out in the sector and Anuke will have to implement code to "generate" new nodes, which makes even less sense.
In the current version of the suggestion, you would run out of resources almost lightning fast and get hardlocked by the tech tree alot

Maybe the suggestion makes the game "more realistic" (although we hundreds of years into the future), but it completely makes the game boring to play and incredibly slow to progress.

If you want to add such a feature to your server, go ahead.

>make infinite amount of every basic res with no ground expanding

Unit cap exists

>Simply spamming units shouldn't ever work, lets get some brains working.

wow going back to the same sector every 40 minutes, deconstructing and then reconstructing drills at a different node takes so much brain power omg i dont think i am smart enough for this 😱 

>In any strategy game you do resource management to conquer new places on the map

^ Irrelevant to the topic. There are different types of strategy games, and each one has its unique factors and styles of gameplay whilst having similar gists

>Max unit count has no connection to resource management

False, the more monos you have, the faster you will be getting copper.
But when you dont have enough copper even with max amount of Monos you are inclined to make better units with faster mine speed, Mindustry does not have to be like Factorio or other strategy games, its unique and that's what makes it good. Simply being like other popular games doesn't make your game any better.

**Comment by Anuken** [comment]
> u can just spam unit miners and make infinite amount of every basic res with no ground expanding (except thor ofc)

This is a real problem, but the takeaway should be "unit mining is bad and needs fixing" rather than "let's introduce an entirely new mechanic". Erekir, for one, will not have any unit miners aside from the core units (which is necessary for bootstrapping, and should have little impact on balance as player count is highly limited).

> In any strategy game you do resource management to conquer new places on the map, but Mindustry lacks this option hence we get senseless PvP and even less understandable survival mode.

Is this an inherent problem with Mindustry, or with the maps people play on? Many servers I see (*especially* big PvP ones) have giant maps with perfectly square ore patches of every resource right next to multiple cores. There's no reason to conquer territory or manage anything, because the unit cap is ridiculous and resources are never an issue.

You could probably get an experience much more conductive to "brains working" by playing on maps that have very low unit limits and small ore patches spread out across a large area, but players don't do this. (Why?)

> significant reworking

It would not require significant reworking only if implemented *by server owners* as a plugin on specially-designed maps. The implementation would look something like this:
```
onWorldLoad:
  oreDepletion = new float[width][height]

every X seconds/ticks:
  go through every building:
    if it's an active drill:
      deplete every ore it is on by some set amount, using the oreDepletion array
      if oreDepletion[x][y] >= someCap:
         remove the ore
```

However, I am not interested in implementing or maintaining such a mechanic in the base game.

**Comment by LeoSko** [comment]
> the unit cap is ridiculous and resources are never an issue

That's exactly why there are so many cases of players not caring about what and how to build - they are not forced to think. Spam schems, t1 units, resources are endless anyway - what can go wrong? *nothing*
So, they build this:
![2021-03-20 01_19_27-Mindustry](https://user-images.githubusercontent.com/4199082/152607632-c954f5a3-f770-420b-8812-543c05647e6b.png)
![2021-07-02 20_28_23-Mindustry](https://user-images.githubusercontent.com/4199082/152607731-7f7ef512-0950-4872-8523-a37fc949c5a9.png)
![2021-12-27 22_21_05-Mindustry](https://user-images.githubusercontent.com/4199082/152607746-2e256007-0935-437c-b912-d6cb958d3d5e.png)

> (Why?)

I might be too hardcore (~~or old hehe~~) for such casuality, it seems to also be the cause for players to stay in the game for longer as this somehow reduces an already steep learning curve of the game - they can play it right here, right now.

For working brains, such mode actually is hex-style pvp (generated maps) or ranked (premade maps), where players need to look around searching for resources, controlling minimap etc. And it is always played much better than simple boxed map.

BTW for "giant maps with perfectly square ore patches of every resource right next to multiple cores" you also forgot "anti-rush wall", just 1 or 2 meeting point(s) and >2:1 aspect ratio. :)

**Comment by IxGamerXL** [comment]
The mechanic of ores being depleted should be toggleable in map settings. All map settings basing around depleting resources are:

- Depletable Resources (Boolean)

- Mining Speed (Float multi)
- Depletion Penalty (Float multi)
- Depletion Duration (Int seconds)

When a ore is used up for long enough, they reach their Depleted phase (less vibrant and less opaque). During the Depleted phase, you only mine it as fast as the current **Mining Speed + Unit Speed - Depletion Penalty** (Doesn't come into consideration if the unit already has 0% Mining Speed).

Of course though, all of this is already possible with server plugins. I remember one server that depleted the water sources as you pumped them out, so we could probably include water with this set of new rules.

**Comment by NrkSed** [comment]
>So, they build this:

Ok whats wrong with the drills in the picture, you are saying placing drills down in high numbers is bad?

**Comment by williams104** [comment]
No its the placement.
Hes saying that its inefficient

**Comment by meatball-sus** [comment]
h o w  a b o u t  _**no.**_
