### ISSUE TITLE
New class of naval units

### ISSUE THREAD

**Issue by Salty-Potato133** [Anuken/Mindustry-Suggestions#3388]
### Describe the content or mechanics you are proposing.
(its a lot of reading, lower line summarizes it in one line.)
Suggestion: A new class of naval units generally for damaging close groups of enemies or bases. 

Concept naval unit class:
Could be built with coal, silicon, and metaglass. Build time could be shorter or similar to the Risso's build time
T1: 
Possible Desc: Fires charged shells at ground enemies.
- Longer range than Risso, but unable to attack air
- The shells explode into a wide radius with lighting, less damage against single targets than other naval units

T2: 
Possible Desc: Fires explosive flak missiles at all enemies. 
- Shorter range than minke
- The missiles explode into a large area with flak projectiles, with less damage against single targets than other naval units

T3:
Possible Desc: Fires close range piercing lasers at all enemies.
- Much shorter range than other naval units of its tier
- Fires Toxopid lasers (scaled to T3 damage)

T4:
Possible Desc: Fires powerful streams of liquid at all nearby enemies.
- Much shorter range than other naval units of its tier
- Fires incinerating slag at all nearby units, burning enemies and pushing them back

T5:
Possible Desc: Shoots missiles and long-range clusters of shells at enemies. 
- Slightly longer range than the Navanax
- Has multiple Ripple-like weapons that shoot clusters of large-radius explosive shells at ground units. 
- The ripples are most effective against close up targets or large targets.
- Fires missiles at all enemies with a much shorter range, to defend it against air

(Exact stats, looks, etc up to devs)

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Reasons why my concept should be added

1. The splash damage would be effective against large groups of enemies or bases, something that could be added to have more variety in ships. This would also fill a gap that was created with the spider nerfs.
2. More naval unit variety gives more naval choices in battles, creating more opportunities where naval units are a good choice. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by EclipseTheOldOne** [comment]
boat aren't meant to be boosted

**Comment by NrkSed** [comment]
>T1:
Possible Desc: Fires charged shells at ground enemies. Capable of flight.

    Can boost, meaning It can be built on land and fly to the water. However, it cannot attack while boosting
    Longer range than Risso, but unable to attack air
    The shells explode into a wide radius with lighting, less damage against single targets than other naval units

Surge shells for a T1?? So it basically becomes a moving surge cyclone.. 
Without anti air 2 horizons will be able to take this thing down though. 
So it would become basically op against ground/naval but have no resistance to air

>T2:
Possible Desc: Fires explosive flak missiles at all enemies. Capable of flight.

    Can boost, meaning It can be built on land and fly to the water. However, it cannot attack while boosting
    Shorter range than minke
    The missiles explode into a large area with flak projectiles, with less damage against single targets than other naval units

Flak isnt supposed to be mounted on a missile, but ok.

>T3:
Possible Desc: Fires close range piercing lasers at all enemies. Capable of flight.

    Can boost, meaning It can be built on land and fly to the water. However, it cannot attack while boosting
    Much shorter range than other naval units of its tier
    Fires Toxopid lasers (scaled to T3 damage)

On its own Toxopid lasers (especially when scaled to T3 damage) are pretty much useless when you are talking about naval combat, ships have way more health then that. Especially against Bryde, which specialises on being long range.Now if it did 110 damage like the Toxopid does then we might be talking then. 
Though it might be good against ground structures idk

>T4:
Possible Desc: Fires powerful streams of liquid at all nearby enemies.

    Much shorter range than other naval units of its tier
    Fires incinerating slag at all nearby units, burning enemies and pushing them back

In this case you just go away from it and fire at it. Sei would outrange it by miles and Aegis(iirc) would slow down your ship even further so it can outrange you

>T5:
Possible Desc: Shoots missiles and long-range clusters of shells at enemies.
-Slightly longer range than the Navanax
-Has multiple Ripple-like weapons that shoot clusters of large-radius explosive shells at ground units.
-The ripples are most effective against close up targets or large targets.
-Fires missiles at all enemies with a much shorter range, to defend it against air

Navanax will be 10 times better than your T5 at close range due to its lasers + it will slow down your reload to 75%
Omura.... well i think you understand why it will win against your T5.


And that ability to boost... SHIPS ARE NOT PLANES. THEY ARE NOT SUPPOSED TO FLY.

In that case you would be able to fly to the smallest pond near the enemy core and destroy it - next gen cheesing.

Dont think these ships would find their use among the others except the fact that you can cheese enemy bases

**Comment by itcannotbe** [comment]
PPTs exist, but are limited to size.

Maybe a larger PPT but for larger units only is needed.

**Comment by OnyxFinger** [comment]
There are things that I agree with and disagree with in that long message, but I don't think that mindustry should have new units yet. It doesn't make much sense since the current units don't give much gameplay difference already. The only important thing is the ground and air thing.
