### ISSUE TITLE
Ground units should not obstruct building

### ISSUE THREAD

**Issue by 64-Tesseract** [Anuken/Mindustry-Suggestions#3405]
### Describe the content or mechanics you are proposing.

Mechs should automatically move out of the way when something is being built over them, and blueprints absolutely shouldn't be cancelled when they can't be built right that moment.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Imagine you're designing a complicated factory, but before you get to a block some random mech that just spawned decides to migrate over said factory.
![M O V E](https://user-images.githubusercontent.com/63184095/154689238-e0db5a45-898e-4d9f-ad4f-5f47b0ee45e7.png)
Yes, I could build a command center away from where I want them, but it takes way too long and I still want other mechs to attack enemies while I'm building.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by NrkSed** [comment]
Could be useful..

**Comment by 50275** [comment]
Throw more junctions around your building

**Comment by 64-Tesseract** [comment]
> Throw more junctions around your building
...How would that help???

**Comment by 50275** [comment]
![image](https://user-images.githubusercontent.com/68676339/154907389-07cc26b6-bcd3-438a-add7-8748954454be.png)
I don't know about you, but this seems pretty effective to me

**Comment by stuffyAI** [comment]
> ![image](https://user-images.githubusercontent.com/68676339/154907389-07cc26b6-bcd3-438a-add7-8748954454be.png) I don't know about you, but this seems pretty effective to me

This also seems incredibly unpractical, I can't just build boxes around all my construction projects.


This is one of the few usable suggestions, but god bless you trying to find someone wanting to implement that..
My easiest guess is to make flow field maps for each team that include planned buildings and let their allied units use them.

**Comment by itcannotbe** [comment]
> My easiest guess is to make flow field maps for each team that include planned buildings and let their allied units use them.

Not easy

**Comment by stuffyAI** [comment]
> Not easy

What would you say is easier than my suggestion?

**Comment by itcannotbe** [comment]
> > Not easy
> 
> What would you say is easier than my suggestion?

Not implementing your suggestion.

**Comment by itcannotbe** [comment]
You can't just make flowfields everynow and then, you'll make the point of using flow fields pointless if you need to update it often.

**Comment by 64-Tesseract** [comment]
well this has gotten out of hand

I suggest something very simple: When the player places a blueprint with a unit in the way, the block gets placed, but cannot build beyond 0%. Units can then just pathfind out of the block, and when they leave it the building can be finished.

**Comment by stuffyAI** [comment]
> You can't just make flowfields every now and then, you'll make the point of using flow fields pointless if you need to update it often.

Which is what we... are already doing?
Every time I place a block, if the game detects that it obstructs a flow field, it needs to adjust the surrounding flow fields to point to the next best available path.
My suggestion literally only says that we story multiple entities of the flow field vortices for teams that are able to build.

Worst case scenario happens when you build ghost blocks without finishing them, meaning you have to calculate the surrounding flow fields pointlessly. Which compared to the rest of the pathfinding is still minimal.



> I suggest something very simple: When the player places a blueprint with a unit in the way, the block gets placed, but cannot build beyond 0%. Units can then just pathfind out of the block, and when they leave it the building can be finished.

Yes but then the enemy also pathfinds, meaning you could possibly juggle enemy units like aircraft to ghost power and back by rapidly deleting/placing

**Comment by 64-Tesseract** [comment]
> Yes but then the enemy also pathfinds

Enemy units are enemies, why would they move out of the way for the player? The _point_ of them is to destroy your blocks, so I think only friendly units should move.

> meaning you could possibly juggle enemy units like aircraft to ghost power and back by rapidly deleting/placing

1. Aircraft don't need to pathfind around blocks...?
2. Can't you already do that? If you've got a long tunnel that the enemies are walking through, can't you block the other side so they need to recalculate? Plus you won't be getting shot down like you would building over them.

**Comment by stuffyAI** [comment]
Aircraft pathfinds to power buildings.
So if I make ghosts of impacts, I can juggle them.



> Enemy units are enemies, why would they move out of the way for the player? The _point_ of them is to destroy your blocks, so I think only friendly units should move.

That is literally what I said, if we don't have flow fields for each team the enemy will move out of their way for ghost blocks.



> 2\. Can't you already do that? If you've got a long tunnel that the enemies are walking through, can't you block the other side so they need to recalculate? Plus you won't be getting shot down like you would building over them.

This is not possible right now, because you need to finish the building, meaning they most likely push one side too far eventually due to construction time. IF enemies would consider your instantly-placable ghost blocks, this might work in some occasions.

**Comment by 64-Tesseract** [comment]
> That is literally what I said, if we don't have flow fields for each team the enemy will move out of their way for ghost blocks.

Ah, that's what you mean... Didn't realize there was only 1 flowfield. I don't know anything about them but it shouldn't be _that_ intensive to calculate 2 of them, or at worst 6, right?

I guess a cheap way to implement this is to first not make blueprint disappear when there's a unit over them, and then it's built when the unit eventually gets out of the way by itself. A special case would need to be made when the unit's idle or rallied at a command point though

**Comment by mvrak** [comment]
stuffyAI> So if I make ghosts of impacts, I can juggle them.

Your claim relies on the idea that the enemy would also respect "ghost" pathfinding.  
There are multiple solutions.  Two simple solutions: the first would be for only friendly units to move out of the way of active building, the second would be for enemies to just not respect "ghost" pathfinding.  I don't think "ghost pathfinding" is a good solution as it would be used for making corridors for free all over the map.  You would get a "free" wall for units, but that seems completely the wrong way to implement it.

I would love to create ghosts and let polys fill them in.  Incidentally that is a solution for this also, since you can place down the ghost buildings, and they would get built when the units move.
