### ISSUE TITLE
Cursed geometry

### ISSUE THREAD

**Issue by Omega596** [Anuken/Mindustry-Suggestions#3407]
### Describe the content or mechanics you are proposing.

https://www.youtube.com/watch?v=c_9HQ3Ngf3c

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

the mindustry geometry will be logical

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
No.

**Comment by Omega596** [comment]
Yes.

**Comment by genNAowl** [comment]
Wall Duo: Gameplay > Realism
Toxopid Shells: Balancing > Realism
Bridge Weaving: [~~Was a Mistake To Implement~~](https://discord.com/channels/391020510269669376/396416151032299521/838760320017235978)

**Comment by oinkymoo** [comment]
1. this should be balancing/feedback, not feature request
2. you need to specify what changes should be made (ex: either allied duos should not be able to shoot over walls, or enemy duos should be able to shoot over allied walls)

**Comment by OnyxFinger** [comment]
No. How the fuck would the game even stay playable after this ? 
Here's an *example* of why : 
Because guns wouldn't all be able to shoot over walls without being shot at, either they are "higher than the walls" and thus because vulnerable, making walls pointless, or they just can't shoot. If they can't shoot when a wall is infront, they'd need a damage buff, and a health buff (else they'd die as soon as they start shooting), so you can just not use the walls

Ya got the problem man ?

**Comment by EclipseTheOldOne** [comment]
1. you can't just "hey please add this bye"
2. 2D game moment
3. literal tower defend game

**Comment by RFAC-Productions** [comment]
Welp safe to say that guy got pounded.
So
No
Please no
