### ISSUE TITLE
Save Logic

### ISSUE THREAD

**Issue by JacopoX1993** [Anuken/Mindustry-Suggestions#3426]
### Describe what you would like changed, and why.

Regarding the following points on the V7 announcement:

Command centers have been removed.
No logic blocks are available on Erekir. They may or may not remain on Serpulo.
A new RTS-like unit control system has been introduced.

### Describe the changes you want to propose. Include possible alternatives.

I agree that NEEDING to learn how to code to play is bad, and RTS controls are great. However, does that mean that logic has to go entirely? Here are my suggestions:

- Offer the player the possibility of RTS-styled unit control, and make it the default way of controlling unit
- Leave unit logic as it currently is 
- One of the following:

1. make command centers enable/disable RTS controls
2. make a linked command center a requirement for a processor to bind a unit
3. scrap command centers altogether

PS: little please, let us have logic on Erekir, too: it is so much fun to play with displays and optimize factories

**Comment by BlueWolf3682** [comment]
You had it easy, kid. Now, the fun begins.

Get ready, cause Erekir will kick your sorry ass.

**Comment by itcannotbe** [comment]
> it is so much fun to play with displays

Sound delusional.

**Comment by oinkymoo** [comment]
i think anuke found that logic does not fit with what he wants the game to be, which is why it's going

**Comment by noncom** [comment]
And I'm here to upvote this. Here's my reasoning and proposal:

It is totally understandable why and how logic breaks coherence among the playerbase. And yes, this is bad, in general. But consider these points to sum up what I think in this analysis:

Points:
- A lot of people immensely enjoy logic. That a big part of the playerbase. Think of how they gonna feel if you remove it. Please do not neglect that aspect, it's important and has very far-going consequencies.
- A lot of people have started learning logic and scripting because of your game. Every now and then new people in the discord keep opening up for themselves the wonderful world of programming, later maybe moving to modding and forth. I know you didn't plan to make a Scratch from Mindustry, but here we go.. you already did it.
- Logic adds a lot and a lot of depth to the gameplay. When using it you actually feel connected to the game world a lot more than if you'd only have the point-and-click interface. Immersion is multiplied by over 9000.
- A lot of people would only wish that the logic feature is developed further, not removed!

Problem:
- Some people don't enjoy logic and get overwhelmed by it. It is rather safe to assume that a certain percent of them will never attempt to overcome the shying.
- It might be hard to support, at times.

Proposal:
Keep logic and make it be enabled or disabled by a game rule. Simple as that:
- You want logic: you're joining PvP that says "logic-enabled".
- You don't want logic: you're joining PvP that says "logic disabled".
- You play campaign: you either use logic or not, however you wish. Nobody forces you. It's a crime to now take away that from the people who enjoy it and were already craving for conquering Erikir by utilizing their brain to 100%.
- In games with enabled logic there is NO problem in using a copy-paste of someones logic setup from the workshop. Because:
   - Everyone has access to it.
   - You don't need to understand how something works to use it. This is very true in our lives, and if you're not agree with that, then units and buildings need to be removed as well because someone doesn't understand how they work.

As a successful example of such approach: Space Engineers. That game has scripting on/off as a game rule, and everyone is happy.

Alternative:
Make it an official mod. Not much difference from making it a game rule, but a different flavor of logistical solution.

**Comment by itcannotbe** [comment]
You do know that by removing logic, the dev is removing another game mechanic to maintain.

**Comment by noncom** [comment]
@itcannotbe I'm not sure what you mean, but you're saying that as if the fact itself is of an absolute undebatable value. Which it is not.

**Comment by itcannotbe** [comment]
Simply put it as, all previous methods of controling units is getting thrown out the window and will be replaced by something different.

**Comment by noncom** [comment]
@itcannotbe how is that related to the topic of this issue?

**Comment by itcannotbe** [comment]
You probably haven't read the announcement.

**Comment by itcannotbe** [comment]
HOW ISN'T IT RELATED TO THE TOPIC AT HAND?

**Comment by noncom** [comment]
Again, I'm not seeing where from you're drawing that conclusion. But I think that I've said what I wanted to say pretty much clearly, and not going to participate in this discussion further atm since it's going offtopic.

**Comment by williams104** [comment]
I like what noncom said, it could be a toggleable thing in custom maps.
Also, what about all those people with logic in their campaign?
This could impact the player base if Anuke takes it away in Serpulo

**Comment by itcannotbe** [comment]
Actually the games doesn't take into consideration logic in calculating stimulated sectors,

Also if units are involved, the player has to now manually control units similar to typical games.

**Comment by itcannotbe** [comment]
> It's a crime to now take away that from the people who enjoy it 

Actually there multiple mechanics or exploits that the dev removed for various reasons throughout the life of the game. I can list them down and state the reasons for removal, but that would be tremendously off-topic.

The community will get used to it eventually.

**Comment by itcannotbe** [comment]
Also since adding of logic to the game, balancing units became difficult due to the flexibility logic provides.

**Comment by williams104** [comment]
Yeah.
Flare-Blast is OP

**Comment by OnyxFinger** [comment]
Although I don't agree with some statements (e.g. flare-blast is OP, right above), I do believe that logic has brought more harm than good to Serpulo. I don't think it should be in Erekir.

**Comment by AMindustryPlayer** [comment]
Although logic is bad in some perspectives, you(Anuke) should not completely remove it.
Instead, you should disable some features from logic for balancing(e.g. Unit binding and control).
Because some schematics really used some features from logic for monitoring itself(e.g. Uses logic-switches to turn it on and off, of course you can transfer this feature to factory blocks/turrets, but the result will be a buggy mess. Therefore, the alternative way is to make switch able to link to other blocks and can be turned on and off together, but what about the other features?)

**Comment by BlueWolf3682** [comment]
Erekir will be massively more difficult than Serpulo. Anuke has entirely changed the balancing scheme of it, and has removed the ease of difficulty that is present on Serpulo. 
If you hate logic being removed from the planet, then you might as well also know this:

Erekir has no launch pad, and either limited or no loadout.

The difficulty spike is MASSIVE, and I highly doubt anyone relying on logic will survive the new planet. 
If you want to win, get good instead of relying on someone elses processor code and furry art display to get by.

**Comment by RealYeet** [comment]
You didn’t have to roast him that hard

**Comment by MEEPofFaith** [comment]
> furry art display

lmao

**Comment by JacopoX1993** [comment]
Roast whom? I do not understand the bitterness: I made a simple and civilized proposal. I really have no idea where lewd stuff and stealing other people's code came in, but given that he mentioned it maybe bluewolf is familiar with this kind of stuff? Something similar goes with who called me delusional. Anyway, my proposal was about the game, not who plays it and I won't comment further on this,

**Comment by noncom** [comment]
You people again talk about a bunch of totally unrelated stuff.

I like programming and engineering. As evidence shows, a lot of people do. This game has this additional depth.
Removing it is not something I'd like to see -- the game would still be fun, but it would lose much of the depth.
On contrary, I'd like to see this feature being cleverly developed and polished further. That is all.

And if your point is that writing programs and engineering fun stuff is somehow easier than playing without it, that only means you have no idea what you are talking about.

**Comment by oinkymoo** [comment]
> * You want logic: you're joining PvP that says "logic enabled".
> * You don't want logic: you're joining PvP that says "logic disabled".

this requires server owners to display this info. players who want to play specifically with or without logic will likely need to find new servers. 

> * You play campaign: you either use logic or not, however you wish. Nobody forces you. It's a crime to now take away that from the people who enjoy it and were already craving for conquering Erekir by utilizing their brain to 100%.

as others have pointed out, logic makes the game significantly easier. if you are aware of the dispute around logic, then yeah, you might decide to not use logic. but if you are a new player just starting in v7, or you aren't involved with the community, you're probably going to pick it up because there's literally nothing stopping you from doing so. anuke specifically wants logic gone, and has no way of preventing players from using what is (from those players' perspective) an intended feature.

**Comment by JacopoX1993** [comment]
Logic might be useful, but it requires plenty of effort to learn. So this

>  logic makes the game significantly easier

essentially boils down to "getting good makes the game easy". Further elaborating on this point, I find that there are other cheesier tactics in the campaign, such as just building a bunch of turrets and then just leaving the sector. Do you think that flare+blast compound is OP? I agree: just remove the bonus damage from carrying the blast compound. We already have crawlers for kamikaze attacks, after all.

> You want logic: you're joining PvP that says "logic enabled". You don't want logic: you're joining PvP that says "logic disabled". this requires server owners to display this info.

If you really dislike logic that much, all you need to do is to disable the logic turrets, which is already possible on servers

> anuke specifically wants logic gone

This is what I cannot argue against: Anuke is the one coding the game and if he wants logic gone then logic is gone. I was hoping that he would listen to the community as well though, and based on the feedback on discord to this post my idea has plenty of support.

**Comment by IxGamerXL** [comment]
Stop me if I am showcasing the same thing already said here.

![20220312_163920](https://user-images.githubusercontent.com/90928500/158037548-8748533d-e16a-4afc-b3ae-38c9ab23a2f7.jpg)

Anuke won't be removing logic blocks from Serpulo @JacopoX1993 but if you really need that logic block fix, you can likely make a mod that allows you to use logic blocks in the new planet, or even make one that creates new logic blocks to fit the theme *(which will likely be required since there's likely going to be no more copper or thorium)*. Playing on this new planet legitimately will require leaving your logic blocks back at home and embrace the new environment with no technical utilities.

**Comment by JacopoX1993** [comment]
@IxGamerXL 

No, that is new; the edit was not there when I started the issue. In it's place, there was something along the lines of "No logic blocks are available on Erekir, and I will likely remove them from Serpulo"

I love logic and I would have liked to see what possibilities it could have offered on the new planet, but I am personally fine with at least getting to keep all the stuff I have already built on Serpulo.

**Comment by noncom** [comment]
I think that the main point is in saving logic. The fact that it is not available on Erekir is a gamedesign choice. The creator wishes so and wishes to explore the different aspects and flavors of Mindustry, having fun creating it, and it's totally understandable. Reimagining the game on Erekir and having freedom in that -- is good.

So, with the logic still being with us I'm sure that those who want to play with logic on Erekir are free to create a mod that adds and adapts it to Erekir. Those who want it -- are going to be able to at least do that for themselves, which is perfectly fine imo.

All this seems to be a fair resolution. And keeps Mindustry up in having those kinds of fun and freedom which not many other games are able to provide. That's what I think.

**Comment by SMOLKEYS** [comment]
> > furry art display
> 
> lmao

r

**Comment by williams104** [comment]
I feel like what Anuke did is the best way, because taking it off Serpulo would affect many late-game builds.
Many people have logic control their entire base and if it was removed all that progress would be lost.
