### ISSUE TITLE
Build cost increment mechanic

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#3434]
### Describe the content or mechanics you are proposing.

A method of increasing build cost per block/s placed

Say if you placed x block.

1st block: base cost
2nd block: base cost +(rounddown((blocks already placed/panned)/(how often increment is applied))(multiplier)(increment here)

And so on.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

A mechanic to prevent spamming blocks without consequences.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by 64-Tesseract** [comment]
y tho?
A wall block takes 6 of a material, does it become stronger the more you build?
And if a troll joins your team and spams, that's just more materials coming out of _your_ core... That's not punishment, that's another way for someone to be annoying

**Comment by itcannotbe** [comment]
It doesn't need to be applied to every block, it's just another balancing mechanism that can be good to have, not to mention would allow the creation of some other game modes through plugins.

**Comment by OnyxFinger** [comment]
> A mechanic to prevent spamming blocks without consequences.

The problem is that it punishes people that built a big factory for a material, or a that placed a lot of defenses etc..

**Comment by itcannotbe** [comment]
It doesn't need to be applied to every block, it's just another balancing mechanism that can be good to have, not to mention would allow the creation of some other game modes through plugins.

**Comment by BlueWolf3682** [comment]
Not useful.

**Comment by stuffyAI** [comment]
> A mechanic to prevent spamming blocks without consequences.

Okay you said that preventing the spamming of blocks is good to have, but how and why exactly does it increase player engagement in the game?

There are games which implement such mechanics, mostly those with some COOP/PVP format between 2/4 players, to hard cap the playing field, but I do not see how this would be needed, less even be fair in Mindustry.
Many PVP maps are not perfectly mirrored, so depending on layout this mechanic could simply give one player a disadvantage because they have to build more structures of a type than the other player for equal results.

**Comment by itcannotbe** [comment]
It doesn't need to be applied to every block though.

For example you want to force a power constraint. On the map, it's as simple as making it costlier to build more generators. Or something to that extent.

It just adds more challenge, by extension forces players to think critically on what to do next carefully.

It just something you can change to make the map harder earlier in the game.

**Comment by itcannotbe** [comment]
Other use cases is to make a block available for use while constraining how many one can place down in one go.

So instead of you being able to spam water extractors, you have to use them wiser until you have more resources to place down more since the newer one is costlier than the last.

**Comment by stuffyAI** [comment]
Would it not be easier to be a good mapmaker and limit factory growth by... the map itself?

If you would want those limitations, you could as well make available space smaller, forcing the challenging 'critical thinking' by reducing the amount of possible buildings. No need to make it a waiting game for the select, mandatory blocks which have building cost increment.
Want the player to have low power? Just reduce coal.
Want the player to have low water? Just reduce water space and coal, can't spam water extractors of you have no power.

There is barely a desired situation in which making a good map doesn't already allow you to limit the player, why don't we just do that instead of enforcing unrealistic rules like 'ah, because you already build 2 of that, suddenly the third one becomes more expensive to build'.

**Comment by itcannotbe** [comment]
> Want the player to have low power? Just reduce coal.

Side Effect, harder silicon production early game.

> Want the player to have low water? Just reduce water space and coal, can't spam water extractors of you have no power.

Side effects, a cramped map.

Also define unrealistic?

**Comment by itcannotbe** [comment]
Additional situations you can use it:

Limit spikes in resources production once better drills become available.

Limits unit production capability

**Comment by stuffyAI** [comment]
So just reduce map space? Feels like a lazy way to implement a limitation you can achieve otherwise.
This also linearizes meta on maps, previously I could choose what style I wanted to play by using my available space different from others, now 'building x becomes more expensive' causes me to simply use other methods instead.


> Limit spikes in resources production once better drills become available.

Why? Seems like a pointless shot in the own foot, why should I be punished for trying to use new technology I unlocked. This only pads virtual playtime.



> Limits unit production capability

Why? I have a hard cap scaling with core level, this only matters in PVP (in which I already explained the unfairness of this idea) or when I use units as tanks and thus need to replace dead ones. Given the vast space efficient unit production designs need, you can also limit this with map size...

**Comment by BlueWolf3682** [comment]
\*builds a conveyor line*
ah shit now my conveyors cost 300k copper each

**Comment by BlueWolf3682** [comment]
Jokes aside, how does it limit unit production? Furthermore, what use is limiting unit production? I doubt unit logic will come into play much after dev branch merge, and units are fine as is.
Limiting resource spikes? Well, why? Are you saying that a game about getting resources should have unnecessary limits on those resources?

**Comment by itcannotbe** [comment]
> how does it limit unit production? 

If you can't build as may reconstructors as you want, you're basically limited.

It doesn't affect campaign that much because of the lower unit cap compared to multiplayer.

> Limiting resource spikes

Yes. It's less of a campaign thing but more of a multiplayer thing.

**Comment by BlueWolf3682** [comment]
Then people would focus on one or two tetratives full time ODD running instead of 5 - if anything, you just forced players to be more effective.
And so? why should multiplayer be limited?

**Comment by Bassem-Const** [comment]
Anuke implements this for april fools but the how often increment is applied thing will be a gargantuan number.
