### ISSUE TITLE
Liquids in core too perhaps?

### ISSUE THREAD

**Issue by Valoneu** [Anuken/Mindustry-Suggestions#3483]
### Describe the content or mechanics you are proposing.

Core being able to be sucked into core and put out by some liquid unloader

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It will improve PVP servers where you get to build more cores or just maps with more cores so you can transfer liquids faster and make more desings

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
What next, allowing players to store coal, spore pods, pyratite and blast compound in cores?

**Comment by Valoneu** [comment]
Well you already can

**Comment by itcannotbe** [comment]
Well... #245

**Comment by IxGamerXL** [comment]
Item teleportation via cores is already an overpowered feature in some maps. Also, the ability to have liquid contained in cores would mean only one liquid type can go to and from the cores, where as Items being put together as they are part of an ItemStack instead of only allowing one type within cores.

It could probably be better that we can have LiquidStacks which allows you to contain multiple liquid types, possibly opening up to building structures with Liquid so you can enhance it or so the recipe is fulfilled.
