### ISSUE TITLE
Processor Comments

### ISSUE THREAD

**Issue by Someonepy** [Anuken/Mindustry-Suggestions#3491]
### Describe the content or mechanics you are proposing.

Instruction like `Print`, but will be skipped in running. (Just a note)
A simple feature, but it will be very helpful for understanding someone else's code.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

More processors' code readability.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IxGamerXL** [comment]
Honestly, why didn't we have this in the first place?

**Comment by end-me-please** [comment]
Suggested and denied before I think

If you use an external editor, you can use jump labels and comments

**Comment by IxGamerXL** [comment]
> Suggested and denied before I think
> 
> If you use an external editor, you can use jump labels and comments

If you're viewing it in-game, it becomes a niche fulfilling element, as it's easily accessible for anyone, and easy to use. Besides, not everyone's going to use an external editor.

As he said:

> Instruction like Print, __but will be skipped in running.__ (Just a note)

This kind of instruction would likely have more space as a note, and will even get skipped so that it doesn't effect runtime. Heck, it could even have Word Wrapping so that all dimensions of screens can read the content of these notes/comments (especially since `print` doesn't word wrap).
