### ISSUE TITLE
The Possible Implementation of gases and crops

### ISSUE THREAD

**Issue by vivaan-web** [Anuken/Mindustry-Suggestions#3504]
### Describe the content or mechanics you are proposing.

I propose that Mindustry should have gases(like liquid or mineral). I also say that mndustry should have crops. Why harvest only spore pods? That's boring. More blocks like greenhouses and harvesters should exist. Why not sea sectors? Sectors that are fought and built on ocean.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Gases will allow for for more items and other options for gaining items when resources are scarce. crops will give more biological items which I think are kind of underrated in normal industry. Sea sectors will give more awareness and use to naval units

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by oinkymoo** [comment]
gases, crops, and sea sectors should have been separate suggestions.

more items is not in itself a good thing. it often adds unnecessary complexity, which is outright bad. also have you considered the possibility that limited resources are intentional?

you never made it clear why more biological items would be useful in the first place. what would one even do with them in a drone-based combat or a fully-automated factory.

there are already several highly aquatic sectors (especially the final campaign sector)

**Comment by WilloIzCitron** [comment]
gasses has implemented on erekir branch
