### ISSUE TITLE
Merge Item and Liquid Void

### ISSUE THREAD

**Issue by Catchears** [Anuken/Mindustry-Suggestions#351]
**Describe what you would like changed, and why.**
I think the item and liquid void should be merged into a single block. The incinerator can handle both liquid and items, so surely the sandbox item should be able to do so as well.

**Describe the changes you want to propose. Include possible alternatives.**
Item void and liquid void are removed and replaced with "void" (or a similar name). The "void" can consume both items and liquids in any quantity. It does not require power and is sandbox-only.

**Comment by SupremeTurtle** [comment]
Yes

**Comment by Catchears** [comment]
Created a pull request, see it here:

https://github.com/Anuken/Mindustry/pull/2286

**Comment by Zenith-LY** [comment]
SMart idea but in which category would it be in? I guess the "misc" category (that one with vaults, shock mines, etc.) But that wouldn't be good since the item and liquid sources are in their respective categories while their counter block  "Void" item is in the misc category and would be mixed So I don't support this idea but it isn't bad either.

**Comment by itcannotbe** [comment]
Why do we need this? The blocks refered to are sandbox only anyways. There would be no benefit it woul bring to normal.gameplay.

**Comment by Catchears** [comment]
I had the same thoughts as you after considering it for a while.
