### ISSUE TITLE
Closed source processors

### ISSUE THREAD

**Issue by Bassem-Const** [Anuken/Mindustry-Suggestions#3632]
### Describe the content or mechanics you are proposing.

An option in processors to lock them for those who have a different IP, UUID, all, or who are different from the one who placed it by the first 2 options.

Locking could mean making them uneditable, or unviewable.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Allows for security in logic without having to detect if someone had changed the code.

That means lots of new things, including one thing which I wanted to make: currency

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BasedUser** [comment]
First of all, what you're suggesting makes no sense. It requires sending more data after world data (or block placement data) was already sent. Why is this a problem? This isn't just one block that needs to be changed, the server itself needs to be changed to selectively send processor code, and only to one client, for logic *the server has to relay* (remember, you're not sending processor data to other clients because it's "locked"), which is at least an overhaul of logic itself, and likely an additional server packet for "stuffing" aforementioned logic effects.
Secondly, if you're concerned about security, have a thought at the following. Both IP and UUID values can be spoofed. Not a single packet Mindustry sends is encrypted. I can pretend to be a user connecting from a specific IP (since UDP doesn't require a handshake), and with my own UUID. Add in a man-in-the-middle attack to get the USID and you can already impersonate an administrator or whoever placed the processor. These attacks are a lot rarer now, but they're still there. 
Thirdly, this is treading a lot into "make your own mod/plugin" territory - there's many things Mindustry could implement, like a UNIX timestamp variable, `@speed` for units and a HTTP request function, as useful as they are, absolutely unnecessary when you look into the usecases and game balance. People have exploited `@time` to desynchronize processors from client to server before and it worked too well.

At that point, you might as well make that a(n also closed source) server mod, or better yet, write currency itself as one. I personally don't see a reason why this should be a feature.

**Comment by deltanedas** [comment]
also this already exists as a mod i think, anukoins
if the only one is by me its unfinished but yeah

**Comment by jumps-are-op** [comment]
How to make a credit card system 101

1: Recreate sha256 in mlog
2: Store hashes of all credit cards in the processor ( or somewhere else )
3: Make a device that read "credit cards" ( connect the device with the credit card throw a memory block )
4: Make a credit card that send the unhashed password throw the memory bank
5: Let the credit card reader hash the password then delete it from the memory bank
6: If the hash is the same as the stored hash then the password is correct
7: Do something to the user if the password is correct 

But again, why do we need a credit card system in the middle of a cross planet war?
