### ISSUE TITLE
waves after guardian

### ISSUE THREAD

**Issue by igrajpl** [Anuken/Mindustry-Suggestions#3645]
### Describe the content or mechanics you are proposing.

I think there should be option to turn off additional waves after defeating guardian in campaing mode.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Some people witch I know and I like to destroy all defense after defeating guardian and build huge factory and these additional waves are just destroing this concept.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
1. There is no waves after you defeat the Guardian.

2. The only reason why the sector you have captured is getting attacked is because there a sector that is an enemy base nearby.

3. The defenses you have to put up doesn't need to be significantly powerful, just enough to overcome the attack based on the threat level of the neighboring enemy base.

4. If you don't want to defeat the enemy base, just surround that enemy base with captured sectors with defenses.

5. Skill issue. 

6. You aren't that familiar with the content (including game mechanics) in the game, yet you dare to make that checkbox? Huh.
