### ISSUE TITLE
More World Proseccor Commands

### ISSUE THREAD

**Issue by Def-Try** [Anuken/Mindustry-Suggestions#3750]
### Describe the content or mechanics you are proposing.

More "World" category commands:
Flush text [x] [y] - display text in world
Particle [x] [y] [particle] [size] - create particle(s) in world
Flush chat message - send text to chat

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Flush text - markers, tutorials, etc
Particle - cutscenes use
Flush chat message - Cutscenes, mission stages, etc

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Zhy54** [comment]
My eyes feel uncomforable after playing a long time on Erekir
(First, I‘m sorry for English is not my first language and I do not often use github.)I think this is because the full screen are orange , it hurt my eyes , espcailly on 3rd map on Erekir. When stop playing to read books , the white paper looks like green ...It's like I've been staring at the sun for a while.This thing never happened when I played the first planet , white , green or dark ground are firendly to play , but orange is a little harsh for me.
