### ISSUE TITLE
Slow down loading in the menu

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry-Suggestions#376]
**Describe what you would like changed, and why.**

On low end devices the loading screen may freeze and then the awesome animations can't be appreciated.

**Describe the changes you want to propose. Include possible alternatives.**

Limit loaded content per tick to not seriously impact framerate (10 fps minimum?) on low end devices.

**Comment by itcannotbe** [comment]
That's a vague request.

**Comment by DeltaNedas** [comment]
yes

**Comment by itcannotbe** [comment]
The start up screen is designed to consume as much resources at it can possibly can, to make start up faster.

System Bottlenecks Ensues.

**Comment by macdowntwo** [comment]
doesn't bloom take a bit of resources? it should be disabled in the loading screen to make it start up a bit more faster

**Comment by itcannotbe** [comment]
It's not really a significant resources consumer.

**Comment by macdowntwo** [comment]
...i see. ill go now

**Comment by PhilipPurwoko** [comment]
It's better slow on loading screen, so the game can run in better performance @DeltaNedas

**Comment by MapleWheels** [comment]
I think his point is that the loading screen/game start animations should be allowed to play smoothly. In theory, this could be solved by giving this take some form of priority or if, in single-thread, ensure that engine iterations are not severely impacted during the sequence.

Although, I fear that this could significantly impact game load times, which are extremely important to user perceptions and also could pose an annoyance. Think as such _"Ever since update XX came out, my game has been loading a lot slower. Hey [social media platform], anyone else noticed this?"_ And so would ensue a new Mindustry Issue ticket about slow load times.

**Comment by DeltaNedas** [comment]
on my phone, my pc can handle it just fine

**Comment by itcannotbe** [comment]
@MapleWheels It's as slow as 5.0 ,but the thing is , 5.0 is a plain loading bar, 6.0 has an animated background and actual files and subsystem loading statuses if you look closely.

**Comment by BlueWolf3682** [comment]
Bloom takes no resources to use, I've had it enabled on my old tablet and my fps does not noticeably suffer. though I agree, being able to see the animations would be epic
