### ISSUE TITLE
Better Schematic GUI

### ISSUE THREAD

**Issue by RoyalFunnyDude** [Anuken/Mindustry-Suggestions#379]
**Describe what you would like changed, and why.**
I think sometimes it is very bothersome to place down a schematic and find out while building it that you don't have enough resources, so I thought maybe there would be a line of text while placing the schematic telling you how much resources you need and how much you have currently.

**Comment by Katsute** [comment]
Already added. #95

**Comment by zethnest** [comment]
@Katsute This would be different. Sometimes you don't want to use a schematic from the schematic menu and want to copy and plop down a schematic and be on your merry way. But you can't because you didn't know there are insufficient ingredients and you need to doze out a couple of minutes before having enough.

**Comment by Katsute** [comment]
#265
