### ISSUE TITLE
Custom Map Rule: Block Count Limits

### ISSUE THREAD

**Issue by IxGamerXL** [Anuken/Mindustry-Suggestions#3796]
### Describe the content or mechanics you are proposing.

A new rule for custom maps which allow you to lock individual buildings to only have so many of one type per team. Buildings already put into the game will count, but exceeding will basically lock the use of that building type until enough space is acquired, which is basically being in debt.

Anytime the capacity of a building is reached, players cannot build anymore of that type, and will have to destroy one of the buildings to get space back. You can also check a building's capacity and count by selecting it and looking below the name of the building.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

A bit of a followup with #3279, but with a more reasonable and more likely appreciated feature with an indirect solution. This can be used to make Water Extractors less easy to spam, Force Projectors less viable for stacking, and plenty of other things.

This practically creates a kind of barrier which prevents players from using too much of a certain building if it keeps making your map trivially easy, but it's still fine to you if players can build a couple of them.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
> Make Water Extractors less easy to spam, Force Projectors less viable for stacking

I don't think you realize this but... these two example are horrible : 
 Water Extractors are fine as they are. I think that some people really don't realize how they think they are still too OP, but when you switch to pumps, the amount of power saved is obvious.

Force Projector stacking, well it's not a thing. It simply doesn't make sense, why would you have a bunch of force projectors that will end up going down while you could have a bunch of menders healing your wall ?
If Force Projectors aren't quite a joke like they used to be, it's because they can absorb bombs from quads or horizons without breaking a sweat (at all, they will never go down to purely AOE based attacks). This function makes stacking a bunch of Force Projectors obsolete, since you only need one per area, only if that area is a possible target for enemy bombers.

**Comment by BlackDeluxeCat** [comment]
I support it. But my point is not at water extractor. This feature would be good for preventing spamming of unbalanced contents(in specific map) such as malign.

**Comment by hello-hello-there** [comment]
Good idea, bad examples.
