### ISSUE TITLE
Cloud storage for Mindustry saves

### ISSUE THREAD

**Issue by BaseModMaker** [Anuken/Mindustry-Suggestions#380]
**Describe the content or mechanics you are proposing.**
An option in Mindustry to upload your save to a cloud storage. That would make playing campaign mode across multiple platforms easier and would prevent you from losing your campaign save (happened too many times to me).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It's more intuitive to upload your save to a cloud storage than having to import your save with a file.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
This has been suggested many times. You can sync the data folder yourself using any cloud storage service of your choice; Mindustry does not need any explicit implementation of it.

**Comment by ThaDaVos** [comment]
Sorry for commenting on a closed issue - but what about someone creating a mod for this?
Would that be a valid implementation?

**Comment by Johnystar** [comment]
> This has been suggested many times. You can sync the data folder yourself using any cloud storage service of your choice; Mindustry does not need any explicit implementation of it.

@Anuken
This doesn't work, because you have to sync the ``settings.bin`` file to get campaign data as well. That's a problem because (my case as an example) my laptop's DPI is significantly higher than my desktop's, so I basically need to use different UI scaling on both if I want a decent experience.

**The problem** is that to get campaign saves working, you also need to sync other things such as UI scaling, which should be kept as machine-specific, unlike saves, which should be the same everywhere.

**A good solution** would be if campaign data were separate from settings and saved in the ``saves`` folder. That way, all you would have to sync would be the ``saves`` and ``schematics`` folders.
