### ISSUE TITLE
remove special behavior of place range check regarding turrets

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry-Suggestions#3805]
### Describe what you would like changed, and why.

placement range check not allowing to place turrets with enemy blocks may have created more problems than it has fixed:
- you can spam walls to prevent the enemy from placing any turrets
- long-range turrets are especially affected by the above and often just can't be placed because there's already some irrelevant blocks far away, extreme example: scathe

### Describe the changes you want to propose. Include possible alternatives.

make placement range check work the same with turrets as it works with other blocks (allow placing turrets with enemy blocks in range)
alternative: make the turret placement range check a soft cap and not a hard cap, example: measure some value (cost?) of the blocks in range, scale inversely to distance(^2?), and check if the sum of those scaled values is smaller than some set threshold

**Comment by Anuken** [comment]
Is this rule even worth keeping around? It was only added to prevent campaign cheesing, and in the end we decided to remove that anyway and nerf building damage instead. It's inherently flawed in PvP, and likely always will be.

**Comment by Ilya246** [comment]
it prevents tactics like just putting a liquid container full of ozone next to enemy walls (that is a real thing and is very effective)

**Comment by OnyxFinger** [comment]
To respond to both comments with my opinion :

The only instances of the rule being used that I found were...bad. You don't really need to restrict building near the enemy anyway since this function is meant to be done using guns. If there are no guns, then it's not like the area is meant to be capable of fighting back, why would you prevent somebody from building in it ?
So I agree that there isn't much in the way of this mechanic being removed (since it's hurrendously annoying sometimes, a random leftover just stops you from building infrastructure in a mile radius).

As for ozone bombing, well I think that you should be capable of dropping near buildings, and that fixes things (and obviously turrets should aim at tanks, which makes a lot of sense since it's storage so why wouldn't you bother removing especially with such a small health pool ?).

**Comment by Anuken** [comment]
> it prevents tactics like just putting a liquid container full of ozone next to enemy walls (on maps without place range check that is a real thing and is very effective)

If a map lets users place such blocks next to enemy structures of any importance, that map is bad. Core protection (polygonal or not) should not let this happen.
