### ISSUE TITLE
phase-heater

### ISSUE THREAD

**Issue by Helium-ion** [Anuken/Mindustry-Suggestions#3859]
### Describe what you would like changed, and why.

The @phase-heater too powerful to seem reasonable.

### Describe the changes you want to propose. Include possible alternatives.

1. Adjust its size to 3.  **(I recommend this way more. So I put it in the first one.** While this can lead to damage to a map that already exists, I think it's acceptable.)
2. The heat it produces rises from 0 to 15 (or less) over time, which means that the heat it produces increases by 1.5 per second, and the heat it produces repeats from 0 at the start of the next production.
3. Adjust the upper limit of the heat it produces to 10 or less.

**Comment by OnyxFinger** [comment]
I'd say just, instead of any of that, make it consume more phase. But a LOT more. Right now pretty much anything that takes phase is free to operate, neoplasia reactors don't consume much, phase heaters don't consume much, and the optional boost for healing is basically just entirely free as long as you have phase.
