### ISSUE TITLE
Melee Turret-like Weapons

### ISSUE THREAD

**Issue by WhyNotDogie** [Anuken/Mindustry-Suggestions#3891]
### Describe the content or mechanics you are proposing.

Adds turrets that are melee, basically turrets with VERY low range but high damage, and that pierce through and hit everything within range (for long swing) otherwise just a dagger that stabs out.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

adds more room for last-minute defenses near the core and and more intriguing styles of defense gameplay, such as its functionality in attack mode, where its more like a reusable ground mine.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Phinner** [comment]
I don't think the game need dedicated "melee" weapons. I mean there are already high damage short ranged turrets such as the fuse and the scorch.

**Comment by OnyxFinger** [comment]
As pointed out by Phinner, those weapons already exist, and I may add they have a pretty good history of being bad. I mean, fuses are way overrated and people only started realizing it in v6 because of everything that changed, especially liches not being a thing anymore. Scorches were only "good" because of a glitch. Now nerfed, scorches aren't actually good anymore (because arcs exist, which are literally the same thing but better).
