### ISSUE TITLE
Building priority

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3894]
### Describe the content or mechanics you are proposing.

When you build a lot of blocks you can chose which ones to build first by tapping on them but only if they are slightly build. If they are only planned you can't chose to build them first. You should

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

When you are under attack and you make large building plan you need to build some block first but you didn't necessarily plan them first so you get destroyed while building blocks what are not the most important

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
Somehow someone disliked this. I guess there could be some issues because of way which building goes first is defined. I didn't look in the code for this, but I'm pretty sure that the order in which blocks are placed is defined as soon as they're placed (there is probably a number labeled to them to know which one goes first), so live updating it may mess with the order in strange ways maybe ?
