### ISSUE TITLE
Shield regen on erekir

### ISSUE THREAD

**Issue by Dangleos** [Anuken/Mindustry-Suggestions#3900]
### Describe the content or mechanics you are proposing.

There are no units on erekir with shield regen field so there is no way to give erekir units shield. What if you would add a shield regen block. It's different from serpulo

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would unlock their gidden potential

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by OnyxFinger** [comment]
that is purposeful, because shield is completely useless to the player. Its only real use is for the mapmakers, to increase enemy health. Anuke realized that implementing it as a mechanic that the player could use on serpulo was a mistake, and thus he didn't add it to erekir.
~~Can you tell I think Erekir is a superior planet in terms of gameplay ?~~
