### ISSUE TITLE
where is units require ammo

### ISSUE THREAD

**Issue by Mythril382** [Anuken/Mindustry-Suggestions#4037]
### Describe the content or mechanics you are proposing.

feature was cool + custom AmmoType thingy for mods

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

nobody hated it (i think)

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
https://discord.com/channels/391020510269669376/396416151032299521/1026954402529022062

**Comment by Anuken** [comment]
*I* hated it, and it was never implemented for Erekir.

If you want to use it in tightly controlled custom mod maps, you still can, if you can figure out how to enable it with the console. It's just not in the editor, because I do not want yet another poorly-maintained half-baked optional feature lying around.
