### ISSUE TITLE
divide silicon arc furnace energy cost

### ISSUE THREAD

**Issue by yesC48** [Anuken/Mindustry-Suggestions#4068]
### Describe what you would like changed, and why.

this has been a pretty annoying thing (for me) and that's why this is here. silicon arc furnace energy cost should be lowered, simply because "the onset" campaign map just doesn't have enough vents to meet the requirements of a silicon arc furnace, the tank fabricator, cliff crushers and plasma bores.

### Describe the changes you want to propose. Include possible alternatives.

lower silicon arc furnace energy cost to 240 power units to make it more ergonomic and for the people who silently complain that the arc furnace demands too much power units to calm down.

**Comment by itcannotbe** [comment]
See Image below regarding why erekir campaign maps are made the way they are:
![Screenshot_20221030_115049](https://user-images.githubusercontent.com/45280919/198861728-f8120ddd-e35a-4c8f-81f2-69d22d5654e3.jpg)

**Comment by TechDudie** [comment]
why can't you cover every single vent with a generator? thats what I do and it works perfectly fine otherwise someone else would have already complained about the impossible map because not enough power and it would be fixed

![Screen Shot 2022-10-29 at 11 13 31 PM](https://user-images.githubusercontent.com/73961295/198862293-d787efb0-575f-4059-9dd1-4dec8b0c39e4.png)

![Screen Shot 2022-10-29 at 11 16 07 PM](https://user-images.githubusercontent.com/73961295/198862325-6e04dd66-eb8e-4da0-a4fd-d348feecd6a5.png)

im pretty sure this is enough

though whacking the onset enemy base is pretty hard for me, wasted like 30 ground units on maybe damaging a third or a half of the base ugh

**Comment by yesC48** [comment]
tbh im just complaining too much so yeah
