### ISSUE TITLE
New Units, and Multiplayer

### ISSUE THREAD

**Issue by Reven3** [Anuken/Mindustry-Suggestions#4091]
### Describe the content or mechanics you are proposing.

|1.|  please read to the end, even if you don't like some of the ideas.  the possibility of creating a friendly server, where one person creates it on his own account, and his friends will be able to join it, just as they will not be tied to one sector, which will allow them to travel around the planet and be more productive.  |2.|  make the red team on Serpulo a serious opponent who will capture untouched bases and develop.  in the fight against him, the players will unite for success.  |3.|new locations that will unlock technologies such as.... "orbital target fabricator."  these are large and expensive spaceships that will be able to transport some units or resources to sectors, but it will take a lot of energy and resources.  2) a cheap analogue of a sign that will fire rockets that will operate at a long range and will deal damage in an area, but it will be slow and will consume silicon, coal and titanium.  3) a mixture of plastan, steelglaas and titanium, which will produce a new type of ammunition that leaves a green fire for 20 seconds after itself, as well as its unique ability will be that it significantly increases the firing range.  4) a new turret that will create a small shield that will repel all damage, and then shoot with a wave that stuns and repels enemies, but such a turret does not overheat for a long time from this.  5) new air units, the task of which is to land combat units, such as daggers or others.  6) A new huge manufacturer of cryogenic liquid.  7) a new huge plastan press that will spend a lot of energy and more resources, but in return give 4 plastan per second.  8) more anti-air turrets.  |4.|  the main base of the red team, as well as the ability to create the main base of your team, where there will be an advantage in delivering resources to other sectors, + 5% to the speed of the mechanisms, as well as + 10% to the damage of turrets.  but in the midst of a war, if you allow your opponent to surround you, there will be the possibility of fighting for your base on an increased difficulty level |5.|  will add a new level for existing blocks, such as an unloader or an illuminator, for example: illuminator level 2 will illuminate in a radius of 50 blocks.  I think that's all?  I was so worried that I even forgot what I wanted.  I hope you notice, have a nice day.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

it will add new features that will bring more interest to the game.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by IVV-NCX** [comment]
I'll simplify this where I can:
1. A way to beat campaign with your teammates, instead of being locked to 1 sector? Enemy team will expand and fight you for territory across the whole world.
2. Ability to send units to other sectors. Resources is already possible.
3. Rocket launcher. Uses silicon, coal, titanium.
4. Ammo that leaves a damaging trail, and increases the range of the turret. Consumes plast, "steelglass",  and titanium.
5. Turret that blocks bullets with a shield, then stuns and repels enemies. Can overheat. 
6. Upgraded cryo factory.
7. Upgraded Plast factory.
8. More Anti-air.
9. Some "fight for world domination" game mode. I can't understand it.
10. Upgraded unloaders & illuminators, or blocks that don't have upgrades yet.
--------------------------------------------------------------------------------------------
My Opinion:
1. No. Difficult to code, laggy due to lack of servers and need to render multiple sectors at a time.
2. No. Units would be OP. Imagine sending a T5 to a sector.
3. Rocket launcher is in V7?
4. No. Increasing range would break balance.
5. Shield projector. EMP/repel turret sounds interesting though...
6. Maybe. Has a chance of breaking balance, T5 is supposed to be a massive investment.
7. Maybe. Plast is meant to be expensive.
8. Why not? Just keep it balanced...
9. Can't figure it out.
10. Unloaders are very strong. Illuminators, yes please. It won't hurt the game. Some blocks don't need upgrades, like Cryo might not.
