### ISSUE TITLE
Real hotkey system please!

### ISSUE THREAD

**Issue by wuigukin** [Anuken/Mindustry-Suggestions#41]
**Describe the content or mechanics you are proposing.**

A better system for hotkeys.

Currently the hotkeys have many issues, some big ones are:
- They are tied to a block's position in the UI instead of the type of block. Because block positions aren't fixed in the UI (they move to accommodate newly researched blocks)- their hotkeys will change throughout the course of a play-through. This makes learning hotkeys impossible, and you also have to re-learn the blocks position in the UI to click on it instead.

-Editing the hotkeys is impossible to do for a single block. If you change one, you must change several. This makes structuring hotkeys in a meaningful way impossible.

I propose to duplicate the way RTS games handle their hotkeys.
StarCraft 2 is a great example. (Even 90's games like StarCraft 1 and WarCraft have better hotkey systems than Mindustry)

While editing the hotkeys in StarCraft is more complicated, their use in-game is fluid and comfortable. It's easy to assign a specific building to a unique key (a key which will only change if you edit it again).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

The current hotkey system is virtually useless and nearly impossible to customize. With an improved system, it will become much easier to select different blocks at will without using the mouse. Thus making the gameplay more fluid and enjoyable.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Katsute** [comment]
#6

**Comment by KK6DOC** [comment]
Personally I agree but because of it I use a custom program to use hot keys (so when I use the numpad keys it switches)
I have 1 to tit conveyer 2 to Thorium wall etc.

**Comment by bvcbvc** [comment]
he probably would have had it this way, but because of how the game is,  similar issues occur with mods, he would probably have to do massive changes to the game to allow something like this, but otherwise its quite a good idea

**Comment by cyrusduong** [comment]
I've thought of two possible feature adds/solutions...

1. Allow customizable hotkey delay time. This is ideal for new players learning the hotkeys and sometimes stumble over selection trying to remember the order or numbers they need to press. Then as they improve they can decrease the delay to complete actions more quickly. Similarly, for experienced players they decrease the delay as it sometimes can be annoyingly long when selecting things in succession very quickly.

2. Separate category and block selection. In addition to 1, by separating the category and block selection a user no longer has to access category using only number keys. Instead we could bind things like the following 

- `P` -> Power(?) Category
- `B` -> Conveyors/Belts/Sorters
...

For a user then to access their blocks it would be a combo of [B, 1, 4]. Instead of [4, 1, 4]. Or the similar.

And beyond 2. individual/customizable keybindings for each block would be nice, but they should be defaulted off/unbound.

**Comment by LeoSko** [comment]
Would be nice to have ability to bind whole schematics to hotkeys as well as single blocks.
