### ISSUE TITLE
Locus Needs to be Nerfed 

### ISSUE THREAD

**Issue by Tree-0** [Anuken/Mindustry-Suggestions#4114]
### Describe what you would like changed, and why.

Locus is unquestionably the most powerful tier 2, and pretty much the cheapest to produce, not requiring graphite for the t1 and not requiring tungsten as the merui factory does. After playing erekir PVP for a few weeks, Locus has become the only viable bulk unit to compose armies out of. It defeats other T2 units of equal or greater numbers without much contest and it equals the precept in dps, giving even T3's competition. 

### Describe the changes you want to propose. Include possible alternatives.

Locus should receive slight health and damage nerfs. Alternatively, Cleroi and Precept could receive some sort of buffs to make them less useless.  Cleroi point defense is not a strong enough ability to make up for locus just being far better in any confrontation, especially when the point defense can't even hit Locus shots. Neither is walking over walls, because right now all you have to do is station a few Locus on your side of the terrain to counter any mechs incoming.

**Comment by Larofeticus** [comment]
Remember when I said "If you just make one kind of unit win every match up*, then people will only use that."?

Well here it is, though instead of a hypothetical stell it's the current locus. Mobility doesn't actually matter in practice; map objectives are stationary and can be camped by locus. They're cheap enough to mass produce and defend *all* valuable objectives. None of the more mobile units have the stats, range, or any special ability to dislodge a locus camp*. 

They're also the best units for attacking because they've got so much hp/armor they can face tank all comparably priced defense while approaching the target. Walls in the way? Who cares. Use that best in tier DPS to remove them.

It took mere hours for all the good players to figure this out, and now everyone that wins does it by spamming locus factories or rushing with eludes before the locus factories can be finished.

**Comment by Garen7** [comment]
Hey I agree with the above stuff when playing on the hex server but can we get some feedback from people from other servers just to err on caution?

**Comment by Tree-0** [comment]
That's not a bad idea, but I'm not sure that any server rules affect Locus's cost and effectiveness compared to other units.

**Comment by Garen7** [comment]
@Tree-0 this is specifically referencing the these rule on that hex server that if units are in a hex that isn't next to an allied core they randomly start dying. most mech and ship units are designed for flanks/backstabs, so for example if I make t2 ships I cant just fly them into my opponents base since they will start dying even if my opponent doesn't build anti air. 

Also t2 mech's point defense turrets are still useful for attacking into enemy defenses and walking over walls help them hit flanks but neither of those are really problems on that hex server

t3 ships and mechs suffer from the same issues as above

t3 tanks get caught on the hex game mode's terrain often and end up entering fights in a single file line which from an RTS standpoint is a significant disadvantage

Of course locus still have very large stats and being easy to spam makes the original post a very real concern but we should wait for input from other servers since they might have people with other concerns that we wouldn't notice

**Comment by Larofeticus** [comment]
Another possible experiment: Take a campaign map, and silently replace all the Malis units and factories with locus and see how it changes the difficulty.

**Comment by laserman367** [comment]
I mean, it's logical that tanks excel at defending compared to other units. Isn't that the whole point of them? I haven't played any pvp but coming from the perspective of a campaign player, tanks seemed extremely weak compared to other units due to their low speed and no special mobility. The pack just died before they could get through the defenses most times

If you want to defend, why mass units rather than build turrets? I just slapped three breaches behind a large then small tungsten wall with a regen projector (and a sublimate to prevent tanks from pouring through a gap in the wall after taking out one turret) and it seemed to hold against 15 locusts pretty handily.

If maps don't play around the extra mobility of fliers/mechs that's on them not on the overall unit balance. You can easily make paths for mech units, you could make little pockets that can only be reached by flying units, etc.

**Comment by Larofeticus** [comment]
Go back to your memory of the campaign and think about the resource price
for the stuff involved. How many tanks were attacking you, and what was
their total cost compared to the total cost of whatever defense you had
wrecking it? How much higher in tech level was the defense? Oxide? Thorium?
Surge? Carbide?

I _very_ strongly suspect that the actual number of tanks was  much smaller
in resource cost. Now imagine how many more tanks would need to be added to
make it even, and if there were a human managing their movement and
attacking well.

In the campaign there is nothing matching resource amounts between the
player and NPCs. The mapmaker gives an arbitrary and unmatched amount of
stuff to the player and malis, and the attacks are set by timers, triggers,
and factories that malis didn't pay for.

To contrast that with pvp, the cost efficiency of every fight, factory, and
turret is a very large component of what determines the match outcome. In
that situation then locus for every purposes is what all the players that
win are choosing.

**Comment by laserman367** [comment]
> Go back to your memory of the campaign and think about the resource price
for the stuff involved. How many tanks were attacking you, and what was
their total cost compared to the total cost of whatever defense you had
wrecking it?

I meant from the aspect of attacking, planes were useful as you could flank around & attack spots without antiair (though the T2 planes have extremely short range so they're a lot less useful than others). Mechs could walk over walls so as long as you survived that long you could do some serious damage. Tanks just... died... I guess without the oxide for regen projectors static defenses will be a lot worse but in the time it takes to make 15 locus I imagine you can get a bit of oxide

**Comment by Tree-0** [comment]
> I haven't played any pvp but coming from the perspective of a campaign player, tanks seemed extremely weak compared to other units due to their low speed and no special mobility. The pack just died before they could get through the defenses most times

I think a lack of pvp experience skews understanding a little bit. Tanks are by far stronger than the other t2 options, and they are much more effective when you have a real player controlling how they attack. even when you are controlling units on an attack map, Campaign also has preset defenses that are far stronger than what a real player can make in the time it takes the other player to make x amount of units. 

> If you want to defend, why mass units rather than build turrets? I just slapped three breaches behind a large then small tungsten wall with a regen projector (and a sublimate to prevent tanks from pouring through a gap in the wall after taking out one turret) and it seemed to hold against 15 locusts pretty handily.

because units behind walls do a much better job of defending for a fifth of the cost, and they are mobile so they can defend multiple areas and go on the offensive, which is important in both attack and pvp.

**Comment by Tree-0** [comment]
> (though the T2 planes have extremely short range so they're a lot less useful than others).

It is usually more viable to power through the defense with armored Locus than it is to try and flank, partially for this reason. 

> Mechs could walk over walls so as long as you survived that long you could do some serious damage.

That's the problem... they're not so good at the surviving. Especially in the face of units that defend more efficiently than turrets.

>  I guess without the oxide for regen projectors static defenses will be a lot worse but in the time it takes to make 15 locus I 
imagine you can get a bit of oxide

You can definitely get some oxide, but regen projectors and whatever other oxide-level tech you can make is not enough to turn the tide of "Locus beats everything else"*

*provided you actually utilize the RTS controls that are now an integral part of the game

**Comment by Larofeticus** [comment]
How about, as a solution, locus attack is changed to target only ground?

**Comment by Tree-0** [comment]
That idea sounds good to me

**Comment by Glino-MES** [comment]
By making Locus unable to target air you also make Avert better in comparison, Which, really isnt a bad thing imo, as it wasn't a very usefull unit in the first place.

I think this is a good development, but it doesn't change the fact that Locus is just an extreme brute force. It has the dps of 152, 2100 hp (which is almost twise as much as other t2!) and 8 armor. Yes, its slow, unmobile and has a tendensy to drown. But its still a tank of 2100 hp and dps of 150 that you can make in, like, 4 minutes!

Compare it to Cleroi: it has 2 segments that can stop 94 dps each. One small issue is that their range is low and the bullets on Erekir tend to be fast. Also this guy is more expensive to build AND has only 1100 hp! Can the segments really block 1k damage in the lifespan of a Cleroi to conpensate? Doubt. Not to mention not all bullets are even affected by segments. Cleroi seems more adept at destroying buldings and has better mobility, but their low health makes Locus seem just better. In the time a Cleroi' would walk over a wall, Loci would destroy that wall.

In the end what makes the Locus so widely used is their DPS, their low mobility makes them get hit a bit more - that is true. 150 dps per tank! a group of just 5 can destroy Bastion core in 6.8 seconds, with armor in account. Balanced.

So if we are nerfing something i think its the damage, if locus didnt melt walls and other t1/t2 like it does now it would make the other 2 units seem like an actually viable choice. If we also make it ground-only, then the nerf would be a bit lesser, 36 to 30 damage per shot?

**Comment by moocowswag** [comment]
Don`t forget locus are also the longest range t2 unit. Imo let locus keep their tank and damage stats but early game range also probably needs a soft rebalance.

**Comment by Garen7** [comment]
Thoughts and opinions on the following changes?
```
Locus attack changed into a projectile
Locus damage per shot: 36 to 27
Cleroi damage per direct hit(not aoe): 2x20.25 to 2x24
Cleroi AoE radius: 23 to 26

(The AoE size change lets the AoE damage hit multiple locus since it can currently only hit one)
```

It would make it so that a cleroi army would still loose to a locus army but a mix tech army will win to the locus army but only if you have proper unit control, see the video below:
https://youtu.be/ZZjcS46Zf5M

this way it would be a strategeic decision between
1. do I want to attack over a terrain wall
2. do I want to spend more time controlling my army
3. do I want to spend more time building my base

The tests are using 8 locus vs 4 locus & 3 cleroi due to the reduced factory output of cleroi factories.

I can fill a spreadsheet demonstrating how this affects how other unit fights pan out if someone wants that also

**Comment by BloodRaven0** [comment]
All excellent suggestions. Making locus unable to target air and making their attacks missiles instead of hitscan are really creative ways to nerd them without actually nerfing stats, and will make for more interesting, tactical and varied gameplay. Although I wouldn't mind a dpa nerf either lol.
