### ISSUE TITLE
Allow the beta/gamma to pick up water

### ISSUE THREAD

**Issue by Devilsknock** [Anuken/Mindustry-Suggestions#4138]
### Describe the content or mechanics you are proposing.

So, unless I'm missing something. The only main way to put out fire is to deconstruct anything flammable or to use the two water related turrets. I think a less annoying and more involved way to put them out is to allow our ship to pick up water and have it create a large splash when dropped or that our weapons temporarily become a water hose until out of water.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Unless I really am just missing something, it adds a nice manual way to deal with fires and allows them to also be less devastating in the early game. Could maybe also make Mono's double as fire fighters where they beeline for water whenever a fire erupts throwing away their current cargo. Would give them another use besides just uncontrollable miners. That might be slightly too powerful and negate the usefulness of the water turret but if nothing else, I think our ship interacting with water would help greatly if that pyro/blast compound line gets hit by a bomber. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BloodRaven0** [comment]
Maybe Monos putting out fires would be too overpowered, but the player ship doing so manually would be kinda cool.
Although I don't know how picking up the water would work control-wise. Water is not an item to be picked up like, say, copper. Maybe a new button on water containers and pumps could do the trick. It would work similarly to picking items up from normal containers, and would be slower with pumps (because you have to wait for the water to be pumped before picking it up), and instantaneous with water tanks (provided there is enough water in them).
