### ISSUE TITLE
Possible V8 Content (Tantros)

### ISSUE THREAD

**Issue by ItsBlaze100** [Anuken/Mindustry-Suggestions#4211]
### Describe the content or mechanics you are proposing.

Being interested in Mindustry and it's unique technologies. I've thought of some cool features that can be added to the Upcoming V8 Update 
(Mainly Tantros Tech) 
The following possible features for Tantros are:
Booster Modules: 3 types 
-Factory: boost unit and Resource production
-Weapon: boost turret and support structures 
-Power: boost power production 
Size 2x2 (basic) 3×3 (advanced)
Note: these Modules are optional, meaning they act as a new type of Booster besides coolants and heat

Sector Generation is more unique, consisting of island, ocean and underwater sectors

Special structures called Liquid barrier and Liquid drain are used to drain water, reveal more base materials and vents for power and create room for infrastructure. Maximum barriers size is 40×40 and draining size 
(for each Liquid drain) is 15×15 around it. Enemy units ignore and never target Liquid barriers only. Units Can go over Liquid barriers. 

Power production on Tantros are Renewables that can be Tidal, wind or Geothermal energy with the possible reactors. 

Units: there will be 3 tech trees. Naval,  Air and Shark (Submarine) units with various new weapons such as Torpedoes, artillery shells, bullets, ocean bombs (mines) and radiation field (slowly damages enemy units)

That's all for now. These features comes from a player who has lots of knowledge of Mindustry and wants to further enhance gameplay 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

These features will add new unique structures, units and increases the various technologies, sectors and strategies used to capture sectors.

Like I said, these features are specifically for the Tantros Tech Tree for the possible upcoming v8 update and adds more strategie to deal with Ocean units on the New Water Planet 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by BloodRaven0** [comment]
There are some nice ideas here. Reading this inspired me to share my own vision for Tantros. Here are my ideas so far:

Units will have 2 types - Ground and Submarines ("air"). Each will have 2 trees - pure damage and utility/support.

-Crab line (Ground tank+dmg; can scale walls)
-Coral line (Ground gatherer/builder/repair/light dmg)
-Shark line (Submarine mobility+dmg)
-Dolphin line (Submarine light dmg/healer/shielder)

Combat units will require to be holding items to use as ammo, similar to turrets. Each unit will have a certain carry capacity that will enable it to fight non-stop for about 30-60 seconds before needing to restock. Units can be set to have a preferred ammo type that they will restock with automatically or if ordered to by clicking on a core or container.
Some units (mostly the utility/support units) may require energy, which they can get from batteries in much the same way. This will be used to mine, repair, build, charge shields or heal, as well as use energy-based weapons such as piercing lasers. Units can be set to recharge automatically. Energy will be displayed as a small yellow bar over the unit.

This will require building forward bases and outposts for recharging and resupplying if you want to push offensively. Core unloaders will make a comeback to make this easier (but not cross-sector resource and core schematic transfers like on Serpulo)

Since Walls can be bypassed by most units, they will only serve as bullet sponges. However, if an enclosed bubble of walls is built, there will be an option to build a "Dome Support" inside it that will close off the area and enemy units will not be able to enter it without making a breach in the walls first. When the dome is breached, the Dome Support will collapse, making entry possible. The dome will not block that team's units, and ducts/conduit bridges can pass through it normally. However, turrets and units will not be able to fire from inside a dome.

Domes could be drained of water by using specialised buildings. The larger the area the dome covers, the slower it's going to get drained, requiring more such buildings to speed up the process.
Certain buildings will be boosted or may only work in a dry environment. This makes it crucial to protect your inner domes, since it will take a while to repair and drain them in the case of a breach.

Most turrets (excluding some early game options) will require specialised ammunition (torpedoes) to fire. Those will be manufactured by factories, and could be used as ammo for high-end units too.

Power delivery will be made via wires that act similarly to bi-directional conveyors for power. This might make supplying lategame buildings with power, liquid and multiple item inputs clunky, so there will be a lategame alternative that acts like Serpulo's power nodes, however they will only work in a dry environment and explode if coming into contact with water (if the dome is breached).

Ducts will be present and will be the only way to get certain gases, required for crafting. Oxygen will be able to be extracted both from ducts (in the early game), as well as passively from the seawater. Oxygen will be used in much the same way as water is on Serpulo for boosting things.

**Comment by ItsBlaze100** [comment]
Interesting ideas. Let me balance each feature you suggested.

There will be a total of 5 unit trees. 3 are pure dmg and 2 are support. Each tree consists of 

- Crab Boats (Pure dmg) Naval Unit: Transforms to Ground unit
-Coral Crab Boats (Support) Naval Unit: Transforms to Ground unit
-Air units (Pure dmg)
- Shark Sub (Pure dmg)
- Dolphin Sub (Support)
- 
To make Tantros Unit trees more unique:
-

**Comment by ItsBlaze100** [comment]
#

**Comment by BloodRaven0** [comment]
Pretty awesome ideas. Depots could be a combination of batteries and vaults and replace both on Tantros.
Also another idea for a building - Sonar. This would have a different function depending on whether the map is at the surface or underwater.

-Underwater maps will have Fog of War enabled and sonars will work in much the same way radars on erekir do. However, they will also show enemy submarines and other units on the minimap in a much larger radius than their field of vision (think scathe range or slightly less).

On the surface there would be no Fog of War, but submarines will be able to submerge, making them invisible until they surface to attack ships or buildings. They can't be seen unless you have your own submerged submarine in range or have a sonar. 

This will create opportunity for interesting attack maps where you have to take out sonars to sneak by heavy defenses with subs.

**Comment by ItsBlaze100** [comment]
Interesting. For subs to enter submerged mode on ocean or island maps, there has to be an anti-sub Torpedo Turret. The turret only works when a "Sonar Radar" is in its radius but the attack range is half the Sonar Sadar's range

-The depot will be changed to Ammo Depot. Storing power and resources for "Only" ammunition purposes. Batteries and Vaults will most probably be separate but reinforced like erekir's vault

-Also when a sub is submerged, they act as stealth units meaning their weapons are disabled during submerging. Their only weapons that work are Torpedoes and the (Support Only) radiation field.

Any amazing feature you suggested will be balanced by me if needed

**Comment by ItsBlaze100** [comment]
To Extremely nerf air units, T4 and T5 Boats are able to produce T1 and T2 air units

-Change Depot to "Storage Bus" 
-Storage busses are able to Store only Items 
(Liquid Tanks are separate) 
-Apply a Weapon module to allow the Storage Bus to store power and resources in it can be used as Unit Ammo
-Bubble Projectors can't be used on land 
(Submerged sectors only). That's where Factory modules comes in. 

-Factories that are required to be in water to operate can be placed in deep waters instead of using a bubble projector 

-Electrolyzers will also be added to Tantros. Requiring water to produce Hydrogen and Oxygen, not Ozone

**Comment by Aiden910** [comment]
Interestingly, I'd begun developing a different concept of my own for Tantros in which there was a high degree of bio-technology. Also, my concept included different resources such as Iron and Steel due to Ferric Floors/Walls as well as Pink Ice Walls being in game at one point. Be this as it may, all of the ideas here seem pretty damn good and I wouldn't be opposed to them being put into the game if that was what was ultimately decided on.

**Comment by BloodRaven0** [comment]
@Aiden910 share yours as well, I'd love to hear them!
The sad thing is that Tantros may never be developed officially by Anuken, since he said he wasn't interested in making another planet.
This means that the community will have to do it as a mod or a fork.

I did some research on the history and types of naval mines and it could be a really nice and in-depth system that could complement a base's defenses. Serpulo's shock mines always seemed underdeveloped to me.

The basic type is the contact mine that is triggered when bumped into by a submarine or ship. It won't target ground units in underwater maps (there will be a different version of it for ground, called the floor mine), since it can be only set at a certain depth. Those will have a very small activation range, requiring units to physically touch them to trigger. This will make "wiggling" through a minefield possible, but micro-intensive. They also don't differentiate between friendly and enemy units, so use with caution. The mines will be visible only to their owner, unless the enemy has a minesweeper sub (from the support tree) that can detect and dismantle them (for their resources, no less!), or just shoot it from a safe distance that may set a chain reaction if they are closely laid.

Laying mines will also be done by a specialized minelayer (from the ground support tree) instead of the player ship - you can queue them, but not build them, instead minelayers nearby will go and lay them.

A more advanced type of mine will be the magnetic mine. They will have a larger trigger range, as well as explosion range, but will be susceptible to "mass minesweeping" by electromagnetic pulses that some subs will have (again, mostly the minesweeper and support tree). This makes them explode, but does not guarantee that the triggering sub will be out of range of the explosion.

The endgame mines will be torpedo mines - they have the largest range and have the added benefit of differentiating between friend and foe. When a target is in range, they will shoot a powerful torpedo at them. This missile can be shot down before making contact however.

**Comment by ItsBlaze100** [comment]
Let me Balance the Mines, Ammo and Generation and finally introduce some Power Generators 

-Land mines will be manufactured by T3 Coral Crab/Boat (Support) unit. After construction, the Land mines are stored in the unit, acting as Payloads. A landmine is 1x1 in size and it can cause a chain reaction if multiple are placed next to each other. Landmines can only be placed by the Player manually controlling it or by commanding it to randomly place mines on a patrol line 

-Ocean Mines will be Manufactured by T3 Dolphin Sub (Support) unit. Mechanicis are exactly the same like the explanation 
above this one 

-When a mine is placed, it will have an Arming time before it can work 

-Iron will be Called Ferrite

-Steel will be called Carbon Ferrite 

-Iron Ore can be found commonly on Ferric Stone 

-Coal Ore can be found commonly on Carbon Stone 

-Arkicyte Ore can be found commonly on Arkic Stone 

-Heat will act as a new Gas on Tantros. Can be extracted using Thermal Power Factories or Reactors. Heat will be used for certain factories and as ammo for a Tantros version of a Flame Thrower (Burning Status effect won't work for units in water) 

POWER PRODUCTION 

-Geothermal Turbine (Early-Mid Game)
-Wind Turbine (Early Game)
-Solar Radiator (Mid Game) better than Surpulo's (Produces Heat Gas)
-Tidal Wave Turbine 

-Uranite Reactor- Uses Uranium, Cryrofluid and Heat Gas to produce Lots of power. Explodes Violently and leave an Acidic Cloud for a period of time that damages all Unit when insufficient Cyrofluid is produced 

-Volcanic Reactor: Requires a Large Geothermal Vent, Large amounts of Water and Phase to produce Lots of power. Also provides Heat Gas as a byproduct. Explodes if too much Heat Gas is sustained in the Reactor, meaning you must use for Heat Gas than it Produces. 

GENERATION
-Island maps: An average map like  e.g (Wendswept Islands). Cannot Drain Protions of the Ocean in such sectors. Ores are already exposed 

-Ocean maps (No islands): Requires Liquid Drains and Bubble Projectors to create room for infrastructure. Reveals Geothermal Vents Ores, Hills and natural Walls (Basically a regular map with mountains but has to be revealed to show) 

-Underwater Maps: Core Produces a Large Bubble around itself for infrastructure. Vents, Ores, Hills and Steep Terrain (Walls) will be seen (Besause you are underwater) but need Bubble Projectors to Drill the Ores and use the Vents 

-Geothermal Vents are 3x5 

-Volcanic Cracks (Vents) are 5x5

A new block called the "Weapons Factory" produces Torpedoes Rocket Mines and such for Unit Ammo ONLY

**Comment by ItsBlaze100** [comment]
Today I'll be suggesting all New Tech for Tantros, with it's own custom resources and purposes (Changes May Apply). This is most probably the most polished content for Tantros. No further Suggestions for features will apply if Necessary 
( I mainly made this Issue, so that's why) 

RESOURCES 

-Metaglass (Starter Resource)
-Ferrite (Iron)
-Carbon Ferrite (Steel)
-Silicon
-Graphite 
-Thorium
-Phase Fabric
-Uranium
-Surge Alloy 

LIQUIDS/GASSES 

-Water
-Cyrofluid 
-Hydrogen
-Oxygen
-Nitrogen
-Thermal Gasses 

TURRETS 

-Riptide (Starter Turret): Fires clumps of Metaglass (Flak) at all enemies 

-Burst: Fires a burst of projectiles that explodes into smaller projectiles. Requires Power and Graphite 

-Erupter: Fires a continuous jet of flame at enemies. Briefly charges up before attacking. Requires Thermal Gas and Hydrogen 

-Sublimator: Fires Torpedoes at Naval Targets. Requires special Torpedo ammo 

-Twister: Fires 4 twisting bullets that explode on impact and has a chance to briefly stuns targets. Requires Thermal Gas, Nitrogen and Oxygen 

-Electron: Fires a Nuclear bomb that leaves behind an Acidic Cloud. Requires Uranium and Cryrofluid 

-Disrupt: Fires an EMP missile that Disables enemies in an area. Slowly damages enemies in the Turret's radius due to it being unstable. Requires Thermal Gas, Power and Surge 

Eliminate: fires a barrage of Homing Missiles and Fragmentary Bullets at all enemies. Requires Missile Ammo, Power, and Uranium 


DRILLS 

-Vent Extractor: Extracts gasses depending on the Vent its on 

-Fusion Drill: Requires Large amounts of power, Hydrogen and Uranium to Drill Large Batches of resources 

-Plasma Drill: Requires Lots of Thermal Gas and Power to Operate 

-Plasma and Large Plasma Bores will also be Added to Tantros 

-Liquid Drain: Extracts water from the Oceans. Requires power to incinerate 

TRANSPORTATION 

-Ducts and all it's variants 
(Router, Bridge, Overflow, Underflow) 

-Conduits and it's varieties
(Junction, Router, Bridge). Cannot transport Thermal Gas 

-Pressurized Conduits and it's varieties
(Junction, Router, Bridge). Capable of transporting Thermal Gas 

-Liquid Tank: Stores liquids or Gases 

-Pressurized Tank: Stores Even more Liquid and gas 

-Drone Bay: Contructs drones that can transport resources. Can travel above and underwater 

-Drop-off Point: Allows drones to drop off resources. Can be configured to drop a specific resource. 

-Capsule Cannon: Fires Larger Batches of items over long distances. Requires power and can be linked to other Capsule Cannons. Can Operate underwater. 

Phase Conveyer: transports Batches of items. Can be placed underwater 

WALLS 

-Metaglass Wall: Blocks incoming projectiles. Releases Frags of Shards when destroyed (Small and Large) 

Ferrite Wall: Blocks Incoming projectiles (Small and Large) 

-Carbon Ferrite Wall: Blocks incoming projectiles. More well Armored than Ferrite Walls (Small and Large) 

-Uranite Wall: Blocks incoming projectiles. Blocks energy and lazer attacks. Explodes Violently when destroyed (Small and Large) 

Shielding Wall: Blocks Incoming projectiles, Projects a force field that Blocks Enemies. Requires power
(Large ONLY) 

POWER PRODUCTION 

Geothermal Generator: Generates power and Thermal Gas from Vents 

Wind Turbine: Produces power from the Weather Conditions 

Solar and Large Solar Radiators: Produces Power from the Sun and produces Thermal Gas and a byproduct 

Tidal Generator: Produces Power from the Ocean Currents. Requires Hydrogen. 

Uranite Reactor: Produces Large amounts of Power. Requires Cyrofluid, Thermal Gas an Uranium to Operate. Explodes and leaves a Cloud of Damaging Gas when insufficient Cyrofluid is inputted 

Volcanic Reactor: Produces Heavy amounts of power and Thermal Gas as a Byproduct. Needs to be placed on a Volcanic Crack. Requires Large Amounts of Cyrofluid and Phase and power to Kickstart the process 

FACTORIES 

-Electrolyzer: Separates water into Hydrogen and Oxygen 

-Thermal Silicon Furnace: Requires Thermal Gas, Sand, Graphite and Power to produce Silicon 

-Phase Fabricator: Requires Thorium, Sand and Nitrogen to produce Phase Fabric. Produce Thermal Gas as a Byproduct. Requires power 

-Thermal Surge Smelter: Fuses Thermal Gas, Silicon and Uranium into Surge. Requires Power 

-Cyro Crystalizer: Produces large amounts of Cyrofluid from Water, Sand and Metaglass. Requires Power. 

-Heat Reactor: Produces Heat and Uranium from Thorium 

-Nitrate Collector: Uses power, Thermal Gas and a Nearby Wind Turbine to produce Nitrogen. 

-Steelworks Factory: Fuses Graphite and Ferrite into Carbon Ferrite. Uses Large amounts of power 

UNIT PRODUCTION 

-Naval Assambly: Constructs Naval Units. Can be used directly or moved into a Naval Assembly again for Upgrading. Requires power and Assembler Modules for further Upgrading 

-Submarine Assembly: Constructs Sub Units. Can be used directly or moved into a Submarine Assembly again for Upgrading. Requires power and Assembler Modules for further Upgrading 

-Support Factory: Constructs Support Units. Can be used directly or into Reconstructors for Upgrading 

-Support Reconstructor: Reconstructs Support units to the Second Tier. Requires Hydrogen 

-Support Fabricator: Fabricator Support units to their third and final tier. Requires Thermal Gas and Nitrogen 

-Repair Pulse Tower: Heals nearby units in a form of Pulsewaves. Requires Oxygen and power 

-Weapons Factory: Produces Torpedoes, Missiles and Mine Bomb for Units to use as Ammo 
(Unit Ammo are actually units and are also Payloads just like the Quell and Disrupt Missiles) 

-Depot and Large Depot: Turns units into Payloads 

SUPPORT 

-Pulsewave Mend Projector: Repair a Large area of damaged Structures. Mends structures in a form of a pulse wave that has a cool down after each Pulse. Requires Hydrogen. Optionally uses Phase to Double healing strength and pulse efficiency 

-Fragment Tower: shoots a Bolt that destroys enemy bullets in an area. Has a Chance to Briefly Stun enemies in radius 

-Storage Bus: Can store items and power. Can increase core Capacity and acts as a unit Ammo Supplier 

-Ruins: The first iteration of Tantros Cores. Contain a self repairing bubble projector when in or under water 

-Seaopolis: The second Iteration 

-Monument: The third and final Iteration 

-Bubble Projector: Requires power, Oxygen and nearby Liquid Drains to drain water and create room for infrastructure. Overheats If too much damage is sustained. Requires Water or Cyrofluid to maintain dry areas of the ocean 

-Factory Module: Boosts Material and Unit Production (Basic and Advanced) Requires Power and Hydrogen 

-Weapon Module: Boosts Turrets and Support Structures (Basic and Advanced).
Requires Power and Cyrofluid 

-Power Module: Boosts Power Production (Advanced Only). Requires Power and Nitrogen 

The Name of the Units and their purposes will be coming soon

**Comment by Aiden910** [comment]
Some of these ideas seem almost like copy-pastes of already existing things from other planets or almost completely outlandish in terms of plausibility. Don't get me wrong though, I think some of the ideas are great and all still. I just wanted to point out some of these things.

**Comment by BloodRaven0** [comment]
@Aiden910 Well, we're not trying to completely reinvent the wheel and make a totally different game here. Some of the things on Erekir are copy-pastes from Serpulo. And it's best to be ambitious with new mechanics and ideas, at least until you get to code them and hit a brick wall headfirst :D

**Comment by ItsBlaze100** [comment]
@Aiden910, Yes I do know that some structures are Copy-Pasted from Surpulo and Erekir but you must understand that Erekir also has some structures that are Copied from Surpulo with attributes that makes the same structures different from each other. If I were to create content that are completely new to Mindustry without any references, then coders would already struggle with the first object. That why some content are referenced to older content in the game to make things easier

-Tantros will have more Tanky Units, especially the Support only going till T3 and Buffer Turrets that can paralyze units and better. Also Cyrofluid will be easier to produce and power production will be more beneficial for more Power Hungry structures. Boats and Subs are well Armored (Like the Tanks on Erekir) and have an arsenal of weapons that makes them pretty deadly

Constructive Criticism is well accepted in this Issue. Just know that. I still have so many ideas on Mindustry's technologies
