### ISSUE TITLE
Natural Neoplasm in Editor

### ISSUE THREAD

**Issue by SyntaxErrorGuy7** [Anuken/Mindustry-Suggestions#4372]
### Describe the content or mechanics you are proposing.

Natural neoplasm woupd basically be just like natural water, slag, oil, cryofluid or arkycite, but you can place pumps over it to produce neoplasm. This neoplasm still spreads to nearby water containing blocks.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It could add some more variety to maps and allow for some interesting techniques including easier ways to drop payloads of neoplasm in the enemy base

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by genialnos** [comment]
neoplasm cant live without water

**Comment by octopuscaat** [comment]
then how does it survive in a liquid tank?

when neoplasm and other liquids like oil, water, slag, and cryofluid come out in a puddle and disperse across the terrain. 
for example, take a cup of water and pour it on a flat surface. does it stay there or disperse across the floor? 
the reason it stays longer is likely because it is more dense or whatever. 

personally i like this idea and have also wanted neoplasm tiles since it was released. although it probably wont be added as neoplasm has no use and is a negetive liquid. but i like neoplasm and it might be good for map makers. chances are if neoplasm tiles are added neoplasm may have a use.
