### ISSUE TITLE
swap the color of hydrogen and ozone

### ISSUE THREAD

**Issue by lokyinng** [Anuken/Mindustry-Suggestions#4415]
### Describe what you would like changed, and why.

swap the color of hydrogen and ozone
also, Electrolyzer should decompose water into hydrogen and oxygen, not ozone unless a build of high-energy ultraviolet rays is in the Electrolyzer

### Describe the changes you want to propose. Include possible alternatives.

swap the color of hydrogen and ozone
it does not affect the balance other than the color of those two gas

**Comment by Eclipse-04** [comment]
nerd reaction

**Comment by overdramaticpanromantic** [comment]
Renaming ozone should not be done for sake of not being tedious. The color swap, however, makes sense, as hydrogen is pink and oxygen is blue in many other games, and can prevent confusion. It takes like 5 seconds, too.

**Comment by itcannotbe** [comment]
What if we don't like being the same as other games?

**Comment by Anuken** [comment]
I usually don't comment on suggestions, but I'd like to point this out since I've seen it brought up several times:

- obviously electrolysis generates oxygen and hydrogen, but I see no reason why this block can't use UV rays or other processes to generate ozone as a second step *(why is this even hard to believe in a game where conveyors run without power?)*
- yes, the output ratios are off, but this was done for balancing reasons
- this issue provides zero justification for actually switching colors at all
- oxygen as an atom is almost universally depicted as being red, while hydrogen is usually depicted as white or blue - think of the H2O molecule
- we are talking about ozone, not oxygen gas, so I don't see why other games' depiction of oxygen molecules matters (it sure isn't breathable...)
- swapping colors for no particular this late in the game's life is extremely silly and would cause mountains of confusion for no good reason

**Comment by MEEPofFaith** [comment]
It can always be done for the funi next year
