### ISSUE TITLE
Let pathfind also work like the old pathfind

### ISSUE THREAD

**Issue by 3Circle** [Anuken/Mindustry-Suggestions#4483]
### Describe what you would like changed, and why.

The new pathfinder logic command is excellent but still attack logic doesn't work correctly because if the coordinates happen to be an enemy block it gives up. I can get it giving up with terrain, but it should be possible to make it pathfind to an enemy core without having to find an empty tile near the core to have the pathfinding work.

### Describe the changes you want to propose. Include possible alternatives.

If the coordinates fall over terrain don't attempt to pathfind.
If the coordinates fall over a block then at least *try* to pathfind to the location, like normal enemy pathfinding.

**Comment by octopuscaat** [comment]
i tottaly agree. this is super annoying when you want them to attack the enemy base but the enemy base cant pathfind there because there is enemy walls. one fix might be to pathfind (assume the pathfind is a line from the unit to the block for this example) to the location ignoring enemy structures (as if they didnt exist/is an air tile) and then say if an enemy structure is in the way of the pathfind, pathfind to the nearest block to the unit _that is on the pathfind_ and try to destroy it and repeat until it reaches its target.
