### ISSUE TITLE
Nerf Steam Generators

### ISSUE THREAD

**Issue by TagGamer555** [Anuken/Mindustry-Suggestions#4488]
### Describe what you would like changed, and why.

I would like for you to nerf Steam Generators, because it's one of the ways to make Sepulo more challenging and balanced.
I don't like how people "stack" those and fuel them up with coal to get a lot of power, it feels a bit too unfair for other generators.
![image](https://github.com/Anuken/Mindustry-Suggestions/assets/69044271/563d01c0-3c9f-48cf-9893-80860b0c64e6)

### Describe the changes you want to propose. Include possible alternatives.

Make so that Steam Generator has item duration of 60 ticks (1 second) instead of 90 ticks (1.5 sec), which will greatly reduce effectiveness of "stacking" Steam Generators.

**Comment by Yep-Nope1** [comment]
Клоун, не пиши сюда больше

**Comment by floppa-coder** [comment]
он БУДЕТ

**Comment by itcannotbe** [comment]
There are better ways of nerfing stacking steam generators that doesn't actually involve slashing their power output by a third.

**Comment by itcannotbe** [comment]
Also, if you want a harder challenge, just erekir.

**Comment by RandomInsultedCoder** [comment]
good idea

**Comment by iceDragonso** [comment]
imagine saying staking steam well stacking combustion and pyros isn't borken even tho u will make less of them but the power output is still higher and 1st generator for erekir is basicly cheap asf and if ur saying to make 2/3 the time of the original coal have more burn time than spore already since spore water schems and if u use coal is usally less efective power output is lower
