### ISSUE TITLE
Add 'unit' instruction in setProp on world processor

### ISSUE THREAD

**Issue by Intervection** [Anuken/Mindustry-Suggestions#4497]
### Describe the content or mechanics you are proposing.

The 'unit' instruction changes the current unit to a new one, like changing from dagger to corvus, or gamma to oct.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Adds more stuff on setProp. When controlling a unit, instead of forcefully killing the player's unit and spawning a new one, you can just change the unit instead, which prevents players from respawning on core due to death.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by rekokoro** [comment]
Isn't better just to use setprop unit to forcibly transfer player control from one unit to another rather than spamming new units id for every occasion? 

like
spawn unit alpha#0001
fetch player id 0
setprop unit player alpha#0001

so player'll result up in selected unit that has been spawned rather than overwriting lot of stuff in unit class.
