### ISSUE TITLE
Moving some pc features to mobile that aren't presented yet

### ISSUE THREAD

**Issue by timich5555** [Anuken/Mindustry-Suggestions#4558]
### Describe the content or mechanics you are proposing.

These features are:
 - Freecam (or pan in PC) 
 - Pausing the building process
 - Upgrading conveyors
 - Rotating conveyor belts (like if they were →→→→ to ↑↑↑↑) 
  Probably more. 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

 - Panning may help you plan the base in one place while constructing in the other so you can save time. Also you could control your units while standing on base. 
 - this can allow you to mine materials at the beginning, when you barely have any. Currently, any planned building while force you to stop mining resources, which makes constructing even longer. 
 - Doesn't need explanation, i guess... 
 - This will help you in creating schemes, so you don't need to click on every single tile to place the conveyor with right rotation - just make a click (or other way to do this, hold for example) to rotate every. 

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by itcannotbe** [comment]
Freecam for mobile can't be added without adding more buttons to the screen which is cluttered already.

**Comment by Rovstam** [comment]
Yes router is the only way.
As an android player (i cant play much because of my low undeveloped wealth), the only thing that desperately needs to be added is that pause on build.

You do also need the Select all units, which one doesnt need to give a reason as to why to add but many questions as of why it isnt implemented.
Maybe low backend engineers? Its impressive they managed to port the game.

But seriously. Assess this god damn thing. Its not fair that stuff with a keyboard even as small as they seem give such humongous advantage. Want to mine copper? Then say goodbye to your building plans, because i dont feel like it!.

I also have posted about this. Still waiting.

**Comment by itcannotbe** [comment]
Select all units is a dumb idea.

Not all units are offensive units.

Select all of the same units exist though.

**Comment by Rovstam** [comment]
But then the question arouses... Why is it on PC and not in android.
I guess lack of general engineers and playtesters.

Just add it. Don't complain. I can't comprehend why would you argue and give reasons on NOT no implement such a feature...

----------Rethorical situation that can possibly happen in any ungiven moment whilst you play Mindustry----------

You are being attacked. Your forces are being destroyed, and your units have to be micromanaged. Oh, turns out you play on android. Then you can't:

1. Select a single specific type of unit unit in a ball of units
2. Select all units without HAVING TO zoom out and spend precious seconds pushing your finger against the screen and moving in 45° clockwise. Waste of time.
3. Select all unit factories without having to click each individual factory, get to your destination, unclick on the command mode, select next factory, because, *no*. Why would you want tht? LMFAO!!.
4. Start building and pause because you need it for some reason we can't discuss here. Again, why would ANYONE want to have this! It doesn't even make sense!!! Hahaha!!... FL

All of which you can do in pc.
You know, if you had to port the game for getting more players AT LEAST try to prioritize the things many, many many players have asked and PLEAD to be given, and if your team can't get to it, why in the first place you HAD to port it to android? As many popular games do, keep yourself in what you can afford and will actually care of updating.

I know what you are going to say. Don't say it. Just add the god DAMN feature and we good. Your team is just losing playerbase which = NO GOOD.

**Comment by Rovstam** [comment]
Lol sorry for being so rough. I am really pissed that this issue is still on.

I don't want the game to be taken down: I want it to thrive.

**Comment by itcannotbe** [comment]
In a normal pvp game with decent people involved you don't even do that.

Even on PC.
