### ISSUE TITLE
Hidden Setting to make the max schematic size higher using a slider

### ISSUE THREAD

**Issue by mse-k** [Anuken/Mindustry-Suggestions#466]
**Describe what you would like changed, and why.**

suggestion is in title, and it should be accessed by some small button in the corner with advanced setting appearing when you click it

would be cool because right now i have alot of multi part schematics because they were too big for the current limits, some pixel art or huge cool builds that are annoying to have to store in 2 or 4 parts that just add more garbage in the way of actual useful schematics

**Describe the changes you want to propose. Include possible alternatives.**

all described above, possibly a way to put folders of schematics that way i can shove all the garbage ones in a folder so i can reach the more useful ones faster, that wouldnt fix it taking a while to place all the parts of them though

**Comment by Anuken** [comment]
Schematics are limited to 32x32 because larger sizes cause lag. The limit won't be changed unless that is solved at some point, and there's no reason to make it a hidden setting if/when it is.

**Comment by DeltaNedas** [comment]
yeah, this isn't like with maps where you can change it and have no problems, pressing T causes crazy lag with just a 64x64 limit

**Comment by IxGamerXL** [comment]
> Schematics are limited to 32x32 because larger sizes cause lag. The limit won't be changed unless that is solved at some point, and there's no reason to make it a hidden setting if/when it is.

I know I know, it's one year ago, but hear me.

I'm pretty sure we have that one gamer out there with beefed ram and all, and secondly, it's probably better if you remove *final static* from Vars.maxSchematicSize, that way we can edit it to any size we wish, through Dev mod or through mods in general. It's not really neccessary to make it impossible to edit after compilation, since the variable's Final and Static keywords are the things keeping us from just editing our copy size.

Unless it breaks, there's no need to lock the maxSchematicSize variable from us, there isn't really a setting that enables you to change the maxSchematicSize ingame without mods, so allowing us to change it successfully would be helpful.

**Comment by buthed010203** [comment]
> I'm pretty sure we have that one gamer out there with beefed ram and all, and secondly, it's probably better if you remove _final static_ from Vars.maxSchematicSize, that way we can edit it to any size we wish, through Dev mod or through mods in general. It's not really neccessary to make it impossible to edit after compilation, since the variable's Final and Static keywords are the things keeping us from just editing our copy size.

Its not the ram usage, its the cpu usage. The game is largely single threaded and the way that schematics are currently implemented is super inefficient. They check validity against every plan the player currently has resulting in exponential increases in cpu usage... a 64x64 schematic being selected with another one already in the build queue means 16,777,216 validity checks. Whats even worse is that those checks are run multiple times per frame... This will be less of an issue when v7 comes out as the validity checks are only run once per frame and their results are reused plus the code inside of the check has been optimized to less than `schemSize^buildPlans` via a quadtree

> Unless it breaks, there's no need to lock the maxSchematicSize variable from us, there isn't really a setting that enables you to change the maxSchematicSize ingame without mods, so allowing us to change it successfully would be helpful.

iirc `static final` vars are slightly more optimized when compiled but i think the main reason is because he doesn't want people using larger schematics: "frankly I don't even want to encourage large schematics" "larger schematics will just lead to more art spam and more templates, which I don't want to encourage"

If you're really that keen on having larger schematics, afaik there is a mod that already does that. There are also alternatives like making your own custom client or just using foo's. If you want to do evil things, you can also use a custom ClassLoader to load your own `Vars.java` instead of loading the base game's but that seems excessive.

**Comment by IxGamerXL** [comment]
> If you're really that keen on having larger schematics, afaik there is a mod that already does that.

The only mod I could find that does that is in v135. I need one that supports 126.2.

**Comment by buthed010203** [comment]
I suppose you could write your own or just use a client then
