### ISSUE TITLE
Have different formation minimum speeds for hovering and naval units, ground units and flying units

### ISSUE THREAD

**Issue by broganeuquoixe** [Anuken/Mindustry-Suggestions#4933]
### Describe what you would like changed, and why.

Since these units already phase out and separate from each other I'd suggest having 3 different minimum speeds that units in a formation can go at. This will also help avoid cases where fast units almost come to a stall because of a small group of slow units that got accidentally selected

https://github.com/Anuken/Mindustry-Suggestions/assets/161990992/3e3bed73-bdc6-485a-b236-7ff25a83b86e

### Describe the changes you want to propose. Include possible alternatives.

I therefore suggest having 3 separate minimum speeds per formation, one for flying units, one for hovering and naval units since they are not very effected by floors (only case i can think of is naval units on tar) and one for ground units.

**Comment by jehosula** [comment]
maybe an option to disable it?

**Comment by S0meM** [comment]
The thing is that normally you want all of your units to arrive at the same time when they are attacking, and so that was probably put in to keep them generally grouped. Removing this would make your light and fast units get obliterated before your heavy units who can take hits arrive. Though I don't have any complaints if it is optional.

**Comment by broganeuquoixe** [comment]
https://github.com/Anuken/Mindustry/issues/9686#issuecomment-2028076678
https://github.com/Anuken/Mindustry/commit/d4abcc91efb981411a736c6a658268645e6d0c4d

Anuke just straight up removed minSpeed so I guess this suggestion is not relevant anymore
