### ISSUE TITLE
Multi player change

### ISSUE THREAD

**Issue by Mememan2085** [Anuken/Mindustry-Suggestions#4954]
### Describe the content or mechanics you are proposing.

I have an 💡 instead of having to on the same network just make it so you can add friends then you can play with them like in minecraft and be able to add friends on ministry 

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

You don't need to be on the same network to play with friends

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Slotterleet** [comment]
Probably won't happen because this proposal will depend on servers which will have to be run 24/7 and will need money to run. Considering the fact that Mindustry is a completely free game outside Steam and iOS, the developer pretty much only makes money from player donations (yes, Steam version is technically a donation as well because PC version is available in itch.io and GitHub for free as well). This will probably be not enough for this kind of thing.
