### ISSUE TITLE
Make server-side sending custom sound

### ISSUE THREAD

**Issue by meohent41zhead** [Anuken/Mindustry-Suggestions#5087]
### Describe the content or mechanics you are proposing.

You can sending sound to player with:

`Call.sound(player.con, Sounds.buttonClick, 100000000, 1000, 1000),`

But you cant:

`Sound sound = new Sound(dataDirectory.child("sounds/audio.wav"));`
`Call.sound(player.con, sound, 100000000, 1000, 1000)`

Why? It system send a packet but cannot create this packet lol.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

JUST MADE IT ASAP lol :v

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by camelStyleUser** [comment]
so you expect to be able to transfer 7217412 bytes every time just to play your sound???????

**Comment by camelStyleUser** [comment]
system sounds can be identified with 8 bytes

**Comment by camelStyleUser** [comment]
at most

**Comment by camelStyleUser** [comment]
here you will have to transfer the entire wav every time

**Comment by camelStyleUser** [comment]
a pretty bad idea, dontcha think

**Comment by camelStyleUser** [comment]
and the server doesnt have any way to save sounds

**Comment by camelStyleUser** [comment]
its backend literally doesnt support that

**Comment by SITUVNgcd** [comment]
WOW! "Good idea".
Well not!

**Comment by meohent41zhead** [comment]
> so you expect to be able to transfer 7217412 bytes every time just to play your sound???????

why not :v. Make new content fun

**Comment by Kieaer** [comment]
To refute, I hate people living in this repository.
https://github.com/Anuken/Mindustry-Suggestions/issues/3827
From a server developer's point of view, this feature is very useful, but the fact is that many features other then this suggestion have not been implemented due to people always being critical.

The implementation method is simple, but at present, even if some people makes a PR, there is a high probability that anuken will reject or ignored.
Even if it is a clear QoL PR. ex) https://github.com/Anuken/Mindustry/pull/8891 https://github.com/Anuken/Mindustry/pull/7603
