### ISSUE TITLE
Enemies target derelict buildings instead of Cores

### ISSUE THREAD

**Issue by 1justsomeone1** [Anuken/Mindustry-Suggestions#5358]
### Describe what you would like changed, and why.

When Core Capture enabled enemies can attack Derelict structures to capture their Core. The problem is that some units target specific derelict structures instead of cores (Flares attack energy sources and etc). This can look strange at maps with Core capture rule and decorative derelict buildings

### Describe the changes you want to propose. Include possible alternatives.

Make units ignore all derelict structures except for their cores.

**Comment by 50275** [comment]
https://github.com/user-attachments/assets/ad19c642-6dfb-4e0f-913a-d26a562b03be

**Comment by 1justsomeone1** [comment]
> 2024-12-06.01-42-30.mp4

What

**Comment by 50275** [comment]
Since you can convert any non-core derelict buildings to your own team (not within another team's core nobuild radius), any map that uses such derelict buildings is designed badly. What purpose do you even have, placing derelict buildings anyway? They won't do anything. Although the game doesn't show it, core capture is on.
