### ISSUE TITLE
Making payload transport useful

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry-Suggestions#553]
**Describe what you would like changed, and why.**
Right now, the payload transport system (payload conveyors, payload routers) is pretty useless, mainly due to the very exact nature of these systems, and their slow speed. Currently, there is no real reason to use a payload conveyor or payload routers (unless moving a naval unit to a reconstructor chain),  mainly due to their slow speed, inability to connect well (as in they have to be perfectly aligned), the fact that they can't push units, and the fact that they can only be used on low tier units. The fact that there is nothing they can go into except reconstructors, which are already normally chained makes the system even worse. There is no real purpose for it right now in any gamemode because of it's heavy limitations.

**Describe the changes you want to propose. Include possible alternatives.**
What I am proposing, first of all, is to change payload conveyors to be more like normal conveyors, instead of the super slow single unit movement they currently have, they should be changed to move at a continuous speed, and be able to carry multiple units, as well as receive a speed buff. Another part of this would be making it so that you can have a conveyor inputting between two conveyors, or having some kind of "corner piece" of some sort to properly align it between conveyors. Along with this, there should be more logic blocks for the payload conveyors (IE junctions, overflow gates, underflow gates), which shouldn't have the same chaining restrictions as normal logic blocks. Something that would be useful but not really that required as well, would be having a higher tier payload conveyor for tier 4/5 units, which would be powered (like the conveyors would need power). This whole thing should also implement unit movement when an actual alive unit is standing on a payload conveyor in the same way that a normal conveyor does it but faster, this will make the payload conveyors useful for funneling groups of units, which is what regular conveyors are useful for right now.

Second of all, there needs to be more blocks that take input from payload conveyors, like some kind of bridge/mass driver sort of transport system, or a slingshot for air units, making the payload transport useful to move units beyond the defense lines of your base, or to launch air units in a direction.

Another concept that would be interesting to look at is the one where using the block factory, payload conveyors could move containers and fill them with items, and then unload them later on, a heavy, large item transport system like that would be useful to have in game.

All in all though, if the stuff I propose here is implemented, there should be a new build tab for "payload transport", as if it stayed in the normal build tab, it would cause that tab to be cluttered and hard to find stuff in, and even if nothing here is good, it would be nice to have a payload transport overhaul to make the whole system have a more proper use in game.

**Comment by Anuken** [comment]
As I see it, there is currently no reason to use payload conveyors *because there's nothing to move with them*. Even if they pushed normal units, I don't really see anyone using them for that purpose - you can just command units to rally or walk around you instead. 

> there should be more logic blocks for the payload conveyors

I *very much* do not want to make an entire new set of transportation blocks for this, especially considering nobody would have a use for these yet. Omnidirectional payload bridges could become needed at some point, but everything else? No.

> having some kind of "corner piece" of some sort to properly align it between conveyors

This seems very niche, and could be handled by the bridges mentioned above instead.

> a higher tier payload conveyor for tier 4/5 units

Yeah, no, I'm not adding 7x7 / 5x5 conveyors, that would be ridiculous. 3x3 conveyors are already pushing the limits as is.

> this will make the payload conveyors useful for funneling groups of units

Will it, though? Titanium conveyors may be slightly more expensive when spammed, but they take up far less space, and can can be used with much higher precision.

> payload conveyors could move containers and fill them with items, and then unload them later on

That's what the (hidden) block loader/unloaders already do. Problem is, I don't see that method of transport being too useful, because most maps are relatively small and mass drivers can already launch things in bulk.

**Comment by Syncinus** [comment]
In my opinion though, stuff like logic bridges and stuff would become useful if payload conveyors moved like normal conveyors (though they would be better moving like plastanium conveyors), and having a proper connect ability without perfect alignement, a corner piece wouldn't actually be too useful, I agree, but them merging from inbetween at the least would be nice. I think it's very fundamental though for them to move like normal conveyors, the current way they move makes them very useless because most of the time unit walking is way faster. Bridges would actually make them somewhat useful, as you could deploy units past a defense system, without having to make holes in it, which is why I think it's important to have bigger conveyors for these so that you can do that with T4/T5 which is what most people are going to be making by endgame anyway, and getting to T4 isn't very hard, and your going to want to move those past your defenses. Them moving like normal conveyors would also be useful in making logic blocks good, because it would allow you to take multiple unit factories, and route them through multiple reconstructor chains, basically allowing for you to have multiple T3 unit factories route into a single T4 factory, I guess only payload router is really truly needed though, but a junction would also be useful for some cases, but not really too fundamental. Really most of my suggestions here are only useful if the way the conveyors move is changed, as that is what I think is the most important change that would have to happen to make payload conveyors useful.

**Comment by Anuken** [comment]
> logic bridges and stuff would become useful if payload conveyors moved like normal conveyors

What's wrong with the way they move? The movement is just visual interpolation. Even if I made it linear, they'd still be *slow*. What you actually want is faster speed, which is just a configurable number unrelated to behavior or similarity with "normal" conveyors.

> unit walking is way faster

What's wrong with walking places? I think making units walk places instead of using conveyors the most of the way makes perfect sense.

> take multiple unit factories, and route them through multiple reconstructor chains

You don't need any advanced transportation for this, and it wouldn't help. You can just arrange the reconstructors to take multiple inputs; it's compact, and no intermediate transportation is required.

> Bridges would actually make them somewhat useful, as you could deploy units past a defense system, without having to make holes in it

Okay, I admit this could be a valid use case, but just barely. There are alternatives to bridges, such as:
- Loading a bunch of units into a carrier and dropping them near the enemy base
- Doors
- Just having a 1-tile path where units come out (no, this should not compromise your defenses)

Usually, the units you should have trouble getting over your defenses are not those that can be put on conveyors on the first place.

Bridges will need to be added eventually, but transporting units over walls is nowhere near enough of a use case to make the whole system *useful*. Conveyors and mass drivers are necessary because you have a *certain resource* at *a constant location* that must be transported to a different location (usually, *your core*). This scenario does not apply to payload conveyors, because you can stick all your payload-related factories right next to each other with no consequences.

**Comment by Syncinus** [comment]
Due to the way the 6.0 collisions work, you can't really make a 1-tile path unless your using the lowest tiers of units, which most defense systems won't be using. And then using a carrier will basically just force you to have to take control of said carrier, and move stuff with it. By making it work by normal conveyors, I more mean that they would be able to have multiple things on them, instead of a single unit per conveyor. By multiple reconstructor chains I mean higher up ones, as a tetrative reconstructor for example is very expensive to build, and very expensive to feed, so it would make sense to try and route multiple things through it, that already normally happens anyway by just deleting the initial unit factory, and then replacing it with another one and freeing all upgraded units.
I guess most of this stuff would only be useful for higher tier units, what I think would be reasonable is only having big bridges to move higher tier units instead of conveyors, which wouldn't be insane in the way that a 5x5, 7x7, or 9x9 conveyor would be, I would say that's decently useful for things like reign which would be the unit type that would be a pain to get through your base, especially with the unit pathfinding getting stuck on walls all the time.
I guess most of this stuff is basically just a different way to do the same thing, but in some cases I would say it could be useful, especially since right now the system doesn't have any purpose, so just giving it some kind of useful functionality would be nice.

**Comment by Anuken** [comment]
> you can't really make a 1-tile path unless your using the lowest tiers of units

I ended up taking the easy way out and making everything have 1x1 tile hitboxes some time ago, so this isn't relevant anymore.

> I more mean that they would be able to have multiple things on them, instead of a single unit per conveyor

Sure, you might be able to pack more daggers onto a conveyor if it supports multiple items. However the amount gained will be relatively small, and it won't really matter, because daggers and other smaller units that can be packed onto these conveyors are able to just... walk.

> And then using a carrier will basically just force you to have to take control of said carrier, and move stuff with it

Yeah, but for higher tiers you don't need to do it often.

> By multiple reconstructor chains I mean higher up ones, as a tetrative reconstructor for example is very expensive to build, and very expensive to feed, so it would make sense to try and route multiple things through it

So why not just directly attach other reconstructors to it? The alternative is 7x7 conveyors/bridges wasting a whole lot of space in your base. Nobody is going to do that.

> only having big bridges to move higher tier units instead of conveyors, which wouldn't be insane in the way that a 5x5, 7x7, or 9x9 conveyor would be

I disagree, it's still insane to have blocks that big, especially considering they won't have any conveyors or corresponding transport blocks with them. It's very inelegant design - why make several bridge block variants just to transport 3-4 different types of units in *very* specific situations?

> useful for things like reign

Okay, but how fast will you be producing reigns? Why not just use payload units? Sure, it's manual, but invasions should be activated manually anyway.

> but in some cases I would say it could be useful

As I said before, it's not enough of a use case to make the whole system useful at all. Even if e.g. 7x7 bridges were to implemented (*which they won't*), it would be the bridges that would be useful, not typical payload conveyors/routers.

**Comment by Syncinus** [comment]
What's even the purpose of the system then, as there seems to be none. I guess now that the hitbox is 1x1 tile again it isn't going to be as bad of a problem to move big units like reign.

> Payload units

What do you mean by payload units? like dagger/mace/fortress? most bases can't be raided by those, and that entire tier is kind of useless due to lack of ability to spam them anymore, and fortress is significantly weaker then spiroct, but that's a different issue, and spiroct doesn't need this kind of transport anyway, it really only affects ground units.

My suggestion here is just to give the system a usage, even if it's not very practical, and even if it is just another way to do the same thing, it could have a use, and in general just be "cool". I don't really have any "good use" for it, but right now it has absolutely no use, so it would be nice to have 
_something_ that it can do, even if it isn't very practical. If there were giant bridges, they should have a huge range for moving stuff from one end of the base to the other, that does have some kind of "use" in moving a big group of units to another part of the base to defend or something like that, but the units would need some kind of thing to trigger them to move into the bridge, like maybe it counting as walkable terrain? and then having said bridges being connectable to multiple other ones, like power nodes. Which I guess would be useful for a few select scenarios, such as moving units across water, or as I said earlier, moving them across the base. I don't think it's too insane to have a bridge of that size, some mods add some insanely huge blocks, but those aren't super useless. I think the best semi-practical use for this system would be long range transport though, via bridges, as that would at least be used in watery maps, or to move stuff between bases. Though it might not be a really really good use, it would still be _used_ in some scenarios, which would at least be some kind of purpose for the system.
