### ISSUE TITLE
A mod maker._.

### ISSUE THREAD

**Issue by Joshwelyt** [Anuken/Mindustry-Suggestions#603]
A mod maker or atleast just a something to do the hard things on making a mod like scripting
Cause some ppl needs to learn scripting before they can make a custom thing or whatever idk 

1. - [ x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x ] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [ x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by itcannotbe** [comment]
1. Why did you murdered literally half of the template?
2. HJSON Modding is easy as fuck. It doesn't get easier than that. Unless your a (redacted)

**Comment by Joshwelyt** [comment]
Ok so here idc about those modding I'm just worried to those ppl that don't understand scripting

**Comment by Gdeft** [comment]
no

**Comment by XEN0PHIL** [comment]
:groundzero:

**Comment by gelo2801-dot** [comment]
Thiz should exsist what about the people who dont know how to code?

**Comment by itcannotbe** [comment]
HJSON exist for people who don't know how to code.

**Comment by scarf-generic** [comment]
I dont know how to code, im not complaining. If i really wanted to make a mod, instead of asking the game dev to give me a set of training wheels i would try and learn whatever language needed to make mods. From what itcannotbe has said, it sounds like the language is extremely easy to learn. If you care enough about making a mod, learn how.

**Comment by Gdeft** [comment]
> Thiz should exsist what about the people who dont know how to code?

Then they should learn. Putting values on keys or fields is easy enough for people who are able to read. JSON is easy enough and already at the simplest form of modding. There's even HJSON that simplifies the JSON syntax to make it easier for people who don't understand how.

> Cause some ppl needs to learn scripting before they can make a custom thing or whatever idk

That's the point of scripting, you have to at least learn to understand the basics. Any modding tool for scripting won't be able to help you to do "hard" things because they are limited and will always be. If you don't want to know how JS works, then don't use it.

If you *really* need one for some reason, someone made a modding tool for Mindustry [here](https://github.com/Paulao17/MindustryModCreator).

**Comment by DeltaNedas** [comment]
this was already suggested and is a very bad idea
any idiot can learn javascript

**Comment by DeltaNedas** [comment]
also this already exists, it's called having hands and a text editor

**Comment by stuffyAI** [comment]
> any idiot can learn javascript

bold of you to assume that one wants to learn javascript :D

**Comment by DS-3K** [comment]
> * Why did you murdered literally half of the template?
> * HJSON Modding is easy as fuck. It doesn't get easier than that. Unless you're (redacted)

.lua modding is way easier, have you ever modded forts?

**Comment by unjown** [comment]
> 1. Why did you murdered literally half of the template?
> 2. HJSON Modding is easy as fuck. It doesn't get easier than that. Unless you're (redacted)

not for everyone

**Comment by gelo2801-dot** [comment]
Ok ok i get it, now please stop?

**Comment by DS-3K** [comment]
Good sir please edit in the full template and your sin will be forgiven <3

**Comment by hadron13** [comment]
> this was already suggested and is a very bad idea
> any idiot can learn javascript

truth
