### ISSUE TITLE
(6.0) New building: Biodome

### ISSUE THREAD

**Issue by Jornker** [Anuken/Mindustry-Suggestions#634]
**Describe the content or mechanics you are proposing.**
A building that acts like a sort of "weather force field" that blocks all weather in a radius, Stopping things like sandstorms and spore storms, so you can see, and are not being pushed around a ton

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Weather (usually sandstorms) can be somewhat annoying, a way to block it in certain area could actually make way for some more intense weather that might actually effect buildings and units in a negative way. Even if you keep the weather as is, please make a way to block sandstorms/sporestorms and other weather, as they are very frustrating to play with.

**Before making this issue, replace the spaces in the following boxes with an `X` to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by RogueRedHawk** [comment]
This is relevant to #610 of course. I definitely think this can be a good solution. Sandstorms (and storms in general) have the opportunity to introduce a unique challenge to the game. One was I can see this being useful is positioning vital resources in the dome so they can be accessed during storms, prioritizing those things over less important ones. Additionally, a reliable way of avoiding the storms makes dealing with them strategic rather than just simply annoying.

Another thing related to storms is they could decrease in intensity in spaces confined by walls or terrain, so you don't need access to the biodome to avoid sandstorms (although the biodome wouldn still be an upgrade).

**Comment by here-be-username** [comment]
An simpler idea to avoid having to add another block: Just have force projectors nullify weather in their range. After all, if they can eat literal bullets, why not also let them stop wind? (And stuff carried around in the wind)
