### ISSUE TITLE
Make Mono (mining) ships not cost anything except energy to create

### ISSUE THREAD

**Issue by LuckyLMJ** [Anuken/Mindustry-Suggestions#754]
Mono ships should cost only energy to create, like it was in v5.
The air factory could be slightly cheaper to create, to keep in line with v5's Draug factory. The Flares from the factory could also be locked behind a higher research then the monos, to make it more balanced.

**Comment by potatoisagender** [comment]
I actually like it how it is. Draugs were too easy to spam. Also rip template.

**Comment by itcannotbe** [comment]
Beside killing removing the template, you just suggested to make them OP once again.

**Comment by Quezler** [comment]
> OP

you're still stuck with the unit limit though

**Comment by Syncinus** [comment]
I agree with this though, I guess it would work. The problem is that it means that you don't need anything to produce the initial unit, on higher tiers as well. I feel like this would only work out if there was a new mining branch of units or something like that, because right now it will be very OP.

**Comment by bsjohnson20** [comment]
Perhaps having the monos free would be good as they don't exactly mine the higher tier ores just copper and lead.

**Comment by potatoisagender** [comment]
still really broken. The whole point is that they cost materials to manufacture, by just making energy you could place down one factory and boom, free monos.

**Comment by sample-text-here** [comment]
I had an idea like this: Split monos into a different mining branch. This would
1. Make it easier to implement a t2 mining drone
2. Let mining drone base cost be cheaper while still making polys/other support drones more expensive

Although the base cost would be a lot, it would still constantly require materials to make (otherwise it would be op)

I think a good mono cost would be 10 silicon 10 lead and to bump up support drone cost to 30 silicon 15 graphite

**Comment by bsjohnson20** [comment]
Hmmm maybe a separate tree for monos so that instead it could mine higher level ores and maybe later when it's a high unit like T5 maybe it can manufacture alloys and stuff

**Comment by sample-text-here** [comment]
> Hmmm maybe a separate tree for monos so that instead it could mine higher level ores and maybe later when it's a high unit like T5 maybe it can manufacture alloys and stuff

That's what I meant by "t2 mining drone". t1-3 could mine copper and lead, then also titanium, then also thorium, each with a slightly faster mining speed than the one before it. t4 and t5, I have no idea. When you said "manufacturing alloys", maybe a t4 could mine sand and coal, and slowly make silicon?

**Comment by unjown** [comment]
the point why Anuke made mono require silicon is because ur sayin a airblast drill (on copper/lead) for only power and 30 copper and 70 lead and avoid spam

**Comment by DS-3K** [comment]
High tier mining drones sound like a terrible idea.
They take a lot of the industry away from mindustry and even though I dont like building infra thaaat much its still a core part off the game
This would also soft nerf pyratite because its even more trouble to make in comparission to other mats
