### ISSUE TITLE
Logic procedure implementation idea

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry-Suggestions#838]
**Describe the content or mechanics you are proposing.**

I *know* this is already on the Trello. This is just my idea for how it could be implemented.

Currently, all logic blocks are on by default. There could be a "procedure processor" checkbox in the processor ui. If it's checked, it will no longer be run unless it's called by from another processor. For example, one processor could draw an icon based on what a memory cell contains. Then another processor could call it (probably by running `run processor1`) to run the code in it. For more flexibility, the end block could have a "return value" field and the caller could set a variable to the returned value (result = run processor1, `run processor1 result`).

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

This would make it much easier to run blocks of code multiple times. Also, it would be easier to organize blocks of code.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by sample-text-here** [comment]
@Legomonster33  How?

**Comment by 50275** [comment]
Is it possible to Control a processor and set Enabled to 0? (false)

**Comment by BasedUser** [comment]
Hi! I just came across this issue and I'd like to tell you about a working implementation of this.

Firstly, why didn't you consider reading a memory cell for "what processor needs to be executed", running:

```arm
read addr cell1 0
jump 0 notEqual addr %ADDRESSNUMBER%```, and then reading the data after that? I used that in TextLib (pinned in the Discord's **#logic**!), and while that has broke with all the release v6 changes - its original idea was to delegate the task of rendering bitmaps to processors via an input bitmap. So it's not just to say that what you're suggesting - interrupts - are impossible - you can also do that INSIDE the processor's config with some sneaky @counter setting shenanigans - many people have. But maybe you're not asking for a solution to this - just an instruction to make this easier; but unfortunately I can't help that. Good luck!

**Comment by stoneRdev** [comment]
To also add, if your ok with using mods, there's a mod called [Anuke Logic](https://github.com/DeltaNedas/anuke-logic) that adds the ability to program processors while they are running. For example, you can store some prewritten programs in a cell, and rather than a jump address, you can pass the location of a program in that cell to load and run. For me this has been easier to use than having my game lag out with huge processor programs. But, you might also need [ui-lib](https://github.com/DeltaNedas/ui-lib) and [RTFM](https://github.com/DeltaNedas/rtfm) to get the instructions to use it. install those three mods, and click on Anuke at the bottom while your programming your processor, and some good info will present itself
