### ISSUE TITLE
Higher tier door

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry-Suggestions#839]
**Describe the content or mechanics you are proposing.**

There should be a higher tier door for end game players because the ones we have right now lack health. Possibly the new tier should have slightly less health than thorium walls.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**

For all players, doors are used for letting units exit and enter past walls they've created. End game players need to work around the current doors because they are too weak. This request is to help that especially after the surge of actually useful ground units.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by superbrias** [comment]
So we got useful ground units, but a few are spider-like and can ignore walls and we got flying transport units that can carry units. Yes a higher health door "would be nice" but the idea is to probably make use of the transports, especially because protecting doors can be a hassle over protecting a wall. I am not sure how much control processors give but I have reason to believe we may even be able to have automatic "flying ski lifts" for getting units over walls.

This is just my two cents.

**Comment by the-kido** [comment]
Actually, the new units that carried other units flew over my head. I still think to an extent it still would be useful but I don't think it's _necessary_ anymore.

**Comment by Bohaska** [comment]
Flying units carrying other units? Spidery units? Can't find anything about that on the wiki.

**Comment by superbrias** [comment]
check the devlog on the discord, it will be coming out next update
