### ISSUE TITLE
Bumping an old feedback

### ISSUE THREAD

**Issue by scarf-generic** [Anuken/Mindustry-Suggestions#856]
Now that there is a suggestions github bot on the discord, im gonna "bump" this month-old water extractor suggestion: https://github.com/Anuken/Mindustry-Suggestions/issues/599
The reasoning behind this is to a. get more input on the idea/gather other possible solutions, and b. hopefully get anuke to comment his thoughts on it. Please dont comment here unless is related to this message and not the old suggestion. Thank you.
(sorry for killing template but it didnt really fit here)

1. - [x] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [x] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [x] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by Anuken** [comment]
I've seen that suggestion before. My opinion: 
- I don't think adding more affinities is confusing. Output is displayed on top of the block, and it can quickly become apparent which tiles matter just by looking at the stats. Modulating *power usage* instead of *output* based on tiles is no less confusing, anyway.
- Inconsistency is fine. You could also say that drills are "wildly inconsistent" because they don't generate any output on most tiles. Letting water extractors give the same *output* regardless of position makes them more spammable, and more prone to abuse in schematics. They *should* be unreliable, and only used as a final resort when water is unavailable.

**Comment by scarf-generic** [comment]
Hmm, i guess that explains why they are in the drills section. I guess overall I think its sad how many things in this game are becoming reliant on the map. Gonna close this & old one cause its probably not going to get added. Thanks for the reply.

**Comment by Anuken** [comment]
> I guess overall I think its sad how many things in this game are becoming reliant on the map.

I think it makes more sense. Aside from blocks that use outside resources (like solar panels), things that extract stuff from the environment should depend on the map. Being able to place something anywhere with the same flat efficiency just seems... cheap.

**Comment by Legomonster33** [comment]
> I guess overall I think its sad how many things in this game are becoming reliant on the map.

im just gonna go out on a limb and say that it seems like thats a good thing, requiring players to play the map instead of just spamming needless schematics

**Comment by 50275** [comment]
What bothers me is that the water extractor, oil extractor, cultivator and steam generator nerfs are just increasing the demand for more schematics for specific terrain - nobody wants to mass custom build designs every game.
I'm predicting now that PVP will be based on who has the largest set of terrain/map specific schematics.
