### ISSUE TITLE
mechs/factory path finding

### ISSUE THREAD

**Issue by cmrcmrmindustry** [Anuken/Mindustry-Suggestions#88]
its not a adding a feature but i did not know if this should go here or in bug cause its not a bug but not a new feature but any ways.

the path finding of the ship/allies that come out of the factory have a weird path finding mechanism. i had mine stuck in one sirtan place cause they thought something was their that they could break but they were just hovering around one spot all crammed into each other.

Also i find they like going onto rails if it heads in the direction they are going, even if its going back wards witch slows them down, but then go around junctions.

all in all great game just the path finding of some things might need some tweaking.

(clarification if it was not clear im not talking about the waves of enemies their path finding system to find the quickest way to the base is amasing its the allies you make from the factorys)

thank you for reading and maybe you will take this into consideration

**Comment by potatoisagender** [comment]
usually when the units cram themselves into a spot, you can fix it by putting conveyor belts in the blockage area. This works especially well with bottlenecks. The units path find the shortest distance wise to the attack area/command center. They dodge around junctions and routers because they cannnot walk through them, unlike conveyors. I agree that there are some weird dead spots in the pathfinding, but they can usually be fixed by deleting solid (e.g. walls) in the way, or adding conveyors to push them when stopped.
