### ISSUE TITLE
Refining ammo

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#906]
**Describe the content or mechanics you are proposing.**
There will be a new factory called the Bullet factory. Any item that goes through it became 'item name' bullet e.g. copper becomes a copper bullet. It will cost titanium, graphite, silicon and lead to produce and use a decent amount of power (80 units?). To make a bullet, you need to add 2 of whatever item you want to make into a bullet (except stuff beyond thorium, you need a higher-level bullet factory), 1 lead and 2 sand to make 2 bullets. Bullets have 1.5 times the damage of their non-bullet counterparts.

IMPORTANT: Turrets can still be supplied with non-bullet ammo.

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
It will create new targets for players to attack and defend (obviously). It will create new types of strategies never seen before and be another obstacle for experienced players to overcome.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.

**Comment by the-kido** [comment]
I don't like the idea of bullets. It just doesn't feel like mindustry. I also think this is a bit overly complicated compared to how it was before.

**Comment by itcannotbe** [comment]
This would just make using turrets harders. Too hard in fact.

**Comment by genNAowl** [comment]
Making something harder like this will end up crashing and burning. Just look at pyratite, and how underused it is.

**Comment by 50275** [comment]
imagine not having ammo in ground zero frozen forest desert wastes the first half of fungal pass and ruinous shores unless you launch titanium

**Comment by SirMachinegun** [comment]
how are we supposed to defend in early waves? Especially in campaign, when you don' have certain resources unlocked.

**Comment by Bohaska** [comment]
Forgot to clarify. Ammo shot doesn't have to be in bullet form. It is just an enchancement.

**Comment by Ferociousfeind** [comment]
Pyratite is underused because who's got the time to bring coal, sand, and lead all together? Nobody, that's who. Bullets, on the other hand, aught to be more complex than just resource -> generic factory -> instantly refined resource. But at the same time, Anuke has mentioned he doesn't want bullet items showing up in the game. For a mod, feel free, but bullets aren't for mindustry vanilla.

**Comment by Bohaska** [comment]
thanks.

**Comment by DS-3K** [comment]
There are some genuinly interesting and good points in these comments, I dont think many issues get discussions this good wow**...**

**Comment by DS-3K** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/906#issuecomment-716102660 

**Amazing comparission!**

**Comment by DS-3K** [comment]
Pyratite is underused because who's got the time to bring coal, sand, and lead all together? Nobody, that's who. Bullets, on the other hand, aught to be more complex than just resource -> generic factory -> instantly refined resource. But at the same time, Anuke has mentioned he doesn't want bullet items showing up in the game. For a mod, feel free, but bullets aren't for mindustry vanilla.
 🎉 1 ❤️ 1 🚀 1 👀 1
 
**Amazing comparission!!**
