### ISSUE TITLE
Campaign is not really challenging and it's boring compared to v5.

### ISSUE THREAD

**Issue by azureblue** [Anuken/Mindustry-Suggestions#930]
**Describe what you would like changed, and why.**
I mean not challenging regarding planning which sector to explore next. When you have titanium, sand and coal in the directly adjacent sectors to the starting one, you can research most stuff and the only reason to explore the planet is to search for thorium.

Also researching is to too easy. I really liked idea of Launch Pads from v5. It makes research more challenging (and let's say realistic) when you staying is the same sector, and you had to make a decision when to launch the core with all the resources in it and LEAVE a sector.

...not to mention there is no point in following the v5 campaign tree in v6.

**Describe the changes you want to propose. Include possible alternatives.**
- return to v5 research mechanics: if you want to use resources for the research - launch the core and leave the sector (you have to have to start from the beginning in that sector) or use Launch Pads
- an option to "buy" expensive another core - so you could occupy more sectors at the same time
- make resources less abundant (especially in terms of variety)
- some endless waves sectors, that force you to leave them at some point
- do something that force you to follow v5 campaign tree - that's the **real campaign** with kind of 'story'

**Comment by itcannotbe** [comment]
Camping != Campaign

**Comment by sample-text-here** [comment]
> you have to have to start from the beginning in that sector

But... the best change in v6 was not having to restart every time. After I reached 1000 waves and launched, I didn’t feel like starting a new map.

**Comment by azureblue** [comment]
Well, I disagree.

I think the idea of launching the core was and leaving the sector behind was great. It force to make decisions and carefully plan which sector would be the best to go next. It also make the more 'realistic', since the core is unique. That being said, during the you would unlock/buy the possibility to have another core to use in different sector and so on.

Now in v6 each sector is a sandbox game, no real reason to another. And if you want 1000 waves, why not just play custom game?

Campaign should be about gradual development, no having sandbox in each sector and all tech and resources after a few hours of playing...

**Comment by sample-text-here** [comment]
v5 was broken. I played ~3 maps, researched launchpads, then went and played 1000 waves in nuclear production. It *should* be about gradual development, but the v5 system didn't work. 90% of my v5 experience was afk, research, repeat. v6 is better, but not perfect. The "launching destroying everything" mechanic wasn't very fun imo because I just afked because I didn't want to start a new map. I think the current sector system is good because you can explore and launch resources, but keep sectors for production/research

> And if you want 1000 waves, why not just play custom game?

That's my point. I didn't feel like going back to the campaign maps. Now it's much better.

> I like to see a core in a campaign as something not easily available

>  That being said, during the game you would unlock/buy the possibility to have another core

They aren't easily available. You can upgrade them for insane amounts of resources, but you can't build them. There is no "possibility to have another core"

---

As for your ideas

> return to v5 research mechanics: if you want to use resources for the research - launch the core and leave the sector (you have to have to start from the beginning in that sector) or use Launch Pads

No. As I said, v5 research is broken. Spamming launch pads can get the entire tech tree researched in ~2-3 hours

> an option to "buy" expensive another core - so you could occupy more sectors at the same time

This is already in the game. Try launching to any other sector

> make resources less abundant (especially in terms of variety)

This is mainly the sector generation's fault and may be fixed soon. Also look at my next point.

> some endless waves sectors, that force you to leave them at some point

No. Sectors should have an end to them to have a sense of progression. An interesting idea would be to make resources run out, forcing you to launch and explore more sectors. (With ~1-2 infinite tiles per ore patch so you can't get softlocked)

> do something that force you to follow v5 campaign tree - that's the real campaign with kind of 'story'

The tech tree lets players research maps, along with blocks/items/liquids/mechs. There does need to be a better campaign story, though. If this was implemented, make it so "pneumatc drill requires frozen forest to be researched" or something like that.

These are just my thoughts, discussion would be fine but please don't be a jerk

**Comment by azureblue** [comment]
I guess we just have different experiences 🙂.
I've played whole v5 campaign multiple times and experienced some sens of development and limitation of resources and tecs (at least compared to v6). 

> Spamming launch pads can get the entire tech tree researched in ~2-3 hours

True. They should send items much slower... But at least you needed them. In v6 you don't even need them to research everything in 2nd or 3rd sector. I really like idea of launch pads, though they should send items much much slower and consume more power. But the main way of getting resources for research should be a core launch.

> They aren't easily available. You can upgrade them for insane amounts of resources, but you can't build them. There is no "possibility to have another core

By another core I mean when you can just get to the adjacent sector for like 2kC/1kL or something - which gives you a new core in that sector. That should be possible, but it should be much much more expensive. I mean **much**. In meantime when you want to go to another sector you should launch one of your cores (literally) and in result abandon one of your sectors. At the beginning of the campaign you would have only one core for some time, which mean you could be present in only one sector.

At first you would be like a nomad going from sector to sector researching and collecting resources for a new core which could settle for a while in some peaceful area 🙂.

Btw. I really like the sectors based campaign in v6 and the whole idea of planet view!.

>  These are just my thoughts, discussion would be fine but please don't be a jerk
Did I say something offending? I didn't intend to, not at all.

Those are also just my thought and nothing more ;).

**Comment by sample-text-here** [comment]
> Did I say something offending? I didn't intend to, not at all.

No, you didn't. I just had some... interesting experiences... talking with people in other issues when I share my opinions
