### ISSUE TITLE
Penalty for running production blocks inefficiently / < 100%

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry-Suggestions#990]
**Describe what you would like changed, and why.**
Currently there is nothing forcing players to build efficient designs aside from using more tiles since power usage already stops when the building lacks necessary inputs*.

**Describe the changes you want to propose. Include possible alternatives.**

A mechanic to make blocks that use resources to make something else use twice what they would normally use if they came from a starved (building lacked the inputs it needs)/stopped state then consume normally in the next production cycle of the building (based on item consumption time)

This wouldn't affect most designs out there. It just make inefficient designs more inefficient.

**Comment by 50275** [comment]
This is... really stupid. Imagine loading into a sector with little coal, and then having your graphite presses work at half the efficiency.
Or, you're making combustion generators on a hard map you probably shouldn't have launched to and all of a sudden you _have to_ do the math to find optimal efficiency for the generators.
Or, you're upgrading your graphite presses to multipresses and you realize that you'll be wasting more coal because you can't afford it.
Or, you have a resource shortage and your surge is trash.
Or, you have to increase your schematic size specifically to cope with a stupid suggestion.
Or, you have to delete any of your designs that might potentially involve cultivators because this design would make them even worse than they already are, because the number of parts you'll need to use to route 6 cultivators to a spore press while needing 12 water extractors is ridiculous.
And, you punish literally every single casual player in the entire game who doesn't want to do the math for literally everything.

**Comment by itcannotbe** [comment]
> This is... really stupid. Imagine loading into a sector with little coal, and then having your graphite presses work at half the efficiency.

They would only penalize you if you made too much presses for the amount of coal that you have. Also underflows and overflows are a thing. They basically prevent every press from being penalized by using the mechanics of the overflow/underflow, item prioritization.

> Or, you're making combustion generators on a hard map you probably shouldn't have launched to and all of a sudden you _have to_ do the math to find optimal efficiency for the generators.

Again. Overflows and underflows. And they cost not a lot even for early game (What is 4 copper and 2 lead?)

> Or, you're upgrading your graphite presses to multipresses and you realize that you'll be wasting more coal because you can't afford to feed it.

Again. Overflows and underflows.

> Or, you have a resource shortage and your surge eats 6 silicon instead of 3.

Why would you even build a lot of alloy smelters when you already know that they use a lot of materials.

> Or, you have to increase your schematic size specifically to cope with a stupid suggestion.

That's the point of nerfs and buffs, changing how the people play the game, consequently changing the meta

> Or, you have to delete any of your designs that might potentially involve cultivators because this design would make them even worse than they already are, because the number of parts you'll need to use to route 6 cultivators to a spore press while needing 12 water extractors which is ridiculous.

Not my problem.

> And, you punish literally every single casual player in the entire game who doesn't want to do the math for literally everything.

Blocks that prioritize one output over the other already exist.
And through them, even visually and without the need for math/famcy calculations, you can determine if your setup hasn't have enough inputs for the number of your production block.



Again. This wouldn't affect most designs out there. It just make inefficient designs more inefficient.

**Comment by 50275** [comment]
You're expecting all players to use underflows and underflows for every single factory in the game?

Cultivators were never the meta, your suggestion just makes them even worse. Many maps will not have water, too. This includes the campaign BTW

The "quad" silicon smelter, widely used by many players will become risky to use. This is a bad thing.

Many players hook up drills directly to factories because it saves a lot of space. Now, they have to make conveyors for everything. Imagine what happens when the next balance change suddenly nerfs them without them knowing?

We need alloy smelters for technologies, and sometimes our defences get destroyed and our poly builders... rebuild them, fast. You can't really stop them either.
All of the above is for nothing, however.

Your suggestion would affect just about every single design in the game, especially those used by newer players who haven't got a good grip on how to play. Frequently I see factories that have a 1:1:1 ratio of water extractors to cultivators to spore presses. The power cost is enough punishment, but this suggestion simply just ruins the experience for any user who wants to play the game casually like the others because of the strict set of patterns that it will enforce on players. Nobody wants to have conveyors and underflow gates for everything they build. Nobody wants to invalidate the quad silicon smelter, and nobody wants to do all the math for a completely perfect schematic.

**Comment by itcannotbe** [comment]
> You're expecting all players to use underflows and underflows for every single factory in the game?

It's a game mechanic already in the game anyways. And it's almost underused except when the exploiting overflow bug (sorterflows) became mainstream.

> Cultivators were never the meta, your suggestion just makes them even worse. Many maps will not have water, too. This includes the campaign BTW

Did I hear the sound of everyone screaming in power cubes?
And cultivators were never considered since oil extractors (v5) were extremely convenient.

> The "quad" silicon smelter, widely used by many players will become risky to use. This is a bad thing.

It will survive.

> Many players hook up drills directly to factories because it saves a lot of space. Now, they have to make conveyors for everything. Imagine what happens when the next balance change suddenly nerfs them without them knowing? You'd have to have huge factories for specific purposes to get a perfect ratio or drastically above what you need.

Well that what was actually happened in the past. The factories weren't attached to drills.

> We need alloy smelters for technologies, and sometimes our defences get destroyed and our poly builders... rebuild them, fast. You can't really stop them either.

Well then protect them.

> Overflows and underflows do not work well on cores and unloaders. Rapidly "changing" the meta destroys the work of people who put in effort into the game.
> All of the above is for nothing, however.

Ah yes. People want never ending buffs, but disgust nerfs because the meta will change? Games die because of that.

> Your suggestion would affect just about every single design in the game, especially those used by newer players who haven't got a good grip on how to play. Frequently I see factories that have a 1:1:1 ratio of water extractors to cultivators to spore presses. The power cost is enough punishment, but this suggestion simply just ruins the experience for any user who wants to play the game casually like the others because of the strict set of patterns that it will enforce on players. Nobody wants to have conveyors and underflow gates for everything they build. Nobody wants to invalidate the quad silicon smelter, and nobody wants to do all the math for a completely perfect schematic.

Used by newer players? Then they would have to use new designs. That's how things go.
 
> It's simply going to make the game a huge mess for beginners who don't know about this, players who want to have generators in any remotely compact pattern, or any experienced player trying to make a schematic.

To be clear. This suggestion only affects buildings that are starved of resources. That's all it covers.

**Comment by itcannotbe** [comment]
Also you are too hostile towards this suggestion because of what? You don't like nerfs? You don't want to redesign your schematics or probabaly have to adapt when most of yoir schematics gets affected?


If your the type of player who only plays using schematics that others have posted online. The solution is simple, just wait for a refreshed schematic. Done.

**Comment by 50275** [comment]
Actually, I made a lot of designs. I had to delete many to make sure that I don't lag when I open up the schematic menu. I didn't like V6's very frequent nerfing of steam generators and water extractors - they made coal much less useful. Aside from that:
  - Your suggestion would force schematic creators to ignore the cultivator (it's already gone from V6, but this suggestion would make it used literally never) unless there is open sources of water nearby, even then oil extractors are better
  - Yes, underflows are already in the game but we shouldn't have to use them to solve a penalty that shouldn't be there to begin with
  - Many factories are attached to drills, but doubling the cost of any that aren't functioning perfectly will be extremely irritating if there is no more of that resource nearby, which happens often in campaign maps and servers
  - Seriously, if you make a single mistake with water or oil you shouldn't simply instantly have everything fail because your factories are not working at 100% efficiency
  - Impact designs will be super SHIT as they take a large amount of time to start and reach high efficiency and will require logic to be effective e.g. carry blast/extra titanium for cyrofluid to reactors
  - Thorium reactors will require more logic
  - We already redesigned all of our schematics, but this would ruin a bunch of other things with them - small scale designs using coal would be useless and would not work

**Comment by scarf-generic** [comment]
> Ah yes. People want never ending buffs, but disgust nerfs because the meta will change? Games die because of that.

Hmm yes v6 doesnt have enough nerfs
People dont mind the game changing, people dont mind things getting balanced (nerfs included, yes), what people do mind is half the game getting nerfed and becoming impossible to play casually. Games die because of that.

**Comment by 50275** [comment]
Close this.

**Comment by Kyllingene** [comment]
I love Mindustry. Part of the reason I love the v6.0 update is because the campaign becomes more casual-friendly. I do not want to design everything efficiently, because I am a casual. This suggestion simply cuts out the casual part of the game. No, I don't want every factory I make have to be either maximumly efficient or nonexistent. The only way this would make sense is as an option in custom maps.

**Comment by itcannotbe** [comment]
Contrary to your perception v5 campaign is the one casual friendly.

But v3 is even more casual friendly because it doesn't have game mechanics you can work with compared to v5 and v6.

Furthermore. I don't really get why people get worked out with a mechanic that just impacts the startup of a block. If it's running consistently then you're fine.

**Comment by 50275** [comment]
If you use underflow gates everywhere, which you will be forced to use everywhere, as well as calculating all of your ratios and having logic for your impact and thorium reactors, as well as stockpiling resources outside of all of your re-constructors, and being very careful about your liquids and production and making sure not to get upgrades to buildings too fast, you'll be fine. Yes. This is fine.

**Comment by ritzip** [comment]
considering there are diodes i don't see why this is a problem

**Comment by 50275** [comment]
yes, you need to diode everything
just don't forget about the sync errors

**Comment by XxsuperdeadlysniperxX** [comment]
@50275 diodes aren't necessary for early, its somewhat necessary for mid game and it ABSOLUTELY necessary late game because you power can die easier

**Comment by Kyllingene** [comment]
>It's simply going to make the game a huge mess for beginners who don't know about this, players who want to have >generators in any remotely compact pattern,

You never addressed this. Making things compact is one of the funnest things in Mindustry, to casual and hardcore alike. However, to make perfectly efficient designs (required if your factories need to be running at literally anything but PERFECT, NO HICCUPS AT ALL EVER), you need space. Lots of it. Also, 
 - early game would be painfully slow, 
 - an enemy in PvP (think of the servers!) destroying 1 conveyor before dying RUINS your production, 
 - and breaches in your defenses are basically impossible to recover from in time. 

Seriously, at LEAST make it 'if < 50% then debuff', or something a little more reasonable. I could get behind this if it was < 10%, maybe < 25%, probably not < 55% (maybe not even < 50%).

**Comment by itcannotbe** [comment]
Ah. No.

You misunderstood everything.
1. The block need to have starved of one of it's needs.
2. The penalty won't be applied if the block is continuously running.

**Comment by XxsuperdeadlysniperxX** [comment]
Can you explain the reasoning like how would this work possibly plz?(you don't have to be detailed im just confused on how this will work)

**Comment by Kyllingene** [comment]
>The block need to have starved of one of it's needs.

So, if a block is has none of a resource, it suddenly requires twice the items, making the next run starved, making it take twice the items, so on and so forth. If you perfectly calculate your production (for example, EXACTLY 1 coal + 2 sand/s to your silicon smelter), but then some jerk of a flare destroys a conveyor before dying. Well, then your silicon stutters for half a second, so it requires more next cycle, but your production isn't enough for that. So, as you spend your time fixing THAT, a NEW flare flies over and stutters your GRAPHITE. Can you see where I'm going here?

>The penalty won't be applied if the block is continuously running.

Wait, so if I devise a logic system that alternates between factories for peak (current) efficiency from small amounts of resources, lets say coal between a graphite press and a silicon smelter, NEITHER of them work anymore? Huh... Cool!

>Currently there is nothing forcing players to build efficient designs aside from using more tiles since power usage already >stops when the building lacks necessary inputs*.

Why not simply make buildings take power constantly, instead of only when producing? Yes, this makes things somewhat harder early-game, but at least it's not impossible. Also, where is the footnote that asterisk implies?

And please. Low-resource maps are super fun. In fact, I made a 1-of-each-ore map. How would that be feasible with this change?

**Comment by Kyllingene** [comment]
>Well that what was actually happened in the past. The factories weren't attached to drills.

Sure. I wasn't around then, but let's say that is true. Why, do you think, that the past, which has fewer balances, updates, and bugfixes, is a better benchmark for fairness than the present?

>Why would you even build a lot of alloy smelters when you already know that they use a lot of materials.

1: That doesn't answer the question.
2: They specified *one* alloy smelter.

>Not my problem. Pumps exist and tile affinities that affect production rate is there in the game for people to use it.
>Also multiple suggestions have been already implemented that make certain blocks less convenient to use. So not my problem.

1: The maps with little water are the dry-themed ones. Therefore, they will be much more likely to have little to no affinities 
with water extractors.

2: Why does the fact that some blocks get nerfed mean that *every* block should get nerfed, and that a block becoming useless is perfectly fine? And by the way, oil extractors are fairly expensive. They require a lot of *water*.

>It will survive.

Probably the lowest-effort argument I've ever seen. Why would it survive if it is horribly inefficient?

>Used by newer players? Then they would have to use new designs. That's how things go.

You assume that every new player wants to use premade schematics. I don't, and my friend ***hates*** the idea. Why do you think that everyone who decides to play this great, multifaceted game is a 2-year-old who just likes winning easily?

>Also you are too hostile towards this suggestion because of what? You don't like nerfs? You don't want to redesign your schematics or probabaly have to adapt when most of yoir schematics gets affected?

Ah yes, the "assume that their reasons are terrible" argument. So effective, so constructive. Even ***if*** that was true, why would that invalidate their other arguments?

**Comment by itcannotbe** [comment]
Bump.
~We all know this would happen when an automated closing gets implemented.~

**Comment by itcannotbe** [comment]
Bump
~This is not the time to die~

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~

**Comment by 50275** [comment]
so, it's V6, and even if this suggestion was implemented, it could be bypassed with logic parts

however, if implemented, you'd instantly erase every single small scale impact/diffriential/cultivator related schematic that didn't have the logic parts to bypass this suggestion's penalty

it's just as redundant as making null sorters not work; it does nothing but force players to make a redundant change (instead of setting all the sorters to something like spore pods, it would be adding logic parts to only allow the production builidng to work when enough resources were inside)

**Comment by 50275** [comment]
so not only is this an unnecessary punishment to any inexperienced player who doesn't know how to play the game very well, (especially if they're new and losing in campaign!) it can be completely bypassed with logic parts

summary
  - Some unfriendly but powerful schematics demand extra resources such as water (e.g. impact reactor) 
  - Literally any player who doesn't have logic parts to completely bypass these limitations are at a huge disadvantage; those who do can completely ignore this for no significant penalty of any kind (just 1 logic processor)

**Comment by itcannotbe** [comment]
> so not only is this an unnecessary punishment to any inexperienced player who doesn't know how to play the game very well, (especially if they're new and losing in campaign!) it can be completely bypassed with logic parts so you're punishing any player unfamiliar with logic parts

Actually no, this hurts more experienced players than inexperienced ones.
 
> summary
> 
>     * Some unfriendly but powerful schematics demand extra resources such as water (e.g. impact reactor)

How did you even arrive at that conclusion?

>     * Literally any player who doesn't have logic parts to completely bypass these limitations are at a huge disadvantage; those who do can completely ignore this for no significant penalty of any kind (just 1 logic processor)

Nope. Cause disabling buildings also considered as stopping them.

**Comment by 50275** [comment]
> Actually no, this hurts more experienced players than inexperienced ones.

unfortunately I was not aware with the sudden unspecified notice of the fact that disabling parts with logic would also reduce their efficiency the same way

> How did you even arrive at that conclusion?

correction: some unfriendly, **small scale,** powerful schematics, **like small numbers of impact reactors** may take extra resources to start up the necessary buildings, such as this one (not mine)
https://media.discordapp.net/attachments/717895174021447690/862730967440687125/image0.png
the design isnt inefficient itself, but this suggestion would nuke the cyrofluid mixer with just one water extractor

> Nope. Cause disabling buildings also considered as stopping them.

no updates to the suggestion to account for v6? you're spending more effort against the bot closing this than keeping the suggestion relevant itself

> It will give rise to a different mindset when building, cause currently it's better to spam multiples of everything across lots of set-ups rather than making a lot of things in one place then getting it to where it is needed. Which is basically what so called "inexperienced players" do.

you should've said you wanted to change the entire meta and a massive chunk of all the schematics in mindustry to begin with! can't imagine living without thorium anymore (because it mostly blocks access to oil extractors (spore plastanium is super expensive) for plastanium to get plastanium conveyors and mass drivers)

the entire schematic meta is about making everything more convenient, and it looks to me like you're aiming on forcing them to make less convenient designs by adding an even bigger limitation to designing schematics

**Comment by itcannotbe** [comment]
> > How did you even arrive at that conclusion?
> 
> correction: some unfriendly, **small scale,** powerful schematics, **like small numbers of impact reactors** may take extra resources to start up the necessary buildings, such as this one (not mine)
> https://media.discordapp.net/attachments/717895174021447690/862730967440687125/image0.png
> the design isnt inefficient itself, but this suggestion would nuke the cyrofluid mixer with just one water extractor

Nah, water extractors will be safe. Because they don't have inputs.
And code wise liquids are a nightmare to deal with as they consume/output per tick.

> > Nope. Cause disabling buildings also considered as stopping them.
> 
> no updates to the suggestion to account for v6? you're spending more effort against the bot closing this than keeping the suggestion relevant itself

Did somethings changed that would necessitate me changing anything?

> > It will give rise to a different mindset when building, cause currently it's better to spam multiples of everything across lots of set-ups rather than making a lot of things in one place then getting it to where it is needed. Which is basically what so called "inexperienced players" do.
> 
> you should've said you wanted to change the entire meta and a massive chunk of all the schematics in mindustry to begin with! can't imagine living without thorium anymore (because it mostly blocks access to oil extractors (spore plastanium is super expensive) for plastanium to get plastanium conveyors and mass drivers)

> the entire schematic meta is about making everything more convenient, and it looks to me like you're aiming on forcing them to make less convenient designs by adding an even bigger limitation to designing schematics

Ah yes convenience...
Fun facts:

Did you know the water extractor had a lot of nerfs thrown at it because of it's convenience? Which also entailed a lot of schematics being remade because of the change.

Did you know the oil extractor was nerfed by changing the mechanic from allowing it to run anywhere to only certail tiles because of it's convenience?

**Comment by 50275** [comment]
> Nah, water extractors will be safe. Because they don't have inputs except power. And code wise, liquids are a nightmare to deal with as they consume/output per tick.

water extractors themselves as buildings are safe, but their use in schematics certainly aren't.

> Did somethings changed that would necessitate me changing anything?

the fact you didn't specify the involvement and interaction with parts in v6 makes discussion less clear. 

> Ah yes convenience...
> Fun facts:

> Did you know the water extractor had a lot of nerfs thrown at it because of it's convenience? Which also entailed a lot of schematics being remade because of the change.

> Did you know the oil extractor was nerfed by changing the mechanic from allowing it to run anywhere to only certail tiles because of it's convenience?

I know both the oil and water extractors were nerfed, but this doesn't involve the balancing of individual buildings; this is about designs that you plan on invalidating, such as the impact design posted. 
---
You're completely ignoring what your suggestion focuses on, which is the effect on designs in the mindustry playerbase.

**Comment by Kyllingene** [comment]
Regardless of the validity of the arguments, this is clearly a dead issue in Anukes eyes, so please, close (and stop bumping other dead issues).

**Comment by itcannotbe** [comment]
Is bumping illegal?

**Comment by itcannotbe** [comment]
Bump
~I am not leting you die~

**Comment by XxsuperdeadlysniperxX** [comment]
Heres my opinion on this

**this is the worst possible thing you could have ever suggested**

The lower the production the worse the output you are already being punished by reduced flow we do not need any punishments also this has already been suggested and has been ignored now close this suggestion and never reopen it

~i am tired of this suggestion being a thing~

(This one specificly)

**Comment by itcannotbe** [comment]
> The lower the production the worse the output you are already being punished by reduced flow we do not need any other punishments also 

It's not even punishment if you put it that way, it's simple math, input at 50% of what the crafter can do, output 50% what the crafter can do.

> this has already been suggested

You sure?

> and has been ignored now close this suggestion and never reopen it

You can't make me, and it's not illegal to do what I'm doing.

> (Also this will mske the game unsuitable to play by everyone)

In what way? It still be playable. It just encourages a different play style where people are maxing out factories instead of having one per each final output you want.

**Comment by Kyllingene** [comment]
@itcannotbe, if I am not mistaken I *very recently* saw you call someone a "RETARDED REDACTED" for commenting on an issue; maybe don't bump hundreds of stale issues and say that at the same time?

**Comment by XxsuperdeadlysniperxX** [comment]
*Test for block*

**Comment by XxsuperdeadlysniperxX** [comment]
Also this idea is bad im not going to explain it cuz your just going to block me again

**Comment by Kyllingene** [comment]
Thanks for a most useless comment, @XxsuperdeadlysniperxX, along with a pointless tag.

But, seriously, if Anuke saw *any* potential in this, he would have acted long before now. Everyone active on the issue opposes it. It is entirely, completely, 100% dead. ***Stop bumping it.***

**Comment by stuffyAI** [comment]
The penalty already is either using more space than needed or not using all the available resources, why would you further penalize beginners?

Regardless, with logic you could specifically save up multiple cycles of resources to avoid your 'penalty' after the first cycle anyway, making this effectively only valid pre-microprocessor whilst keeping the 'more space wasted' penalty.

Also let's not even mention the unfairness of this 'feature' provided by latency/lag, causing you schematic to be considered inefficient due to playing on a server or phone.

**Comment by itcannotbe** [comment]
> The penalty already is either using more space than needed or not using all the available resources, why would you further penalize beginners?

It won't. What it would penalize more are compact schematics. Which beginners can't make.

> Regardless, with logic you could specifically save up multiple cycles of resources to avoid your 'penalty' after the first cycle anyway, making this effectively only valid pre-microprocessor whilst keeping the 'more space wasted' penalty.

It won't.

> Also let's not even mention the unfairness of this 'feature' provided by latency/lag, causing you schematic to be considered inefficient due to playing on a server or phone.

It also won't.

**Comment by stuffyAI** [comment]
> It won't. You seem you have a bad understanding when the penalty would be applied.

The description is 
"make something else use twice what they would normally use if they came from a starved (building lacked the inputs it needs)/stopped state then consume normally in the next production cycle"

So logic could resolve it exactly like that, if for example my building needs 10 copper I could save 1000 copper, spend 20 copper as penalty in the first cycle and then use the remaining 980 copper linearly because the building isn't starved in that time. even if my storage input isn't at the speed of 10 _copper/cycletime_.
Then I just wait until I have 1000 copper again.



> It also won't. You seem you have a bad understanding when the penalty would be applied.

Well I would wish to see your code on how a 'starved' state is defined then, because if we just fetch the variance between _x max usage_ - _x current usage_ of a building this will 100% give us a 'starved' state with lag and de-sync.



> Which beginners can't make unless they use schematics right of the bat.

Jump in a public campaign and tell me you never seen a beginner conjoin production buildings below 100% throughput, those are exactly the kind of people to use water extractors 1:1 cultivators.

**Comment by itcannotbe** [comment]
> > It won't. You seem you have a bad understanding when the penalty would be applied.
> 
> The description is
> "make something else use twice what they would normally use if they came from a starved (building lacked the inputs it needs)/stopped state then consume normally in the next production cycle"
> 
> So logic could resolve it exactly like that, if for example my building needs 10 copper I could save 1000 copper, spend 20 copper as penalty in the first cycle and then use the remaining 980 copper linearly because the building isn't starved in that time. even if my storage input isn't at the speed of 10 _copper/cycletime_.
> Then I just wait until I have 1000 copper again.

In that case then the mechanic does what it was intended to do. Also you can't do that to compact complex schematics anyways.

> > It also won't. You seem you have a bad understanding when the penalty would be applied.
> 
> Well I would wish to see your code on how a 'starved' state is defined then, because if we just fetch the variance between _x max usage_ - _x current usage_ of a building this will 100% give us a 'starved' state with lag and de-sync.


It won't why would a buiding with items inside of it that it needs for it's next cycle considered starved at any point, even with lag. It should only check before actually using the items.

> > Which beginners can't make unless they use schematics right of the bat.
> 
> Jump in a public campaign and tell me you never seen a beginner conjoin production buildings below 100% throughput, those are exactly the kind of people to use water extractors 1:1 cultivators.

But the catch is this only affects ittems. Also this will make crafters = less efficient. Which would be a positive thing with multiplayer. Cause it forces people to not make individual standalone factories.

**Comment by stuffyAI** [comment]
> In that case then the mechanic does what it was intended to do

Now: inefficiency penalized with more space wasted
Your mechanic: inefficiency penalized with more space wasted, also make the game eat more processing power



> why would a buiding with items inside of it that it needs for it's next cycle considered starved at any point

For the same reason 1:1 impact schematics in 6.0 eventually failed on high-load servers, the Impact Reactor suddenly lost input speed despite it mathematically working at 100% throughput.
While this specific case has been 'fixed' (more like worked around), you would again introduce similar problems with schematics that 'mathematically' work at 100% efficiency, however in practice will just penalize existing in high-load servers or running on low-end hardware.



> But the catch is this only affects ittems. 

Items a beginner doesn't need because...?



> Which would be a positive thing with multiplayer. Cause it forces people to not make individual standalone factories.

Not the opposite? If your change gets implemented, I am even less inclined to trust the schematics of other players, forcing me to do everything by myself just to ensure 100% efficiency. This against just shoots beginners in the foot as the pros will start dismantling their stuff even earlier.

**Comment by itcannotbe** [comment]
> > In that case then the mechanic does what it was intended to do
> 
> Now: inefficiency penalized with more space wasted
> Your mechanic: inefficiency penalized with more space wasted, also make the game eat more processing power
But it will making more centralized production of certain items will make people use less crafters overall so...... the load just shiftted.

> > why would a buiding with items inside of it that it needs for it's next cycle considered starved at any point
> 
> For the same reason 1:1 impact schematics in 6.0 eventually failed on high-load servers, the Impact Reactor suddenly lost input speed despite it mathematically working at 100% throughput.
> While this specific case has been 'fixed' (more like worked around), you would again introduce similar problems with schematics that 'mathematically' work at 100% efficiency, however in practice will just penalize existing in high-load servers or running on low-end hardware.
> 

Try blaming floating point precision.

> > But the catch is this only affects ittems.
> 
> Items a beginner doesn't need because...?
> 
> > Which would be a positive thing with multiplayer. Cause it forces people to not make individual standalone factories.
> 
> Not the opposite? If your change gets implemented, I am even less inclined to trust the schematics of other players, forcing me to do everything by myself just to ensure 100% efficiency. This against just shoots beginners in the foot as the pros will start dismantling their stuff even earlier.

Unless it's pvp a few wasted resources is negligible. Also the solution to early game wasting would be basically use less crafters.

**Comment by stuffyAI** [comment]
> the load just shiftted.

Having to calculate the variance of productions buildings to get a fair 'efficiency' score every-time throughput changes is much, much more expensive than having 5x more producers which run at 20%.

 

> Try blaming floating point precision.

Tick-frame differences causing certain timers to de-sync by single cycles, exponentially penalizing producers at the end of the chain. We could just not add a feature like that.



> Unless it's pvp a few wasted resources is negligible.

If your change is negligible, why add it.



> Also the solution to early game wasting would be basically use less crafters.

Again, do everything yourself.
You basically void cooperation, because I cannot trust player 2 to build an array of blast mixers exactly matching my spore and pyratite production so we don't waste resources.
This also makes planning annoying, previously I could lay out more producers than needed to reserve space, with your change I would have to progressively complete it matching my intake.

**Comment by itcannotbe** [comment]
> > the load just shiftted.
> 
> Having to calculate the variance of productions buildings to get a fair 'efficiency' score every-time throughput changes is much, much more expensive than having 5x more producers which run at 20%.

It's on a block on block basis, It would just have to run basically a check similar to the block status. Has inputs? Can output? If not next cycle would need 2x as base before it can satisfy has inputs.

> > Unless it's pvp a few wasted resources is negligible.
> 
> If your change is negligible, why add it.

I was referring to early game when I said that.

> > Also the solution to early game wasting would be basically use less crafters.
> 
> Again, do everything yourself.
> You basically void cooperation, because I cannot trust player 2 to build an array of blast mixers exactly matching my spore and pyratite production so we don't waste resources.
> This also makes planning annoying, previously I could lay out more producers than needed to reserve space, with your change I would have to progressively complete it matching my intake.

Or basically over/underflows down the line.

**Comment by stuffyAI** [comment]
> Has inputs? Can output? If not next cycle would need 2x as base before it can satisfy has inputs.

Taking an absolute means that 99% satisfaction doubles your resource cost, because the second you paid the double input price you have to pay it again even if you satisfy it just a single frame late. This is absurd to do without averages.



> I was referring to early game when I said that.

How is double copper price early more negligible than double phase/surge cost late-game?



> Or basically over/underflows down the line.

So... one such gate for every input (cause splitting could mean <100% efficiency) aka... more space needed for the same?
I don't see the point then, this is what we effectively had before just with more attention to satisfying a building first rather than even distribution.

**Comment by itcannotbe** [comment]
> > Has inputs? Can output? If not next cycle would need 2x as base before it can satisfy has inputs.
> 
> Taking an absolute means that 99% satisfaction doubles your resource cost, because the second you paid the double input price you have to pay it again even if you satisfy it just a single frame late. This is absurd to do without averages.

So how does block status even works?

> > I was referring to early game when I said that.
> 
> How is double copper price early more negligible than double phase/surge cost late-game?

Because early game you mostly deal with easily obtainable items.

> > Or basically over/underflows down the line.
> 
> So... one such gate for every input (cause splitting could mean <100% efficiency) aka... more space needed for the same?
> I don't see the point then, this is what we effectively had before just with more attention to satisfying a building first rather than even distribution.

Actually currently, the people are basically making production localized. i.e. making everything you need to make the final output of what you want near the final crafter.

**Comment by Kyllingene** [comment]
I think the original version of the comment was correct and better worded:

> What it would penalize more are compact schematics.

It more clearly shows the absurdity of this idea; also, ***Anuke has had more than enough time to see this issue; either he will implement it, and this has no further purpose, or he won't, and this has no further purpose. Close it.***

**Comment by stuffyAI** [comment]
> So how does block status even works?

This was supposed to be an idea provided by you, I am surprised that you don't understand the code but talked about game speed. Currently we know if a block can craft, how much progress in doing so has, we know how much of each resource it has and needs, and what its current speed is (from overdrive and affinities).

If we declare a producer to be 'dead' whenever it has any periods of times not actively producing we get that absurd 2x price even when we supply with 99% coverage, alternatively we would have to store previous cycles and calculate a true efficiency, which costs a little more RAM and much more CPU, as for a fair and statistically correct evaluation we would have to take squares of all values and then a root of said deviance, the latter _every_ time our building doesn't produce.



> Because early game you mostly deal with easily obtainable items.

In an incremental progression game like Mindustry every instance of efficiency loss is major to the entire factory development speed, exponential here because it affects all producers.



> Overflow and underflows are not even used near conveyors anymore because of the current attitude of production.

Went through the trouble to build a 6.X Version again to play with 'casuals', I don't seem to have the same experience as you.

Regardless, what do you have against that staying the way it is, I really do not see how this suggestion actually solves anything, even if it was feasible to implement.
